"""Saved shared AI reused in recipient-language digests, never generated by them."""
import asyncio
from dataclasses import replace

import pytest
from sqlalchemy import delete, func, select
from test_digest_periods import recipient
from test_digest_topics import settled_matches
from test_interest_execution import artifacts, execution, run

from helvetic_lens import digests
from helvetic_lens.auth_mail import AuthMailer
from helvetic_lens.digest_briefs import attach, render
from helvetic_lens.models import (
    DigestDelivery,
    InterestEventAssessment,
    Job,
    Profile,
    RegulatoryDocumentVersion,
    RegulatoryEventState,
    User,
)

__all__ = ["artifacts", "execution"]


def ready(execution, *, locale="en-CH"):
    service = execution[0]
    from helvetic_lens.model_settings import local_docker_base_url
    # Match the same host/Compose endpoint normalization used by the real worker.
    # All requests are still intercepted by the synthetic HTTP transport.
    service.settings.apertus_base_url = local_docker_base_url()
    service.settings.apertus_product_id = ""
    service.model_client = execution[1].client
    user = recipient(service)
    with service.db.session() as session:
        session.get(User, user).locale = locale
        session.commit()
    execution[5]["locale"] = execution[6]["profiles"][0]["grants"][0]["locale"] = locale
    execution[7]()
    settled_matches(service)
    service.save_digest_preference(user, enabled=True, frequency="weekly", sources=[], severities=[])
    saved = run(execution, locale=locale[:2])
    assert saved["status"] == "succeeded"
    return service, user, saved


async def preview(service, user, **kwargs):
    async with service.runtime_cache_scope():
        return service.digest_overview(user, preview_page=True, **kwargs)["preview"]


async def observed(service):
    async with service.runtime_cache_scope():
        return service.brief_read_context(), service.relation_runtime_observation()


@pytest.mark.parametrize("locale", ["de-CH", "fr-CH", "it-CH", "rm-CH", "en-CH"])
def test_approved_saved_variant_uses_recipients_language(execution, locale):
    service, user, saved = ready(execution, locale=locale)
    requests_before = len(execution[4]["requests"])
    brief = asyncio.run(preview(service, user))["events"][0]["brief"]
    assert brief["status"] == "available" and brief["locale"] == locale[:2]
    assert brief["assessment_id"] == saved["id"]
    assert len(execution[4]["requests"]) == requests_before + 1  # one metadata GET, no per-event probes
    assert len(execution[4]["generated"]) == 1


@pytest.mark.parametrize("state", ["queued", "running", "failed"])
def test_unfinished_saved_brief_is_not_presented_as_low_importance(execution, state):
    service, user, saved = ready(execution)
    with service.db.session() as session:
        record = session.get(InterestEventAssessment, saved["id"])
        record.status, record.result = state, None
        session.commit()
    brief = asyncio.run(preview(service, user))["events"][0]["brief"]
    assert brief["status"] == ("failed" if state == "failed" else "pending")
    assert "importance" not in brief and "what_happened" not in brief
    assert len(execution[4]["generated"]) == 1


def test_digest_excerpt_preserves_complete_saved_reason_set(execution, harness):
    from test_topic_matching import create_topic
    from test_topic_validity import evaluate
    for index in range(2):
        topic = create_topic(harness[0], key=f"extra-digest-brief-{index}", name=f"Additional naturalisation interest {index}")
        evaluate(execution[0], topic, execution[2], "history")
    service, user, saved = ready(execution)
    brief = asyncio.run(preview(service, user))["events"][0]["brief"]
    assert brief["more_reasons"] and len(brief["why_in_radar"]) == 3
    with service.db.session() as session:
        assert len(session.get(InterestEventAssessment, saved["id"]).result["why_in_radar"]) == 4
    assert len(execution[4]["generated"]) == 1


def test_preview_and_actual_delivery_reuse_same_saved_assessment(execution, monkeypatch):
    service, user, saved = ready(execution)
    state = execution[4]
    generated, counts = len(state["generated"]), len(state["counts"])
    summary = asyncio.run(preview(service, user))
    brief = summary["events"][0]["brief"]
    assert brief["status"] == "available" and brief["assessment_id"] == saved["id"]
    assert brief["what_happened"] == saved["result"]["what_happened"]
    assert brief["locale"] == "en" and len(brief["why_in_radar"]) == 2
    assert all(url.startswith("/corpus-evidence/") for url in brief["evidence_links"].values())
    captured = []
    def mail(_self, *args, **kwargs):
        captured.append(args)
        return "development"
    monkeypatch.setattr(AuthMailer, "send_message", mail)
    job = service.enqueue_digest_now(user)
    result = asyncio.run(service.execute_job(job["id"]))
    assert result["state"] == "succeeded", result
    assert len(captured) == 1 and brief["what_happened"]["text"] in captured[0][2]
    assert "/corpus-evidence/" in captured[0][2] and "/corpus-evidence/" in captured[0][3]
    with service.db.session() as session:
        delivery = session.get(DigestDelivery, job["target_id"])
        assert delivery.summary["events"][0]["brief"] == brief
        assert session.scalar(select(func.count()).select_from(InterestEventAssessment)) == 1
        assert session.scalar(select(func.count()).select_from(Job).where(Job.type == "interest_event_brief")) == 0
    assert len(state["generated"]) == generated and len(state["counts"]) == counts


@pytest.mark.parametrize("locale", ["de-CH", "fr-CH", "it-CH", "rm-CH"])
def test_missing_recipient_language_never_falls_back_to_english(execution, locale):
    service, user, _ = ready(execution)
    with service.db.session() as session:
        session.get(User, user).locale = locale
        session.commit()
    brief = asyncio.run(preview(service, user))["events"][0]["brief"]
    assert brief["status"] == "not_scheduled" and brief["locale"] == locale[:2]
    assert "what_happened" not in brief
    override = asyncio.run(preview(service, user, output_locale="en-CH"))["events"][0]["brief"]
    assert override["status"] == "available"
    assert len(execution[4]["generated"]) == 1


@pytest.mark.parametrize("change", ["profile", "evidence", "invalid", "context", "foreign_context", "revoked", "offline"])
def test_currentness_and_access_fences_withhold_old_prose(execution, change):
    service, user, saved = ready(execution)
    context, _ = asyncio.run(observed(service))
    with service.db.session() as session:
        configuration = service.brief_configuration(session)
        if change == "profile":
            session.scalar(select(Profile)).revision += 1
        elif change == "evidence":
            session.get(RegulatoryDocumentVersion, execution[3]).evidence_revision += 1
        elif change == "invalid":
            row = session.get(InterestEventAssessment, saved["id"])
            row.result = {**row.result, "what_happened": {"text": "UNVERIFIED", "evidence_ids": ["foreign"]}}
        elif change == "context":
            configuration = "different-public-settings"
        elif change == "foreign_context":
            context = replace(context, organization_id="another-tenant")
        elif change == "revoked":
            session.execute(delete(RegulatoryEventState).where(RegulatoryEventState.event_id == execution[2]))
        elif change == "offline":
            context = None
        session.commit()
        summary = {"events": [{"event_id": execution[2]}]}
        summary = attach(session, service.organization_id, summary, "en", context=context, configuration=configuration)
        assert summary["events"][0]["brief"]["status"] != "available"
        assert "what_happened" not in summary["events"][0]["brief"]
    assert len(execution[4]["generated"]) == 1


def test_recipient_locale_is_reloaded_at_send_not_from_preparation(execution, monkeypatch):
    service, user, _ = ready(execution)
    job = service.enqueue_digest_now(user)
    context, runtime = asyncio.run(observed(service))
    with service.db.session() as session:
        selection = digests.prepare_batch(session, job["target_id"], settings=service.settings, runtime=runtime)
        session.get(User, user).locale = "fr-CH"
        session.commit()
    captured = []
    monkeypatch.setattr(AuthMailer, "send_message", lambda _self, *args, **kwargs: captured.append(args) or "development")
    result = digests.deliver(service.db, service.environment_settings, job["target_id"], selection=selection,
                            analysis_settings=service.settings, runtime=runtime, brief_context=context)
    assert result["status"] == "succeeded" and len(captured) == 1
    assert result["summary"]["events"][0]["brief"]["locale"] == "fr"
    assert result["summary"]["events"][0]["brief"]["status"] == "not_scheduled"
    assert "Synthetic source provides" not in captured[0][2] and '<html lang="fr-CH">' in captured[0][3]
    assert len(execution[4]["generated"]) == 1


@pytest.mark.parametrize("locale", ["de", "fr", "it", "rm", "en"])
def test_email_copy_escapes_prose_and_never_renders_another_language(execution, locale):
    service, user, _ = ready(execution)
    brief = asyncio.run(preview(service, user))["events"][0]["brief"]
    # Rendering fixture only, not a claim of multilingual model approval.
    brief["locale"] = locale
    brief["what_happened"]["text"] = '<script>alert("synthetic")</script>'
    text, html = render(brief, f"{locale}-CH", lambda path: "https://example.invalid" + path)
    assert "<script>" not in html and "&lt;script&gt;" in html
    assert any("/corpus-evidence/" in line for line in text)
    assert f'lang="{locale}"' in html
    other = "fr-CH" if locale == "en" else "en-CH"
    assert "&lt;script&gt;" not in render(brief, other, lambda path: path)[1]
