import type { Locale } from "./i18n";
const en = {
  title: "Auction ending-soon reminders",
  schedule: "Reminder schedule",
  empty: "No reminders on this page.",
  note: "Follow a lot and set hours before its end in your profile. A reminder needs current source evidence and a known deadline. Acknowledging it does not review the lot or place a bid.",
  scheduled: "Scheduled",
  ready: "Ready",
  acknowledged: "Acknowledged",
  invalidated: "No longer applicable",
  waiting: "Waiting for current eligible evidence",
  due: "Reminder due",
  end: "Auction ends",
  hours: "Hours before end",
  acknowledge: "Acknowledge reminder",
  open: "Open reminder",
  unavailable:
    "Some reminders cannot be shown with current source access or evidence.",
};
export const auctionReminderCopy: Record<
  Locale,
  Record<keyof typeof en, string>
> = {
  "en-CH": en,
  "de-CH": {
    title: "Erinnerungen an das Auktionsende",
    schedule: "Geplante Erinnerungen",
    empty: "Keine Erinnerungen auf dieser Seite.",
    note: "Verfolgen Sie ein Los und wählen Sie im Profil die Stunden vor Auktionsende. Erinnerungen benötigen aktuelle Quelldaten und einen bekannten Endtermin. Eine Bestätigung prüft kein Los und gibt kein Gebot ab.",
    scheduled: "Geplant",
    ready: "Bereit",
    acknowledged: "Bestätigt",
    invalidated: "Nicht mehr anwendbar",
    waiting: "Wartet auf aktuelle geeignete Belege",
    due: "Erinnerung fällig",
    end: "Auktionsende",
    hours: "Stunden vor dem Ende",
    acknowledge: "Erinnerung bestätigen",
    open: "Erinnerung öffnen",
    unavailable:
      "Einige Erinnerungen sind mit dem aktuellen Quellenzugang oder Datenstand nicht verfügbar.",
  },
  "fr-CH": {
    title: "Rappels de fin d’enchères",
    schedule: "Calendrier des rappels",
    empty: "Aucun rappel sur cette page.",
    note: "Suivez un lot et choisissez les heures avant sa fin dans votre profil. Les rappels exigent des données actuelles et une échéance connue. Confirmer un rappel n’examine pas le lot et ne place aucune enchère.",
    scheduled: "Planifié",
    ready: "Prêt",
    acknowledged: "Confirmé",
    invalidated: "N’est plus applicable",
    waiting: "En attente de données actuelles admissibles",
    due: "Rappel prévu",
    end: "Fin des enchères",
    hours: "Heures avant la fin",
    acknowledge: "Confirmer le rappel",
    open: "Ouvrir le rappel",
    unavailable:
      "Certains rappels ne sont pas disponibles avec les droits ou données actuels.",
  },
  "it-CH": {
    title: "Promemoria di conclusione aste",
    schedule: "Calendario promemoria",
    empty: "Nessun promemoria in questa pagina.",
    note: "Segui un lotto e scegli le ore prima della fine nel profilo. I promemoria richiedono dati attuali e una scadenza nota. Confermare un promemoria non esamina il lotto e non effettua offerte.",
    scheduled: "Programmato",
    ready: "Pronto",
    acknowledged: "Confermato",
    invalidated: "Non più applicabile",
    waiting: "In attesa di dati attuali idonei",
    due: "Promemoria previsto",
    end: "Fine asta",
    hours: "Ore prima della fine",
    acknowledge: "Conferma promemoria",
    open: "Apri promemoria",
    unavailable:
      "Alcuni promemoria non sono disponibili con i permessi o i dati attuali.",
  },
  "rm-CH": {
    title: "Regurdanzas a la fin d’inchants",
    schedule: "Plan da regurdanzas",
    empty: "Naginas regurdanzas sin questa pagina.",
    note: "Suandai in lot e tschernì las uras avant la fin en il profil. Regurdanzas dovran datas actualas ed in termin enconuschent. Confermar ina regurdientscha na controlla nagin lot e na fa nagina offerta.",
    scheduled: "Planisà",
    ready: "Pront",
    acknowledged: "Confermà",
    invalidated: "Betg pli applitgabel",
    waiting: "Spetga datas actualas adattadas",
    due: "Regurdientscha planisada",
    end: "Fin da l’inchant",
    hours: "Uras avant la fin",
    acknowledge: "Confermar regurdientscha",
    open: "Avrir regurdientscha",
    unavailable:
      "Intginas regurdanzas n’èn betg disponiblas cun las permissiuns u datas actualas.",
  },
};
