import type { Locale } from "./i18n";

const en = {
  title: "Auction Watch",
  intro: "Save the assets, places and price limits you want to follow.",
  private:
    "Profiles and settings are private to your account in this organization.",
  source:
    "Official auction data access is not configured yet. You can save your interests now. Saving does not start collection or send notifications.",
  assessment:
    "Starting prices, estimates and current bids are different. Choose which price your budget applies to; missing prices remain unknown. Decisions in Helvetic Lens never place a bid.",
  saved: "Saved profiles",
  create: "Create auction profile",
  portfolio: "Profile name",
  save: "Save draft",
  edit: "Edit profile",
  history: "Configuration history",
  version: "Version",
  archive: "Archive profile",
  remove: "Delete profile",
  confirm: "Permanently delete this archived profile and its private history?",
  cancel: "Cancel",
  refresh: "Refresh",
  back: "Back",
  next: "Next page",
  loading: "Loading profiles…",
  empty: "No saved profiles.",
  failed: "The profile is unavailable. Refresh and try again.",
  conflict: "The profile changed. Refresh before saving again.",
  invalid: "Check the name, categories, price and reminder hours.",
  unavailable: "Auction Watch is unavailable for this account or environment.",
  readonly: "Changes require an organization administrator role.",
  draft: "Draft",
  active: "Active",
  paused: "Paused",
  archived: "Archived",
  categories: "Asset categories",
  geography: "Initial source area: Ticino (TI)",
  locations: "Asset locations",
  keywords: "Words or phrases",
  brands: "Brands",
  lines:
    "One per line; up to 30. Explicit phrases only, without automatic translation.",
  budget: "Maximum price (CHF; blank for no limit)",
  priceKind: "Compare budget with",
  reminder: "Ending-soon reminder (hours before end; blank for none)",
  notices: "Changes to follow",
  settingsOnly:
    "These preferences are saved for future monitoring. Email consent is separate and is not granted by this form.",
  official: "Open official Ticino auctions",
  none: "Not set",
  real_estate: "Real estate",
  vehicles: "Vehicles",
  equipment: "Equipment",
  furniture: "Furniture",
  bicycles: "Bicycles",
  jewellery: "Jewellery",
  precious_metals: "Precious metals",
  other: "Other assets",
  current_bid: "Current bid",
  starting_price: "Starting price",
  minimum_price: "Minimum price",
  estimate: "Estimate",
  new_match: "New matching auctions",
  price_above_limit: "Price crosses above my limit",
  every_bid_change: "Every bid change",
  deadline_change: "Deadline changes",
  documents_change: "Document changes",
  conditions_change: "Condition changes",
  cancellation: "Cancellation",
};
type Copy = Record<keyof typeof en, string>;
export const auctionCopy: Record<Locale, Copy> = {
  "en-CH": en,
  "de-CH": {
    title: "Auktionsmonitoring",
    intro: "Speichern Sie gesuchte Objekte, Orte und Preisgrenzen.",
    private:
      "Profile und Einstellungen sind in dieser Organisation nur für Ihr Konto sichtbar.",
    source:
      "Der Zugang zu offiziellen Auktionsdaten ist noch nicht eingerichtet. Sie können Ihre Interessen bereits speichern. Speichern startet weder die Datensammlung noch Benachrichtigungen.",
    assessment:
      "Startpreise, Schätzwerte und aktuelle Gebote sind verschieden. Wählen Sie den Preis für Ihre Budgetprüfung; fehlende Preise bleiben unbekannt. Entscheidungen in Helvetic Lens geben niemals ein Gebot ab.",
    saved: "Gespeicherte Profile",
    create: "Auktionsprofil erstellen",
    portfolio: "Profilname",
    save: "Entwurf speichern",
    edit: "Profil bearbeiten",
    history: "Einstellungsverlauf",
    version: "Version",
    archive: "Profil archivieren",
    remove: "Profil löschen",
    confirm:
      "Dieses archivierte Profil und seinen privaten Verlauf endgültig löschen?",
    cancel: "Abbrechen",
    refresh: "Aktualisieren",
    back: "Zurück",
    next: "Nächste Seite",
    loading: "Profile werden geladen…",
    empty: "Keine gespeicherten Profile.",
    failed:
      "Das Profil ist nicht verfügbar. Aktualisieren und erneut versuchen.",
    conflict: "Das Profil wurde geändert. Vor dem Speichern aktualisieren.",
    invalid: "Name, Kategorien, Preis und Erinnerungsstunden prüfen.",
    unavailable:
      "Auktionsmonitoring ist für dieses Konto oder diese Umgebung nicht verfügbar.",
    readonly: "Änderungen erfordern die Rolle Organisationsadministrator.",
    draft: "Entwurf",
    active: "Aktiv",
    paused: "Pausiert",
    archived: "Archiviert",
    categories: "Objektkategorien",
    geography: "Anfängliches Quellengebiet: Tessin (TI)",
    locations: "Standorte der Objekte",
    keywords: "Wörter oder Ausdrücke",
    brands: "Marken",
    lines:
      "Ein Eintrag pro Zeile, höchstens 30. Explizite Ausdrücke ohne automatische Übersetzung.",
    budget: "Höchstpreis (CHF; leer für keine Grenze)",
    priceKind: "Budget vergleichen mit",
    reminder: "Erinnerung vor Auktionsende (Stunden; leer für keine)",
    notices: "Zu beobachtende Änderungen",
    settingsOnly:
      "Diese Einstellungen werden für künftiges Monitoring gespeichert. Dieses Formular erteilt keine E-Mail-Einwilligung.",
    official: "Offizielle Tessiner Auktionen öffnen",
    none: "Nicht festgelegt",
    real_estate: "Immobilien",
    vehicles: "Fahrzeuge",
    equipment: "Ausrüstung",
    furniture: "Möbel",
    bicycles: "Fahrräder",
    jewellery: "Schmuck",
    precious_metals: "Edelmetalle",
    other: "Andere Objekte",
    current_bid: "Aktuelles Gebot",
    starting_price: "Startpreis",
    minimum_price: "Mindestpreis",
    estimate: "Schätzwert",
    new_match: "Neue passende Auktionen",
    price_above_limit: "Preis überschreitet meine Grenze",
    every_bid_change: "Jede Gebotsänderung",
    deadline_change: "Friständerungen",
    documents_change: "Dokumentänderungen",
    conditions_change: "Geänderte Bedingungen",
    cancellation: "Absage",
  },
  "fr-CH": {
    title: "Veille des enchères",
    intro: "Enregistrez les biens, lieux et limites de prix à suivre.",
    private: "Vos profils et réglages sont privés dans cette organisation.",
    source:
      "L’accès aux données officielles des enchères n’est pas encore configuré. Vous pouvez enregistrer vos intérêts. Cela ne lance ni collecte ni notification.",
    assessment:
      "Prix de départ, estimations et offres actuelles sont distincts. Choisissez le prix auquel appliquer votre budget ; un prix absent reste inconnu. Les décisions dans Helvetic Lens ne placent jamais d’offre.",
    saved: "Profils enregistrés",
    create: "Créer un profil d’enchères",
    portfolio: "Nom du profil",
    save: "Enregistrer le brouillon",
    edit: "Modifier le profil",
    history: "Historique des réglages",
    version: "Version",
    archive: "Archiver le profil",
    remove: "Supprimer le profil",
    confirm:
      "Supprimer définitivement ce profil archivé et son historique privé ?",
    cancel: "Annuler",
    refresh: "Actualiser",
    back: "Retour",
    next: "Page suivante",
    loading: "Chargement des profils…",
    empty: "Aucun profil enregistré.",
    failed: "Profil indisponible. Actualisez et réessayez.",
    conflict: "Le profil a changé. Actualisez avant d’enregistrer.",
    invalid:
      "Vérifiez le nom, les catégories, le prix et les heures de rappel.",
    unavailable:
      "La veille des enchères est indisponible pour ce compte ou cet environnement.",
    readonly:
      "Les modifications nécessitent le rôle d’administrateur de l’organisation.",
    draft: "Brouillon",
    active: "Actif",
    paused: "En pause",
    archived: "Archivé",
    categories: "Catégories de biens",
    geography: "Zone initiale de la source : Tessin (TI)",
    locations: "Lieux des biens",
    keywords: "Mots ou expressions",
    brands: "Marques",
    lines:
      "Un par ligne, 30 maximum. Expressions explicites, sans traduction automatique.",
    budget: "Prix maximal (CHF ; vide pour aucune limite)",
    priceKind: "Comparer le budget avec",
    reminder: "Rappel de clôture (heures avant la fin ; vide pour aucun)",
    notices: "Changements à suivre",
    settingsOnly:
      "Ces préférences sont conservées pour le suivi futur. Ce formulaire n’accorde pas de consentement aux e-mails.",
    official: "Ouvrir les enchères officielles du Tessin",
    none: "Non défini",
    real_estate: "Immobilier",
    vehicles: "Véhicules",
    equipment: "Équipement",
    furniture: "Mobilier",
    bicycles: "Vélos",
    jewellery: "Bijoux",
    precious_metals: "Métaux précieux",
    other: "Autres biens",
    current_bid: "Offre actuelle",
    starting_price: "Prix de départ",
    minimum_price: "Prix minimal",
    estimate: "Estimation",
    new_match: "Nouvelles enchères pertinentes",
    price_above_limit: "Le prix dépasse ma limite",
    every_bid_change: "Chaque changement d’offre",
    deadline_change: "Changements d’échéance",
    documents_change: "Changements de documents",
    conditions_change: "Changements des conditions",
    cancellation: "Annulation",
  },
  "it-CH": {
    title: "Monitoraggio aste",
    intro: "Salva i beni, i luoghi e i limiti di prezzo da seguire.",
    private:
      "Profili e impostazioni sono privati per il tuo account nell’organizzazione.",
    source:
      "L’accesso ai dati ufficiali delle aste non è ancora configurato. Puoi già salvare i tuoi interessi. Il salvataggio non avvia raccolte o notifiche.",
    assessment:
      "Prezzo iniziale, stima e offerta corrente sono distinti. Scegli quale prezzo confrontare con il budget; i prezzi mancanti restano sconosciuti. Le decisioni in Helvetic Lens non presentano mai offerte.",
    saved: "Profili salvati",
    create: "Crea profilo aste",
    portfolio: "Nome del profilo",
    save: "Salva bozza",
    edit: "Modifica profilo",
    history: "Cronologia impostazioni",
    version: "Versione",
    archive: "Archivia profilo",
    remove: "Elimina profilo",
    confirm:
      "Eliminare definitivamente questo profilo archiviato e la sua cronologia privata?",
    cancel: "Annulla",
    refresh: "Aggiorna",
    back: "Indietro",
    next: "Pagina successiva",
    loading: "Caricamento profili…",
    empty: "Nessun profilo salvato.",
    failed: "Profilo non disponibile. Aggiorna e riprova.",
    conflict: "Il profilo è cambiato. Aggiorna prima di salvare.",
    invalid: "Controlla nome, categorie, prezzo e ore di promemoria.",
    unavailable:
      "Monitoraggio aste non disponibile per questo account o ambiente.",
    readonly:
      "Le modifiche richiedono il ruolo di amministratore dell’organizzazione.",
    draft: "Bozza",
    active: "Attivo",
    paused: "In pausa",
    archived: "Archiviato",
    categories: "Categorie di beni",
    geography: "Area iniziale della fonte: Ticino (TI)",
    locations: "Ubicazione dei beni",
    keywords: "Parole o frasi",
    brands: "Marche",
    lines:
      "Una voce per riga, massimo 30. Frasi esplicite, senza traduzione automatica.",
    budget: "Prezzo massimo (CHF; vuoto per nessun limite)",
    priceKind: "Confronta il budget con",
    reminder: "Promemoria scadenza (ore prima della fine; vuoto per nessuno)",
    notices: "Modifiche da seguire",
    settingsOnly:
      "Preferenze salvate per il monitoraggio futuro. Questo modulo non concede il consenso alle e-mail.",
    official: "Apri le aste ufficiali del Ticino",
    none: "Non impostato",
    real_estate: "Immobili",
    vehicles: "Veicoli",
    equipment: "Attrezzature",
    furniture: "Mobili",
    bicycles: "Biciclette",
    jewellery: "Gioielli",
    precious_metals: "Metalli preziosi",
    other: "Altri beni",
    current_bid: "Offerta corrente",
    starting_price: "Prezzo iniziale",
    minimum_price: "Prezzo minimo",
    estimate: "Stima",
    new_match: "Nuove aste pertinenti",
    price_above_limit: "Il prezzo supera il mio limite",
    every_bid_change: "Ogni modifica dell’offerta",
    deadline_change: "Modifiche della scadenza",
    documents_change: "Modifiche dei documenti",
    conditions_change: "Modifiche delle condizioni",
    cancellation: "Annullamento",
  },
  "rm-CH": {
    title: "Observaziun d’aucziuns",
    intro:
      "Memorisai ils objects, ils lieus ed ils limits da pretsch da suandar.",
    private:
      "Profils e parameters èn privats per Voss conto en questa organisaziun.",
    source:
      "L’access a las datas uffizialas d’aucziuns n’è anc betg configurà. Vus pudais memorisar Voss interess. Quai na cumenza nagina rimnada e na trametta naginas notificaziuns.",
    assessment:
      "Pretsch inizial, stimaziun ed offerta actuala èn differents. Tschernei il pretsch per Voss budget; pretschs mancants restan nunenconuschents. Decisiuns en Helvetic Lens na fan mai in’offerta.",
    saved: "Profils memorisads",
    create: "Crear profil d’aucziuns",
    portfolio: "Num dal profil",
    save: "Memorisar sboz",
    edit: "Modifitgar profil",
    history: "Istorgia dals parameters",
    version: "Versiun",
    archive: "Archivar profil",
    remove: "Stizzar profil",
    confirm:
      "Stizzar definitivamain quest profil archivà e sia istorgia privata?",
    cancel: "Interrumper",
    refresh: "Actualisar",
    back: "Enavos",
    next: "Proxima pagina",
    loading: "Chargiar profils…",
    empty: "Nagins profils memorisads.",
    failed: "Profil betg disponibel. Actualisai e pruvai anc ina giada.",
    conflict: "Il profil è sa midà. Actualisai avant da memorisar.",
    invalid: "Controllai num, categorias, pretsch ed uras dal pro memoria.",
    unavailable:
      "L’observaziun d’aucziuns n’è betg disponibla per quest conto u ambient.",
    readonly: "Midadas dovran la rolla d’administratur da l’organisaziun.",
    draft: "Sboz",
    active: "Activ",
    paused: "En pausa",
    archived: "Archivà",
    categories: "Categorias d’objects",
    geography: "Regiun iniziala da la funtauna: Tessin (TI)",
    locations: "Lieus dals objects",
    keywords: "Pleds u expressiuns",
    brands: "Marcas",
    lines:
      "Ina per lingia, maximalmain 30. Expressiuns explicitas senza translaziun automatica.",
    budget: "Pretsch maximal (CHF; vid per nagin limit)",
    priceKind: "Cumparegliar il budget cun",
    reminder: "Pro memoria (uras avant la fin; vid per nagin)",
    notices: "Midadas da suandar",
    settingsOnly:
      "Quests parameters vegnan memorisads per l’observaziun futura. Quest formular na dat nagin consentiment per e-mails.",
    official: "Avrir las aucziuns uffizialas dal Tessin",
    none: "Betg definì",
    real_estate: "Immobiglias",
    vehicles: "Vehichels",
    equipment: "Equipament",
    furniture: "Mobiglias",
    bicycles: "Velos",
    jewellery: "Bischutaria",
    precious_metals: "Metals prezius",
    other: "Auters objects",
    current_bid: "Offerta actuala",
    starting_price: "Pretsch inizial",
    minimum_price: "Pretsch minimal",
    estimate: "Stimaziun",
    new_match: "Novas aucziuns adattadas",
    price_above_limit: "Il pretsch surpassa mes limit",
    every_bid_change: "Mintga midada d’offerta",
    deadline_change: "Midadas dal termin",
    documents_change: "Midadas da documents",
    conditions_change: "Midadas da cundiziuns",
    cancellation: "Annullaziun",
  },
};
