import type { Locale } from "./i18n";

const en = {
  sourceHelp:
    "Each profile checks access to official auction records before monitoring starts. Coverage can be partial.",
  check: "Check source access",
  start: "Start monitoring",
  pause: "Pause monitoring",
  resume: "Resume monitoring",
  sourceReady: "Current official records are available for this profile.",
  partial: "This does not establish complete canton coverage.",
  missing:
    "Source access or current records are missing. Your profile is saved; live monitoring has not started.",
  cantons: "Unverified cantons",
  lastCheck: "Last check",
  nextCheck: "Next check",
  items: "Auction and lot watchlist",
  empty:
    "No matching or uncertain candidates have been saved yet. An empty list does not prove that no auctions exist.",
  refreshItems: "Check saved source updates",
  onlyFollowed: "Only followed lots",
  follow: "Follow this lot",
  unfollow: "Stop following",
  inspect: "Inspect",
  bid: "Considering a bid",
  no_bid: "No bid",
  monitor: "Monitor",
  decision: "Internal decision",
  internal:
    "These decisions are private planning notes. They do not register you, contact the seller or place a bid.",
  needsReview: "Review again",
  reviewed: "Reviewed",
  unknown: "Unknown",
  match: "Matches profile",
  excluded: "Outside profile",
  explanation: "Why this result",
  unavailable:
    "Current source evidence is unavailable or awaiting refresh. Saved decisions remain visible.",
  noDecisionAccess:
    "The current source permission does not allow a new review decision.",
  price: "Published prices",
  status: "Official status",
  deadline: "Auction ends",
  observed: "Observed",
  official: "Official source",
  history: "Source version history",
  description: "Description",
  documents: "Document references",
  sourceVersion: "Source version",
  unavailableVersion: "This version's source content is no longer available.",
  minorUnits: "minor units",
  source: "Source",
  email:
    "Email and ending-soon delivery are not available yet. Review changes in this watchlist.",
  fields: {
    canton: "Canton",
    category: "Category",
    asset_location: "Asset location",
    brand: "Brand",
    title_description: "Words or phrases",
    budget: "Budget",
  },
  statuses: {
    announced: "Announced",
    open: "Open",
    closed: "Closed",
    cancelled: "Cancelled",
    postponed: "Postponed",
    unknown: "Unknown",
  },
};
type Copy = {
  [K in keyof typeof en]: (typeof en)[K] extends string
    ? string
    : Record<keyof (typeof en)[K], string>;
};
export const auctionTrackingCopy: Record<Locale, Copy> = {
  "en-CH": en,
  "de-CH": {
    sourceHelp:
      "Jedes Profil prüft vor dem Start den Zugang zu offiziellen Auktionsdaten. Die Abdeckung kann unvollständig sein.",
    check: "Quellenzugang prüfen",
    start: "Monitoring starten",
    pause: "Monitoring pausieren",
    resume: "Monitoring fortsetzen",
    sourceReady:
      "Aktuelle offizielle Datensätze sind für dieses Profil verfügbar.",
    partial: "Dies bestätigt keine vollständige kantonale Abdeckung.",
    missing:
      "Quellenzugang oder aktuelle Daten fehlen. Ihr Profil ist gespeichert; das Live-Monitoring wurde nicht gestartet.",
    cantons: "Nicht bestätigte Kantone",
    lastCheck: "Letzte Prüfung",
    nextCheck: "Nächste Prüfung",
    items: "Beobachtete Auktionen und Lose",
    empty:
      "Noch keine passenden oder unklaren Kandidaten gespeichert. Eine leere Liste beweist nicht, dass es keine Auktionen gibt.",
    refreshItems: "Gespeicherte Quellenänderungen prüfen",
    onlyFollowed: "Nur verfolgte Lose",
    follow: "Los verfolgen",
    unfollow: "Verfolgung beenden",
    inspect: "Besichtigen",
    bid: "Gebot erwägen",
    no_bid: "Kein Gebot",
    monitor: "Beobachten",
    decision: "Interne Entscheidung",
    internal:
      "Diese Entscheidungen sind private Planungsnotizen. Sie registrieren Sie nicht, kontaktieren keine Verkäufer und geben kein Gebot ab.",
    needsReview: "Erneut prüfen",
    reviewed: "Geprüft",
    unknown: "Unbekannt",
    match: "Passt zum Profil",
    excluded: "Ausserhalb des Profils",
    explanation: "Warum dieses Ergebnis",
    unavailable:
      "Aktuelle Quellenbelege fehlen oder werden aktualisiert. Gespeicherte Entscheidungen bleiben sichtbar.",
    noDecisionAccess:
      "Die aktuelle Quellenfreigabe erlaubt keine neue Prüfentscheidung.",
    price: "Veröffentlichte Preise",
    status: "Offizieller Status",
    deadline: "Auktionsende",
    observed: "Beobachtet",
    official: "Offizielle Quelle",
    history: "Quellenversionen",
    description: "Beschreibung",
    documents: "Dokumentreferenzen",
    sourceVersion: "Quellenversion",
    unavailableVersion:
      "Der Quelleninhalt dieser Version ist nicht mehr verfügbar.",
    minorUnits: "Untereinheiten",
    source: "Quelle",
    email:
      "E-Mail- und Endzeit-Erinnerungen sind noch nicht verfügbar. Prüfen Sie Änderungen in dieser Beobachtungsliste.",
    fields: {
      canton: "Kanton",
      category: "Kategorie",
      asset_location: "Standort",
      brand: "Marke",
      title_description: "Wörter oder Ausdrücke",
      budget: "Budget",
    },
    statuses: {
      announced: "Angekündigt",
      open: "Offen",
      closed: "Beendet",
      cancelled: "Abgesagt",
      postponed: "Verschoben",
      unknown: "Unbekannt",
    },
  },
  "fr-CH": {
    sourceHelp:
      "Chaque profil vérifie l’accès aux données officielles avant le démarrage. La couverture peut être partielle.",
    check: "Vérifier l’accès à la source",
    start: "Démarrer le suivi",
    pause: "Suspendre le suivi",
    resume: "Reprendre le suivi",
    sourceReady:
      "Des données officielles actuelles sont disponibles pour ce profil.",
    partial: "Cela ne confirme pas une couverture cantonale complète.",
    missing:
      "L’accès à la source ou les données actuelles manquent. Votre profil est enregistré ; le suivi en direct n’a pas démarré.",
    cantons: "Cantons non vérifiés",
    lastCheck: "Dernière vérification",
    nextCheck: "Prochaine vérification",
    items: "Enchères et lots suivis",
    empty:
      "Aucun résultat correspondant ou incertain n’a encore été enregistré. Une liste vide ne prouve pas l’absence d’enchères.",
    refreshItems: "Vérifier les mises à jour enregistrées",
    onlyFollowed: "Lots suivis uniquement",
    follow: "Suivre ce lot",
    unfollow: "Ne plus suivre",
    inspect: "Examiner",
    bid: "Envisager une offre",
    no_bid: "Pas d’offre",
    monitor: "Surveiller",
    decision: "Décision interne",
    internal:
      "Ces décisions sont des notes privées de planification. Elles ne vous inscrivent pas, ne contactent pas le vendeur et ne déposent aucune offre.",
    needsReview: "À réexaminer",
    reviewed: "Examiné",
    unknown: "Inconnu",
    match: "Correspond au profil",
    excluded: "Hors profil",
    explanation: "Pourquoi ce résultat",
    unavailable:
      "Les preuves actuelles de la source sont indisponibles ou en cours d’actualisation. Les décisions enregistrées restent visibles.",
    noDecisionAccess:
      "L’autorisation actuelle de la source ne permet pas de nouvelle décision d’examen.",
    price: "Prix publiés",
    status: "Statut officiel",
    deadline: "Fin des enchères",
    observed: "Observé",
    official: "Source officielle",
    history: "Historique des versions de la source",
    description: "Description",
    documents: "Références documentaires",
    sourceVersion: "Version de la source",
    unavailableVersion: "Le contenu de cette version n’est plus disponible.",
    minorUnits: "unités mineures",
    source: "Source",
    email:
      "Les e-mails et rappels de fin ne sont pas encore disponibles. Consultez les changements dans cette liste.",
    fields: {
      canton: "Canton",
      category: "Catégorie",
      asset_location: "Lieu du bien",
      brand: "Marque",
      title_description: "Mots ou expressions",
      budget: "Budget",
    },
    statuses: {
      announced: "Annoncé",
      open: "Ouvert",
      closed: "Terminé",
      cancelled: "Annulé",
      postponed: "Reporté",
      unknown: "Inconnu",
    },
  },
  "it-CH": {
    sourceHelp:
      "Ogni profilo verifica l’accesso ai dati ufficiali prima dell’avvio. La copertura può essere parziale.",
    check: "Verifica accesso alla fonte",
    start: "Avvia monitoraggio",
    pause: "Sospendi monitoraggio",
    resume: "Riprendi monitoraggio",
    sourceReady:
      "Sono disponibili dati ufficiali aggiornati per questo profilo.",
    partial: "Questo non conferma una copertura cantonale completa.",
    missing:
      "Mancano accesso alla fonte o dati aggiornati. Il profilo è salvato; il monitoraggio dal vivo non è iniziato.",
    cantons: "Cantoni non verificati",
    lastCheck: "Ultima verifica",
    nextCheck: "Prossima verifica",
    items: "Aste e lotti monitorati",
    empty:
      "Nessun risultato pertinente o incerto è ancora stato salvato. Un elenco vuoto non dimostra l’assenza di aste.",
    refreshItems: "Verifica aggiornamenti salvati",
    onlyFollowed: "Solo lotti seguiti",
    follow: "Segui questo lotto",
    unfollow: "Smetti di seguire",
    inspect: "Ispezionare",
    bid: "Valutare un’offerta",
    no_bid: "Nessuna offerta",
    monitor: "Monitorare",
    decision: "Decisione interna",
    internal:
      "Queste decisioni sono note di pianificazione private. Non effettuano iscrizioni, non contattano il venditore e non presentano offerte.",
    needsReview: "Da riesaminare",
    reviewed: "Esaminato",
    unknown: "Sconosciuto",
    match: "Corrisponde al profilo",
    excluded: "Fuori profilo",
    explanation: "Perché questo risultato",
    unavailable:
      "Le prove aggiornate della fonte non sono disponibili o sono in aggiornamento. Le decisioni salvate restano visibili.",
    noDecisionAccess:
      "L’autorizzazione attuale della fonte non consente una nuova decisione di revisione.",
    price: "Prezzi pubblicati",
    status: "Stato ufficiale",
    deadline: "Fine dell’asta",
    observed: "Osservato",
    official: "Fonte ufficiale",
    history: "Cronologia delle versioni della fonte",
    description: "Descrizione",
    documents: "Riferimenti ai documenti",
    sourceVersion: "Versione della fonte",
    unavailableVersion:
      "Il contenuto di questa versione non è più disponibile.",
    minorUnits: "unità minori",
    source: "Fonte",
    email:
      "E-mail e promemoria di scadenza non sono ancora disponibili. Controlla gli aggiornamenti in questo elenco.",
    fields: {
      canton: "Cantone",
      category: "Categoria",
      asset_location: "Ubicazione del bene",
      brand: "Marca",
      title_description: "Parole o frasi",
      budget: "Budget",
    },
    statuses: {
      announced: "Annunciato",
      open: "Aperto",
      closed: "Concluso",
      cancelled: "Annullato",
      postponed: "Rinviato",
      unknown: "Sconosciuto",
    },
  },
  "rm-CH": {
    sourceHelp:
      "Mintga profil controlla l’access a datas uffizialas avant il cumenzament. La cuvrida po esser parziala.",
    check: "Controllar l’access a la funtauna",
    start: "Cumenzar il monitoring",
    pause: "Pausar il monitoring",
    resume: "Cuntinuar il monitoring",
    sourceReady: "Datas uffizialas actualas èn disponiblas per quest profil.",
    partial: "Quai na conferma betg ina cuvrida chantunala cumpletta.",
    missing:
      "L’access a la funtauna u datas actualas mancan. Voss profil è memorisà; il monitoring actual n’ha betg cumenzà.",
    cantons: "Chantuns betg verifitgads",
    lastCheck: "Ultima controlla",
    nextCheck: "Proxima controlla",
    items: "Aucziuns e lots observads",
    empty:
      "Anc nagins resultats adattads u intscherts memorisads. Ina glista vida na cumprova betg ch’i na dat naginas aucziuns.",
    refreshItems: "Controllar actualisaziuns memorisadas",
    onlyFollowed: "Mo lots suandads",
    follow: "Suandar quest lot",
    unfollow: "Betg pli suandar",
    inspect: "Examinar",
    bid: "Examinar in’offerta",
    no_bid: "Naginas offertas",
    monitor: "Observar",
    decision: "Decisiun interna",
    internal:
      "Questas decisiuns èn notizias privatas da planisaziun. Ellas na registreschan betg, na contacteschan nagin vendider e na fan naginas offertas.",
    needsReview: "Examinar danovamain",
    reviewed: "Examinà",
    unknown: "Nunenconuschent",
    match: "Correspunda al profil",
    excluded: "Ordaifer il profil",
    explanation: "Pertge quest resultat",
    unavailable:
      "Las cumprovas actualas da la funtauna n’èn betg disponiblas u vegnan actualisadas. Decisiuns memorisadas restan visiblas.",
    noDecisionAccess:
      "La permissiun actuala da la funtauna na permetta betg ina nova decisiun d’examinaziun.",
    price: "Pretschs publitgads",
    status: "Status uffizial",
    deadline: "Fin da l’aucziun",
    observed: "Observà",
    official: "Funtauna uffiziala",
    history: "Istorgia da las versiuns da la funtauna",
    description: "Descripziun",
    documents: "Referenzas als documents",
    sourceVersion: "Versiun da la funtauna",
    unavailableVersion: "Il cuntegn da questa versiun n’è betg pli disponibel.",
    minorUnits: "unitads pitschnas",
    source: "Funtauna",
    email:
      "E-mails e regurdanzas da scadenza n’èn anc betg disponibels. Consultai las midadas en questa glista.",
    fields: {
      canton: "Chantun",
      category: "Categoria",
      asset_location: "Lieu da l’object",
      brand: "Marca",
      title_description: "Pleds u expressiuns",
      budget: "Budget",
    },
    statuses: {
      announced: "Annunzià",
      open: "Avert",
      closed: "Terminà",
      cancelled: "Annullà",
      postponed: "Spustà",
      unknown: "Nunenconuschent",
    },
  },
};
