import type {Locale} from "./i18n";
import type {SavedInterestBrief} from "./interest-brief";

export type HistoryItem={id:string;status:"queued"|"running"|"succeeded"|"failed"|"superseded";created_at:string;finished_at:string|null;attempts:number;locale:string;model:string;route:string;profile_revision:number};
export type BriefHistoryPage={event_id:string;locale:string;items:HistoryItem[];next_cursor:string|null};
export type HistoricalBrief=Omit<SavedInterestBrief,"status"> & {status:"historical"|"historical_unavailable"|"legacy_context_missing";assessment_status:HistoryItem["status"];provenance?:{input_fingerprint:string;profile_revision:number;provider_calls:number;model:{model:string;route:string;runtime_fingerprint:string}}};
type Copy={title:string;help:string;empty:string;refresh:string;older:string;first:string;open:string;model:string;profile:string;attempts:string;provenance:string;historical:string;historical_unavailable:string;legacy_context_missing:string;error:string;queued:string;running:string;succeeded:string;failed:string;superseded:string};
export const briefHistoryCopy:Record<Locale,Copy>={
  "en-CH":{title:"AI brief history",help:"Saved assessments for this event in your language. Opening history never generates or translates an answer. Earlier assessments describe their original inputs, not today's situation.",empty:"No assessments saved in this language.",refresh:"Refresh history",older:"Older assessments",first:"Latest assessments",open:"Inspect saved assessment",model:"Model",profile:"Profile revision",attempts:"Attempts",provenance:"Recorded analysis details",historical:"Historical assessment. Saved sources and original context were checked; current applicability and legal correctness are not established.",historical_unavailable:"This historical result cannot be validated against its saved context and currently accessible sources. No unverified prose is shown.",legacy_context_missing:"This older record has no complete historical context snapshot. Its metadata remains available; today's profile was not substituted.",error:"History could not be loaded. Retry without generating a new answer.",queued:"Queued",running:"Running",succeeded:"Saved",failed:"Failed",superseded:"Superseded"},
  "de-CH":{title:"Verlauf der KI-Analysen",help:"Gespeicherte Bewertungen dieses Ereignisses in Ihrer Sprache. Der Verlauf erzeugt oder übersetzt keine Antwort. Frühere Bewertungen beziehen sich auf damalige Eingaben, nicht auf die heutige Situation.",empty:"Keine Bewertungen in dieser Sprache gespeichert.",refresh:"Verlauf aktualisieren",older:"Ältere Bewertungen",first:"Neueste Bewertungen",open:"Gespeicherte Bewertung ansehen",model:"Modell",profile:"Profilfassung",attempts:"Versuche",provenance:"Aufgezeichnete Analysedetails",historical:"Historische Bewertung. Gespeicherte Quellen und ursprünglicher Kontext wurden geprüft; heutige Anwendbarkeit und rechtliche Richtigkeit sind nicht bestätigt.",historical_unavailable:"Dieses historische Ergebnis lässt sich nicht anhand des gespeicherten Kontexts und der zugänglichen Quellen validieren. Kein ungeprüfter Text wird angezeigt.",legacy_context_missing:"Dieser ältere Eintrag enthält keinen vollständigen historischen Kontext. Metadaten bleiben verfügbar; das heutige Profil wurde nicht eingesetzt.",error:"Verlauf konnte nicht geladen werden. Versuchen Sie es ohne neue Generierung erneut.",queued:"In Warteschlange",running:"Läuft",succeeded:"Gespeichert",failed:"Fehlgeschlagen",superseded:"Überholt"},
  "fr-CH":{title:"Historique des analyses IA",help:"Évaluations enregistrées pour cet événement dans votre langue. L’historique ne génère ni ne traduit de réponse. Les anciennes évaluations décrivent leurs données d’origine, pas la situation actuelle.",empty:"Aucune évaluation enregistrée dans cette langue.",refresh:"Actualiser l’historique",older:"Évaluations plus anciennes",first:"Évaluations récentes",open:"Consulter l’évaluation enregistrée",model:"Modèle",profile:"Révision du profil",attempts:"Tentatives",provenance:"Détails d’analyse enregistrés",historical:"Évaluation historique. Sources enregistrées et contexte d’origine vérifiés ; applicabilité actuelle et exactitude juridique non établies.",historical_unavailable:"Ce résultat historique ne peut pas être validé avec son contexte enregistré et les sources accessibles. Aucun texte non vérifié n’est affiché.",legacy_context_missing:"Cet ancien enregistrement ne contient pas de contexte historique complet. Ses métadonnées restent disponibles ; le profil actuel n’a pas été substitué.",error:"Impossible de charger l’historique. Réessayez sans générer de réponse.",queued:"En attente",running:"En cours",succeeded:"Enregistrée",failed:"Échec",superseded:"Remplacée"},
  "it-CH":{title:"Cronologia delle analisi IA",help:"Valutazioni salvate per questo evento nella tua lingua. La cronologia non genera né traduce risposte. Le valutazioni precedenti descrivono i dati originali, non la situazione attuale.",empty:"Nessuna valutazione salvata in questa lingua.",refresh:"Aggiorna cronologia",older:"Valutazioni precedenti",first:"Valutazioni recenti",open:"Consulta valutazione salvata",model:"Modello",profile:"Revisione del profilo",attempts:"Tentativi",provenance:"Dettagli dell’analisi registrata",historical:"Valutazione storica. Fonti salvate e contesto originale verificati; applicabilità attuale e correttezza legale non accertate.",historical_unavailable:"Questo risultato storico non può essere validato con il contesto salvato e le fonti accessibili. Nessun testo non verificato viene mostrato.",legacy_context_missing:"Questo vecchio record non contiene un contesto storico completo. I metadati restano disponibili; il profilo attuale non è stato sostituito.",error:"Impossibile caricare la cronologia. Riprova senza generare una nuova risposta.",queued:"In coda",running:"In corso",succeeded:"Salvata",failed:"Non riuscita",superseded:"Superata"},
  "rm-CH":{title:"Istorgia da las analisas IA",help:"Valitaziuns memorisadas per quest eveniment en Vossa lingua. L’istorgia na generescha ni translatescha respostas. Valitaziuns anteriuras descrivan lur datas originalas, betg la situaziun actuala.",empty:"Naginas valitaziuns memorisadas en questa lingua.",refresh:"Actualisar l’istorgia",older:"Valitaziuns pli veglias",first:"Valitaziuns recentas",open:"Examinar la valitaziun memorisada",model:"Model",profile:"Revisiun dal profil",attempts:"Emprovas",provenance:"Detagls da l’analisa registrada",historical:"Valitaziun istorica. Funtaunas memorisadas e context original examinads; applicabilitad actuala e correctadad giuridica betg confermadas.",historical_unavailable:"Quest resultat istoric na po betg vegnir validà cun il context memorisà e las funtaunas accessiblas. Nagins texts betg verifitgads vegnan mussads.",legacy_context_missing:"Questa registraziun pli veglia na cuntegna betg in context istoric cumplett. Las metadatas restan disponiblas; il profil actual n’è betg vegnì substituì.",error:"L’istorgia n’ha betg pudì vegnir chargiada. Empruvai danovamain senza generar ina resposta.",queued:"En colonna",running:"En elavuraziun",succeeded:"Memorisada",failed:"Betg reussida",superseded:"Surpassada"},
};
