import type { Locale } from "./i18n";

export type FeedbackDecision = "useful" | "not_useful" | "withdrawn";
export type BriefFeedbackRecord = {id: string; assessment_id: string; decision: FeedbackDecision; note: string; created_at: string};
export type BriefFeedbackPage = {assessment_id: string; latest: BriefFeedbackRecord | null; items: BriefFeedbackRecord[]; has_more: boolean; next_cursor: string | null};
type Copy = {title: string; help: string; useful: string; not_useful: string; withdrawn: string; withdraw: string; note: string; saving: string; saved: string; history: string; next: string; first: string; reload: string; failed: string; conflict: string; limit: string};
export const briefFeedbackCopy: Record<Locale, Copy> = {
  "en-CH": {title:"Was this AI brief useful?",help:"Your feedback concerns this saved brief only. It does not change the shared analysis, monitoring rules or model. Do not include sensitive information.",useful:"Useful",not_useful:"Not useful",withdrawn:"Feedback withdrawn",withdraw:"Withdraw feedback",note:"Optional explanation (up to 1,000 characters)",saving:"Saving…",saved:"Your saved feedback",history:"Your feedback history",next:"Older feedback",first:"Latest feedback",reload:"Reload feedback",failed:"Could not load or save feedback. Your text is retained; reload and try again.",conflict:"Your feedback changed in another session. Reload and review it before saving again.",limit:"You have reached 24-hour feedback limit. Try again later."},
  "de-CH": {title:"War diese KI-Kurzbewertung hilfreich?",help:"Ihre Rückmeldung betrifft nur diese gespeicherte Bewertung. Sie ändert weder die gemeinsame Analyse noch Überwachungsregeln oder Modell. Geben Sie keine sensiblen Informationen ein.",useful:"Hilfreich",not_useful:"Nicht hilfreich",withdrawn:"Rückmeldung zurückgezogen",withdraw:"Rückmeldung zurückziehen",note:"Optionale Begründung (bis zu 1’000 Zeichen)",saving:"Wird gespeichert…",saved:"Ihre gespeicherte Rückmeldung",history:"Ihr Rückmeldungsverlauf",next:"Ältere Rückmeldungen",first:"Neueste Rückmeldungen",reload:"Rückmeldungen neu laden",failed:"Rückmeldungen konnten nicht geladen oder gespeichert werden. Ihr Text bleibt erhalten; laden Sie neu und versuchen Sie es erneut.",conflict:"Ihre Rückmeldung wurde in einer anderen Sitzung geändert. Laden Sie sie neu und prüfen Sie sie vor dem Speichern.",limit:"Das Rückmeldungslimit für 24 Stunden ist erreicht. Versuchen Sie es später erneut."},
  "fr-CH": {title:"Cette synthèse IA était-elle utile ?",help:"Votre avis concerne uniquement cette synthèse enregistrée. Il ne modifie ni l’analyse partagée, ni les règles de veille, ni le modèle. N’incluez pas d’informations sensibles.",useful:"Utile",not_useful:"Pas utile",withdrawn:"Avis retiré",withdraw:"Retirer mon avis",note:"Explication facultative (1 000 caractères maximum)",saving:"Enregistrement…",saved:"Votre avis enregistré",history:"Historique de vos avis",next:"Avis plus anciens",first:"Avis récents",reload:"Recharger les avis",failed:"Impossible de charger ou d’enregistrer votre avis. Votre texte est conservé ; rechargez et réessayez.",conflict:"Votre avis a changé dans une autre session. Rechargez-le et vérifiez-le avant d’enregistrer à nouveau.",limit:"Vous avez atteint la limite d’avis sur 24 heures. Réessayez plus tard."},
  "it-CH": {title:"Questa sintesi IA è stata utile?",help:"Il tuo feedback riguarda solo questa sintesi salvata. Non modifica l’analisi condivisa, le regole di monitoraggio o il modello. Non includere informazioni sensibili.",useful:"Utile",not_useful:"Non utile",withdrawn:"Feedback ritirato",withdraw:"Ritira il feedback",note:"Spiegazione facoltativa (massimo 1.000 caratteri)",saving:"Salvataggio…",saved:"Il tuo feedback salvato",history:"Cronologia dei tuoi feedback",next:"Feedback precedenti",first:"Feedback recenti",reload:"Ricarica i feedback",failed:"Impossibile caricare o salvare il feedback. Il testo è conservato; ricarica e riprova.",conflict:"Il tuo feedback è cambiato in un’altra sessione. Ricaricalo e controllalo prima di salvare di nuovo.",limit:"Hai raggiunto il limite di feedback su 24 ore. Riprova più tardi."},
  "rm-CH": {title:"È questa resumaziun IA stada utila?",help:"Voss resun pertutga mo questa resumaziun memorisada. El na mida ni l’analisa cuminaivla, ni las reglas da surveglianza, ni il model. N’inditgai naginas infurmaziuns sensiblas.",useful:"Utila",not_useful:"Betg utila",withdrawn:"Resun retratg",withdraw:"Retratger il resun",note:"Motivaziun facultativa (maximal 1’000 caracters)",saving:"Memorisar…",saved:"Voss resun memorisà",history:"Istorgia da voss resuns",next:"Resuns pli vegls",first:"Resuns recents",reload:"Rechargiar ils resuns",failed:"Il resun n’ha betg pudì vegnir chargià u memorisà. Voss text resta mantegnì; chargiai danovamain ed empruvai anc ina giada.",conflict:"Voss resun è vegnì midà en in’autra sessiun. Chargiai e controllai el avant da memorisar danovamain.",limit:"Vus avais cuntanschì la limita da resuns per 24 uras. Empruvai pli tard."},
};
