import type {Locale} from "./i18n";

export type ReviewDecision = "confirmed" | "rejected" | "withdrawn";
export type BriefReview = {id: string; assessment_id: string; actor_user_id: string | null; decision: ReviewDecision; note: string; created_at: string; target_fingerprint: string};
export type BriefReviewPage = {assessment_id: string; locale: string; target_fingerprint: string; latest: BriefReview | null; matches_saved_assessment: boolean; items: BriefReview[]; next_cursor: string | null};
type Copy = {title:string;help:string;confirmed:string;rejected:string;withdrawn:string;confirm:string;reject:string;withdraw:string;note:string;reload:string;history:string;older:string;first:string;failed:string;conflict:string;unreviewed:string;changed:string;original:string};
export const briefReviewCopy: Record<Locale, Copy> = {
  "en-CH": {title:"Organization relevance review",help:"Administrators review the relevance of this exact brief for everyone in the organization. This is not legal approval. Rejection withholds the brief from recommendations; sources and history remain. No AI request or monitoring rule changes.",confirmed:"Relevance confirmed by an administrator",rejected:"An administrator rejected this brief's relevance. Sources remain available.",withdrawn:"Administrator review withdrawn",confirm:"Confirm relevance",reject:"Reject relevance",withdraw:"Withdraw decision",note:"Shared explanation (3–2,000 characters; do not include secrets)",reload:"Reload reviews",history:"Shared review history",older:"Older reviews",first:"Latest reviews",failed:"Could not load or save the review. Your explanation is retained; retry or reload.",conflict:"The brief or review changed. Reload and inspect it before saving again.",unreviewed:"Not reviewed by an administrator",changed:"The last decision applies to different saved content. Review this version separately.",original:"Inspect the rejected brief as history"},
  "de-CH": {title:"Relevanzprüfung der Organisation",help:"Administratoren prüfen die Relevanz dieser genauen Analyse für die ganze Organisation. Dies ist keine rechtliche Freigabe. Eine Ablehnung entfernt die Analyse aus Empfehlungen; Quellen und Verlauf bleiben. Keine KI-Anfrage oder Regeländerung.",confirmed:"Relevanz durch Administrator bestätigt",rejected:"Ein Administrator hat die Relevanz dieser Analyse abgelehnt. Quellen bleiben verfügbar.",withdrawn:"Administratorentscheidung zurückgezogen",confirm:"Relevanz bestätigen",reject:"Relevanz ablehnen",withdraw:"Entscheidung zurückziehen",note:"Gemeinsame Begründung (3–2’000 Zeichen; keine Geheimnisse)",reload:"Prüfungen neu laden",history:"Gemeinsamer Prüfverlauf",older:"Ältere Prüfungen",first:"Neueste Prüfungen",failed:"Prüfung konnte nicht geladen oder gespeichert werden. Ihre Begründung bleibt erhalten; versuchen Sie es erneut oder laden Sie neu.",conflict:"Analyse oder Prüfung geändert. Laden und prüfen Sie vor dem Speichern erneut.",unreviewed:"Noch nicht durch einen Administrator geprüft",changed:"Die letzte Entscheidung betrifft andere gespeicherte Inhalte. Prüfen Sie diese Fassung separat.",original:"Abgelehnte Analyse im Verlauf ansehen"},
  "fr-CH": {title:"Examen de pertinence de l’organisation",help:"Les administrateurs examinent la pertinence de cette analyse précise pour toute l’organisation. Ce n’est pas une approbation juridique. Le rejet retire l’analyse des recommandations ; sources et historique restent. Aucune requête IA ni modification des règles.",confirmed:"Pertinence confirmée par un administrateur",rejected:"Un administrateur a rejeté la pertinence de cette analyse. Les sources restent disponibles.",withdrawn:"Décision administrative retirée",confirm:"Confirmer la pertinence",reject:"Rejeter la pertinence",withdraw:"Retirer la décision",note:"Explication partagée (3 à 2 000 caractères ; aucun secret)",reload:"Recharger les examens",history:"Historique partagé des examens",older:"Examens plus anciens",first:"Examens récents",failed:"Impossible de charger ou d’enregistrer l’examen. Votre explication est conservée ; réessayez ou rechargez.",conflict:"L’analyse ou l’examen a changé. Rechargez et vérifiez avant d’enregistrer.",unreviewed:"Pas encore examiné par un administrateur",changed:"La dernière décision concerne un autre contenu enregistré. Examinez cette version séparément.",original:"Consulter l’analyse rejetée dans l’historique"},
  "it-CH": {title:"Verifica di rilevanza dell’organizzazione",help:"Gli amministratori verificano la rilevanza di questa esatta analisi per tutta l’organizzazione. Non è un’approvazione legale. Il rifiuto rimuove l’analisi dalle raccomandazioni; fonti e cronologia restano. Nessuna richiesta IA o modifica delle regole.",confirmed:"Rilevanza confermata da un amministratore",rejected:"Un amministratore ha respinto la rilevanza di questa analisi. Le fonti restano disponibili.",withdrawn:"Decisione amministrativa ritirata",confirm:"Conferma rilevanza",reject:"Respingi rilevanza",withdraw:"Ritira decisione",note:"Spiegazione condivisa (3–2.000 caratteri; nessun segreto)",reload:"Ricarica le verifiche",history:"Cronologia condivisa delle verifiche",older:"Verifiche precedenti",first:"Verifiche recenti",failed:"Impossibile caricare o salvare la verifica. La spiegazione è conservata; riprova o ricarica.",conflict:"L’analisi o la verifica è cambiata. Ricarica e controlla prima di salvare.",unreviewed:"Non ancora verificata da un amministratore",changed:"L’ultima decisione riguarda contenuti salvati diversi. Verifica questa versione separatamente.",original:"Consulta l’analisi respinta nella cronologia"},
  "rm-CH": {title:"Examinaziun da relevanza da l’organisaziun",help:"Administraturs examineschan la relevanza da questa analisa exacta per l’entira organisaziun. Quai n’è nagina approvaziun giuridica. Ina refusaziun allontanescha l’analisa da las recumandaziuns; funtaunas ed istorgia restan. Nagina dumonda IA u midada da reglas.",confirmed:"Relevanza confermada d’in administratur",rejected:"In administratur ha refusà la relevanza da questa analisa. Las funtaunas restan disponiblas.",withdrawn:"Decisiun administrativa retratga",confirm:"Confermar relevanza",reject:"Refusar relevanza",withdraw:"Retratger la decisiun",note:"Motivaziun communabla (3–2’000 caracters; nagins secrets)",reload:"Rechargiar examinaziuns",history:"Istorgia communabla da las examinaziuns",older:"Examinaziuns pli veglias",first:"Examinaziuns recentas",failed:"L’examinaziun n’ha betg pudì vegnir chargiada u memorisada. Vossa motivaziun resta mantegnida; empruvai danovamain u rechargiai.",conflict:"L’analisa u l’examinaziun è sa midada. Rechargiai e controllai avant da memorisar.",unreviewed:"Anc betg examinada d’in administratur",changed:"L’ultima decisiun pertutga auters cuntegns memorisads. Examinai questa versiun separadamain.",original:"Examinar l’analisa refusada en l’istorgia"},
};
