import type { Locale } from "./i18n";

const en = {
  title: "Responsibility and decision notes",
  assigned: "Responsible for this item",
  unassigned: "Unassigned",
  former: "Former member",
  inactive: "Unavailable for new assignments",
  comment: "Comment on this evidence",
  help: "Save a note without marking this item reviewed, or record a decision together with its responsible person and comment. No external message or submission is sent.",
  save: "Save responsibility and comment",
  decide: "Save decision, responsibility and comment",
  decision: "Internal decision",
  choose: "Choose a decision",
  history: "Work history",
  empty: "No responsibility or decision notes yet.",
  earlier: "Earlier entries",
  older: "Based on older evidence",
  current: "Based on the current evidence",
  evidence: "Evidence sequence",
  version: "Item version",
  actor: "Recorded by",
  note: "Responsibility / comment only",
  hidden: "This entry’s evidence is unavailable. Its content is withheld.",
  unavailable:
    "Current evidence is unavailable. Saved work is retained; refresh the evidence before continuing.",
  failed:
    "The item or your access changed, or the request failed. Reload before continuing; unsaved input was cleared.",
  loading: "Loading item work…",
  reload: "Reload item work",
  saved: "Saved with this evidence version.",
  readOnly:
    "You can read this history. Changes require an administrator and permitted current evidence.",
  moreMembers: "More administrators",
  assignment: "Assignment filter",
  all: "All assignments",
  mine: "Assigned to me",
};
export const businessItemCopy: Record<
  Locale,
  Record<keyof typeof en, string>
> = {
  "en-CH": en,
  "de-CH": {
    title: "Zuständigkeit und Entscheidungsnotizen",
    assigned: "Verantwortlich für diesen Eintrag",
    unassigned: "Nicht zugewiesen",
    former: "Ehemaliges Mitglied",
    inactive: "Für neue Zuweisungen nicht verfügbar",
    comment: "Kommentar zu diesen Belegen",
    help: "Speichern Sie eine Notiz, ohne den Eintrag als geprüft zu markieren, oder einen Entscheid zusammen mit Zuständigkeit und Kommentar. Es wird keine externe Nachricht oder Eingabe versandt.",
    save: "Zuständigkeit und Kommentar speichern",
    decide: "Entscheid, Zuständigkeit und Kommentar speichern",
    decision: "Interner Entscheid",
    choose: "Entscheid auswählen",
    history: "Bearbeitungsverlauf",
    empty: "Noch keine Zuständigkeits- oder Entscheidungsnotizen.",
    earlier: "Frühere Einträge",
    older: "Basiert auf älteren Belegen",
    current: "Basiert auf aktuellen Belegen",
    evidence: "Belegfolge",
    version: "Eintragsversion",
    actor: "Erfasst von",
    note: "Nur Zuständigkeit / Kommentar",
    hidden:
      "Die Belege dieses Eintrags sind nicht verfügbar. Der Inhalt wird nicht angezeigt.",
    unavailable:
      "Aktuelle Belege sind nicht verfügbar. Gespeicherte Arbeit bleibt erhalten; aktualisieren Sie zuerst die Belege.",
    failed:
      "Der Eintrag oder Ihr Zugriff hat sich geändert, oder die Anfrage ist fehlgeschlagen. Laden Sie neu; ungespeicherte Eingaben wurden gelöscht.",
    loading: "Bearbeitungsdaten werden geladen…",
    reload: "Bearbeitungsdaten neu laden",
    saved: "Mit dieser Belegversion gespeichert.",
    readOnly:
      "Sie können diesen Verlauf lesen. Änderungen erfordern Administrationsrechte und erlaubte aktuelle Belege.",
    moreMembers: "Weitere Administrationen",
    assignment: "Zuständigkeitsfilter",
    all: "Alle Zuständigkeiten",
    mine: "Mir zugewiesen",
  },
  "fr-CH": {
    title: "Responsabilité et notes de décision",
    assigned: "Responsable de cet élément",
    unassigned: "Non attribué",
    former: "Ancien membre",
    inactive: "Indisponible pour de nouvelles attributions",
    comment: "Commentaire sur ces preuves",
    help: "Enregistrez une note sans marquer l’élément comme examiné, ou une décision avec son responsable et son commentaire. Aucun message ni dépôt externe n’est envoyé.",
    save: "Enregistrer le responsable et le commentaire",
    decide: "Enregistrer la décision, le responsable et le commentaire",
    decision: "Décision interne",
    choose: "Choisir une décision",
    history: "Historique du travail",
    empty: "Aucune note de responsabilité ou de décision.",
    earlier: "Entrées précédentes",
    older: "Fondé sur des preuves antérieures",
    current: "Fondé sur les preuves actuelles",
    evidence: "Séquence des preuves",
    version: "Version de l’élément",
    actor: "Enregistré par",
    note: "Responsabilité / commentaire uniquement",
    hidden:
      "Les preuves de cette entrée sont indisponibles. Son contenu est masqué.",
    unavailable:
      "Les preuves actuelles sont indisponibles. Le travail enregistré est conservé ; actualisez les preuves avant de continuer.",
    failed:
      "L’élément ou votre accès a changé, ou la requête a échoué. Rechargez avant de continuer ; les saisies non enregistrées ont été effacées.",
    loading: "Chargement du travail…",
    reload: "Recharger le travail",
    saved: "Enregistré avec cette version des preuves.",
    readOnly:
      "Vous pouvez lire cet historique. Les modifications nécessitent un administrateur et des preuves actuelles autorisées.",
    moreMembers: "Autres administrateurs",
    assignment: "Filtre d’attribution",
    all: "Toutes les attributions",
    mine: "Attribué à moi",
  },
  "it-CH": {
    title: "Responsabilità e note decisionali",
    assigned: "Responsabile di questo elemento",
    unassigned: "Non assegnato",
    former: "Ex membro",
    inactive: "Non disponibile per nuove assegnazioni",
    comment: "Commento su queste evidenze",
    help: "Salva una nota senza segnare l’elemento come esaminato, oppure una decisione con responsabile e commento. Non vengono inviati messaggi o domande esterne.",
    save: "Salva responsabile e commento",
    decide: "Salva decisione, responsabile e commento",
    decision: "Decisione interna",
    choose: "Scegli una decisione",
    history: "Cronologia del lavoro",
    empty: "Nessuna nota di responsabilità o decisione.",
    earlier: "Voci precedenti",
    older: "Basato su evidenze precedenti",
    current: "Basato sulle evidenze attuali",
    evidence: "Sequenza delle evidenze",
    version: "Versione dell’elemento",
    actor: "Registrato da",
    note: "Solo responsabilità / commento",
    hidden:
      "Le evidenze di questa voce non sono disponibili. Il contenuto è nascosto.",
    unavailable:
      "Le evidenze attuali non sono disponibili. Il lavoro salvato è conservato; aggiorna le evidenze prima di continuare.",
    failed:
      "L’elemento o il tuo accesso è cambiato, oppure la richiesta è fallita. Ricarica prima di continuare; i dati non salvati sono stati cancellati.",
    loading: "Caricamento del lavoro…",
    reload: "Ricarica il lavoro",
    saved: "Salvato con questa versione delle evidenze.",
    readOnly:
      "Puoi leggere questa cronologia. Le modifiche richiedono un amministratore ed evidenze attuali autorizzate.",
    moreMembers: "Altri amministratori",
    assignment: "Filtro di assegnazione",
    all: "Tutte le assegnazioni",
    mine: "Assegnato a me",
  },
  "rm-CH": {
    title: "Responsabladad e notas da decisiun",
    assigned: "Responsabel per questa endataziun",
    unassigned: "Betg attribuì",
    former: "Anteriur commember",
    inactive: "Betg disponibel per novas attribuziuns",
    comment: "Commentari davart quests mussaments",
    help: "Memorisai ina nota senza marcar l’endataziun sco examinada, u ina decisiun cun responsabel e commentari. Nagins messadis u inoltraziuns externas vegnan tramess.",
    save: "Memorisar responsabel e commentari",
    decide: "Memorisar decisiun, responsabel e commentari",
    decision: "Decisiun interna",
    choose: "Tscherner ina decisiun",
    history: "Istorgia da lavur",
    empty: "Anc naginas notas da responsabladad u decisiun.",
    earlier: "Endataziuns anteriuras",
    older: "Sa basa sin mussaments pli vegls",
    current: "Sa basa sin ils mussaments actuals",
    evidence: "Successiun dals mussaments",
    version: "Versiun da l’endataziun",
    actor: "Registrà da",
    note: "Mo responsabladad / commentari",
    hidden:
      "Ils mussaments da questa endataziun n’èn betg disponibels. Il cuntegn na vegn betg mussà.",
    unavailable:
      "Ils mussaments actuals n’èn betg disponibels. La lavur memorisada resta; actualisai ils mussaments avant che cuntinuar.",
    failed:
      "L’endataziun u Voss access è sa midà, u la dumonda n’è betg reussida. Chargiai danovamain; las endataziuns betg memorisadas èn stizzadas.",
    loading: "Chargiar la lavur…",
    reload: "Chargiar danovamain la lavur",
    saved: "Memorisà cun questa versiun dals mussaments.",
    readOnly:
      "Vus pudais leger questa istorgia. Midadas dovran in administratur e mussaments actuals permess.",
    moreMembers: "Ulteriurs administraturs",
    assignment: "Filter d’attribuziun",
    all: "Tut las attribuziuns",
    mine: "Attribuì a mai",
  },
};
