import type { Locale } from "./i18n";

export const commuteWeekdays: Record<Locale, string[]> = {
  "en-CH": [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
  ],
  "de-CH": [
    "Montag",
    "Dienstag",
    "Mittwoch",
    "Donnerstag",
    "Freitag",
    "Samstag",
    "Sonntag",
  ],
  "fr-CH": [
    "Lundi",
    "Mardi",
    "Mercredi",
    "Jeudi",
    "Vendredi",
    "Samedi",
    "Dimanche",
  ],
  "it-CH": [
    "Lunedì",
    "Martedì",
    "Mercoledì",
    "Giovedì",
    "Venerdì",
    "Sabato",
    "Domenica",
  ],
  "rm-CH": [
    "Glindesdi",
    "Mardi",
    "Mesemna",
    "Gievgia",
    "Venderdi",
    "Sonda",
    "Dumengia",
  ],
};

const en = {
  today: "Journey updates",
  why: "Why this appears",
  unread_journey_change: "This saved journey has an unread transport update.",
  outside_window_saved: "The update was kept under your outside-window policy.",
  savedUpdate: "Saved update",
  latestState: "Latest known state",
  newerUpdate:
    "A newer update is available. The linked version is preserved below.",
  olderSettings: "This event belongs to earlier journey settings.",
  urgent: "Cancellation reported",
  todayEmpty: "No unread journey updates in this page.",
  title: "Commute Watch",
  intro:
    "Follow changes affecting your regular journey, on your chosen days and times.",
  privacy:
    "Your saved journeys and review history are private to your account in this workspace.",
  coverage:
    "Search covers imported, verified journey legs only. An empty result does not mean that no service exists.",
  noMail:
    "Updates appear here and in Today. Open a saved journey to configure optional emails with explicit consent.",
  create: "Add a commute",
  edit: "Edit settings",
  name: "Journey name",
  settings: "Journey settings",
  day: "Date to check",
  query: "Route or station",
  search: "Find journey legs",
  selected: "Selected journey legs",
  select: "Add leg",
  remove: "Remove leg",
  moveUp: "Move earlier",
  unknownLeg: "Journey leg unavailable",
  weekdays: "Days of the week",
  startTime: "From",
  endTime: "Until",
  timezone:
    "Times use Europe/Zurich. An end time before the start continues into the next day.",
  threshold: "Alert at a delay of (minutes)",
  reset: "Show improvement at or below (minutes)",
  cancellation: "Cancellations",
  skipped: "Boarding or alighting stop skipped",
  notices: "Official service notices",
  outside: "Outside the journey window",
  ignore: "Ignore",
  digest: "Keep for a future digest",
  check: "Preview journey",
  save: "Save draft",
  cancel: "Cancel",
  preview: "Journey preview",
  previewHelp:
    "Preview checks saved source data and the dated timetable. It does not fetch live predictions.",
  sourceOff:
    "Fresh, permitted transport data is not available. You can prepare a draft; monitoring cannot start yet.",
  featureOff: "Commute Watch is not enabled in this environment.",
  start: "Start monitoring",
  pause: "Pause",
  resume: "Resume",
  pause_today: "Pause today",
  unpause_today: "Continue today",
  archive: "Archive",
  delete: "Delete commute",
  deletePrompt: "Delete this commute and its private history?",
  confirmDelete: "Confirm deletion",
  refresh: "Refresh",
  loading: "Loading…",
  failed: "Unable to load or save. Refresh and try again.",
  conflict: "This record changed. Refresh before trying again.",
  invalid: "Check the journey, weekdays, time window and delay thresholds.",
  empty: "No saved commutes yet.",
  noLegs: "No verified journey legs found for this date.",
  noEvents:
    "No stored changes yet. This is not confirmation that the journey is running normally.",
  readonly: "Your role permits viewing only.",
  more: "Next page",
  previous: "Previous page",
  history: "Event history",
  revisions: "Settings history",
  events: "Journey changes",
  review: "Mark this version reviewed",
  reviewed: "Reviewed",
  unread: "New changes",
  mute: "Mute event",
  unmute: "Unmute event",
  unavailable: "Evidence unavailable",
  lastCheck: "Last check",
  nextCheck: "Next check",
  observation: "Source observation",
  delay: "Reported delay (minutes)",
  lastKnown: "Last known condition; current running is not confirmed.",
  source: "Official source",
  evidence: "Source evidence",
  normalized:
    "Saved normalized source fields; this is not the full original feed.",
  revision: "Settings revision",
  unknown: "Unknown",
  draft: "Draft",
  active: "Active",
  paused: "Paused",
  archived: "Archived",
  not_started: "Not started",
  ready: "Source data available",
  waiting: "Waiting for a check",
  waiting_for_predictions: "Waiting for relevant predictions",
  stale: "Out of date",
  access_unavailable: "Access unavailable",
  normal: "Within the delay threshold",
  delayed: "Material delay",
  cancelled: "Cancelled",
  interrupted: "Stop skipped",
  restored: "Service restored",
  improved: "Delay improved",
  notice: "Service notice",
  present: "Available",
  missing: "Missing from the feed",
  expired: "No longer valid",
  timetable: "No unambiguous, verified timetable is available for this date.",
  transfer:
    "Connected journeys need verified interchange data before they can start.",
  outsideReason: "A departure is outside the selected days or time window.",
  gap: "This local time does not exist on the selected date due to the clock change.",
};
export type CommuteCopy = { [K in keyof typeof en]: string };
export const commuteCopy: Record<Locale, CommuteCopy> = {
  "en-CH": en,
  "de-CH": {
    today: "Fahrtänderungen",
    why: "Warum dieser Eintrag erscheint",
    unread_journey_change:
      "Für diese gespeicherte Fahrt liegt eine ungelesene Verkehrsmeldung vor.",
    outside_window_saved:
      "Die Meldung wurde gemäss Ihrer Regel für Zeiten ausserhalb des Fahrtfensters gespeichert.",
    savedUpdate: "Gespeicherte Meldung",
    latestState: "Letzter bekannter Zustand",
    newerUpdate:
      "Eine neuere Meldung ist verfügbar. Die verlinkte Version bleibt unten erhalten.",
    olderSettings: "Dieses Ereignis gehört zu früheren Fahrteinstellungen.",
    urgent: "Ausfall gemeldet",
    todayEmpty: "Keine ungelesenen Fahrtänderungen auf dieser Seite.",
    title: "Pendelstrecke",
    intro:
      "Verfolgen Sie Änderungen Ihrer regelmässigen Fahrt an den gewählten Tagen und zu den gewählten Zeiten.",
    privacy:
      "Gespeicherte Fahrten und Prüfverlauf sind nur für Ihr Konto in diesem Arbeitsbereich sichtbar.",
    coverage:
      "Die Suche umfasst nur importierte, geprüfte Fahrtabschnitte. Ein leeres Ergebnis bedeutet nicht, dass keine Verbindung besteht.",
    noMail:
      "Änderungen erscheinen hier und unter Heute. Öffnen Sie eine gespeicherte Fahrt, um optionale E-Mails mit ausdrücklicher Zustimmung einzurichten.",
    create: "Pendelstrecke hinzufügen",
    edit: "Einstellungen bearbeiten",
    name: "Name der Fahrt",
    settings: "Fahrteinstellungen",
    day: "Datum zur Prüfung",
    query: "Linie oder Haltestelle",
    search: "Fahrtabschnitte suchen",
    selected: "Gewählte Fahrtabschnitte",
    select: "Abschnitt hinzufügen",
    remove: "Abschnitt entfernen",
    moveUp: "Nach vorne",
    unknownLeg: "Fahrtabschnitt nicht verfügbar",
    weekdays: "Wochentage",
    startTime: "Von",
    endTime: "Bis",
    timezone:
      "Zeiten gelten für Europe/Zurich. Eine Endzeit vor der Startzeit liegt am Folgetag.",
    threshold: "Meldung ab Verspätung (Minuten)",
    reset: "Verbesserung bei höchstens (Minuten)",
    cancellation: "Ausfälle",
    skipped: "Ein- oder Ausstiegshaltestelle entfällt",
    notices: "Offizielle Betriebsmeldungen",
    outside: "Ausserhalb des Zeitfensters",
    ignore: "Ignorieren",
    digest: "Für eine spätere Zusammenfassung speichern",
    check: "Fahrtvorschau",
    save: "Entwurf speichern",
    cancel: "Abbrechen",
    preview: "Fahrtvorschau",
    previewHelp:
      "Die Vorschau prüft gespeicherte Quelldaten und den datierten Fahrplan. Sie ruft keine Live-Prognosen ab.",
    sourceOff:
      "Aktuelle, freigegebene Verkehrsdaten fehlen. Sie können einen Entwurf vorbereiten; die Überwachung kann noch nicht starten.",
    featureOff: "Die Pendelüberwachung ist in dieser Umgebung nicht aktiviert.",
    start: "Überwachung starten",
    pause: "Pausieren",
    resume: "Fortsetzen",
    pause_today: "Heute pausieren",
    unpause_today: "Heute fortsetzen",
    archive: "Archivieren",
    delete: "Pendelstrecke löschen",
    deletePrompt: "Diese Pendelstrecke und ihren privaten Verlauf löschen?",
    confirmDelete: "Löschen bestätigen",
    refresh: "Aktualisieren",
    loading: "Wird geladen…",
    failed:
      "Laden oder Speichern fehlgeschlagen. Aktualisieren Sie die Ansicht und versuchen Sie es erneut.",
    conflict:
      "Dieser Eintrag wurde geändert. Aktualisieren Sie ihn vor einem neuen Versuch.",
    invalid:
      "Prüfen Sie Fahrt, Wochentage, Zeitfenster und Verspätungsschwellen.",
    empty: "Noch keine gespeicherten Pendelstrecken.",
    noLegs: "Keine geprüften Fahrtabschnitte für dieses Datum gefunden.",
    noEvents:
      "Noch keine gespeicherten Änderungen. Das bestätigt keinen normalen Betrieb.",
    readonly: "Ihre Rolle erlaubt nur das Lesen.",
    more: "Nächste Seite",
    previous: "Vorherige Seite",
    history: "Ereignisverlauf",
    revisions: "Einstellungsverlauf",
    events: "Änderungen der Fahrt",
    review: "Diese Version als geprüft markieren",
    reviewed: "Geprüft",
    unread: "Neue Änderungen",
    mute: "Ereignis stummschalten",
    unmute: "Stummschaltung aufheben",
    unavailable: "Nachweis nicht verfügbar",
    lastCheck: "Letzte Prüfung",
    nextCheck: "Nächste Prüfung",
    observation: "Quellenbeobachtung",
    delay: "Gemeldete Verspätung (Minuten)",
    lastKnown:
      "Letzter bekannter Zustand; der aktuelle Betrieb ist nicht bestätigt.",
    source: "Offizielle Quelle",
    evidence: "Quellennachweis",
    normalized:
      "Gespeicherte normalisierte Quellenfelder; nicht der vollständige Originalfeed.",
    revision: "Einstellungsversion",
    unknown: "Unbekannt",
    draft: "Entwurf",
    active: "Aktiv",
    paused: "Pausiert",
    archived: "Archiviert",
    not_started: "Nicht gestartet",
    ready: "Quelldaten verfügbar",
    waiting: "Wartet auf Prüfung",
    waiting_for_predictions: "Wartet auf passende Prognosen",
    stale: "Veraltet",
    access_unavailable: "Zugriff nicht verfügbar",
    normal: "Unter der Verspätungsschwelle",
    delayed: "Erhebliche Verspätung",
    cancelled: "Ausgefallen",
    interrupted: "Haltestelle entfällt",
    restored: "Betrieb wiederhergestellt",
    improved: "Verspätung verringert",
    notice: "Betriebsmeldung",
    present: "Verfügbar",
    missing: "Fehlt im Feed",
    expired: "Nicht mehr gültig",
    timetable:
      "Für dieses Datum ist kein eindeutiger, geprüfter Fahrplan verfügbar.",
    transfer:
      "Verbundene Fahrten benötigen vor dem Start geprüfte Umsteigedaten.",
    outsideReason:
      "Eine Abfahrt liegt ausserhalb der gewählten Tage oder Zeiten.",
    gap: "Diese Ortszeit existiert am gewählten Datum wegen der Zeitumstellung nicht.",
  },
  "fr-CH": {
    today: "Changements des trajets",
    why: "Pourquoi cet élément apparaît",
    unread_journey_change:
      "Ce trajet enregistré possède une information de transport non lue.",
    outside_window_saved:
      "Cette information a été conservée selon votre règle hors plage horaire.",
    savedUpdate: "Information enregistrée",
    latestState: "Dernier état connu",
    newerUpdate:
      "Une information plus récente est disponible. La version liée reste conservée ci-dessous.",
    olderSettings: "Cet événement appartient à d'anciens paramètres du trajet.",
    urgent: "Suppression signalée",
    todayEmpty: "Aucun changement de trajet non lu sur cette page.",
    title: "Trajets réguliers",
    intro:
      "Suivez les changements de votre trajet habituel aux jours et heures choisis.",
    privacy:
      "Vos trajets et leur historique de vérification sont privés à votre compte dans cet espace.",
    coverage:
      "La recherche couvre uniquement les étapes importées et vérifiées. Un résultat vide ne signifie pas qu'aucune liaison n'existe.",
    noMail:
      "Les changements apparaissent ici et dans Aujourd'hui. Ouvrez un trajet enregistré pour configurer des e-mails facultatifs avec votre consentement explicite.",
    create: "Ajouter un trajet",
    edit: "Modifier les paramètres",
    name: "Nom du trajet",
    settings: "Paramètres du trajet",
    day: "Date à vérifier",
    query: "Ligne ou arrêt",
    search: "Rechercher des étapes",
    selected: "Étapes sélectionnées",
    select: "Ajouter l'étape",
    remove: "Retirer l'étape",
    moveUp: "Avancer",
    unknownLeg: "Étape indisponible",
    weekdays: "Jours de la semaine",
    startTime: "De",
    endTime: "À",
    timezone:
      "Les heures utilisent Europe/Zurich. Une fin antérieure au début se situe le lendemain.",
    threshold: "Alerter dès un retard de (minutes)",
    reset: "Amélioration à un retard maximal de (minutes)",
    cancellation: "Suppressions",
    skipped: "Arrêt de montée ou de descente non desservi",
    notices: "Informations officielles de service",
    outside: "Hors de la plage du trajet",
    ignore: "Ignorer",
    digest: "Conserver pour une future synthèse",
    check: "Prévisualiser le trajet",
    save: "Enregistrer le brouillon",
    cancel: "Annuler",
    preview: "Aperçu du trajet",
    previewHelp:
      "L'aperçu vérifie les données enregistrées et l'horaire daté. Il ne récupère pas de prévisions en direct.",
    sourceOff:
      "Les données de transport récentes et autorisées sont indisponibles. Vous pouvez préparer un brouillon ; la surveillance ne peut pas encore démarrer.",
    featureOff:
      "La surveillance des trajets n'est pas activée dans cet environnement.",
    start: "Démarrer la surveillance",
    pause: "Mettre en pause",
    resume: "Reprendre",
    pause_today: "Pause aujourd'hui",
    unpause_today: "Reprendre aujourd'hui",
    archive: "Archiver",
    delete: "Supprimer le trajet",
    deletePrompt: "Supprimer ce trajet et son historique privé ?",
    confirmDelete: "Confirmer la suppression",
    refresh: "Actualiser",
    loading: "Chargement…",
    failed:
      "Échec du chargement ou de l'enregistrement. Actualisez et réessayez.",
    conflict: "Cet élément a changé. Actualisez avant de réessayer.",
    invalid:
      "Vérifiez le trajet, les jours, la plage horaire et les seuils de retard.",
    empty: "Aucun trajet enregistré.",
    noLegs: "Aucune étape vérifiée trouvée pour cette date.",
    noEvents:
      "Aucun changement enregistré. Cela ne confirme pas un fonctionnement normal du trajet.",
    readonly: "Votre rôle permet uniquement la consultation.",
    more: "Page suivante",
    previous: "Page précédente",
    history: "Historique de l'événement",
    revisions: "Historique des paramètres",
    events: "Changements du trajet",
    review: "Marquer cette version comme vérifiée",
    reviewed: "Vérifié",
    unread: "Nouveaux changements",
    mute: "Mettre l'événement en sourdine",
    unmute: "Réactiver l'événement",
    unavailable: "Preuve indisponible",
    lastCheck: "Dernière vérification",
    nextCheck: "Prochaine vérification",
    observation: "Observation de la source",
    delay: "Retard signalé (minutes)",
    lastKnown:
      "Dernier état connu ; la circulation actuelle n'est pas confirmée.",
    source: "Source officielle",
    evidence: "Preuve de la source",
    normalized:
      "Champs normalisés enregistrés ; il ne s'agit pas du flux original complet.",
    revision: "Version des paramètres",
    unknown: "Inconnu",
    draft: "Brouillon",
    active: "Actif",
    paused: "En pause",
    archived: "Archivé",
    not_started: "Non démarré",
    ready: "Données de source disponibles",
    waiting: "En attente de vérification",
    waiting_for_predictions: "En attente de prévisions pertinentes",
    stale: "Périmé",
    access_unavailable: "Accès indisponible",
    normal: "Sous le seuil de retard",
    delayed: "Retard important",
    cancelled: "Supprimé",
    interrupted: "Arrêt non desservi",
    restored: "Service rétabli",
    improved: "Retard réduit",
    notice: "Information de service",
    present: "Disponible",
    missing: "Absent du flux",
    expired: "N'est plus valable",
    timetable:
      "Aucun horaire vérifié et non ambigu n'est disponible pour cette date.",
    transfer:
      "Les trajets avec correspondance nécessitent des données de transfert vérifiées avant le démarrage.",
    outsideReason:
      "Un départ est en dehors des jours ou horaires sélectionnés.",
    gap: "Cette heure locale n'existe pas à la date choisie en raison du changement d'heure.",
  },
  "it-CH": {
    today: "Aggiornamenti dei percorsi",
    why: "Perché compare",
    unread_journey_change:
      "Questo percorso salvato ha un aggiornamento di trasporto non letto.",
    outside_window_saved:
      "L'aggiornamento è stato conservato secondo la regola fuori fascia oraria.",
    savedUpdate: "Aggiornamento salvato",
    latestState: "Ultimo stato noto",
    newerUpdate:
      "È disponibile un aggiornamento più recente. La versione collegata è conservata qui sotto.",
    olderSettings:
      "Questo evento appartiene a impostazioni precedenti del percorso.",
    urgent: "Soppressione segnalata",
    todayEmpty: "Nessun aggiornamento di percorso non letto in questa pagina.",
    title: "Percorsi abituali",
    intro:
      "Segui i cambiamenti del tuo percorso abituale nei giorni e negli orari scelti.",
    privacy:
      "I percorsi salvati e la cronologia delle verifiche sono privati per il tuo account in questo spazio.",
    coverage:
      "La ricerca comprende solo tratte importate e verificate. Nessun risultato non significa assenza di collegamenti.",
    noMail:
      "Gli aggiornamenti appaiono qui e in Oggi. Apri un viaggio salvato per configurare e-mail facoltative con consenso esplicito.",
    create: "Aggiungi un percorso",
    edit: "Modifica impostazioni",
    name: "Nome del percorso",
    settings: "Impostazioni del percorso",
    day: "Data da verificare",
    query: "Linea o fermata",
    search: "Cerca tratte",
    selected: "Tratte selezionate",
    select: "Aggiungi tratta",
    remove: "Rimuovi tratta",
    moveUp: "Sposta prima",
    unknownLeg: "Tratta non disponibile",
    weekdays: "Giorni della settimana",
    startTime: "Dalle",
    endTime: "Alle",
    timezone:
      "Gli orari usano Europe/Zurich. Un orario finale precedente all'inizio indica il giorno successivo.",
    threshold: "Avvisa da un ritardo di (minuti)",
    reset: "Miglioramento a un ritardo massimo di (minuti)",
    cancellation: "Soppressioni",
    skipped: "Fermata di salita o discesa saltata",
    notices: "Avvisi ufficiali di servizio",
    outside: "Fuori dalla fascia del percorso",
    ignore: "Ignora",
    digest: "Conserva per un riepilogo futuro",
    check: "Anteprima del percorso",
    save: "Salva bozza",
    cancel: "Annulla",
    preview: "Anteprima del percorso",
    previewHelp:
      "L'anteprima verifica i dati salvati e l'orario della data scelta. Non richiede previsioni in tempo reale.",
    sourceOff:
      "I dati di trasporto recenti e autorizzati non sono disponibili. Puoi preparare una bozza; il monitoraggio non può ancora partire.",
    featureOff: "Il monitoraggio dei percorsi non è attivo in questo ambiente.",
    start: "Avvia monitoraggio",
    pause: "Sospendi",
    resume: "Riprendi",
    pause_today: "Sospendi oggi",
    unpause_today: "Riprendi oggi",
    archive: "Archivia",
    delete: "Elimina percorso",
    deletePrompt: "Eliminare questo percorso e la sua cronologia privata?",
    confirmDelete: "Conferma eliminazione",
    refresh: "Aggiorna",
    loading: "Caricamento…",
    failed: "Caricamento o salvataggio non riuscito. Aggiorna e riprova.",
    conflict: "Questa voce è cambiata. Aggiorna prima di riprovare.",
    invalid: "Controlla percorso, giorni, fascia oraria e soglie di ritardo.",
    empty: "Nessun percorso salvato.",
    noLegs: "Nessuna tratta verificata trovata per questa data.",
    noEvents:
      "Nessun cambiamento salvato. Non conferma il regolare svolgimento del viaggio.",
    readonly: "Il tuo ruolo consente solo la consultazione.",
    more: "Pagina successiva",
    previous: "Pagina precedente",
    history: "Cronologia evento",
    revisions: "Cronologia impostazioni",
    events: "Cambiamenti del percorso",
    review: "Segna questa versione come verificata",
    reviewed: "Verificato",
    unread: "Nuovi cambiamenti",
    mute: "Silenzia evento",
    unmute: "Riattiva evento",
    unavailable: "Prova non disponibile",
    lastCheck: "Ultima verifica",
    nextCheck: "Prossima verifica",
    observation: "Osservazione della fonte",
    delay: "Ritardo segnalato (minuti)",
    lastKnown:
      "Ultima condizione nota; la circolazione attuale non è confermata.",
    source: "Fonte ufficiale",
    evidence: "Prova della fonte",
    normalized:
      "Campi normalizzati salvati; non è il flusso originale completo.",
    revision: "Versione impostazioni",
    unknown: "Sconosciuto",
    draft: "Bozza",
    active: "Attivo",
    paused: "Sospeso",
    archived: "Archiviato",
    not_started: "Non avviato",
    ready: "Dati della fonte disponibili",
    waiting: "In attesa di verifica",
    waiting_for_predictions: "In attesa di previsioni pertinenti",
    stale: "Non aggiornato",
    access_unavailable: "Accesso non disponibile",
    normal: "Entro la soglia di ritardo",
    delayed: "Ritardo rilevante",
    cancelled: "Soppresso",
    interrupted: "Fermata saltata",
    restored: "Servizio ripristinato",
    improved: "Ritardo ridotto",
    notice: "Avviso di servizio",
    present: "Disponibile",
    missing: "Assente dal flusso",
    expired: "Non più valido",
    timetable:
      "Nessun orario verificato e univoco è disponibile per questa data.",
    transfer:
      "I percorsi con coincidenze richiedono dati di interscambio verificati prima dell'avvio.",
    outsideReason: "Una partenza è fuori dai giorni o dagli orari selezionati.",
    gap: "Quest'ora locale non esiste nella data scelta a causa del cambio d'ora.",
  },
  "rm-CH": {
    today: "Midadas dals viadis",
    why: "Pertge che questa endataziun cumpara",
    unread_journey_change:
      "Quest viadi memorisà ha in avis da transport betg legì.",
    outside_window_saved:
      "L'avis è vegnì conservà tenor Vossa regla ordaifer la fanestra dal viadi.",
    savedUpdate: "Avis memorisà",
    latestState: "Ultim stadi enconuschent",
    newerUpdate:
      "In avis pli nov è disponibel. La versiun colliada resta conservada qua sut.",
    olderSettings: "Quest eveniment tutga tar parameters precedents dal viadi.",
    urgent: "Annulaziun annunziada",
    todayEmpty: "Naginas midadas da viadi betg legidas sin questa pagina.",
    title: "Viadis regulars",
    intro:
      "Suandai las midadas da Voss viadi regular ils dis ed a las uras tschernidas.",
    privacy:
      "Voss viadis memorisads e l'istorgia da verificaziun èn privats per Voss conto en quest spazi da lavur.",
    coverage:
      "La tschertga cumpiglia mo etappas importadas e verifitgadas. In resultat vid na signifitga betg ch'i na dat nagina colliaziun.",
    noMail:
      "Las midadas cumparan qua ed en Oz. Avri in viadi memorisà per configurar e-mails facultativs cun consentiment explicit.",
    create: "Agiuntar in viadi",
    edit: "Modifitgar ils parameters",
    name: "Num dal viadi",
    settings: "Parameters dal viadi",
    day: "Data da verificar",
    query: "Lingia u fermada",
    search: "Tschertgar etappas",
    selected: "Etappas tschernidas",
    select: "Agiuntar l'etappa",
    remove: "Allontanar l'etappa",
    moveUp: "Spustar enavant",
    unknownLeg: "Etappa betg disponibla",
    weekdays: "Dis da l'emna",
    startTime: "Da",
    endTime: "Fin",
    timezone:
      "Las uras valan per Europe/Zurich. Ina fin avant il cumenzament è il di suandant.",
    threshold: "Avisar a partir d'in retard da (minutas)",
    reset: "Meglieraziun tar maximalmain (minutas)",
    cancellation: "Annulaziuns",
    skipped: "Fermada da muntada u sortida omessa",
    notices: "Avis uffizials dal servetsch",
    outside: "Ordaifer la fanestra dal viadi",
    ignore: "Ignorar",
    digest: "Conservar per ina resumaziun futura",
    check: "Prevista dal viadi",
    save: "Memorisar il sboz",
    cancel: "Interrumper",
    preview: "Prevista dal viadi",
    previewHelp:
      "La prevista verifitgescha las datas memorisadas e l'urari datà. Ella na dumonda naginas prognosas en temp real.",
    sourceOff:
      "Datas da transport actualas ed autorisadas n'èn betg disponiblas. Vus pudais preparar in sboz; la surveglianza na po anc betg cumenzar.",
    featureOff: "La surveglianza da viadis n'è betg activada en quest ambient.",
    start: "Cumenzar la surveglianza",
    pause: "Far pausa",
    resume: "Cuntinuar",
    pause_today: "Far pausa oz",
    unpause_today: "Cuntinuar oz",
    archive: "Archivar",
    delete: "Stizzar il viadi",
    deletePrompt: "Stizzar quest viadi e sia istorgia privata?",
    confirmDelete: "Confermar il stizzar",
    refresh: "Actualisar",
    loading: "Chargiar…",
    failed:
      "Chargiar u memorisar n'è betg reussì. Actualisai e pruvai danovamain.",
    conflict:
      "Questa endataziun è vegnida midada. Actualisai avant d'empruvar danovamain.",
    invalid:
      "Verifitgai il viadi, ils dis, la fanestra d'uras e las limitas dal retard.",
    empty: "Anc nagins viadis memorisads.",
    noLegs: "Naginas etappas verifitgadas chattadas per questa data.",
    noEvents:
      "Anc naginas midadas memorisadas. Quai na conferma betg in viadi normal.",
    readonly: "Vossa rolla permetta mo da leger.",
    more: "Proxima pagina",
    previous: "Pagina precedenta",
    history: "Istorgia da l'eveniment",
    revisions: "Istorgia dals parameters",
    events: "Midadas dal viadi",
    review: "Marcar questa versiun sco verifitgada",
    reviewed: "Verifitgà",
    unread: "Novas midadas",
    mute: "Metter l'eveniment sin mut",
    unmute: "Reactivar l'eveniment",
    unavailable: "Cumprova betg disponibla",
    lastCheck: "Ultima verificaziun",
    nextCheck: "Proxima verificaziun",
    observation: "Observaziun da la funtauna",
    delay: "Retard annunzià (minutas)",
    lastKnown:
      "Ultim stadi enconuschent; il servetsch actual n'è betg confermà.",
    source: "Funtauna uffiziala",
    evidence: "Cumprova da la funtauna",
    normalized:
      "Champs normalisads memorisads; quai n'è betg il fluss original cumplet.",
    revision: "Versiun dals parameters",
    unknown: "Nunenconuschent",
    draft: "Sboz",
    active: "Activ",
    paused: "En pausa",
    archived: "Archivà",
    not_started: "Betg cumenzà",
    ready: "Datas da la funtauna disponiblas",
    waiting: "Spetga ina verificaziun",
    waiting_for_predictions: "Spetga prognosas relevantas",
    stale: "Betg pli actual",
    access_unavailable: "Access betg disponibel",
    normal: "Sut la limita dal retard",
    delayed: "Retard relevant",
    cancelled: "Annulà",
    interrupted: "Fermada omessa",
    restored: "Servetsch restabilì",
    improved: "Retard reducì",
    notice: "Avis dal servetsch",
    present: "Disponibel",
    missing: "Manca en il fluss",
    expired: "Betg pli valaivel",
    timetable:
      "Nagin urari verifitgà ed univoc n'è disponibel per questa data.",
    transfer:
      "Viadis colliads dovran datas da midada verifitgadas avant da cumenzar.",
    outsideReason: "Ina partenza è ordaifer ils dis u las uras tschernidas.",
    gap: "Questa ura locala n'exista betg a la data tschernida pervi da la midada d'ura.",
  },
};
