import type { Locale } from "./i18n";
const en = {
  title: "Review brief",
  finding: "Findings",
  discussion: "Discussion",
  task: "Tasks",
  note: "Editorial workspace notes, stored separately from AI answers. Dates below record saved revisions.",
  fictional: "Fictional contributor",
  author: "Contributor",
  role: "Role",
  body: "Note",
  open: "Open",
  in_progress: "In progress",
  complete: "Complete",
  recorded: "Recorded",
  due: "Internal target date",
  graph: "Open Influence Graph",
  law: "Monitored document",
  none: "No document linked",
  add: "Add note",
  remove: "Remove note",
  sources: "Supporting sources",
  status: "Task status",
  revision: "Saved revision",
  empty: "No notes in this category.",
  failed: "The review brief could not be loaded.",
  retry: "Retry",
  name: "Title",
  kind: "Category",
};
export const dossierReviewCopy: Record<Locale, typeof en> = {
  "en-CH": en,
  "de-CH": {
    title: "Prüfvermerk",
    finding: "Erkenntnisse",
    discussion: "Diskussion",
    task: "Aufgaben",
    note: "Redaktionelle Arbeitsnotizen, getrennt von KI-Antworten gespeichert. Die Daten bezeichnen gespeicherte Revisionen.",
    fictional: "Fiktive Person",
    author: "Verfasser",
    role: "Rolle",
    body: "Notiz",
    open: "Offen",
    in_progress: "In Bearbeitung",
    complete: "Erledigt",
    recorded: "Erfasst",
    due: "Interner Zieltermin",
    graph: "Influence Graph öffnen",
    law: "Überwachtes Dokument",
    none: "Kein Dokument verknüpft",
    add: "Notiz hinzufügen",
    remove: "Notiz entfernen",
    sources: "Belegquellen",
    status: "Aufgabenstatus",
    revision: "Gespeicherte Revision",
    empty: "Keine Notizen in dieser Kategorie.",
    failed: "Der Prüfvermerk konnte nicht geladen werden.",
    retry: "Erneut versuchen",
    name: "Titel",
    kind: "Kategorie",
  },
  "fr-CH": {
    title: "Note de revue",
    finding: "Constats",
    discussion: "Discussion",
    task: "Tâches",
    note: "Notes éditoriales conservées séparément des réponses IA. Les dates indiquent les révisions enregistrées.",
    fictional: "Personnage fictif",
    author: "Contributeur",
    role: "Rôle",
    body: "Note",
    open: "Ouvert",
    in_progress: "En cours",
    complete: "Terminé",
    recorded: "Enregistré",
    due: "Échéance interne",
    graph: "Ouvrir Influence Graph",
    law: "Document suivi",
    none: "Aucun document lié",
    add: "Ajouter une note",
    remove: "Retirer la note",
    sources: "Sources justificatives",
    status: "Statut de la tâche",
    revision: "Révision enregistrée",
    empty: "Aucune note dans cette catégorie.",
    failed: "Impossible de charger la note de revue.",
    retry: "Réessayer",
    name: "Titre",
    kind: "Catégorie",
  },
  "it-CH": {
    title: "Nota di revisione",
    finding: "Risultati",
    discussion: "Discussione",
    task: "Attività",
    note: "Note redazionali conservate separatamente dalle risposte IA. Le date indicano le revisioni salvate.",
    fictional: "Persona fittizia",
    author: "Autore",
    role: "Ruolo",
    body: "Nota",
    open: "Aperto",
    in_progress: "In corso",
    complete: "Completato",
    recorded: "Registrato",
    due: "Scadenza interna",
    graph: "Apri Influence Graph",
    law: "Documento monitorato",
    none: "Nessun documento collegato",
    add: "Aggiungi nota",
    remove: "Rimuovi nota",
    sources: "Fonti di supporto",
    status: "Stato attività",
    revision: "Revisione salvata",
    empty: "Nessuna nota in questa categoria.",
    failed: "Impossibile caricare la nota di revisione.",
    retry: "Riprova",
    name: "Titolo",
    kind: "Categoria",
  },
  "rm-CH": {
    title: "Nota da controlla",
    finding: "Resultats",
    discussion: "Discussiun",
    task: "Incumbensas",
    note: "Notas redacziunalas memorisadas separadamain da las respostas IA. Las datas inditgeschan las revisiuns memorisadas.",
    fictional: "Persuna fictiva",
    author: "Autur",
    role: "Rolla",
    body: "Nota",
    open: "Avert",
    in_progress: "En elavuraziun",
    complete: "Terminà",
    recorded: "Registrà",
    due: "Termin intern",
    graph: "Avrir Influence Graph",
    law: "Document surveglià",
    none: "Nagin document collià",
    add: "Agiuntar nota",
    remove: "Allontanar nota",
    sources: "Funtaunas da cumprova",
    status: "Status da l’incumbensa",
    revision: "Revisiun memorisada",
    empty: "Naginas notas en questa categoria.",
    failed: "La nota da controlla n’ha betg pudì vegnir chargiada.",
    retry: "Empruvar danovamain",
    name: "Titel",
    kind: "Categoria",
  },
};
