import type { Locale } from "./i18n";

const locales: Locale[] = ["de-CH", "fr-CH", "it-CH", "rm-CH", "en-CH"];
const words = {
  meteoalarm: [
    "MeteoAlarm",
    "MeteoAlarm",
    "MeteoAlarm",
    "MeteoAlarm",
    "MeteoAlarm",
  ],
  incompleteHistory: [
    "Diese Warnung wurde als Aktualisierung übernommen. Frühere amtliche Fassungen sind hier nicht verfügbar.",
    "Cette alerte a été reçue sous forme de mise à jour. Les versions officielles antérieures ne sont pas disponibles ici.",
    "Questo avviso è stato ricevuto come aggiornamento. Le versioni ufficiali precedenti non sono disponibili qui.",
    "Quest avertiment è vegnì retschavì sco actualisaziun. Versiuns uffizialas anteriuras n’èn betg disponiblas qua.",
    "This warning was received as an update. Earlier official versions are not available here.",
  ],
  noLongerListed: [
    "Die Quelle führt diese Warnung nicht mehr auf. Das ist keine amtliche Entwarnung. Frühere Fassungen bleiben im Verlauf verfügbar.",
    "La source ne répertorie plus cette alerte. Cela ne constitue pas une levée officielle de l’alerte. Les versions précédentes restent dans l’historique.",
    "La fonte non elenca più questo avviso. Non equivale a un cessato allarme ufficiale. Le versioni precedenti restano nella cronologia.",
    "La funtauna na mussa betg pli quest avertiment. Quai n’è betg ina fin uffiziala da l’alarm. Las versiuns anteriuras restan en l’istorgia.",
    "The source no longer lists this warning. This is not an official all-clear. Earlier versions remain in the history.",
  ],
  sourceNotCurrent: [
    "Die Quelle konnte nicht rechtzeitig vollständig geprüft werden. Die aktuellen Anweisungen können nicht bestätigt werden; prüfen Sie die amtliche Quelle.",
    "La source n’a pas pu être entièrement vérifiée à temps. Les consignes actuelles ne peuvent pas être confirmées ; consultez la source officielle.",
    "Non è stato possibile verificare completamente la fonte in tempo. Le istruzioni attuali non possono essere confermate; consultare la fonte ufficiale.",
    "La funtauna n’ha betg pudì vegnir controllada cumplainamain a temp. Las instrucziuns actualas na pon betg vegnir confermadas; consultai la funtauna uffiziala.",
    "The source could not be fully checked in time. Current instructions cannot be confirmed; check the official source.",
  ],
  impacts: [
    "Amtlich beschriebene Auswirkungen",
    "Impacts décrits par la source officielle",
    "Impatti descritti dalla fonte ufficiale",
    "Consequenzas descrittas da la funtauna uffiziala",
    "Officially described impacts",
  ],
  today: [
    "Neue Warnungen für meine Orte",
    "Nouvelles alertes pour mes lieux",
    "Nuovi avvisi per i miei luoghi",
    "Novs avertiments per mes lieus",
    "New warnings for my places",
  ],
  inbox: [
    "Aktive Warnungen für meine Orte",
    "Alertes actives pour mes lieux",
    "Avvisi attivi per i miei luoghi",
    "Avertiments activs per mes lieus",
    "Active warnings for my places",
  ],
  todayScope: [
    "Ungelesene Änderungen der letzten 48 Stunden. Stummgeschaltete Typen sind ausgeblendet.",
    "Changements non lus des dernières 48 heures. Les types masqués ne sont pas affichés.",
    "Modifiche non lette delle ultime 48 ore. I tipi silenziati sono nascosti.",
    "Midadas betg legidas da las ultimas 48 uras. Tips cun avisaziuns deactivadas èn zuppads.",
    "Unread changes from the last 48 hours. Muted types are hidden.",
  ],
  inboxScope: [
    "Ungelesene Warnungen und Alarme für gespeicherte Orte, einschliesslich angekündigter Warnungen. Stummgeschaltete Typen sind ausgeblendet.",
    "Alertes et alarmes non lues pour les lieux enregistrés, y compris celles annoncées. Les types masqués ne sont pas affichés.",
    "Avvisi e allarmi non letti per i luoghi salvati, inclusi quelli previsti. I tipi silenziati sono nascosti.",
    "Avertiments ed alarms betg legids per lieus memorisads, inclus ils annunziads. Tips cun avisaziuns deactivadas èn zuppads.",
    "Unread warnings and alarms for saved places, including planned warnings. Muted types are hidden.",
  ],
  openInstructions: [
    "Warnung und amtliche Anweisungen öffnen",
    "Ouvrir l’alerte et les consignes officielles",
    "Apri avviso e istruzioni ufficiali",
    "Avrir l’avertiment e las instrucziuns uffizialas",
    "Open warning and official instructions",
  ],
  feedEmpty: [
    "Keine ungelesenen Warnungen in dieser Auswahl.",
    "Aucune alerte non lue dans cette sélection.",
    "Nessun avviso non letto in questa selezione.",
    "Nagins avertiments betg legids en questa selecziun.",
    "No unread warnings in this selection.",
  ],
  detected: [
    "Änderung erkannt",
    "Changement détecté",
    "Modifica rilevata",
    "Midada constatada",
    "Change detected",
  ],
  importance: [
    "Warnstufe",
    "Niveau de l’alerte",
    "Livello dell’avviso",
    "Nivel da l’avertiment",
    "Warning level",
  ],
  information: [
    "Information",
    "Information",
    "Informazione",
    "Infurmaziun",
    "Information",
  ],
  warning: ["Warnung", "Alerte", "Avviso", "Avertiment", "Warning"],
  alarm: ["Alarm", "Alarme", "Allarme", "Alarm", "Alarm"],
  placeSettings: [
    "Gespeicherter Ort",
    "Lieu enregistré",
    "Luogo salvato",
    "Lieu memorisà",
    "Saved place",
  ],
  events: [
    "Warnungen für diesen Ort",
    "Alertes pour ce lieu",
    "Avvisi per questo luogo",
    "Avertiments per quest lieu",
    "Warnings for this place",
  ],
  current: [
    "Aktuelle Warnung",
    "Alerte actuelle",
    "Avviso attuale",
    "Avertiment actual",
    "Current warning",
  ],
  historical: [
    "Historische Fassung",
    "Version historique",
    "Versione storica",
    "Versiun istorica",
    "Historical revision",
  ],
  history: [
    "Warnungsverlauf",
    "Historique de l’alerte",
    "Cronologia dell’avviso",
    "Istorgia da l’avertiment",
    "Warning history",
  ],
  audit: [
    "Meine Aktionen",
    "Mes actions",
    "Le mie azioni",
    "Mias acziuns",
    "My actions",
  ],
  official: [
    "Amtliche Mitteilung",
    "Message officiel",
    "Messaggio ufficiale",
    "Communicaziun uffiziala",
    "Official message",
  ],
  instructions: [
    "Amtliche Anweisungen",
    "Consignes officielles",
    "Istruzioni ufficiali",
    "Instrucziuns uffizialas",
    "Official instructions",
  ],
  noInstructions: [
    "Keine Anweisungen in dieser Sprachfassung.",
    "Aucune consigne dans cette version linguistique.",
    "Nessuna istruzione in questa versione linguistica.",
    "Naginas instrucziuns en questa versiun linguistica.",
    "No instructions in this language version.",
  ],
  language: [
    "Sprache der Quelle",
    "Langue de la source",
    "Lingua della fonte",
    "Lingua da la funtauna",
    "Source language",
  ],
  original: [
    "Originaltext der Quelle; keine automatische Übersetzung.",
    "Texte original de la source, sans traduction automatique.",
    "Testo originale della fonte, senza traduzione automatica.",
    "Text original da la funtauna, senza translaziun automatica.",
    "Original source text; no automatic translation.",
  ],
  fetched: [
    "Zuletzt von der Quelle erhalten",
    "Dernière réception de la source",
    "Ultima ricezione dalla fonte",
    "Ultima recepziun da la funtauna",
    "Last received from source",
  ],
  published: [
    "Von der Quelle veröffentlicht",
    "Publié par la source",
    "Pubblicato dalla fonte",
    "Publitgà da la funtauna",
    "Published by source",
  ],
  effective: [
    "Gültig ab",
    "Valable dès",
    "Valido da",
    "Vala a partir da",
    "Effective from",
  ],
  expires: [
    "Gültig bis",
    "Valable jusqu’au",
    "Valido fino a",
    "Vala fin",
    "Valid until",
  ],
  openOfficial: [
    "Amtliche Seite öffnen",
    "Ouvrir la page officielle",
    "Apri la pagina ufficiale",
    "Avrir la pagina uffiziala",
    "Open official page",
  ],
  coverage: [
    "Diese Liste bestätigt keine vollständige Gefahrenabdeckung. Fehlende Daten sind keine Entwarnung.",
    "Cette liste ne confirme pas une couverture complète des dangers. L’absence de données n’est pas une levée d’alerte.",
    "Questo elenco non conferma una copertura completa dei pericoli. L’assenza di dati non è un cessato allarme.",
    "Questa glista na conferma betg ina cuvrida cumpletta dals privels. Datas mancantas n’èn betg ina fin d’alarm.",
    "This list does not confirm complete hazard coverage. Missing data is not an all-clear.",
  ],
  empty: [
    "Keine bestätigten Warnungen in dieser Auswahl.",
    "Aucune alerte confirmée dans cette sélection.",
    "Nessun avviso confermato in questa selezione.",
    "Nagins avertiments confermads en questa selecziun.",
    "No confirmed warnings in this selection.",
  ],
  unavailable: [
    "Nicht verfügbar",
    "Indisponible",
    "Non disponibile",
    "Betg disponibel",
    "Unavailable",
  ],
  unavailableDetail: [
    "Die Belege sind nicht mehr bestätigt oder zugänglich. Daraus folgt keine Entwarnung.",
    "Les éléments ne sont plus confirmés ou accessibles. Cela ne signifie pas une levée d’alerte.",
    "Le prove non sono più confermate o accessibili. Questo non significa cessato allarme.",
    "Las cumprovas n’èn betg pli confermadas u accessiblas. Quai na signifitga betg ina fin d’alarm.",
    "The evidence is no longer confirmed or accessible. This does not mean an all-clear.",
  ],
  active: ["Aktiv", "Active", "Attivo", "Activ", "Active"],
  planned: [
    "Künftig gültig",
    "Valable ultérieurement",
    "Valido in futuro",
    "Vala pli tard",
    "Effective later",
  ],
  resolved: [
    "Amtliche Entwarnung",
    "Levée d’alerte officielle",
    "Cessato allarme ufficiale",
    "Fin d’alarm uffiziala",
    "Official all-clear",
  ],
  cancelled: [
    "Mitteilung zurückgezogen",
    "Message retiré",
    "Messaggio ritirato",
    "Communicaziun retratga",
    "Notice withdrawn",
  ],
  cancelledDetail: [
    "Die Quelle hat die Mitteilung zurückgezogen. Das ist keine Bestätigung, dass die Gefahr vorbei ist.",
    "La source a retiré le message. Cela ne confirme pas la fin du danger.",
    "La fonte ha ritirato il messaggio. Questo non conferma che il pericolo sia terminato.",
    "La funtauna ha retratg la communicaziun. Quai na conferma betg che il privel saja passà.",
    "The source withdrew the notice. This does not confirm that the danger has passed.",
  ],
  not_relevant: [
    "Ausserhalb der aktuellen Auswahl",
    "Hors de la sélection actuelle",
    "Fuori dalla selezione attuale",
    "Ordaifer la selecziun actuala",
    "Outside current selection",
  ],
  reviewed: ["Gesehen", "Consulté", "Esaminato", "Vesì", "Reviewed"],
  needsReview: [
    "Erneut ansehen",
    "À consulter",
    "Da esaminare",
    "Da guardar",
    "Needs review",
  ],
  markReviewed: [
    "Als gesehen markieren",
    "Marquer comme consulté",
    "Segna come esaminato",
    "Marcar sco vesì",
    "Mark as reviewed",
  ],
  dismiss: [
    "Betrifft mich nicht",
    "Ne me concerne pas",
    "Non mi riguarda",
    "Na ma pertutga betg",
    "Not relevant to me",
  ],
  dismissed: [
    "Als nicht relevant markiert",
    "Marqué comme non pertinent",
    "Segnato come non pertinente",
    "Marcà sco betg relevant",
    "Marked not relevant",
  ],
  muteTitle: [
    "Gefahrenarten stummschalten",
    "Mettre des types de danger en sourdine",
    "Silenzia tipi di pericolo",
    "Metter tips da privel sin mut",
    "Mute hazard types",
  ],
  muteHint: [
    "Gilt nur für diesen gespeicherten Ort. Verlauf und Gesehen-Markierungen bleiben erhalten.",
    "S’applique uniquement à ce lieu enregistré. L’historique et les consultations sont conservés.",
    "Si applica solo a questo luogo salvato. Cronologia e revisioni restano disponibili.",
    "Vala mo per quest lieu memorisà. L’istorgia e las marcaziuns restan mantegnidas.",
    "Applies only to this saved place. History and review records are preserved.",
  ],
  mute: [
    "Stummschalten",
    "Mettre en sourdine",
    "Silenzia",
    "Metter sin mut",
    "Mute",
  ],
  unmute: [
    "Stummschaltung aufheben",
    "Réactiver",
    "Riattiva",
    "Reactivar",
    "Unmute",
  ],
  muted: ["Stummgeschaltet", "En sourdine", "Silenziato", "Sin mut", "Muted"],
  back: [
    "Zur Warnungsliste",
    "Retour aux alertes",
    "Torna agli avvisi",
    "Enavos als avertiments",
    "Back to warnings",
  ],
  openCurrent: [
    "Aktuelle Fassung öffnen",
    "Ouvrir la version actuelle",
    "Apri la versione attuale",
    "Avrir la versiun actuala",
    "Open current revision",
  ],
  invalidLink: [
    "Dieser Warnungslink ist ungültig. Öffnen Sie die Warnung erneut aus der Liste.",
    "Ce lien d’alerte est invalide. Rouvrez l’alerte depuis la liste.",
    "Questo collegamento non è valido. Riapri l’avviso dall’elenco.",
    "Questa colliaziun n’è betg valida. Avri l’avertiment danovamain ord la glista.",
    "This warning link is invalid. Reopen the warning from the list.",
  ],
  adminFilter: [
    "Die Quelle nennt diese Gemeinde; möglicherweise ist nur ein Teil betroffen.",
    "La source mentionne cette commune ; seule une partie peut être touchée.",
    "La fonte indica questo comune; potrebbe esserne interessata solo una parte.",
    "La funtauna numna questa vischnanca; eventualmain è mo ina part pertutgada.",
    "The source names this municipality; only part of it may be affected.",
  ],
  geometryMatch: [
    "Der gespeicherte Ort überschneidet sich mit dem Gebiet der Quelle.",
    "Le lieu enregistré recoupe la zone indiquée par la source.",
    "Il luogo salvato interseca l’area indicata dalla fonte.",
    "Il lieu memorisà sa cruscha cun il territori da la funtauna.",
    "The saved location intersects the area provided by the source.",
  ],
  certainty: [
    "Sicherheit laut Quelle",
    "Certitude selon la source",
    "Certezza secondo la fonte",
    "Segirezza tenor la funtauna",
    "Certainty reported by source",
  ],
  Observed: ["Beobachtet", "Observé", "Osservato", "Observà", "Observed"],
  Likely: ["Wahrscheinlich", "Probable", "Probabile", "Probabel", "Likely"],
  Possible: ["Möglich", "Possible", "Possibile", "Pussaivel", "Possible"],
  Unlikely: [
    "Unwahrscheinlich",
    "Peu probable",
    "Improbabile",
    "Pauc probabel",
    "Unlikely",
  ],
  Unknown: [
    "Unbekannt",
    "Inconnue",
    "Sconosciuta",
    "Nunenconuschenta",
    "Unknown",
  ],
} as const;
export type HazardEventCopy = { [K in keyof typeof words]: string };
export const hazardEventCopy = Object.fromEntries(
  locales.map((locale, index) => [
    locale,
    Object.fromEntries(
      Object.entries(words).map(([key, values]) => [key, values[index]]),
    ),
  ]),
) as Record<Locale, HazardEventCopy>;
