import type { Locale } from "./i18n";

const locales: Locale[] = ["de-CH", "fr-CH", "it-CH", "rm-CH", "en-CH"];
const words = {
  title: [
    "Warnungen für meine Orte",
    "Alertes pour mes lieux",
    "Avvisi per i miei luoghi",
    "Avertiments per mes lieus",
    "Warnings for my places",
  ],
  locationCheck: [
    "Ortsprüfung",
    "Vérification du lieu",
    "Verifica del luogo",
    "Verificaziun dal lieu",
    "Location check",
  ],
  locationVerified: [
    "Der Ort wurde einer Schweizer Gemeinde zugeordnet.",
    "Le lieu a été associé à une commune suisse.",
    "Il luogo è stato associato a un comune svizzero.",
    "Il lieu è vegnì attribuì ad ina vischnanca svizra.",
    "The location was matched to a Swiss municipality.",
  ],
  locationOutside: [
    "Diese Koordinaten liegen ausserhalb der Schweiz. Bitte prüfen Sie den Ort.",
    "Ces coordonnées sont hors de Suisse. Vérifiez le lieu.",
    "Queste coordinate sono fuori dalla Svizzera. Verifica il luogo.",
    "Questas coordinatas èn ordaifer la Svizra. Verifitgai il lieu.",
    "These coordinates are outside Switzerland. Check the location.",
  ],
  locationCantonMismatch: [
    "Der Ort gehört nicht zum gewählten Kanton.",
    "Le lieu n’appartient pas au canton sélectionné.",
    "Il luogo non appartiene al cantone selezionato.",
    "Il lieu na tutga betg al chantun tschernì.",
    "The location does not belong to the selected canton.",
  ],
  locationBorder: [
    "Die Lage an einer Grenze lässt sich nicht sicher zuordnen.",
    "La proximité d’une limite ne permet pas une attribution certaine.",
    "La vicinanza a un confine non consente un’attribuzione certa.",
    "La posiziun sper in cunfin na permetta betg in’attribuziun segira.",
    "The location is too close to a boundary to assign with confidence.",
  ],
  locationUnknown: [
    "Der Ort konnte nicht zugeordnet werden. Prüfen Sie die Koordinaten oder die aktuelle Gemeindenummer.",
    "Le lieu n’a pas pu être identifié. Vérifiez les coordonnées ou le numéro actuel de la commune.",
    "Impossibile identificare il luogo. Verifica le coordinate o il numero attuale del comune.",
    "Il lieu n’ha betg pudì vegnir attribuì. Verifitgai las coordinatas u il numer actual da la vischnanca.",
    "The location could not be matched. Check the coordinates or current municipality number.",
  ],
  catalogueUnavailable: [
    "Die geprüften Gemeindegrenzen sind derzeit nicht verfügbar.",
    "Les limites communales vérifiées sont actuellement indisponibles.",
    "I confini comunali verificati non sono attualmente disponibili.",
    "Ils cunfins communals verifitgads n’èn actualmain betg disponibels.",
    "The reviewed municipality boundaries are currently unavailable.",
  ],
  catalogueExpired: [
    "Die Gemeindegrenzen müssen erneut geprüft werden. Der Ort ist noch nicht bestätigt.",
    "Les limites communales doivent être revérifiées. Le lieu n’est pas encore confirmé.",
    "I confini comunali devono essere ricontrollati. Il luogo non è ancora confermato.",
    "Ils cunfins communals ston vegnir verifitgads danovamain. Il lieu n’è anc betg confermà.",
    "The municipality boundaries need to be reviewed again. The location is not yet confirmed.",
  ],
  catalogueEdition: [
    "Grenzstand",
    "Édition des limites",
    "Edizione dei confini",
    "Ediziun dals cunfins",
    "Boundary edition",
  ],
  radiusUnverified: [
    "Die Abdeckung des gesamten Umkreises durch Warnquellen ist noch nicht bestätigt.",
    "La couverture de l’ensemble du rayon par les sources d’alerte n’est pas encore confirmée.",
    "La copertura dell’intero raggio da parte delle fonti di avviso non è ancora confermata.",
    "La cuvrida da l’entir radius tras las funtaunas d’avertiment n’è anc betg confermada.",
    "Warning-source coverage of the entire radius is not yet confirmed.",
  ],
  intro: [
    "Speichern Sie private Orte und wählen Sie die gewünschten Warnungen.",
    "Enregistrez des lieux privés et choisissez les alertes souhaitées.",
    "Salva luoghi privati e scegli gli avvisi desiderati.",
    "Memorisai lieus privats e tschernì ils avertiments giavischads.",
    "Save private places and choose the warnings you want to follow.",
  ],
  pending: [
    "Speichern erstellt einen privaten Entwurf. Starten Sie die Überwachung separat, sobald Quelle und Gebiet geprüft sind. E-Mails benötigen eine eigene Zustimmung.",
    "Enregistrer crée un brouillon privé. Démarrez la surveillance séparément après vérification de la source et de la zone. Les e-mails nécessitent un consentement distinct.",
    "Il salvataggio crea una bozza privata. Avvia il monitoraggio separatamente dopo la verifica della fonte e dell’area. Le e-mail richiedono un consenso distinto.",
    "Memorisar creescha in sboz privat. Avviai la surveglianza separadamain suenter la verificaziun da la funtauna e dal territori. E-mails dovran in consentiment separà.",
    "Saving creates a private draft. Start monitoring separately once the source and area are verified. Email requires separate consent.",
  ],
  create: [
    "Ort hinzufügen",
    "Ajouter un lieu",
    "Aggiungi luogo",
    "Agiuntar in lieu",
    "Add place",
  ],
  name: [
    "Name des Ortes",
    "Nom du lieu",
    "Nome del luogo",
    "Num dal lieu",
    "Place name",
  ],
  empty: [
    "Noch keine gespeicherten Orte.",
    "Aucun lieu enregistré.",
    "Nessun luogo salvato.",
    "Anc nagins lieus memorisads.",
    "No saved places yet.",
  ],
  point: [
    "Koordinaten",
    "Coordonnées",
    "Coordinate",
    "Coordinatas",
    "Coordinates",
  ],
  municipality: ["Gemeinde", "Commune", "Comune", "Vischnanca", "Municipality"],
  municipalityCode: [
    "BFS-Gemeindenummer",
    "Numéro OFS de la commune",
    "Numero UST del comune",
    "Numer UST da la vischnanca",
    "Official municipality number",
  ],
  canton: ["Kanton", "Canton", "Cantone", "Chantun", "Canton"],
  choose: ["Bitte wählen", "Sélectionner", "Seleziona", "Tschernir", "Choose"],
  latitude: ["Breitengrad", "Latitude", "Latitudine", "Latituda", "Latitude"],
  longitude: [
    "Längengrad",
    "Longitude",
    "Longitudine",
    "Longituda",
    "Longitude",
  ],
  radius: [
    "Umkreis (km)",
    "Rayon (km)",
    "Raggio (km)",
    "Radius (km)",
    "Radius (km)",
  ],
  hazards: [
    "Gefahrenarten",
    "Types de danger",
    "Tipi di pericolo",
    "Tips da privel",
    "Hazard types",
  ],
  flood: ["Hochwasser", "Crue", "Piena", "Aua gronda", "Flood"],
  storm: ["Unwetter", "Intempéries", "Maltempo", "Stemprà", "Storm"],
  forest_fire: [
    "Waldbrand",
    "Incendie de forêt",
    "Incendio boschivo",
    "Incendi da guaud",
    "Forest fire",
  ],
  heavy_snow: [
    "Starker Schneefall",
    "Fortes chutes de neige",
    "Forti nevicate",
    "Ferma naiv",
    "Heavy snow",
  ],
  power_outage: [
    "Stromausfall",
    "Panne de courant",
    "Interruzione elettrica",
    "Interrupziun da l’electricitad",
    "Power outage",
  ],
  civil_protection_warning: [
    "Bevölkerungsschutz",
    "Protection de la population",
    "Protezione della popolazione",
    "Protecziun da la populaziun",
    "Civil protection",
  ],
  importance: [
    "Mindeststufe",
    "Niveau minimal",
    "Livello minimo",
    "Stgalim minimal",
    "Minimum importance",
  ],
  information: [
    "Information oder höher",
    "Information ou plus",
    "Informazione o superiore",
    "Infurmaziun u pli aut",
    "Information or higher",
  ],
  warning: [
    "Warnung oder höher",
    "Alerte ou plus",
    "Allerta o superiore",
    "Avertiment u pli aut",
    "Warning or higher",
  ],
  alarm: ["Alarm", "Alarme", "Allarme", "Alarm", "Alarm"],
  remove: [
    "Ort löschen",
    "Supprimer le lieu",
    "Elimina luogo",
    "Stizzar il lieu",
    "Delete place",
  ],
  confirmDelete: [
    "Ort und private Einstellungshistorie endgültig löschen?",
    "Supprimer définitivement ce lieu et l’historique privé de ses réglages ?",
    "Eliminare definitivamente questo luogo e la cronologia privata delle impostazioni?",
    "Stizzar definitivamain quest lieu e la cronologia privata da sias configuraziuns?",
    "Permanently delete this place and its private configuration history?",
  ],
  changed: [
    "Die Einstellungen wurden geändert. Bitte aktualisieren.",
    "Les réglages ont changé. Actualisez la page.",
    "Le impostazioni sono cambiate. Aggiorna la pagina.",
    "Las configuraziuns èn vegnidas midadas. Actualisai la pagina.",
    "The settings changed. Refresh before editing again.",
  ],
  unavailable: [
    "Die Ortsüberwachung ist derzeit nicht verfügbar.",
    "La surveillance des lieux est actuellement indisponible.",
    "Il monitoraggio dei luoghi non è disponibile.",
    "La surveglianza da lieus n’è actualmain betg disponibla.",
    "Location monitoring is currently unavailable.",
  ],
  required: [
    "Wählen Sie mindestens eine Gefahrenart.",
    "Choisissez au moins un type de danger.",
    "Scegli almeno un tipo di pericolo.",
    "Tschernì almain in tip da privel.",
    "Choose at least one hazard type.",
  ],
} as const;
export type HazardCopy = { [K in keyof typeof words]: string };
export const hazardCopy = Object.fromEntries(
  locales.map((locale, index) => [
    locale,
    Object.fromEntries(
      Object.entries(words).map(([key, values]) => [key, values[index]]),
    ),
  ]),
) as Record<Locale, HazardCopy>;
