import type { Locale } from "./i18n";

const en = {
  title: "Influence Graph",
  intro: "Inspect relationships. Follow the evidence.",
  prototype: "Research workspace",
  example: "Public reference dossier",
  private: "Workspace dossiers",
  snapshot: "Evidence checked",
  sourceLanguage: "Dossier language",
  limits: "What this does not establish",
  graph: "Graph",
  list: "Evidence list",
  perspective: "Show",
  entity: "Entity",
  allEntities: "All entities",
  all: "All relationships",
  documented: "Documented relationships",
  money: "Confirmed money flows",
  policy: "Policy connections",
  graphHelp:
    "Choose a numbered connection to inspect its evidence. The complete list provides the same information.",
  moneyHelp:
    "Only recorded payments with primary evidence, an amount, currency and period. Ownership and possible benefits are excluded.",
  empty:
    "No relationships match this view. Missing evidence does not prove that a relationship or payment does not exist.",
  connections: "Relationships",
  entities: "Entities",
  sources: "Sources",
  evidence: "Evidence",
  supporting: "Supporting source",
  disputing: "Counter-statement",
  open: "Open source",
  locator: "Page / section",
  summary: "Evidence summary",
  quote: "Exact quote (optional)",
  sourceDate: "Published",
  checked: "Checked",
  effective: "Applies as of",
  undated: "Not dated",
  scope: "Scope and limits",
  noArchive: "No retained source extract. The live page may change.",
  extract: "Retained source extract",
  extractHelp:
    "Paste a permitted extract. This retains your text; it does not capture or verify the live page.",
  gaps: "Open evidence questions",
  count: "visible",
  clear: "Clear filters",
  selected: "Selected connection",
  new: "New dossier",
  copy: "Copy to workspace",
  edit: "Edit dossier",
  save: "Save revision",
  cancel: "Cancel",
  remove: "Remove",
  add: "Add",
  details: "Dossier",
  relations: "Relationships",
  name: "Name / title",
  kind: "Type",
  country: "Country code (optional)",
  from: "From",
  to: "To",
  label: "Connection label",
  statement: "Claim",
  status: "Evidence status",
  note: "Reason / review note",
  url: "Source URL",
  publisher: "Publisher",
  language: "Language code",
  source: "Source",
  date: "Dossier review date",
  amount: "Amount",
  currency: "Currency",
  periodStart: "Period from",
  periodEnd: "Period to",
  paid: "Paid",
  proposed: "Proposed",
  basis: "Payment basis",
  addEvidence: "Add supporting evidence",
  addCounter: "Add counter-statement",
  missing: "Missing evidence (one item per line)",
  limitLines: "Limits (one item per line)",
  required: "Complete the required fields and evidence before saving.",
  saved: "Revision saved.",
  loading: "Loading…",
  failed:
    "The request failed. Your draft is retained. Check access and try again.",
  conflict:
    "A newer revision exists. Your draft is retained; copy your changes before loading the latest version.",
  readonly:
    "Viewers can read workspace dossiers. An administrator can edit and record reviews.",
  history: "Revision history",
  revision: "Revision",
  latest: "Load latest",
  older: "Older revisions",
  more: "More dossiers",
  refresh: "Refresh",
  archive: "Archive",
  restore: "Restore",
  active: "Active",
  archived: "Archived",
  review: "Record review",
  reviewed: "Reviewed",
  needs_revision: "Needs revision",
  draft: "Not reviewed",
  reviewHelp:
    "An editorial decision applies only to this revision. It does not verify every claim or change evidence statuses.",
  reasonHelp:
    "Describe what changed or what you checked (at least 3 characters).",
  export: "Download dossier JSON",
  workspaceHelp:
    "Shared with this workspace. Source text and editorial notes are retained in revision history.",
  discard: "Discard your unsaved dossier changes?",
  unavailable: "Workspace dossiers require a signed-in session.",
  historical:
    "Historical revision — load the latest version to edit or review.",
  noDossiers: "No dossiers in this view.",
  integrity: "Saved document SHA-256",
  deletedActor: "Deleted account",
  author: "Actor",
  noSelection: "Choose a relationship to inspect its evidence.",
  graphFull: "No available graph position.",
  statuses: {
    documented: "Documented",
    reported: "Reported",
    disputed: "Disputed",
    not_established: "Not established",
  },
  entityKinds: {
    person: "Person",
    company: "Company",
    initiative: "Initiative",
    policy: "Policy",
    group: "Group / aggregate",
  },
  sourceKinds: {
    primary_corporate: "Corporate primary source",
    primary_government: "Government primary source",
    primary_campaign: "Campaign primary source",
    reporting: "Journalistic reporting",
  },
  relationKinds: {
    family: "Family",
    role: "Role",
    campaign: "Campaign",
    ownership: "Ownership",
    business: "Business relationship",
    policy_proposal: "Policy proposal",
    potential_impact: "Potential effect",
    dividend: "Dividend payment",
  },
};

export const influenceCopy: Record<Locale, typeof en> = {
  "en-CH": en,
  "de-CH": {
    title: "Influence Graph",
    intro: "Beziehungen prüfen. Belegen folgen.",
    prototype: "Recherchebereich",
    example: "Öffentliches Referenzdossier",
    private: "Dossiers des Arbeitsbereichs",
    snapshot: "Belege geprüft",
    sourceLanguage: "Dossiersprache",
    limits: "Was damit nicht belegt ist",
    graph: "Graph",
    list: "Belegliste",
    perspective: "Anzeigen",
    entity: "Akteur",
    allEntities: "Alle Akteure",
    all: "Alle Beziehungen",
    documented: "Dokumentierte Beziehungen",
    money: "Bestätigte Geldflüsse",
    policy: "Politische Verbindungen",
    graphHelp:
      "Eine nummerierte Verbindung öffnet ihre Belege. Die vollständige Liste bietet dieselben Informationen.",
    moneyHelp:
      "Nur erfasste Zahlungen mit Primärbeleg, Betrag, Währung und Zeitraum. Beteiligungen und mögliche Vorteile sind ausgeschlossen.",
    empty:
      "Keine Beziehungen in dieser Ansicht. Fehlende Belege beweisen nicht, dass eine Beziehung oder Zahlung nicht existiert.",
    connections: "Beziehungen",
    entities: "Akteure",
    sources: "Quellen",
    evidence: "Belege",
    supporting: "Stützende Quelle",
    disputing: "Gegendarstellung",
    open: "Quelle öffnen",
    locator: "Seite / Abschnitt",
    summary: "Zusammenfassung des Belegs",
    quote: "Wörtliches Zitat (optional)",
    sourceDate: "Veröffentlicht",
    checked: "Geprüft",
    effective: "Stand",
    undated: "Undatiert",
    scope: "Geltungsbereich und Grenzen",
    noArchive:
      "Kein gespeicherter Quellenauszug. Die Webseite kann sich ändern.",
    extract: "Gespeicherter Quellenauszug",
    extractHelp:
      "Einen zulässigen Auszug einfügen. Ihr Text wird gespeichert; die Webseite wird nicht erfasst oder geprüft.",
    gaps: "Offene Belegfragen",
    count: "sichtbar",
    clear: "Filter zurücksetzen",
    selected: "Gewählte Verbindung",
    new: "Neues Dossier",
    copy: "In Arbeitsbereich kopieren",
    edit: "Dossier bearbeiten",
    save: "Version speichern",
    cancel: "Abbrechen",
    remove: "Entfernen",
    add: "Hinzufügen",
    details: "Dossier",
    relations: "Beziehungen",
    name: "Name / Titel",
    kind: "Typ",
    country: "Ländercode (optional)",
    from: "Von",
    to: "Zu",
    label: "Verbindungsbezeichnung",
    statement: "Aussage",
    status: "Belegstatus",
    note: "Begründung / Prüfvermerk",
    url: "Quellen-URL",
    publisher: "Herausgeber",
    language: "Sprachcode",
    source: "Quelle",
    date: "Prüfdatum des Dossiers",
    amount: "Betrag",
    currency: "Währung",
    periodStart: "Zeitraum von",
    periodEnd: "Zeitraum bis",
    paid: "Bezahlt",
    proposed: "Vorgeschlagen",
    basis: "Zahlungsgrundlage",
    addEvidence: "Stützenden Beleg hinzufügen",
    addCounter: "Gegendarstellung hinzufügen",
    missing: "Fehlende Belege (einer pro Zeile)",
    limitLines: "Grenzen (eine pro Zeile)",
    required: "Pflichtfelder und Belege vor dem Speichern vervollständigen.",
    saved: "Version gespeichert.",
    loading: "Wird geladen…",
    failed:
      "Anfrage fehlgeschlagen. Ihr Entwurf bleibt erhalten. Zugriff prüfen und erneut versuchen.",
    conflict:
      "Eine neuere Version existiert. Ihr Entwurf bleibt erhalten; kopieren Sie Ihre Änderungen vor dem Laden der neuesten Version.",
    readonly:
      "Leser können Dossiers ansehen. Administratoren können bearbeiten und Prüfungen erfassen.",
    history: "Versionsverlauf",
    revision: "Version",
    latest: "Neueste laden",
    older: "Ältere Versionen",
    more: "Weitere Dossiers",
    refresh: "Aktualisieren",
    archive: "Archivieren",
    restore: "Wiederherstellen",
    active: "Aktiv",
    archived: "Archiviert",
    review: "Prüfung erfassen",
    reviewed: "Geprüft",
    needs_revision: "Überarbeitung nötig",
    draft: "Ungeprüft",
    reviewHelp:
      "Eine redaktionelle Entscheidung gilt nur für diese Version. Sie bestätigt nicht jede Aussage und ändert keine Belegstatus.",
    reasonHelp: "Änderungen oder Prüfung beschreiben (mindestens 3 Zeichen).",
    export: "Dossier als JSON herunterladen",
    workspaceHelp:
      "Mit diesem Arbeitsbereich geteilt. Quellentexte und Prüfvermerke bleiben im Versionsverlauf erhalten.",
    discard: "Ungespeicherte Änderungen verwerfen?",
    unavailable: "Für Arbeitsbereichsdossiers ist eine Anmeldung erforderlich.",
    historical:
      "Historische Version — zum Bearbeiten oder Prüfen die neueste laden.",
    noDossiers: "Keine Dossiers in dieser Ansicht.",
    integrity: "SHA-256 des gespeicherten Dokuments",
    deletedActor: "Gelöschtes Konto",
    author: "Bearbeiter",
    noSelection: "Eine Beziehung auswählen, um ihre Belege zu prüfen.",
    graphFull: "Keine freie Position im Graphen verfügbar.",
    statuses: {
      documented: "Dokumentiert",
      reported: "Berichtet",
      disputed: "Bestritten",
      not_established: "Nicht belegt",
    },
    entityKinds: {
      person: "Person",
      company: "Unternehmen",
      initiative: "Initiative",
      policy: "Regelwerk",
      group: "Gruppe / Summe",
    },
    sourceKinds: {
      primary_corporate: "Primärquelle des Unternehmens",
      primary_government: "Behördliche Primärquelle",
      primary_campaign: "Primärquelle der Kampagne",
      reporting: "Journalistischer Bericht",
    },
    relationKinds: {
      family: "Familie",
      role: "Funktion",
      campaign: "Kampagne",
      ownership: "Beteiligung",
      business: "Geschäftsbeziehung",
      policy_proposal: "Politischer Vorschlag",
      potential_impact: "Mögliche Wirkung",
      dividend: "Dividendenzahlung",
    },
  },
  "fr-CH": {
    title: "Influence Graph",
    intro: "Examiner les liens. Suivre les preuves.",
    prototype: "Espace de recherche",
    example: "Dossier public de référence",
    private: "Dossiers de cet espace",
    snapshot: "Preuves vérifiées",
    sourceLanguage: "Langue du dossier",
    limits: "Ce que cela ne démontre pas",
    graph: "Graphe",
    list: "Liste des preuves",
    perspective: "Afficher",
    entity: "Entité",
    allEntities: "Toutes les entités",
    all: "Tous les liens",
    documented: "Liens documentés",
    money: "Flux financiers confirmés",
    policy: "Liens politiques",
    graphHelp:
      "Choisir un lien numéroté pour examiner ses preuves. La liste complète contient les mêmes informations.",
    moneyHelp:
      "Seulement les paiements consignés avec preuve primaire, montant, devise et période. Participations et avantages possibles sont exclus.",
    empty:
      "Aucun lien dans cette vue. Une preuve manquante ne démontre pas l'absence de lien ou de paiement.",
    connections: "Liens",
    entities: "Entités",
    sources: "Sources",
    evidence: "Preuves",
    supporting: "Source à l'appui",
    disputing: "Réponse contradictoire",
    open: "Ouvrir la source",
    locator: "Page / section",
    summary: "Résumé de la preuve",
    quote: "Citation exacte (facultative)",
    sourceDate: "Publié",
    checked: "Vérifié",
    effective: "Situation au",
    undated: "Non daté",
    scope: "Portée et limites",
    noArchive: "Aucun extrait conservé. La page peut changer.",
    extract: "Extrait de source conservé",
    extractHelp:
      "Coller un extrait autorisé. Le texte est conservé ; la page n'est ni capturée ni vérifiée.",
    gaps: "Questions de preuve ouvertes",
    count: "visibles",
    clear: "Réinitialiser les filtres",
    selected: "Lien sélectionné",
    new: "Nouveau dossier",
    copy: "Copier dans cet espace",
    edit: "Modifier le dossier",
    save: "Enregistrer la version",
    cancel: "Annuler",
    remove: "Retirer",
    add: "Ajouter",
    details: "Dossier",
    relations: "Liens",
    name: "Nom / titre",
    kind: "Type",
    country: "Code pays (facultatif)",
    from: "De",
    to: "Vers",
    label: "Libellé du lien",
    statement: "Affirmation",
    status: "Statut de preuve",
    note: "Motif / note de vérification",
    url: "URL de la source",
    publisher: "Éditeur",
    language: "Code langue",
    source: "Source",
    date: "Date de vérification du dossier",
    amount: "Montant",
    currency: "Devise",
    periodStart: "Début de période",
    periodEnd: "Fin de période",
    paid: "Payé",
    proposed: "Proposé",
    basis: "Base du paiement",
    addEvidence: "Ajouter une preuve",
    addCounter: "Ajouter une réponse contradictoire",
    missing: "Preuves manquantes (une par ligne)",
    limitLines: "Limites (une par ligne)",
    required:
      "Compléter les champs obligatoires et les preuves avant d'enregistrer.",
    saved: "Version enregistrée.",
    loading: "Chargement…",
    failed:
      "La demande a échoué. Le brouillon est conservé. Vérifier l'accès et réessayer.",
    conflict:
      "Une version plus récente existe. Le brouillon est conservé ; copier les modifications avant de charger la dernière version.",
    readonly:
      "Les lecteurs consultent les dossiers. Un administrateur peut modifier et enregistrer les vérifications.",
    history: "Historique des versions",
    revision: "Version",
    latest: "Charger la dernière",
    older: "Versions antérieures",
    more: "Autres dossiers",
    refresh: "Actualiser",
    archive: "Archiver",
    restore: "Restaurer",
    active: "Actifs",
    archived: "Archivés",
    review: "Consigner une vérification",
    reviewed: "Vérifié",
    needs_revision: "À réviser",
    draft: "Non vérifié",
    reviewHelp:
      "Une décision éditoriale concerne uniquement cette version. Elle ne vérifie pas toutes les affirmations et ne change pas les statuts de preuve.",
    reasonHelp:
      "Décrire les changements ou la vérification (au moins 3 caractères).",
    export: "Télécharger le dossier JSON",
    workspaceHelp:
      "Partagé avec cet espace. Textes sources et notes restent dans l'historique des versions.",
    discard: "Abandonner les modifications non enregistrées ?",
    unavailable:
      "Une connexion est nécessaire pour les dossiers de cet espace.",
    historical:
      "Version historique — charger la dernière pour modifier ou vérifier.",
    noDossiers: "Aucun dossier dans cette vue.",
    integrity: "SHA-256 du document conservé",
    deletedActor: "Compte supprimé",
    author: "Auteur",
    noSelection: "Choisir un lien pour examiner ses preuves.",
    graphFull: "Aucune position disponible dans le graphe.",
    statuses: {
      documented: "Documenté",
      reported: "Rapporté",
      disputed: "Contesté",
      not_established: "Non établi",
    },
    entityKinds: {
      person: "Personne",
      company: "Entreprise",
      initiative: "Initiative",
      policy: "Politique",
      group: "Groupe / agrégat",
    },
    sourceKinds: {
      primary_corporate: "Source primaire d'entreprise",
      primary_government: "Source primaire officielle",
      primary_campaign: "Source primaire de campagne",
      reporting: "Enquête journalistique",
    },
    relationKinds: {
      family: "Famille",
      role: "Fonction",
      campaign: "Campagne",
      ownership: "Participation",
      business: "Relation commerciale",
      policy_proposal: "Proposition politique",
      potential_impact: "Effet possible",
      dividend: "Versement de dividende",
    },
  },
  "it-CH": {
    title: "Influence Graph",
    intro: "Esaminare i legami. Seguire le prove.",
    prototype: "Area di ricerca",
    example: "Dossier pubblico di riferimento",
    private: "Dossier dell'area di lavoro",
    snapshot: "Prove verificate",
    sourceLanguage: "Lingua del dossier",
    limits: "Cosa non dimostrano questi dati",
    graph: "Grafo",
    list: "Elenco delle prove",
    perspective: "Mostra",
    entity: "Entità",
    allEntities: "Tutte le entità",
    all: "Tutti i legami",
    documented: "Legami documentati",
    money: "Flussi finanziari confermati",
    policy: "Legami politici",
    graphHelp:
      "Selezionare un legame numerato per esaminarne le prove. L'elenco completo contiene le stesse informazioni.",
    moneyHelp:
      "Solo pagamenti registrati con prova primaria, importo, valuta e periodo. Partecipazioni e possibili benefici sono esclusi.",
    empty:
      "Nessun legame in questa vista. La mancanza di prove non dimostra l'assenza di un legame o pagamento.",
    connections: "Legami",
    entities: "Entità",
    sources: "Fonti",
    evidence: "Prove",
    supporting: "Fonte a sostegno",
    disputing: "Replica",
    open: "Apri fonte",
    locator: "Pagina / sezione",
    summary: "Sintesi della prova",
    quote: "Citazione esatta (facoltativa)",
    sourceDate: "Pubblicato",
    checked: "Verificato",
    effective: "Situazione al",
    undated: "Non datato",
    scope: "Portata e limiti",
    noArchive: "Nessun estratto conservato. La pagina può cambiare.",
    extract: "Estratto della fonte conservato",
    extractHelp:
      "Incollare un estratto consentito. Il testo viene conservato; la pagina non viene acquisita o verificata.",
    gaps: "Questioni probatorie aperte",
    count: "visibili",
    clear: "Azzera filtri",
    selected: "Legame selezionato",
    new: "Nuovo dossier",
    copy: "Copia nell'area di lavoro",
    edit: "Modifica dossier",
    save: "Salva versione",
    cancel: "Annulla",
    remove: "Rimuovi",
    add: "Aggiungi",
    details: "Dossier",
    relations: "Legami",
    name: "Nome / titolo",
    kind: "Tipo",
    country: "Codice paese (facoltativo)",
    from: "Da",
    to: "A",
    label: "Etichetta del legame",
    statement: "Affermazione",
    status: "Stato della prova",
    note: "Motivo / nota di verifica",
    url: "URL della fonte",
    publisher: "Editore",
    language: "Codice lingua",
    source: "Fonte",
    date: "Data di verifica del dossier",
    amount: "Importo",
    currency: "Valuta",
    periodStart: "Periodo dal",
    periodEnd: "Periodo al",
    paid: "Pagato",
    proposed: "Proposto",
    basis: "Base del pagamento",
    addEvidence: "Aggiungi prova a sostegno",
    addCounter: "Aggiungi replica",
    missing: "Prove mancanti (una per riga)",
    limitLines: "Limiti (uno per riga)",
    required: "Completare i campi obbligatori e le prove prima di salvare.",
    saved: "Versione salvata.",
    loading: "Caricamento…",
    failed:
      "Richiesta non riuscita. La bozza è conservata. Verificare l'accesso e riprovare.",
    conflict:
      "Esiste una versione più recente. La bozza è conservata; copiare le modifiche prima di caricare l'ultima versione.",
    readonly:
      "I lettori possono consultare i dossier. Un amministratore può modificare e registrare verifiche.",
    history: "Cronologia delle versioni",
    revision: "Versione",
    latest: "Carica ultima",
    older: "Versioni precedenti",
    more: "Altri dossier",
    refresh: "Aggiorna",
    archive: "Archivia",
    restore: "Ripristina",
    active: "Attivi",
    archived: "Archiviati",
    review: "Registra verifica",
    reviewed: "Verificato",
    needs_revision: "Da rivedere",
    draft: "Non verificato",
    reviewHelp:
      "Una decisione editoriale riguarda solo questa versione. Non verifica ogni affermazione e non modifica gli stati delle prove.",
    reasonHelp: "Descrivere le modifiche o la verifica (almeno 3 caratteri).",
    export: "Scarica dossier JSON",
    workspaceHelp:
      "Condiviso con quest'area di lavoro. Testi delle fonti e note restano nella cronologia.",
    discard: "Scartare le modifiche non salvate?",
    unavailable: "I dossier dell'area di lavoro richiedono l'accesso.",
    historical:
      "Versione storica — caricare l'ultima per modificare o verificare.",
    noDossiers: "Nessun dossier in questa vista.",
    integrity: "SHA-256 del documento conservato",
    deletedActor: "Account eliminato",
    author: "Autore",
    noSelection: "Selezionare un legame per esaminarne le prove.",
    graphFull: "Nessuna posizione disponibile nel grafo.",
    statuses: {
      documented: "Documentato",
      reported: "Riportato",
      disputed: "Contestato",
      not_established: "Non accertato",
    },
    entityKinds: {
      person: "Persona",
      company: "Azienda",
      initiative: "Iniziativa",
      policy: "Politica",
      group: "Gruppo / aggregato",
    },
    sourceKinds: {
      primary_corporate: "Fonte primaria aziendale",
      primary_government: "Fonte primaria ufficiale",
      primary_campaign: "Fonte primaria della campagna",
      reporting: "Inchiesta giornalistica",
    },
    relationKinds: {
      family: "Famiglia",
      role: "Ruolo",
      campaign: "Campagna",
      ownership: "Partecipazione",
      business: "Relazione commerciale",
      policy_proposal: "Proposta politica",
      potential_impact: "Possibile effetto",
      dividend: "Pagamento dividendi",
    },
  },
  "rm-CH": {
    title: "Influence Graph",
    intro: "Examinar las relaziuns. Suandar las cumprovas.",
    prototype: "Spazi da retschertga",
    example: "Dossier public da referenza",
    private: "Dossiers dal spazi da lavur",
    snapshot: "Cumprovas examinadas",
    sourceLanguage: "Lingua dal dossier",
    limits: "Tge che quai na cumprova betg",
    graph: "Graf",
    list: "Glista da cumprovas",
    perspective: "Mussar",
    entity: "Entitad",
    allEntities: "Tut las entitads",
    all: "Tut las relaziuns",
    documented: "Relaziuns documentadas",
    money: "Fluss da daners confermads",
    policy: "Relaziuns politicas",
    graphHelp:
      "Tscherner ina relaziun numerada per examinar las cumprovas. La glista cumpletta porscha las medemas infurmaziuns.",
    moneyHelp:
      "Mo pajaments registrads cun cumprova primara, import, valuta e perioda. Participaziuns e profits pussaivels èn exclus.",
    empty:
      "Naginas relaziuns en questa vista. Cumprovas mancantas na cumprovan betg l'absenza d'ina relaziun u d'in pajament.",
    connections: "Relaziuns",
    entities: "Entitads",
    sources: "Funtaunas",
    evidence: "Cumprovas",
    supporting: "Funtauna da sustegn",
    disputing: "Cuntradecleraziun",
    open: "Avrir la funtauna",
    locator: "Pagina / secziun",
    summary: "Resumaziun da la cumprova",
    quote: "Citat exact (facultativ)",
    sourceDate: "Publitgà",
    checked: "Examinà",
    effective: "Stadi dals",
    undated: "Senza data",
    scope: "Champ e cunfins",
    noArchive: "Nagin extract da funtauna conservà. La pagina po sa midar.",
    extract: "Extract da funtauna conservà",
    extractHelp:
      "Inserir in extract permess. Il text vegn conservà; la pagina na vegn betg registrada u verifitgada.",
    gaps: "Dumondas da cumprova avertas",
    count: "visiblas",
    clear: "Redefinir ils filters",
    selected: "Relaziun tschernida",
    new: "Nov dossier",
    copy: "Copiar en il spazi da lavur",
    edit: "Modifitgar il dossier",
    save: "Memorisar la versiun",
    cancel: "Interrumper",
    remove: "Allontanar",
    add: "Agiuntar",
    details: "Dossier",
    relations: "Relaziuns",
    name: "Num / titel",
    kind: "Tip",
    country: "Code dal pajais (facultativ)",
    from: "Da",
    to: "A",
    label: "Denominaziun da la relaziun",
    statement: "Affirmaziun",
    status: "Stadi da cumprova",
    note: "Motiv / nota d'examinaziun",
    url: "URL da la funtauna",
    publisher: "Editur",
    language: "Code da lingua",
    source: "Funtauna",
    date: "Data d'examinaziun dal dossier",
    amount: "Import",
    currency: "Valuta",
    periodStart: "Perioda da",
    periodEnd: "Perioda fin",
    paid: "Pajà",
    proposed: "Proponì",
    basis: "Basa dal pajament",
    addEvidence: "Agiuntar ina cumprova",
    addCounter: "Agiuntar ina cuntradecleraziun",
    missing: "Cumprovas mancantas (ina per lingia)",
    limitLines: "Cunfins (in per lingia)",
    required:
      "Cumplettar ils champs obligatorics e las cumprovas avant memorisar.",
    saved: "Versiun memorisada.",
    loading: "Chargiar…",
    failed:
      "La dumonda n'è betg reussida. Il sboz resta conservà. Examinar l'access ed empruvar danovamain.",
    conflict:
      "Ina versiun pli nova exista. Il sboz resta conservà; copiar las midadas avant chargiar la versiun actuala.",
    readonly:
      "Lecturs pon consultar ils dossiers. Administraturs pon modifitgar e registrar examinaziuns.",
    history: "Istorgia da las versiuns",
    revision: "Versiun",
    latest: "Chargiar l'actuala",
    older: "Versiuns pli veglias",
    more: "Ulteriurs dossiers",
    refresh: "Actualisar",
    archive: "Archivar",
    restore: "Restabilir",
    active: "Activs",
    archived: "Archivads",
    review: "Registrar l'examinaziun",
    reviewed: "Examinà",
    needs_revision: "Da reveder",
    draft: "Betg examinà",
    reviewHelp:
      "Ina decisiun redacziunala vala mo per questa versiun. Ella na verifitgescha betg mintga affirmaziun e na mida betg ils stadis da cumprova.",
    reasonHelp: "Descriver las midadas u l'examinaziun (almain 3 segns).",
    export: "Telechargiar il dossier JSON",
    workspaceHelp:
      "Cundividì cun quest spazi da lavur. Texts da funtaunas e notas restan en l'istorgia.",
    discard: "Rebittar las midadas betg memorisadas?",
    unavailable: "Ils dossiers dal spazi da lavur dovran in'annunzia.",
    historical:
      "Versiun istorica — chargiar l'actuala per modifitgar u examinar.",
    noDossiers: "Nagins dossiers en questa vista.",
    integrity: "SHA-256 dal document conservà",
    deletedActor: "Conto stizzà",
    author: "Autur",
    noSelection: "Tscherner ina relaziun per examinar las cumprovas.",
    graphFull: "Nagina posiziun libra en il graf.",
    statuses: {
      documented: "Documentà",
      reported: "Rapportà",
      disputed: "Contestà",
      not_established: "Betg cumprovà",
    },
    entityKinds: {
      person: "Persuna",
      company: "Interpresa",
      initiative: "Iniziativa",
      policy: "Politica",
      group: "Gruppa / aggregat",
    },
    sourceKinds: {
      primary_corporate: "Funtauna primara da l'interpresa",
      primary_government: "Funtauna primara uffiziala",
      primary_campaign: "Funtauna primara da la campagna",
      reporting: "Rapport schurnalistic",
    },
    relationKinds: {
      family: "Famiglia",
      role: "Rolla",
      campaign: "Campagna",
      ownership: "Participaziun",
      business: "Relaziun commerziala",
      policy_proposal: "Proposta politica",
      potential_impact: "Effect pussaivel",
      dividend: "Pajament da dividendas",
    },
  },
};
export type InfluenceCopy = typeof en;
