import type { Locale } from "./i18n";

export type BriefClaim = { text: string; evidence_ids: string[] };
export type SavedInterestBrief = {
  status: "not_scheduled" | "pending" | "available" | "failed" | "stale" | "runtime_unverified" | "not_current" | "unavailable";
  assessment_id: string | null; saved_at: string | null; locale: string; ai_calls: number;
  evidence_links?: Record<string, string>; interest_names?: Record<string, string>;
  result: null | {
    what_happened: BriefClaim; why_in_radar: Array<BriefClaim & { interest_id: string }>;
    importance: BriefClaim & { level: "high" | "medium" | "low" | "undetermined" };
    next_step: BriefClaim & { kind: "review" | "no_action_now" }; uncertainty: string;
    input_limitations: string[];
  };
};

type Copy = { title: string; help: string; refresh: string; saved: string; why: string; importance: string;
  next: string; limitations: string; source: string; level: Record<string, string>;
  status: Record<SavedInterestBrief["status"], string> };

export const interestBriefCopy: Record<Locale, Copy> = {
  "en-CH": { title: "Saved AI relevance brief", help: "One shared explanation for your organization. Opening this panel never generates a new answer.", refresh: "Check saved brief", saved: "Saved", why: "Why this is in your radar", importance: "Importance for your organization", next: "Suggested review", limitations: "Limits and uncertainty", source: "Evidence", level: {high:"High",medium:"Medium",low:"Low",undetermined:"Not assessed"}, status: {not_scheduled:"No brief has been saved in this language. Source monitoring remains available.",pending:"Analysis is queued or running. Check again later; this page does not start it.",available:"Saved brief matches the checked inputs and approved local model. Verify the evidence before acting.",failed:"Analysis failed or was cancelled. No new attempt was started by this view.",stale:"The saved brief does not match the current inputs. A new assessment is needed.",runtime_unverified:"The current approved local model could not be verified. A saved answer is not being presented as current.",not_current:"The monitoring interests or evidence could not be validated. No current AI conclusion is shown.",unavailable:"The saved result could not be validated. No unverified conclusion is displayed."}},
  "de-CH": { title: "Gespeicherte KI-Relevanzanalyse", help: "Eine gemeinsame Erklärung für Ihre Organisation. Das Öffnen erzeugt keine neue Antwort.", refresh: "Gespeicherte Analyse prüfen", saved: "Gespeichert", why: "Warum dies in Ihrem Radar erscheint", importance: "Bedeutung für Ihre Organisation", next: "Empfohlene Prüfung", limitations: "Grenzen und Unsicherheit", source: "Beleg", level:{high:"Hoch",medium:"Mittel",low:"Niedrig",undetermined:"Nicht bewertet"}, status:{not_scheduled:"In dieser Sprache wurde keine Analyse gespeichert. Die Quellenüberwachung bleibt verfügbar.",pending:"Die Analyse wartet oder läuft. Prüfen Sie später erneut; diese Seite startet sie nicht.",available:"Die gespeicherte Analyse entspricht den geprüften Eingaben und dem freigegebenen lokalen Modell. Prüfen Sie die Belege vor einer Handlung.",failed:"Die Analyse ist fehlgeschlagen oder wurde abgebrochen. Diese Ansicht startet keinen neuen Versuch.",stale:"Die gespeicherte Analyse entspricht nicht den aktuellen Eingaben. Eine neue Bewertung ist erforderlich.",runtime_unverified:"Das aktuell freigegebene lokale Modell konnte nicht verifiziert werden. Eine gespeicherte Antwort wird nicht als aktuell dargestellt.",not_current:"Überwachungsinteressen oder Belege konnten nicht validiert werden. Es wird keine aktuelle KI-Schlussfolgerung angezeigt.",unavailable:"Das gespeicherte Ergebnis konnte nicht validiert werden. Es wird keine ungeprüfte Schlussfolgerung angezeigt."}},
  "fr-CH": { title: "Analyse IA de pertinence enregistrée", help: "Une explication partagée par votre organisation. Ouvrir ce panneau ne génère jamais de nouvelle réponse.", refresh: "Vérifier l’analyse enregistrée", saved: "Enregistrée", why: "Pourquoi cela figure dans votre radar", importance: "Importance pour votre organisation", next: "Examen suggéré", limitations: "Limites et incertitudes", source: "Preuve", level:{high:"Élevée",medium:"Moyenne",low:"Faible",undetermined:"Non évaluée"}, status:{not_scheduled:"Aucune analyse enregistrée dans cette langue. La surveillance des sources reste disponible.",pending:"L’analyse est en attente ou en cours. Revenez plus tard ; cette page ne la lance pas.",available:"L’analyse enregistrée correspond aux données vérifiées et au modèle local approuvé. Vérifiez les preuves avant d’agir.",failed:"L’analyse a échoué ou a été annulée. Cette vue ne lance pas de nouvel essai.",stale:"L’analyse enregistrée ne correspond plus aux données actuelles. Une nouvelle évaluation est nécessaire.",runtime_unverified:"Le modèle local actuellement approuvé n’a pas pu être vérifié. Une réponse enregistrée n’est pas présentée comme actuelle.",not_current:"Les intérêts surveillés ou les preuves n’ont pas pu être validés. Aucune conclusion IA actuelle n’est affichée.",unavailable:"Le résultat enregistré n’a pas pu être validé. Aucune conclusion non vérifiée n’est affichée."}},
  "it-CH": { title: "Analisi IA di rilevanza salvata", help: "Una spiegazione condivisa per la vostra organizzazione. Aprire questo pannello non genera nuove risposte.", refresh: "Verifica l’analisi salvata", saved: "Salvata", why: "Perché compare nel vostro radar", importance: "Importanza per la vostra organizzazione", next: "Verifica suggerita", limitations: "Limiti e incertezze", source: "Prova", level:{high:"Alta",medium:"Media",low:"Bassa",undetermined:"Non valutata"}, status:{not_scheduled:"Nessuna analisi salvata in questa lingua. Il monitoraggio delle fonti resta disponibile.",pending:"L’analisi è in coda o in corso. Riprovate più tardi; questa pagina non la avvia.",available:"L’analisi salvata corrisponde ai dati verificati e al modello locale approvato. Verificate le prove prima di agire.",failed:"L’analisi è fallita o è stata annullata. Questa vista non avvia un nuovo tentativo.",stale:"L’analisi salvata non corrisponde ai dati attuali. Serve una nuova valutazione.",runtime_unverified:"Non è stato possibile verificare il modello locale attualmente approvato. Una risposta salvata non viene presentata come attuale.",not_current:"Non è stato possibile validare gli interessi monitorati o le prove. Non viene mostrata alcuna conclusione IA attuale.",unavailable:"Non è stato possibile validare il risultato salvato. Non viene mostrata alcuna conclusione non verificata."}},
  "rm-CH": { title: "Analisa IA da relevanza memorisada", help: "Ina decleraziun communabla per Vossa organisaziun. Avrir quest champ na generescha nagina nova resposta.", refresh: "Examinar l’analisa memorisada", saved: "Memorisada", why: "Pertge che quai cumpara en Voss radar", importance: "Impurtanza per Vossa organisaziun", next: "Examinaziun recumandada", limitations: "Limits ed intschertezza", source: "Cumprova", level:{high:"Auta",medium:"Mesauna",low:"Bassa",undetermined:"Betg valitada"}, status:{not_scheduled:"Naginas analisas memorisadas en questa lingua. La surveglianza da las funtaunas resta disponibla.",pending:"L’analisa spetga u vegn fatga. Examinai pli tard; questa pagina na la lantscha betg.",available:"L’analisa memorisada correspunda a las datas examinadas ed al model local approvà. Examinai las cumprovas avant d’agir.",failed:"L’analisa n’è betg reussida u è vegnida interrutta. Questa vista na lantscha nagina nova emprova.",stale:"L’analisa memorisada na correspunda betg a las datas actualas. Ina nova valitaziun è necessaria.",runtime_unverified:"Il model local actualmain approvà n’ha betg pudì vegnir verifitgà. Ina resposta memorisada na vegn betg preschentada sco actuala.",not_current:"Ils interess survegliads u las cumprovas n’han betg pudì vegnir validats. Nagina conclusiun IA actuala vegn mussada.",unavailable:"Il resultat memorisà n’ha betg pudì vegnir validà. Nagina conclusiun betg verifitgada vegn mussada."}},
};
