import type { Locale } from "./i18n";

const en = {
  shortTitle: "Profiles",
  activationRecord: "Choices saved at activation",
  readiness:
    "Saved operational status, not a live source check. Collection intervals are not delivery guarantees. The final activation step enables your selected source subscriptions; this preview does not.",
  title: "Monitoring profiles",
  new: "Set up monitoring",
  intro:
    "From your client's context to the developments that matter. Five clear steps, one saved monitoring profile.",
  steps: ["Context", "Topics", "Sources", "Delivery", "Activate"],
  descriptions: [
    "Who are you monitoring for?",
    "What should we pay attention to?",
    "Where should we look?",
    "How would you like to stay informed?",
    "Review your choices and start monitoring.",
  ],
  empty:
    "No monitoring profiles yet. Create a profile for a client or your organization.",
  unnamed: "Untitled profile",
  draft: "Private draft",
  active: "Activated",
  paused: "Paused",
  continue: "Continue setup",
  open: "Open profile",
  updated: "Last saved",
  back: "Back",
  next: "Continue",
  save: "Save draft",
  saved: "Draft saved",
  saving: "Saving…",
  all: "All profiles",
  step: "Step",
  client: "A client",
  organization: "My organization",
  name: "Client / profile name",
  sector: "Sector or activity",
  goal: "What changes matter to you?",
  goalHint:
    "Describe the business, decisions and subjects you want to follow. This context guides topic suggestions.",
  coverage: "Available coverage: Switzerland",
  coverageHint:
    "Only the selected catalogue sources are monitored. Coverage and collection health are shown below. Additional jurisdictions remain requests until a suitable source is connected.",
  extraJurisdictions: "Other jurisdictions to request (optional)",
  suggest: "Suggest topics with AI",
  suggesting: "Preparing suggestions…",
  suggestionError:
    "AI could not prepare usable topics. Please retry or add a topic manually.",
  manual: "Add a topic",
  feedback: "Refine the suggestions (optional)",
  suggestions: "Proposed topics",
  apply: "Use these topics",
  replaceHint:
    "Using these suggestions replaces the current topic cards. Review and edit them before activation.",
  topicName: "Topic name",
  description: "What to follow",
  keywords: "Keywords and synonyms (comma separated)",
  references: "Reference notes (optional)",
  referencesHint:
    "Notes are unverified and are not legal evidence. Only linked source documents support a legal conclusion.",
  remove: "Remove",
  selected: "Monitor this topic",
  topicsHint:
    "Choose up to six topics. AI is optional; you can write every topic yourself. Keywords match saved source text, so include useful source-language synonyms.",
  sourcesHint:
    "Choose at least one available source pack. Activation reuses saved documents and starts the existing matching workflow. It does not grant access to additional publishers.",
  gaps: "Coverage and known gaps",
  currentState: "Current subscription",
  custom: "Request an additional source",
  sourceName: "Publisher / source name",
  sourceUrl: "Public HTTPS URL",
  sourceKind: "Source role",
  binding: "Binding law / decisions",
  pending: "Pending legislation",
  signals: "Commentary / signals",
  addSource: "Save source request",
  requested: "Requested · collection inactive",
  requestsHint:
    "Requests stay with this profile. They need a separately configured and approved source before collection can begin.",
  inApp: "In-app monitoring",
  inAppHint:
    "Saved matches appear in Topics and Today. Source collection and matching can take time.",
  keep: "Keep my current email settings",
  daily: "Daily digest",
  weekly: "Weekly digest",
  off: "Turn off my organization digest",
  deliveryHint:
    "This is your personal digest for the whole current organization, including other interests. It is not a separate mailing list for this profile. Existing filters and schedule are retained; colleagues' settings stay personal.",
  consent: "Apply this change to my personal organization digest",
  emailUnavailable:
    "Daily and weekly email require a verified address and configured email delivery. You can activate in-app monitoring now.",
  currentDelivery: "Current email delivery",
  enabled: "Enabled",
  disabled: "Off",
  manageDelivery: "Manage digest and filters",
  preview: "Preview saved matches",
  previewHint:
    "A bounded preview of saved events, not a sample alert or proof of complete coverage. Matches are candidates for review, not confirmed legal impact.",
  noMatches:
    "No saved matching events in this preview. Monitoring can still be activated. Missing data does not mean there are no developments.",
  evidence: "Open source evidence",
  scanned: "Saved events scanned",
  candidates: "Candidates",
  previewTime: "Preview captured",
  review: "Review profile",
  edit: "Edit",
  activate: "Activate monitoring",
  activating: "Activating…",
  reviewHint:
    "Activation shares this profile with your organization and creates the selected monitoring topics. Custom source requests remain inactive.",
  success: "Monitoring profile activated",
  successHint:
    "Your topics and source subscriptions are saved. The existing collection and matching jobs will populate results as evidence becomes available.",
  topicsLink: "Open topics and review history",
  today: "Open Today",
  pause: "Pause all profile topics",
  resume: "Resume profile topics",
  pauseHint:
    "Pause stops this profile's topics. Shared source subscriptions and your personal digest retain their settings. Archived topics are not resumed.",
  export: "Export profile",
  viewer:
    "An organization administrator can create and activate profiles. You can inspect shared profiles here.",
  required: "Complete the required fields before continuing.",
  pickTopics:
    "Select at least one topic and fill in its name, description and keywords.",
  pickSources: "Select at least one available source pack.",
  invalidSource:
    "Enter a source name and public HTTPS URL without credentials.",
  unsaved: "Changes are not saved yet. Continue or Save draft to keep them.",
  leave: "Leave without saving these changes?",
  selectedTopics: "Selected topics",
  sourceCount: "Selected source packs",
  jurisdiction: "Monitored jurisdiction",
  loading: "Loading profile…",
  limit: "Up to six topics per profile.",
  aiNotice:
    "Your context and feedback are sent to the organization's configured AI provider when you request suggestions.",
  nextPage: "Next profiles",
  previousPage: "Previous profiles",
};
type Copy = {
  [K in keyof typeof en]: (typeof en)[K] extends string[] ? string[] : string;
};
export const legalProfilesCopy: Record<Locale, Copy> = {
  "en-CH": en,
  "de-CH": {
    shortTitle: "Profile",
    activationRecord: "Bei der Aktivierung gespeicherte Auswahl",
    readiness:
      "Gespeicherter Betriebszustand, keine Live-Prüfung. Erfassungsintervalle sind keine Zustellgarantie. Erst die abschliessende Aktivierung schaltet gewählte Quellenabonnements ein, nicht diese Vorschau.",
    title: "Monitoring-Profile",
    new: "Monitoring einrichten",
    intro:
      "Vom Kontext Ihrer Kundschaft zu relevanten Entwicklungen. Fünf klare Schritte, ein gespeichertes Monitoring-Profil.",
    steps: ["Kontext", "Themen", "Quellen", "Zustellung", "Aktivieren"],
    descriptions: [
      "Für wen beobachten Sie?",
      "Worauf sollen wir achten?",
      "Wo sollen wir suchen?",
      "Wie möchten Sie informiert werden?",
      "Prüfen Sie Ihre Auswahl und starten Sie.",
    ],
    empty:
      "Noch keine Profile. Erstellen Sie eines für Ihre Kundschaft oder Organisation.",
    unnamed: "Unbenanntes Profil",
    draft: "Privater Entwurf",
    active: "Aktiviert",
    paused: "Pausiert",
    continue: "Einrichtung fortsetzen",
    open: "Profil öffnen",
    updated: "Zuletzt gespeichert",
    back: "Zurück",
    next: "Weiter",
    save: "Entwurf speichern",
    saved: "Entwurf gespeichert",
    saving: "Wird gespeichert…",
    all: "Alle Profile",
    step: "Schritt",
    client: "Eine Kundin / ein Kunde",
    organization: "Meine Organisation",
    name: "Kunden- / Profilname",
    sector: "Branche oder Tätigkeit",
    goal: "Welche Änderungen sind relevant?",
    goalHint:
      "Beschreiben Sie Tätigkeit, Entscheidungen und Themen. Dieser Kontext steuert die Themenvorschläge.",
    coverage: "Verfügbare Abdeckung: Schweiz",
    coverageHint:
      "Nur gewählte Katalogquellen werden beobachtet. Abdeckung und Zustand sind unten sichtbar. Weitere Rechtsräume bleiben Anfragen, bis passende Quellen angeschlossen sind.",
    extraJurisdictions: "Weitere gewünschte Rechtsräume (optional)",
    suggest: "Themen mit KI vorschlagen",
    suggesting: "Vorschläge werden erstellt…",
    suggestionError:
      "Die KI konnte keine brauchbaren Themen erstellen. Versuchen Sie es erneut oder fügen Sie ein Thema manuell hinzu.",
    manual: "Thema hinzufügen",
    feedback: "Vorschläge verfeinern (optional)",
    suggestions: "Vorgeschlagene Themen",
    apply: "Diese Themen übernehmen",
    replaceHint:
      "Die Übernahme ersetzt die aktuellen Themenkarten. Prüfen und bearbeiten Sie diese vor der Aktivierung.",
    topicName: "Themenname",
    description: "Was beobachten?",
    keywords: "Suchbegriffe und Synonyme (kommagetrennt)",
    references: "Referenznotizen (optional)",
    referencesHint:
      "Notizen sind ungeprüft und kein Rechtsnachweis. Rechtliche Schlussfolgerungen benötigen verlinkte Quelldokumente.",
    remove: "Entfernen",
    selected: "Dieses Thema beobachten",
    topicsHint:
      "Wählen Sie bis zu sechs Themen. KI ist optional. Suchbegriffe werden mit gespeichertem Quelltext abgeglichen; ergänzen Sie Synonyme in den Quellsprachen.",
    sourcesHint:
      "Wählen Sie mindestens ein verfügbares Quellenpaket. Die Aktivierung nutzt gespeicherte Dokumente und die bestehende Zuordnung. Sie gewährt keinen Zugang zu weiteren Herausgebern.",
    gaps: "Abdeckung und bekannte Lücken",
    currentState: "Aktuelles Abonnement",
    custom: "Weitere Quelle anfragen",
    sourceName: "Herausgeber / Quellenname",
    sourceUrl: "Öffentliche HTTPS-URL",
    sourceKind: "Rolle der Quelle",
    binding: "Geltendes Recht / Entscheide",
    pending: "Laufende Gesetzgebung",
    signals: "Kommentare / Signale",
    addSource: "Quellenanfrage speichern",
    requested: "Angefragt · Erfassung inaktiv",
    requestsHint:
      "Anfragen bleiben im Profil. Die Erfassung benötigt eine separat konfigurierte und freigegebene Quelle.",
    inApp: "Monitoring in der App",
    inAppHint:
      "Gespeicherte Treffer erscheinen unter Themen und Heute. Erfassung und Zuordnung können dauern.",
    keep: "Aktuelle E-Mail-Einstellungen behalten",
    daily: "Täglicher Digest",
    weekly: "Wöchentlicher Digest",
    off: "Meinen Organisations-Digest ausschalten",
    deliveryHint:
      "Dies ist Ihr persönlicher Digest für die gesamte aktuelle Organisation, einschliesslich anderer Interessen. Es ist keine eigene Versandliste dieses Profils. Filter und Zeitplan bleiben erhalten; die Einstellungen Ihrer Kollegen bleiben persönlich.",
    consent:
      "Diese Änderung auf meinen persönlichen Organisations-Digest anwenden",
    emailUnavailable:
      "Tägliche und wöchentliche E-Mails benötigen eine bestätigte Adresse und konfigurierte Zustellung. Monitoring in der App ist jetzt möglich.",
    currentDelivery: "Aktuelle E-Mail-Zustellung",
    enabled: "Aktiv",
    disabled: "Aus",
    manageDelivery: "Digest und Filter verwalten",
    preview: "Gespeicherte Treffer ansehen",
    previewHint:
      "Begrenzte Vorschau gespeicherter Ereignisse, keine Beispielmeldung oder vollständige Abdeckung. Treffer sind Prüfkandidaten, keine bestätigten Rechtsfolgen.",
    noMatches:
      "Keine gespeicherten Treffer in dieser Vorschau. Monitoring kann trotzdem aktiviert werden. Fehlende Daten bedeuten nicht, dass keine Entwicklungen vorliegen.",
    evidence: "Quellennachweis öffnen",
    scanned: "Geprüfte gespeicherte Ereignisse",
    candidates: "Kandidaten",
    previewTime: "Vorschau erstellt",
    review: "Profil prüfen",
    edit: "Bearbeiten",
    activate: "Monitoring aktivieren",
    activating: "Wird aktiviert…",
    reviewHint:
      "Die Aktivierung teilt das Profil mit Ihrer Organisation und erstellt die gewählten Themen. Zusätzliche Quellenanfragen bleiben inaktiv.",
    success: "Monitoring-Profil aktiviert",
    successHint:
      "Themen und Quellenabonnements sind gespeichert. Bestehende Erfassungs- und Zuordnungsaufträge liefern Ergebnisse, sobald Nachweise vorliegen.",
    topicsLink: "Themen und Prüfverlauf öffnen",
    today: "Heute öffnen",
    pause: "Alle Profilthemen pausieren",
    resume: "Profilthemen fortsetzen",
    pauseHint:
      "Die Pause stoppt die Themen dieses Profils. Gemeinsame Quellenabonnements und Ihr Digest behalten ihre Einstellungen. Archivierte Themen werden nicht fortgesetzt.",
    export: "Profil exportieren",
    viewer:
      "Organisationsadministratoren können Profile erstellen und aktivieren. Sie können hier geteilte Profile einsehen.",
    required: "Füllen Sie die Pflichtfelder aus.",
    pickTopics:
      "Wählen Sie ein Thema und ergänzen Sie Name, Beschreibung und Suchbegriffe.",
    pickSources: "Wählen Sie mindestens ein verfügbares Quellenpaket.",
    invalidSource:
      "Geben Sie einen Namen und eine öffentliche HTTPS-URL ohne Zugangsdaten ein.",
    unsaved:
      "Änderungen noch nicht gespeichert. Weiter oder Entwurf speichern wählen.",
    leave: "Ohne Speichern verlassen?",
    selectedTopics: "Gewählte Themen",
    sourceCount: "Gewählte Quellenpakete",
    jurisdiction: "Beobachteter Rechtsraum",
    loading: "Profil wird geladen…",
    limit: "Bis zu sechs Themen pro Profil.",
    aiNotice:
      "Bei einer Anfrage werden Kontext und Rückmeldung an den konfigurierten KI-Anbieter Ihrer Organisation gesendet.",
    nextPage: "Nächste Profile",
    previousPage: "Vorherige Profile",
  },
  "fr-CH": {
    shortTitle: "Profils",
    activationRecord: "Choix enregistrés lors de l’activation",
    readiness:
      "État opérationnel enregistré, sans vérification en direct. Les intervalles ne garantissent pas la diffusion. Seule l’étape finale active les abonnements sélectionnés, pas cet aperçu.",
    title: "Profils de veille",
    new: "Configurer une veille",
    intro:
      "Du contexte de votre client aux évolutions pertinentes. Cinq étapes claires, un profil enregistré.",
    steps: ["Contexte", "Thèmes", "Sources", "Diffusion", "Activer"],
    descriptions: [
      "Pour qui effectuez-vous la veille ?",
      "Quels sujets faut-il suivre ?",
      "Où chercher ?",
      "Comment souhaitez-vous être informé ?",
      "Vérifiez vos choix et démarrez la veille.",
    ],
    empty: "Aucun profil. Créez-en un pour un client ou votre organisation.",
    unnamed: "Profil sans titre",
    draft: "Brouillon privé",
    active: "Activé",
    paused: "En pause",
    continue: "Reprendre la configuration",
    open: "Ouvrir le profil",
    updated: "Dernier enregistrement",
    back: "Retour",
    next: "Continuer",
    save: "Enregistrer le brouillon",
    saved: "Brouillon enregistré",
    saving: "Enregistrement…",
    all: "Tous les profils",
    step: "Étape",
    client: "Un client",
    organization: "Mon organisation",
    name: "Nom du client / profil",
    sector: "Secteur ou activité",
    goal: "Quelles évolutions vous concernent ?",
    goalHint:
      "Décrivez l'activité, les décisions et les sujets à suivre. Ce contexte guide les propositions.",
    coverage: "Couverture disponible : Suisse",
    coverageHint:
      "Seules les sources sélectionnées sont suivies. La couverture et l'état de collecte figurent ci-dessous. Les autres juridictions restent des demandes jusqu'au raccordement d'une source adaptée.",
    extraJurisdictions: "Autres juridictions souhaitées (facultatif)",
    suggest: "Proposer des thèmes avec l'IA",
    suggesting: "Préparation des propositions…",
    suggestionError:
      "L’IA n’a pas pu préparer de sujets utilisables. Réessayez ou ajoutez un sujet manuellement.",
    manual: "Ajouter un thème",
    feedback: "Affiner les propositions (facultatif)",
    suggestions: "Thèmes proposés",
    apply: "Utiliser ces thèmes",
    replaceHint:
      "Cette action remplace les fiches actuelles. Vérifiez et modifiez les thèmes avant l'activation.",
    topicName: "Nom du thème",
    description: "Éléments à suivre",
    keywords: "Mots-clés et synonymes (séparés par des virgules)",
    references: "Notes de référence (facultatif)",
    referencesHint:
      "Les notes ne sont pas vérifiées et ne constituent pas des preuves juridiques. Toute conclusion doit s'appuyer sur les documents sources liés.",
    remove: "Retirer",
    selected: "Suivre ce thème",
    topicsHint:
      "Choisissez jusqu'à six thèmes. L'IA est facultative. Les mots-clés sont recherchés dans les textes enregistrés ; ajoutez des synonymes dans les langues des sources.",
    sourcesHint:
      "Sélectionnez au moins un ensemble de sources disponible. L'activation réutilise les documents enregistrés et lance le rapprochement existant. Elle n'ouvre aucun accès à d'autres éditeurs.",
    gaps: "Couverture et lacunes connues",
    currentState: "Abonnement actuel",
    custom: "Demander une source supplémentaire",
    sourceName: "Éditeur / nom de source",
    sourceUrl: "URL HTTPS publique",
    sourceKind: "Rôle de la source",
    binding: "Droit en vigueur / décisions",
    pending: "Projets législatifs",
    signals: "Commentaires / signaux",
    addSource: "Enregistrer la demande",
    requested: "Demandée · collecte inactive",
    requestsHint:
      "Les demandes restent dans le profil. La collecte nécessite une source configurée et approuvée séparément.",
    inApp: "Veille dans l'application",
    inAppHint:
      "Les résultats enregistrés apparaissent dans Thèmes et Aujourd'hui. La collecte et le rapprochement peuvent prendre du temps.",
    keep: "Conserver mes réglages email",
    daily: "Synthèse quotidienne",
    weekly: "Synthèse hebdomadaire",
    off: "Désactiver ma synthèse de l'organisation",
    deliveryHint:
      "Il s'agit de votre synthèse personnelle pour toute l'organisation actuelle, y compris vos autres intérêts. Ce profil n'a pas de liste de diffusion distincte. Filtres et horaire sont conservés ; les collègues gardent leurs propres réglages.",
    consent:
      "Appliquer ce changement à ma synthèse personnelle de l'organisation",
    emailUnavailable:
      "Les emails quotidiens et hebdomadaires nécessitent une adresse vérifiée et une diffusion configurée. La veille dans l'application peut être activée maintenant.",
    currentDelivery: "Diffusion email actuelle",
    enabled: "Activée",
    disabled: "Désactivée",
    manageDelivery: "Gérer la synthèse et les filtres",
    preview: "Aperçu des résultats enregistrés",
    previewHint:
      "Aperçu limité des événements enregistrés, pas une alerte fictive ni une couverture complète. Les résultats sont à examiner, sans impact juridique confirmé.",
    noMatches:
      "Aucun résultat enregistré dans cet aperçu. La veille peut être activée. L'absence de données ne signifie pas l'absence d'évolutions.",
    evidence: "Ouvrir la source",
    scanned: "Événements enregistrés examinés",
    candidates: "Résultats possibles",
    previewTime: "Aperçu établi",
    review: "Vérifier le profil",
    edit: "Modifier",
    activate: "Activer la veille",
    activating: "Activation…",
    reviewHint:
      "L'activation partage ce profil avec l'organisation et crée les thèmes sélectionnés. Les demandes de sources supplémentaires restent inactives.",
    success: "Profil de veille activé",
    successHint:
      "Les thèmes et abonnements sont enregistrés. Les tâches existantes de collecte et de rapprochement fourniront les résultats dès que des preuves seront disponibles.",
    topicsLink: "Ouvrir les thèmes et l'historique",
    today: "Ouvrir Aujourd'hui",
    pause: "Suspendre tous les thèmes du profil",
    resume: "Reprendre les thèmes du profil",
    pauseHint:
      "La pause arrête les thèmes du profil. Les abonnements partagés et votre synthèse conservent leurs réglages. Les thèmes archivés ne reprennent pas.",
    export: "Exporter le profil",
    viewer:
      "Un administrateur peut créer et activer des profils. Vous pouvez consulter les profils partagés.",
    required: "Renseignez les champs obligatoires.",
    pickTopics:
      "Sélectionnez un thème avec un nom, une description et des mots-clés.",
    pickSources: "Sélectionnez au moins un ensemble de sources disponible.",
    invalidSource:
      "Indiquez un nom et une URL HTTPS publique sans identifiants.",
    unsaved:
      "Modifications non enregistrées. Continuez ou enregistrez le brouillon.",
    leave: "Quitter sans enregistrer ?",
    selectedTopics: "Thèmes sélectionnés",
    sourceCount: "Ensembles de sources sélectionnés",
    jurisdiction: "Juridiction suivie",
    loading: "Chargement du profil…",
    limit: "Six thèmes maximum par profil.",
    aiNotice:
      "Le contexte et vos précisions sont envoyés au fournisseur d'IA configuré de l'organisation lorsque vous demandez des propositions.",
    nextPage: "Profils suivants",
    previousPage: "Profils précédents",
  },
  "it-CH": {
    shortTitle: "Profili",
    activationRecord: "Scelte salvate all’attivazione",
    readiness:
      "Stato operativo salvato, non una verifica in diretta. Gli intervalli non garantiscono l’invio. Solo il passo finale attiva gli abbonamenti scelti, non questa anteprima.",
    title: "Profili di monitoraggio",
    new: "Configura il monitoraggio",
    intro:
      "Dal contesto del cliente agli sviluppi rilevanti. Cinque semplici passi, un profilo salvato.",
    steps: ["Contesto", "Temi", "Fonti", "Invio", "Attiva"],
    descriptions: [
      "Per chi svolgi il monitoraggio?",
      "Quali temi dobbiamo seguire?",
      "Dove cercare?",
      "Come desideri essere informato?",
      "Verifica le scelte e avvia il monitoraggio.",
    ],
    empty:
      "Nessun profilo. Creane uno per un cliente o per la tua organizzazione.",
    unnamed: "Profilo senza titolo",
    draft: "Bozza privata",
    active: "Attivato",
    paused: "In pausa",
    continue: "Riprendi la configurazione",
    open: "Apri profilo",
    updated: "Ultimo salvataggio",
    back: "Indietro",
    next: "Continua",
    save: "Salva bozza",
    saved: "Bozza salvata",
    saving: "Salvataggio…",
    all: "Tutti i profili",
    step: "Passo",
    client: "Un cliente",
    organization: "La mia organizzazione",
    name: "Nome del cliente / profilo",
    sector: "Settore o attività",
    goal: "Quali cambiamenti ti interessano?",
    goalHint:
      "Descrivi attività, decisioni e temi da seguire. Il contesto guida i suggerimenti.",
    coverage: "Copertura disponibile: Svizzera",
    coverageHint:
      "Sono monitorate solo le fonti selezionate. Copertura e stato della raccolta sono visibili sotto. Altre giurisdizioni restano richieste fino al collegamento di fonti adatte.",
    extraJurisdictions: "Altre giurisdizioni richieste (facoltativo)",
    suggest: "Suggerisci temi con l'IA",
    suggesting: "Preparazione dei suggerimenti…",
    suggestionError:
      "L’IA non è riuscita a preparare argomenti utilizzabili. Riprova o aggiungi un argomento manualmente.",
    manual: "Aggiungi tema",
    feedback: "Affina i suggerimenti (facoltativo)",
    suggestions: "Temi proposti",
    apply: "Usa questi temi",
    replaceHint:
      "L'adozione sostituisce le schede attuali. Verifica e modifica i temi prima dell'attivazione.",
    topicName: "Nome del tema",
    description: "Cosa seguire",
    keywords: "Parole chiave e sinonimi (separati da virgole)",
    references: "Note sui riferimenti (facoltativo)",
    referencesHint:
      "Le note non sono verificate e non costituiscono prove giuridiche. Le conclusioni richiedono documenti di fonte collegati.",
    remove: "Rimuovi",
    selected: "Monitora questo tema",
    topicsHint:
      "Scegli fino a sei temi. L'IA è facoltativa. Le parole chiave vengono cercate nel testo salvato; aggiungi sinonimi nelle lingue delle fonti.",
    sourcesHint:
      "Scegli almeno un pacchetto di fonti disponibile. L'attivazione riutilizza documenti salvati e avvia il processo di abbinamento esistente. Non concede accesso ad altri editori.",
    gaps: "Copertura e lacune note",
    currentState: "Abbonamento attuale",
    custom: "Richiedi un'altra fonte",
    sourceName: "Editore / nome della fonte",
    sourceUrl: "URL HTTPS pubblico",
    sourceKind: "Ruolo della fonte",
    binding: "Diritto vigente / decisioni",
    pending: "Progetti legislativi",
    signals: "Commenti / segnali",
    addSource: "Salva richiesta di fonte",
    requested: "Richiesta · raccolta inattiva",
    requestsHint:
      "Le richieste restano nel profilo. La raccolta richiede una fonte configurata e approvata separatamente.",
    inApp: "Monitoraggio nell'app",
    inAppHint:
      "I risultati salvati compaiono in Temi e Oggi. Raccolta e abbinamento possono richiedere tempo.",
    keep: "Mantieni le mie impostazioni email",
    daily: "Riepilogo giornaliero",
    weekly: "Riepilogo settimanale",
    off: "Disattiva il mio riepilogo dell'organizzazione",
    deliveryHint:
      "È il tuo riepilogo personale per tutta l'organizzazione attuale, inclusi gli altri interessi. Non è una lista di invio separata per questo profilo. Filtri e orario sono conservati; i colleghi mantengono le proprie impostazioni.",
    consent:
      "Applica questa modifica al mio riepilogo personale dell'organizzazione",
    emailUnavailable:
      "Le email giornaliere e settimanali richiedono un indirizzo verificato e l'invio configurato. Puoi attivare subito il monitoraggio nell'app.",
    currentDelivery: "Invio email attuale",
    enabled: "Attivo",
    disabled: "Disattivato",
    manageDelivery: "Gestisci riepilogo e filtri",
    preview: "Anteprima dei risultati salvati",
    previewHint:
      "Anteprima limitata di eventi salvati, non un avviso fittizio né una copertura completa. I risultati richiedono verifica e non confermano un impatto giuridico.",
    noMatches:
      "Nessun risultato salvato in questa anteprima. Il monitoraggio può essere attivato. L'assenza di dati non indica l'assenza di sviluppi.",
    evidence: "Apri la fonte",
    scanned: "Eventi salvati esaminati",
    candidates: "Candidati",
    previewTime: "Anteprima acquisita",
    review: "Verifica il profilo",
    edit: "Modifica",
    activate: "Attiva monitoraggio",
    activating: "Attivazione…",
    reviewHint:
      "L'attivazione condivide il profilo con l'organizzazione e crea i temi scelti. Le richieste di fonti aggiuntive restano inattive.",
    success: "Profilo di monitoraggio attivato",
    successHint:
      "Temi e abbonamenti sono salvati. I processi di raccolta e abbinamento forniranno risultati quando saranno disponibili le prove.",
    topicsLink: "Apri temi e cronologia",
    today: "Apri Oggi",
    pause: "Sospendi tutti i temi del profilo",
    resume: "Riprendi i temi del profilo",
    pauseHint:
      "La pausa ferma i temi del profilo. Fonti condivise e riepilogo personale mantengono le impostazioni. I temi archiviati non riprendono.",
    export: "Esporta profilo",
    viewer:
      "Un amministratore può creare e attivare profili. Puoi consultare i profili condivisi.",
    required: "Compila i campi obbligatori.",
    pickTopics:
      "Seleziona un tema e inserisci nome, descrizione e parole chiave.",
    pickSources: "Seleziona almeno un pacchetto di fonti disponibile.",
    invalidSource:
      "Inserisci un nome e un URL HTTPS pubblico senza credenziali.",
    unsaved: "Modifiche non ancora salvate. Continua o salva la bozza.",
    leave: "Uscire senza salvare?",
    selectedTopics: "Temi selezionati",
    sourceCount: "Pacchetti di fonti selezionati",
    jurisdiction: "Giurisdizione monitorata",
    loading: "Caricamento profilo…",
    limit: "Massimo sei temi per profilo.",
    aiNotice:
      "Contesto e indicazioni vengono inviati al fornitore IA configurato dell'organizzazione quando richiedi suggerimenti.",
    nextPage: "Profili successivi",
    previousPage: "Profili precedenti",
  },
  "rm-CH": {
    shortTitle: "Profils",
    activationRecord: "Selecziun memorisada tar l’activaziun",
    readiness:
      "Stadi operativ memorisà, nagina controlla directa. Intervals na garanteschan nagina spediziun. Mo il davos pass activescha ils abunaments tschernids, betg questa prevista.",
    title: "Profils da surveglianza",
    new: "Endrizzar la surveglianza",
    intro:
      "Dal context da la clientella als svilups relevants. Tschintg pass clers, in profil memorisà.",
    steps: ["Context", "Temas", "Funtaunas", "Spediziun", "Activar"],
    descriptions: [
      "Per tgi surveglias Vus?",
      "Tge temas duain nus seguir?",
      "Nua duain nus tschertgar?",
      "Co vulais Vus vegnir infurmà?",
      "Controllai la selecziun ed activai la surveglianza.",
    ],
    empty: "Anc nagins profils. Creai in per in client u Vossa organisaziun.",
    unnamed: "Profil senza titel",
    draft: "Sboz privat",
    active: "Activà",
    paused: "En pausa",
    continue: "Cuntinuar l'endrizzament",
    open: "Avrir il profil",
    updated: "Memorisà il davos",
    back: "Enavos",
    next: "Cuntinuar",
    save: "Memorisar il sboz",
    saved: "Sboz memorisà",
    saving: "Memorisaziun…",
    all: "Tut ils profils",
    step: "Pass",
    client: "In client",
    organization: "Mia organisaziun",
    name: "Num dal client / profil",
    sector: "Sectur u activitad",
    goal: "Tge midadas èn relevantas?",
    goalHint:
      "Descrivai l'activitad, las decisiuns ed ils temas. Quest context gida las propostas.",
    coverage: "Cuverta disponibla: Svizra",
    coverageHint:
      "Mo las funtaunas tschernidas vegnan survegliadas. La cuverta ed il stadi èn inditgads sutvart. Autras giurisdicziuns restan dumondas fin ch'ina funtauna adattada è colliada.",
    extraJurisdictions: "Autras giurisdicziuns giavischadas (facultativ)",
    suggest: "Proponer temas cun IA",
    suggesting: "Preparar propostas…",
    suggestionError:
      "L’IA n’ha betg pudì preparar temas utilisabels. Emprova anc ina giada u agiunta in tema manualmain.",
    manual: "Agiuntar in tema",
    feedback: "Precisar las propostas (facultativ)",
    suggestions: "Temas proponids",
    apply: "Surpigliar quests temas",
    replaceHint:
      "Questa acziun remplazza las cartas actualas. Controllai e modifitgai ils temas avant l'activaziun.",
    topicName: "Num dal tema",
    description: "Tge seguir",
    keywords: "Chavazzins e sinonims (separads cun commas)",
    references: "Notizias da referenza (facultativ)",
    referencesHint:
      "Las notizias n'èn betg verifitgadas e n'èn naginas cumprovas giuridicas. Conclusiuns dovran documents da funtauna colliads.",
    remove: "Allontanar",
    selected: "Survegliar quest tema",
    topicsHint:
      "Tscherni fin sis temas. L'IA è facultativa. Ils chavazzins vegnan tschertgads en il text memorisà; agiuntai sinonims en las linguas da las funtaunas.",
    sourcesHint:
      "Tscherni almain in pachet da funtaunas disponibel. L'activaziun utilisescha documents memorisads e l'attribuziun existenta. Ella na dat nagin access ad auters editurs.",
    gaps: "Cuverta e largias enconuschentas",
    currentState: "Abunament actual",
    custom: "Dumandar in'ulteriura funtauna",
    sourceName: "Editur / num da la funtauna",
    sourceUrl: "URL HTTPS public",
    sourceKind: "Rolla da la funtauna",
    binding: "Dretg valaivel / decisiuns",
    pending: "Projects legislativs",
    signals: "Commentaris / signals",
    addSource: "Memorisar la dumonda",
    requested: "Dumandà · rimnada inactiva",
    requestsHint:
      "Las dumondas restan en il profil. La rimnada dovra ina funtauna configurada ed approvada separadamain.",
    inApp: "Surveglianza en l'app",
    inAppHint:
      "Resultats memorisads cumparan sut Temas ed Oz. La rimnada e l'attribuziun pon durar.",
    keep: "Mantegnair mes parameters dad email",
    daily: "Resumaziun quotidiana",
    weekly: "Resumaziun emnila",
    off: "Deactivar mia resumaziun da l'organisaziun",
    deliveryHint:
      "Quai è Vossa resumaziun persunala per l'entira organisaziun actuala, inclus auters interess. Quest profil n'ha nagina glista da spediziun separada. Filters ed urari restan; ils collegas mantegnan lur agens parameters.",
    consent:
      "Applitgar questa midada a mia resumaziun persunala da l'organisaziun",
    emailUnavailable:
      "Emails quotidians ed emnils dovran in'adressa verifitgada ed ina spediziun configurada. La surveglianza en l'app po vegnir activada ussa.",
    currentDelivery: "Spediziun dad email actuala",
    enabled: "Activada",
    disabled: "Deactivada",
    manageDelivery: "Administrar resumaziun e filters",
    preview: "Prevista dals resultats memorisads",
    previewHint:
      "Prevista limitada d'eveniments memorisads, nagin avis fictiv u cuverta cumpletta. Ils resultats èn candidats da controllar, naginas consequenzas giuridicas confermadas.",
    noMatches:
      "Nagins resultats memorisads en questa prevista. La surveglianza po vegnir activada. Datas mancantas na signifitgan betg ch'i na dat nagins svilups.",
    evidence: "Avrir la funtauna",
    scanned: "Eveniments memorisads examinads",
    candidates: "Candidats",
    previewTime: "Prevista creada",
    review: "Controllar il profil",
    edit: "Modifitgar",
    activate: "Activar la surveglianza",
    activating: "Activaziun…",
    reviewHint:
      "L'activaziun cundivida il profil cun l'organisaziun e creescha ils temas tschernids. Dumondas da funtaunas supplementaras restan inactivas.",
    success: "Profil da surveglianza activà",
    successHint:
      "Temas ed abunaments èn memorisads. Las incumbensas existentas furneschan resultats cura che cumprovas èn disponiblas.",
    topicsLink: "Avrir temas ed istorgia",
    today: "Avrir Oz",
    pause: "Metter tut ils temas en pausa",
    resume: "Cuntinuar ils temas dal profil",
    pauseHint:
      "La pausa ferma ils temas dal profil. Funtaunas communablas e resumaziun persunala mantegnan lur parameters. Temas archivads na vegnan betg reactivads.",
    export: "Exportar il profil",
    viewer:
      "In administratur po crear ed activar profils. Vus pudais consultar profils cundividids.",
    required: "Empleni ils champs obligatorics.",
    pickTopics: "Tscherni in tema cun num, descripziun e chavazzins.",
    pickSources: "Tscherni almain in pachet da funtaunas disponibel.",
    invalidSource:
      "Endatai in num ed in URL HTTPS public senza datas d'access.",
    unsaved: "Midadas anc betg memorisadas. Cuntinuai u memorisai il sboz.",
    leave: "Bandunar senza memorisar?",
    selectedTopics: "Temas tschernids",
    sourceCount: "Pachets da funtaunas tschernids",
    jurisdiction: "Giurisdicziun survegliada",
    loading: "Chargiar il profil…",
    limit: "Fin sis temas per profil.",
    aiNotice:
      "Il context e Vossas indicaziuns vegnan tramess al purschider IA configurà da l'organisaziun cura che Vus dumandais propostas.",
    nextPage: "Profils suandants",
    previousPage: "Profils precedents",
  },
};
