import type { Locale } from "./i18n";

const en = {
  tripUpdates: "GTFS-RT",
  serviceAlerts: "Service Alerts",
  title: "Monitoring settings",
  intro:
    "Choose one of nine categories to manage its monitors, delivery preferences and source connection.",
  category: "Monitoring category",
  monitors: "Monitors and preferences",
  connector: "Source connection",
  note: "Shared source connections are managed by a platform administrator. Your monitor settings and email consent remain personal unless you explicitly share a business monitor.",
  public:
    "This connector uses public data and does not need a website login or password.",
  boundary:
    "The access check tests the saved connection. An accessible endpoint or successful login does not confirm data coverage, freshness or permission to use every field.",
  save: "Save connection",
  check: "Check saved access",
  reload: "Reload",
  busy: "Working…",
  saved: "Connection saved. New operations will use these settings.",
  failed:
    "The operation could not be confirmed. Reload the current settings before trying again.",
  admin:
    "A platform administrator can change this connection and check access.",
  configured: "Configured",
  missing: "Not configured",
  keep: "Keep saved value",
  replace: "Replace value",
  clear: "Clear value",
  value: "New value",
  enabled: "Collect from this source",
  permission: "Reviewed source permission",
  automatic: "Default / no selected permission",
  static: "Collect the static timetable",
  dataset: "Static timetable dataset",
  cache: "Timetable storage limit (bytes)",
  storage: "Public source storage limit (bytes)",
  versions: "Maximum versions per monitor",
  login: "API username",
  password: "API password",
  key: "API key",
  operations: "Detailed source status",
  changed: "Save changes before checking access.",
  ready: "Endpoint accessible",
  authenticated: "Login accepted",
  denied: "Access denied",
  unavailable: "Access not confirmed",
  limited: "Try again after one minute",
  unexpected: "Unexpected response",
  redirect: "Redirect returned; credentials were not forwarded",
  results: "Last access check",
  readOnly: "Deployment configuration (read only)",
};
export const monitoringSettingsCopy: Record<Locale, typeof en> = {
  "en-CH": en,
  "de-CH": {
    ...en,
    title: "Monitoring-Einstellungen",
    intro:
      "Wählen Sie eine der neun Kategorien für Monitore, Zustellung und Quellenzugang.",
    category: "Monitoring-Kategorie",
    monitors: "Monitore und Einstellungen",
    connector: "Quellenverbindung",
    note: "Gemeinsame Quellenzugänge verwaltet die Plattformadministration. Monitore und E-Mail-Einwilligung bleiben persönlich, sofern Sie einen Geschäftsmonitor nicht ausdrücklich teilen.",
    public:
      "Diese Verbindung verwendet öffentliche Daten und benötigt kein Website-Passwort.",
    boundary:
      "Die Prüfung testet die gespeicherte Verbindung. Erreichbarkeit oder Anmeldung bestätigen weder Abdeckung, Aktualität noch sämtliche Nutzungsrechte.",
    save: "Verbindung speichern",
    check: "Gespeicherten Zugang prüfen",
    reload: "Neu laden",
    busy: "Wird bearbeitet…",
    saved: "Gespeichert. Neue Vorgänge verwenden diese Einstellungen.",
    failed:
      "Der Vorgang konnte nicht bestätigt werden. Laden Sie die aktuellen Einstellungen erneut.",
    admin: "Die Plattformadministration kann diesen Zugang ändern und prüfen.",
    configured: "Konfiguriert",
    missing: "Nicht konfiguriert",
    keep: "Wert beibehalten",
    replace: "Wert ersetzen",
    clear: "Wert löschen",
    value: "Neuer Wert",
    enabled: "Diese Quelle abrufen",
    permission: "Geprüfte Quellengenehmigung",
    automatic: "Standard / keine Auswahl",
    static: "Statischen Fahrplan abrufen",
    dataset: "Fahrplandatensatz",
    cache: "Fahrplanspeicherlimit (Bytes)",
    storage: "Quellenspeicherlimit (Bytes)",
    versions: "Maximale Versionen je Monitor",
    login: "API-Benutzername",
    password: "API-Passwort",
    key: "API-Schlüssel",
    operations: "Detaillierter Quellenstatus",
    changed: "Änderungen vor der Zugangsprüfung speichern.",
    ready: "Endpunkt erreichbar",
    authenticated: "Anmeldung bestätigt",
    denied: "Zugang verweigert",
    unavailable: "Zugang nicht bestätigt",
    limited: "Nach einer Minute erneut versuchen",
    unexpected: "Unerwartete Antwort",
    redirect: "Weiterleitung; Zugangsdaten wurden nicht weitergegeben",
    results: "Letzte Zugangsprüfung",
    readOnly: "Deployment-Konfiguration (schreibgeschützt)",
  },
  "fr-CH": {
    ...en,
    title: "Paramètres du monitoring",
    intro:
      "Choisissez une des neuf catégories pour gérer ses suivis, notifications et sources.",
    category: "Catégorie de suivi",
    monitors: "Suivis et préférences",
    connector: "Connexion à la source",
    note: "Les connexions partagées sont gérées par un administrateur de plateforme. Vos suivis et consentements restent personnels sauf partage explicite d’un suivi professionnel.",
    public:
      "Cette connexion utilise des données publiques sans identifiants de site web.",
    boundary:
      "Le test utilise la connexion enregistrée. Un accès ou une connexion réussie ne confirme ni couverture, ni fraîcheur, ni tous les droits d’utilisation.",
    save: "Enregistrer la connexion",
    check: "Vérifier l’accès enregistré",
    reload: "Recharger",
    busy: "En cours…",
    saved: "Enregistré. Les nouvelles opérations utiliseront ces paramètres.",
    failed:
      "L’opération n’a pas pu être confirmée. Rechargez les paramètres actuels.",
    admin:
      "Un administrateur de plateforme peut modifier et vérifier cet accès.",
    configured: "Configuré",
    missing: "Non configuré",
    keep: "Conserver la valeur",
    replace: "Remplacer la valeur",
    clear: "Effacer la valeur",
    value: "Nouvelle valeur",
    enabled: "Collecter cette source",
    permission: "Autorisation de source vérifiée",
    automatic: "Défaut / aucune sélection",
    static: "Collecter l’horaire statique",
    dataset: "Jeu de données des horaires",
    cache: "Limite de stockage des horaires (octets)",
    storage: "Limite de stockage public (octets)",
    versions: "Versions maximales par suivi",
    login: "Identifiant API",
    password: "Mot de passe API",
    key: "Clé API",
    operations: "État détaillé des sources",
    changed: "Enregistrez les modifications avant de vérifier l’accès.",
    ready: "Point d’accès joignable",
    authenticated: "Connexion acceptée",
    denied: "Accès refusé",
    unavailable: "Accès non confirmé",
    limited: "Réessayez après une minute",
    unexpected: "Réponse inattendue",
    redirect: "Redirection ; identifiants non transmis",
    results: "Dernier test d’accès",
    readOnly: "Configuration du déploiement (lecture seule)",
  },
  "it-CH": {
    ...en,
    title: "Impostazioni del monitoraggio",
    intro:
      "Scegli una delle nove categorie per gestire monitor, notifiche e connessioni alle fonti.",
    category: "Categoria di monitoraggio",
    monitors: "Monitor e preferenze",
    connector: "Connessione alla fonte",
    note: "Le connessioni condivise sono gestite dall’amministratore della piattaforma. Monitor e consensi email restano personali salvo condivisione esplicita di un monitor aziendale.",
    public:
      "Questa connessione usa dati pubblici e non richiede credenziali del sito web.",
    boundary:
      "La verifica usa la connessione salvata. Accesso e autenticazione non confermano copertura, aggiornamento o tutti i diritti d’uso.",
    save: "Salva connessione",
    check: "Verifica accesso salvato",
    reload: "Ricarica",
    busy: "Operazione in corso…",
    saved: "Salvato. Le nuove operazioni useranno queste impostazioni.",
    failed: "Operazione non confermata. Ricarica le impostazioni correnti.",
    admin:
      "Un amministratore della piattaforma può modificare e verificare l’accesso.",
    configured: "Configurato",
    missing: "Non configurato",
    keep: "Mantieni valore",
    replace: "Sostituisci valore",
    clear: "Cancella valore",
    value: "Nuovo valore",
    enabled: "Raccogli da questa fonte",
    permission: "Autorizzazione della fonte verificata",
    automatic: "Predefinito / nessuna selezione",
    static: "Raccogli orario statico",
    dataset: "Dataset dell’orario",
    cache: "Limite archivio orari (byte)",
    storage: "Limite archivio pubblico (byte)",
    versions: "Versioni massime per monitor",
    login: "Nome utente API",
    password: "Password API",
    key: "Chiave API",
    operations: "Stato dettagliato delle fonti",
    changed: "Salva le modifiche prima della verifica.",
    ready: "Endpoint raggiungibile",
    authenticated: "Accesso accettato",
    denied: "Accesso negato",
    unavailable: "Accesso non confermato",
    limited: "Riprova tra un minuto",
    unexpected: "Risposta inattesa",
    redirect: "Reindirizzamento; credenziali non inoltrate",
    results: "Ultima verifica di accesso",
    readOnly: "Configurazione del deployment (sola lettura)",
  },
  "rm-CH": {
    ...en,
    title: "Configuraziuns dal monitoring",
    intro:
      "Tscherna ina da las nov categorias per administrar monitorings, notificaziuns e funtaunas.",
    category: "Categoria da monitoring",
    monitors: "Monitorings e preferenzas",
    connector: "Colliaziun cun la funtauna",
    note: "L’administraziun da la plattafurma gestiunescha las colliaziuns communablas. Monitorings e consentiments dad e-mail restan persunals senza ina partiziun explicita.",
    public:
      "Questa colliaziun dovra datas publicas e nagin pled-clav dal website.",
    boundary:
      "La controlla examinescha la colliaziun memorisada. In access u login reussì na conferma betg cuvrida, actualitad u tut ils dretgs d’utilisaziun.",
    save: "Memorisar la colliaziun",
    check: "Controllar l’access memorisà",
    reload: "Rechargiar",
    busy: "En elavuraziun…",
    saved: "Memorisà. Novas operaziuns dovran questas configuraziuns.",
    failed:
      "L’operaziun n’ha betg pudì vegnir confermada. Rechargia las configuraziuns actualas.",
    admin:
      "L’administraziun da la plattafurma po midar e controllar quest access.",
    configured: "Configurà",
    missing: "Betg configurà",
    keep: "Mantegnair la valur",
    replace: "Substituir la valur",
    clear: "Stizzar la valur",
    value: "Nova valur",
    enabled: "Rimnar da questa funtauna",
    permission: "Permissiun da funtauna controllada",
    automatic: "Standard / nagina selecziun",
    static: "Rimnar l’urari static",
    dataset: "Datas da l’urari",
    cache: "Limit da memoria da l’urari (bytes)",
    storage: "Limit da memoria publica (bytes)",
    versions: "Versiuns maximalas per monitoring",
    login: "Num d’utilisader API",
    password: "Pled-clav API",
    key: "Clav API",
    operations: "Stadi detaglià da las funtaunas",
    changed: "Memorisescha las midadas avant la controlla.",
    ready: "Punct d’access cuntanschibel",
    authenticated: "Login acceptà",
    denied: "Access refusà",
    unavailable: "Access betg confermà",
    limited: "Empruvar suenter ina minuta",
    unexpected: "Resposta nunspetgada",
    redirect: "Renviament; datas d’access betg transmessas",
    results: "Ultima controlla d’access",
    readOnly: "Configuraziun dal deployment (mo lectura)",
  },
};
