import type { Locale } from "./i18n";

const en = {
  title: "Review selected changes",
  select: "Select for review",
  help: "Select up to 20 changes on this page, preview their evidence, then confirm each decision. All selected decisions are saved together. No message, bid or other submission is sent.",
  preview: "Preview selected evidence",
  apply: "Save displayed decisions",
  clear: "Clear selection",
  choose: "Choose an internal decision",
  loading: "Checking selected evidence…",
  failed:
    "The records or access changed, or the request failed. The preview was cleared. Check the current records and preview again before retrying; a lost response does not prove that nothing was saved.",
  saved: "Selected decisions were saved. The queues have been refreshed.",
  original: "Open original evidence",
  excerpt: "Selected source fields — open the original for full context.",
  more: "More source fields are available in the original record.",
  reviewed: "Reviewed",
  bid: "Bid",
  no_bid: "No bid",
  monitor: "Keep monitoring",
  inspect: "Inspect",
  relevant: "Relevant",
  not_relevant: "Not relevant",
  counsel: "Refer to counsel",
};
export const monitoringBatchCopy: Record<
  Locale,
  Record<keyof typeof en, string>
> = {
  "en-CH": en,
  "de-CH": {
    title: "Ausgewählte Änderungen prüfen",
    select: "Zur Prüfung auswählen",
    help: "Wählen Sie bis zu 20 Änderungen auf dieser Seite, prüfen Sie ihre Belege und bestätigen Sie jede Entscheidung. Alle Entscheidungen werden zusammen gespeichert. Keine Nachricht, kein Gebot und keine Einreichung wird gesendet.",
    preview: "Ausgewählte Belege prüfen",
    apply: "Angezeigte Entscheidungen speichern",
    clear: "Auswahl löschen",
    choose: "Interne Entscheidung wählen",
    loading: "Ausgewählte Belege werden geprüft…",
    failed:
      "Die Einträge oder der Zugriff haben sich geändert, oder die Anfrage ist fehlgeschlagen. Die Vorschau wurde gelöscht. Prüfen Sie die aktuellen Einträge vor einem neuen Versuch; eine verlorene Antwort beweist nicht, dass nichts gespeichert wurde.",
    saved:
      "Die ausgewählten Entscheidungen wurden gespeichert. Die Listen wurden aktualisiert.",
    original: "Originalbelege öffnen",
    excerpt:
      "Ausgewählte Quellenfelder – für den vollständigen Kontext das Original öffnen.",
    more: "Weitere Quellenfelder stehen im Originaleintrag.",
    reviewed: "Geprüft",
    bid: "Angebot abgeben",
    no_bid: "Kein Angebot",
    monitor: "Weiter beobachten",
    inspect: "Besichtigen",
    relevant: "Relevant",
    not_relevant: "Nicht relevant",
    counsel: "An Rechtsberatung verweisen",
  },
  "fr-CH": {
    title: "Examiner les changements sélectionnés",
    select: "Sélectionner pour examen",
    help: "Sélectionnez jusqu’à 20 changements sur cette page, examinez leurs preuves et confirmez chaque décision. Toutes les décisions sont enregistrées ensemble. Aucun message, aucune offre ni soumission n’est envoyé.",
    preview: "Voir les preuves sélectionnées",
    apply: "Enregistrer les décisions affichées",
    clear: "Effacer la sélection",
    choose: "Choisir une décision interne",
    loading: "Vérification des preuves sélectionnées…",
    failed:
      "Les éléments ou les accès ont changé, ou la requête a échoué. L’aperçu a été effacé. Vérifiez les éléments actuels avant de réessayer ; une réponse perdue ne prouve pas que rien n’a été enregistré.",
    saved:
      "Les décisions sélectionnées ont été enregistrées. Les listes ont été actualisées.",
    original: "Ouvrir les preuves originales",
    excerpt:
      "Champs sélectionnés de la source — ouvrez l’original pour le contexte complet.",
    more: "D’autres champs sont disponibles dans l’élément original.",
    reviewed: "Examiné",
    bid: "Soumissionner",
    no_bid: "Ne pas soumissionner",
    monitor: "Continuer le suivi",
    inspect: "Inspecter",
    relevant: "Pertinent",
    not_relevant: "Non pertinent",
    counsel: "Consulter un juriste",
  },
  "it-CH": {
    title: "Esamina le modifiche selezionate",
    select: "Seleziona per la revisione",
    help: "Seleziona fino a 20 modifiche in questa pagina, esamina le prove e conferma ogni decisione. Tutte le decisioni vengono salvate insieme. Non viene inviato alcun messaggio, offerta o candidatura.",
    preview: "Visualizza le prove selezionate",
    apply: "Salva le decisioni visualizzate",
    clear: "Cancella selezione",
    choose: "Scegli una decisione interna",
    loading: "Verifica delle prove selezionate…",
    failed:
      "I dati o gli accessi sono cambiati, oppure la richiesta non è riuscita. L’anteprima è stata cancellata. Controlla i dati attuali prima di riprovare; una risposta persa non dimostra che nulla sia stato salvato.",
    saved:
      "Le decisioni selezionate sono state salvate. Gli elenchi sono stati aggiornati.",
    original: "Apri le prove originali",
    excerpt:
      "Campi selezionati della fonte — apri l’originale per il contesto completo.",
    more: "Altri campi sono disponibili nel documento originale.",
    reviewed: "Esaminato",
    bid: "Presentare offerta",
    no_bid: "Nessuna offerta",
    monitor: "Continua il monitoraggio",
    inspect: "Ispezionare",
    relevant: "Rilevante",
    not_relevant: "Non rilevante",
    counsel: "Consultare un legale",
  },
  "rm-CH": {
    title: "Examinar las midadas tschernidas",
    select: "Tscherner per l’examinaziun",
    help: "Tscherni fin 20 midadas sin questa pagina, examinai lur cumprovas e confermai mintga decisiun. Tut las decisiuns vegnan memorisadas ensemen. Nagina communicaziun, offerta u inoltraziun vegn tramessa.",
    preview: "Mussar las cumprovas tschernidas",
    apply: "Memorisar las decisiuns mussadas",
    clear: "Stizzar la selecziun",
    choose: "Tscherner ina decisiun interna",
    loading: "Las cumprovas tschernidas vegnan examinadas…",
    failed:
      "Las datas u l’access èn sa midads, u la dumonda n’è betg reussida. La prevista è vegnida stizzada. Examinai las datas actualas avant da repeter; ina resposta persa na cumprova betg che nagut n’è vegnì memorisà.",
    saved:
      "Las decisiuns tschernidas èn memorisadas. Las glistas èn actualisadas.",
    original: "Avrir las cumprovas originalas",
    excerpt:
      "Champs tschernids da la funtauna — avrir l’original per il context cumplet.",
    more: "Ulteriurs champs èn disponibels en l’original.",
    reviewed: "Examinà",
    bid: "Far in’offerta",
    no_bid: "Naginas offertas",
    monitor: "Cuntinuar a survegliar",
    inspect: "Inspectar",
    relevant: "Relevant",
    not_relevant: "Betg relevant",
    counsel: "Consultar in giurist",
  },
};
