import type { Locale } from "./i18n";

const en = {
  action_required: "Action required",
  source_unavailable:
    "The source could not be refreshed. Any retained value is shown with its original time; a failed refresh does not mean no change.",
  controls: "Monitoring and email settings",
  artifactHash: "Source file SHA-256",
  attribution: "Source: MeteoSwiss",
  emailStatus: "Email delivery history",
  pending: "Queued",
  sending: "Sending",
  sent: "Sent",
  suppressed: "Not sent",
  uncertainDelivery:
    "Delivery could not be confirmed; it will not be resent automatically.",
  exportHistory: "Download private history",
  exportNote:
    "The JSONL file contains settings, observations and review decisions. A final complete record confirms the full export; it cannot restore a live monitor.",
  reviews: "Review decisions",
  title: "Current pollen state",
  today: "Changes to review",
  history: "All observations and changes",
  category_changed: "The category changed under the approved scale.",
  none: "None",
  low: "Low",
  moderate: "Moderate",
  high: "High",
  very_high: "Very high",
  load: "Reload current state",
  waiting: "Waiting for official data. No value means unknown, not zero.",
  measured: "Measured",
  forecast: "Forecast",
  observedAt: "Observation time",
  issuedAt: "Forecast issued",
  validAt: "Forecast valid for",
  retrieved: "Retrieved",
  previous: "Previous value",
  current: "Current value",
  why: "Why this appeared",
  evidence: "Evidence and source history",
  noChanges: "No material changes to review.",
  start: "Start monitoring",
  pause: "Pause monitoring",
  resume: "Resume monitoring",
  archive: "Archive monitoring",
  mute: "Mute notifications",
  unmute: "Unmute notifications",
  unsubscribe: "Turn off email",
  consent_email: "Enable email",
  consent: "I want pollen email using the schedule shown in my saved settings.",
  consentNote:
    "Email stays off until you explicitly consent. Pausing turns off consent; resuming starts with current data without sending old alerts.",
  paused:
    "Paused. Previous evidence is retained; this does not mean pollen levels have fallen.",
  archived: "Archived. Collection and delivery for this monitor have stopped.",
  active: "Monitoring is active.",
  reviewed: "Reviewed",
  not_relevant: "Not relevant",
  continue: "Continue monitoring",
  new: "Needs review",
  retry: "Retry the same operation",
  conflict:
    "The monitor changed. Reload and review its current state before trying again.",
  uncertain:
    "The response was interrupted. Retry the same operation to recover its result without repeating it.",
  failed:
    "The current state could not be loaded. Reload to check current access and data.",
  unavailable: "Unavailable",
  stale: "Out of date",
  usable: "Available",
  missing: "No value reported",
  unverified: "Not yet verified",
  initial: "Initial state",
  state: "State update",
  material: "Material change",
  revision: "Source correction",
  recovered: "Data available again",
  threshold_triggered: "Your selected threshold was reached.",
  threshold_reset: "The value fell to your reset threshold.",
  rapid_triggered:
    "Your selected increase over the comparison window was reached.",
  rapid_reset: "The increase no longer meets your rule.",
  limit:
    "Station and model data describe environmental concentrations, not your symptoms or exact exposure.",
  confirmArchive:
    "Archive this monitor? Its existing settings and evidence will remain available.",
};
type Copy = { [K in keyof typeof en]: string };
export const pollenRuntimeCopy: Record<Locale, Copy> = {
  "en-CH": en,
  "de-CH": {
    action_required: "Handlung erforderlich",
    source_unavailable:
      "Die Quelle konnte nicht aktualisiert werden. Gespeicherte Werte behalten ihre ursprüngliche Zeit; ein fehlgeschlagener Abruf bedeutet nicht, dass es keine Änderung gibt.",
    controls: "Monitoring und E-Mail-Einstellungen",
    artifactHash: "Quelldatei SHA-256",
    attribution: "Source: MeteoSwiss",
    emailStatus: "E-Mail-Versandverlauf",
    pending: "In Warteschlange",
    sending: "Wird gesendet",
    sent: "Gesendet",
    suppressed: "Nicht gesendet",
    uncertainDelivery:
      "Der Versand konnte nicht bestätigt werden; er wird nicht automatisch wiederholt.",
    exportHistory: "Privaten Verlauf herunterladen",
    exportNote:
      "Die JSONL-Datei enthält Einstellungen, Beobachtungen und Prüfentscheide. Ein abschliessender Vollständigkeitsvermerk bestätigt den vollständigen Export; sie stellt kein aktives Monitoring wieder her.",
    reviews: "Prüfentscheide",
    category_changed:
      "Die Kategorie hat sich gemäss der geprüften Skala geändert.",
    none: "Keine",
    low: "Gering",
    moderate: "Mässig",
    high: "Hoch",
    very_high: "Sehr hoch",
    title: "Aktueller Pollenstand",
    today: "Änderungen zur Prüfung",
    history: "Alle Messwerte und Änderungen",
    load: "Aktuellen Stand neu laden",
    waiting:
      "Warten auf offizielle Daten. Ein fehlender Wert bedeutet unbekannt, nicht null.",
    measured: "Gemessen",
    forecast: "Prognose",
    observedAt: "Messzeit",
    issuedAt: "Prognose erstellt",
    validAt: "Prognose gültig für",
    retrieved: "Abgerufen",
    previous: "Vorheriger Wert",
    current: "Aktueller Wert",
    why: "Warum dies angezeigt wird",
    evidence: "Belege und Quellenverlauf",
    noChanges: "Keine wesentlichen Änderungen zur Prüfung.",
    start: "Monitoring starten",
    pause: "Monitoring pausieren",
    resume: "Monitoring fortsetzen",
    archive: "Monitoring archivieren",
    mute: "Mitteilungen stummschalten",
    unmute: "Mitteilungen aktivieren",
    unsubscribe: "E-Mail ausschalten",
    consent_email: "E-Mail aktivieren",
    consent:
      "Ich möchte Pollen-E-Mails gemäss dem Zeitplan in meinen gespeicherten Einstellungen erhalten.",
    consentNote:
      "E-Mail bleibt bis zu Ihrer ausdrücklichen Zustimmung ausgeschaltet. Pausieren widerruft die Zustimmung; Fortsetzen beginnt mit aktuellen Daten ohne alte Meldungen.",
    paused:
      "Pausiert. Bisherige Belege bleiben erhalten; dies bedeutet keinen Rückgang der Pollenwerte.",
    archived:
      "Archiviert. Erfassung und Versand für diesen Monitor sind beendet.",
    active: "Monitoring ist aktiv.",
    reviewed: "Geprüft",
    not_relevant: "Nicht relevant",
    continue: "Weiter beobachten",
    new: "Zu prüfen",
    retry: "Denselben Vorgang erneut versuchen",
    conflict:
      "Der Monitor wurde geändert. Laden und prüfen Sie den aktuellen Stand vor einem neuen Versuch.",
    uncertain:
      "Die Antwort wurde unterbrochen. Wiederholen Sie denselben Vorgang, um das Ergebnis ohne doppelte Ausführung abzurufen.",
    failed:
      "Der aktuelle Stand konnte nicht geladen werden. Laden Sie erneut, um Zugriff und Daten zu prüfen.",
    unavailable: "Nicht verfügbar",
    stale: "Veraltet",
    usable: "Verfügbar",
    missing: "Kein Wert gemeldet",
    unverified: "Noch nicht geprüft",
    initial: "Ausgangszustand",
    state: "Aktualisierung",
    material: "Wesentliche Änderung",
    revision: "Quellenkorrektur",
    recovered: "Daten wieder verfügbar",
    threshold_triggered: "Ihr gewählter Schwellenwert wurde erreicht.",
    threshold_reset: "Der Wert ist auf Ihre Rücksetzschwelle gesunken.",
    rapid_triggered:
      "Ihr gewählter Anstieg im Vergleichszeitraum wurde erreicht.",
    rapid_reset: "Der Anstieg erfüllt Ihre Regel nicht mehr.",
    limit:
      "Stations- und Modelldaten beschreiben Umweltkonzentrationen, nicht Ihre Symptome oder genaue Exposition.",
    confirmArchive:
      "Diesen Monitor archivieren? Einstellungen und bisherige Belege bleiben verfügbar.",
  },
  "fr-CH": {
    action_required: "Action requise",
    source_unavailable:
      "La source n’a pas pu être actualisée. Les valeurs conservées gardent leur heure d’origine ; un échec de récupération ne signifie pas une absence de changement.",
    controls: "Paramètres du suivi et des e-mails",
    artifactHash: "SHA-256 du fichier source",
    attribution: "Source: MeteoSwiss",
    emailStatus: "Historique d’envoi des e-mails",
    pending: "En attente",
    sending: "Envoi en cours",
    sent: "Envoyé",
    suppressed: "Non envoyé",
    uncertainDelivery:
      "L’envoi n’a pas pu être confirmé ; il ne sera pas répété automatiquement.",
    exportHistory: "Télécharger l’historique privé",
    exportNote:
      "Le fichier JSONL contient les paramètres, observations et décisions. Un enregistrement final confirme l’export complet ; il ne permet pas de restaurer un suivi actif.",
    reviews: "Décisions d’examen",
    category_changed: "La catégorie a changé selon l’échelle approuvée.",
    none: "Nulle",
    low: "Faible",
    moderate: "Modérée",
    high: "Forte",
    very_high: "Très forte",
    title: "État actuel du pollen",
    today: "Changements à examiner",
    history: "Toutes les observations et modifications",
    load: "Recharger l’état actuel",
    waiting:
      "En attente de données officielles. Une valeur absente signifie inconnue, et non zéro.",
    measured: "Mesuré",
    forecast: "Prévision",
    observedAt: "Heure de mesure",
    issuedAt: "Prévision émise",
    validAt: "Prévision valable pour",
    retrieved: "Récupéré",
    previous: "Valeur précédente",
    current: "Valeur actuelle",
    why: "Pourquoi cet élément apparaît",
    evidence: "Preuves et historique de la source",
    noChanges: "Aucun changement significatif à examiner.",
    start: "Démarrer le suivi",
    pause: "Mettre en pause",
    resume: "Reprendre le suivi",
    archive: "Archiver le suivi",
    mute: "Suspendre les notifications",
    unmute: "Réactiver les notifications",
    unsubscribe: "Désactiver les e-mails",
    consent_email: "Activer les e-mails",
    consent:
      "Je souhaite recevoir des e-mails sur le pollen selon l’horaire de mes paramètres enregistrés.",
    consentNote:
      "Les e-mails restent désactivés sans consentement explicite. La pause retire ce consentement ; la reprise utilise les données actuelles sans envoyer d’anciennes alertes.",
    paused:
      "En pause. Les preuves précédentes sont conservées ; cela ne signifie pas une baisse du pollen.",
    archived: "Archivé. La collecte et l’envoi pour ce suivi sont arrêtés.",
    active: "Le suivi est actif.",
    reviewed: "Examiné",
    not_relevant: "Non pertinent",
    continue: "Continuer le suivi",
    new: "À examiner",
    retry: "Réessayer la même opération",
    conflict:
      "Le suivi a changé. Rechargez et examinez son état actuel avant de réessayer.",
    uncertain:
      "La réponse a été interrompue. Réessayez la même opération pour récupérer son résultat sans la répéter.",
    failed:
      "L’état actuel n’a pas pu être chargé. Rechargez pour vérifier l’accès et les données.",
    unavailable: "Indisponible",
    stale: "Périmé",
    usable: "Disponible",
    missing: "Aucune valeur signalée",
    unverified: "Pas encore vérifié",
    initial: "État initial",
    state: "Mise à jour",
    material: "Changement significatif",
    revision: "Correction de la source",
    recovered: "Données de nouveau disponibles",
    threshold_triggered: "Le seuil choisi a été atteint.",
    threshold_reset:
      "La valeur est descendue jusqu’à votre seuil de réinitialisation.",
    rapid_triggered:
      "L’augmentation choisie sur la période de comparaison a été atteinte.",
    rapid_reset: "L’augmentation ne remplit plus votre règle.",
    limit:
      "Les données des stations et modèles décrivent les concentrations environnementales, pas vos symptômes ni votre exposition exacte.",
    confirmArchive:
      "Archiver ce suivi ? Ses paramètres et preuves existantes resteront disponibles.",
  },
  "it-CH": {
    action_required: "Azione richiesta",
    source_unavailable:
      "Impossibile aggiornare la fonte. I valori conservati mantengono l’ora originale; un recupero fallito non significa assenza di cambiamenti.",
    controls: "Impostazioni di monitoraggio ed e-mail",
    artifactHash: "SHA-256 del file sorgente",
    attribution: "Source: MeteoSwiss",
    emailStatus: "Cronologia invio e-mail",
    pending: "In coda",
    sending: "Invio in corso",
    sent: "Inviato",
    suppressed: "Non inviato",
    uncertainDelivery:
      "L’invio non è stato confermato; non sarà ripetuto automaticamente.",
    exportHistory: "Scarica cronologia privata",
    exportNote:
      "Il file JSONL contiene impostazioni, osservazioni e decisioni. Un record finale conferma l’esportazione completa; non ripristina un monitoraggio attivo.",
    reviews: "Decisioni di revisione",
    category_changed: "La categoria è cambiata secondo la scala approvata.",
    none: "Nessuna",
    low: "Bassa",
    moderate: "Moderata",
    high: "Alta",
    very_high: "Molto alta",
    title: "Stato attuale dei pollini",
    today: "Cambiamenti da esaminare",
    history: "Tutte le osservazioni e le modifiche",
    load: "Ricarica lo stato attuale",
    waiting:
      "In attesa di dati ufficiali. Un valore assente significa sconosciuto, non zero.",
    measured: "Misurato",
    forecast: "Previsione",
    observedAt: "Ora della misurazione",
    issuedAt: "Previsione emessa",
    validAt: "Previsione valida per",
    retrieved: "Recuperato",
    previous: "Valore precedente",
    current: "Valore attuale",
    why: "Perché compare",
    evidence: "Prove e cronologia della fonte",
    noChanges: "Nessun cambiamento significativo da esaminare.",
    start: "Avvia monitoraggio",
    pause: "Metti in pausa",
    resume: "Riprendi monitoraggio",
    archive: "Archivia monitoraggio",
    mute: "Silenzia notifiche",
    unmute: "Riattiva notifiche",
    unsubscribe: "Disattiva e-mail",
    consent_email: "Attiva e-mail",
    consent:
      "Desidero ricevere e-mail sui pollini secondo l’orario delle mie impostazioni salvate.",
    consentNote:
      "Le e-mail restano disattivate senza consenso esplicito. La pausa revoca il consenso; la ripresa utilizza i dati attuali senza inviare vecchi avvisi.",
    paused:
      "In pausa. Le prove precedenti sono conservate; non significa che i pollini siano diminuiti.",
    archived:
      "Archiviato. La raccolta e l’invio per questo monitoraggio sono terminati.",
    active: "Il monitoraggio è attivo.",
    reviewed: "Esaminato",
    not_relevant: "Non pertinente",
    continue: "Continua monitoraggio",
    new: "Da esaminare",
    retry: "Riprova la stessa operazione",
    conflict:
      "Il monitoraggio è cambiato. Ricarica ed esamina lo stato attuale prima di riprovare.",
    uncertain:
      "La risposta è stata interrotta. Riprova la stessa operazione per recuperarne l’esito senza ripeterla.",
    failed:
      "Impossibile caricare lo stato attuale. Ricarica per verificare accesso e dati.",
    unavailable: "Non disponibile",
    stale: "Non aggiornato",
    usable: "Disponibile",
    missing: "Nessun valore segnalato",
    unverified: "Non ancora verificato",
    initial: "Stato iniziale",
    state: "Aggiornamento",
    material: "Cambiamento significativo",
    revision: "Correzione della fonte",
    recovered: "Dati nuovamente disponibili",
    threshold_triggered: "È stata raggiunta la soglia scelta.",
    threshold_reset: "Il valore è sceso alla soglia di ripristino.",
    rapid_triggered:
      "È stato raggiunto l’aumento scelto nel periodo di confronto.",
    rapid_reset: "L’aumento non soddisfa più la regola.",
    limit:
      "I dati delle stazioni e dei modelli descrivono concentrazioni ambientali, non sintomi o esposizione individuale esatta.",
    confirmArchive:
      "Archiviare questo monitoraggio? Le impostazioni e le prove esistenti resteranno disponibili.",
  },
  "rm-CH": {
    action_required: "Acziun necessaria",
    source_unavailable:
      "La funtauna n’ha betg pudì vegnir actualisada. Valurs memorisadas mantegnan lur temp original; in clom fallì na signifitga betg nagina midada.",
    controls: "Parameters da monitoring ed e-mail",
    artifactHash: "SHA-256 da la datoteca da funtauna",
    attribution: "Source: MeteoSwiss",
    emailStatus: "Istorgia da spediziun dad e-mails",
    pending: "En la colonna",
    sending: "Spediziun en curs",
    sent: "Tramess",
    suppressed: "Betg tramess",
    uncertainDelivery:
      "La spediziun n’ha betg pudì vegnir confermada; ella na vegn betg repetida automaticamain.",
    exportHistory: "Telechargiar l’istorgia privata",
    exportNote:
      "La datoteca JSONL cuntegna parameters, observaziuns e decisiuns. In record final conferma l’export cumplett; el na restaurescha betg in monitoring activ.",
    reviews: "Decisiuns da controlla",
    category_changed: "La categoria è sa midada tenor la scala verifitgada.",
    none: "Nagina",
    low: "Bassa",
    moderate: "Moderada",
    high: "Auta",
    very_high: "Fitg auta",
    title: "Stadi actual dal pollen",
    today: "Midadas da controllar",
    history: "Tut las observaziuns e midadas",
    load: "Chargiar da nov il stadi actual",
    waiting:
      "Spetgar sin datas uffizialas. Ina valur che manca signifitga nunenconuschent, betg nulla.",
    measured: "Mesirà",
    forecast: "Prognosa",
    observedAt: "Temp da mesiraziun",
    issuedAt: "Prognosa publitgada",
    validAt: "Prognosa valaivla per",
    retrieved: "Retratg",
    previous: "Valur precedenta",
    current: "Valur actuala",
    why: "Pertge che quai cumpara",
    evidence: "Cumprovas ed istorgia da la funtauna",
    noChanges: "Naginas midadas essenzialas da controllar.",
    start: "Cumenzar il monitoring",
    pause: "Far pausa",
    resume: "Cuntinuar il monitoring",
    archive: "Archivar il monitoring",
    mute: "Deactivar notificaziuns",
    unmute: "Reactivar notificaziuns",
    unsubscribe: "Deactivar e-mails",
    consent_email: "Activar e-mails",
    consent:
      "Jau vul retschaiver e-mails davart pollen tenor l’urari en mes parameters memorisads.",
    consentNote:
      "E-mails restan deactivads senza consentiment explicit. Ina pausa revoca il consentiment; la cuntinuaziun dovra datas actualas senza trametter vegls avis.",
    paused:
      "En pausa. Las cumprovas precedentas restan; quai na signifitga betg che las valurs dal pollen sajan sa reducidas.",
    archived:
      "Archivà. La rimnada e la spediziun per quest monitoring èn terminadas.",
    active: "Il monitoring è activ.",
    reviewed: "Controllà",
    not_relevant: "Betg relevant",
    continue: "Cuntinuar ad observar",
    new: "Da controllar",
    retry: "Empruvar da nov la medema operaziun",
    conflict:
      "Il monitoring è sa midà. Chargia e controlla il stadi actual avant d’empruvar da nov.",
    uncertain:
      "La resposta è vegnida interrutta. Repeta la medema operaziun per recuperar il resultat senza la far duas giadas.",
    failed:
      "Il stadi actual n’ha betg pudì vegnir chargià. Chargia da nov per controllar l’access e las datas.",
    unavailable: "Betg disponibel",
    stale: "Betg pli actual",
    usable: "Disponibel",
    missing: "Nagina valur annunziada",
    unverified: "Anc betg verifitgà",
    initial: "Stadi inizial",
    state: "Actualisaziun",
    material: "Midada essenziala",
    revision: "Correctura da la funtauna",
    recovered: "Datas puspè disponiblas",
    threshold_triggered: "La sava tschernida è vegnida cuntanschida.",
    threshold_reset: "La valur è crudada sin tia sava da restabiliment.",
    rapid_triggered:
      "L’augment tschernì durant il temp da cumparegliaziun è vegnì cuntanschì.",
    rapid_reset: "L’augment na correspunda betg pli a tia regla.",
    limit:
      "Las datas da staziuns e models descrivan concentraziuns en l’ambient, betg tes sintoms u tia exposiziun exacta.",
    confirmArchive:
      "Archivar quest monitoring? Ils parameters e las cumprovas existentas restan disponibels.",
  },
};
