import type { Locale } from "./i18n";

const en = {
  title: "Related developments",
  intro:
    "Compare warnings, water observations and road events in one private location story. A possible relationship does not establish a common cause. Each source keeps its own status and review.",
  stories: "My stories",
  newStory: "Create a story",
  name: "Story name",
  candidates: "Choose source events",
  selected: "Selected events",
  empty:
    "No events on this page. Create a monitor in the source section, or continue to the next page. Missing evidence never means that the area is safe.",
  noStories: "No saved stories in this view.",
  more: "Next page",
  previous: "First page",
  refresh: "Refresh",
  loading: "Loading…",
  failed:
    "Could not complete this request. Refresh and check your access or the latest event version, then retry.",
  warnings: "Warnings",
  river: "Rivers and lakes",
  traffic: "Road traffic",
  available: "Current evidence",
  historical: "Historical evidence",
  unavailable: "Evidence unavailable",
  source: "Source identity",
  state: "Source status",
  current: "Current source status",
  open: "Open exact source version",
  reviewed: "Reviewed at source",
  notReviewed: "Not reviewed at source",
  unknown: "Unknown",
  geography: "Reviewed area",
  missingPlace:
    "No current geographic binding. An operator must review the source feature against the official boundary edition.",
  time: "Source time",
  instant: "Observation at one instant",
  interval: "Explicit validity interval",
  unknownTime: "Source time is incomplete; no overlap is assumed.",
  possible: "Possible relationship",
  unverified: "Relationship requires rechecking",
  separate: "Separate event",
  reason: "Relationship check",
  same_verified_area_and_overlapping_time:
    "Same reviewed area and overlapping explicit source time.",
  source_unavailable: "A source is unavailable.",
  same_event: "These references belong to the same authority event.",
  geography_unavailable: "A geographic binding is missing, expired or revoked.",
  geography_changed: "The source geography changed.",
  different_places: "Different reviewed areas.",
  time_unknown: "Explicit source time is missing.",
  different_times: "The source times do not overlap.",
  save: "Save group",
  edit: "Edit group / split",
  remove: "Remove from this group",
  cancel: "Cancel editing",
  check: "Check relationship",
  refreshMembers: "Load current source versions",
  noTransfer:
    "Grouping and splitting do not send notifications, change source reviews or delete events. Removed events remain available in their source section.",
  limit:
    "Choose up to 12 events. A new story needs at least two source directions and verified location/time for every pair.",
  archive: "Archive story",
  restore: "Restore story",
  archived: "Archived",
  active: "Active",
  history: "Revision history",
  version: "Version",
  useRevision: "Use these members in a new revision",
  create: "Created",
  revise: "Revised",
  split: "Split",
  merge: "Members added",
  saved: "Saved",
  readonly:
    "Your role can read saved stories. Editing requires workspace management access.",
  signIn: "Sign in to read your private stories.",
  bindingReview: "Review geographic binding",
  reviewIntro:
    "Operator review only. Verify the exact source feature and municipality using permitted evidence. A name or nearby timestamp is insufficient. This review grants no source rights.",
  inspect: "Inspect source feature",
  areaCode: "BFS municipality code",
  checkArea: "Check official area",
  evidenceHash: "SHA-256 of reviewed geographic evidence",
  validUntil: "Review valid until (UTC)",
  attest:
    "I verified that this exact source feature belongs to this municipality using the referenced evidence.",
  publish: "Save geographic review",
  revoke: "Revoke binding",
  sourceFeature: "Exact source feature",
  existingBindings: "Existing binding reviews",
  noBindings: "No binding reviews.",
};
type Copy = { [K in keyof typeof en]: string };
export const relatedCopy: Record<Locale, Copy> = {
  "en-CH": en,
  "de-CH": {
    title: "Zusammenhängende Entwicklungen",
    intro:
      "Warnungen, Gewässermessungen und Verkehrsereignisse in einer privaten Ortsübersicht vergleichen. Ein möglicher Zusammenhang beweist keine gemeinsame Ursache. Jede Quelle behält ihren eigenen Status und ihre Prüfung.",
    stories: "Meine Gruppen",
    newStory: "Gruppe erstellen",
    name: "Name der Gruppe",
    candidates: "Quellereignisse auswählen",
    selected: "Ausgewählte Ereignisse",
    empty:
      "Keine Ereignisse auf dieser Seite. Einen Monitor im Quellbereich erstellen oder zur nächsten Seite wechseln. Fehlende Daten bedeuten keine Entwarnung.",
    noStories: "Keine gespeicherten Gruppen in dieser Ansicht.",
    more: "Nächste Seite",
    previous: "Erste Seite",
    refresh: "Aktualisieren",
    loading: "Wird geladen…",
    failed:
      "Anfrage fehlgeschlagen. Aktualisieren, Zugriff und Ereignisversion prüfen und erneut versuchen.",
    warnings: "Warnungen",
    river: "Flüsse und Seen",
    traffic: "Strassenverkehr",
    available: "Aktuelle Nachweise",
    historical: "Historische Nachweise",
    unavailable: "Nachweise nicht verfügbar",
    source: "Quellidentität",
    state: "Quellstatus",
    current: "Aktueller Quellstatus",
    open: "Genaue Quellversion öffnen",
    reviewed: "An der Quelle geprüft",
    notReviewed: "An der Quelle ungeprüft",
    unknown: "Unbekannt",
    geography: "Geprüftes Gebiet",
    missingPlace:
      "Keine aktuelle geografische Zuordnung. Ein Betreiber muss das Quellobjekt anhand der amtlichen Gebietsversion prüfen.",
    time: "Quellzeit",
    instant: "Messung zu einem Zeitpunkt",
    interval: "Ausdrücklicher Gültigkeitszeitraum",
    unknownTime:
      "Quellzeit unvollständig; es wird keine Überschneidung angenommen.",
    possible: "Möglicher Zusammenhang",
    unverified: "Zusammenhang erneut prüfen",
    separate: "Einzelnes Ereignis",
    reason: "Zusammenhangsprüfung",
    same_verified_area_and_overlapping_time:
      "Gleiches geprüftes Gebiet und überlappende ausdrückliche Quellzeiten.",
    source_unavailable: "Eine Quelle ist nicht verfügbar.",
    same_event: "Diese Verweise gehören zum gleichen behördlichen Ereignis.",
    geography_unavailable:
      "Eine Zuordnung fehlt, ist abgelaufen oder widerrufen.",
    geography_changed: "Die Quellgeografie hat sich geändert.",
    different_places: "Unterschiedliche geprüfte Gebiete.",
    time_unknown: "Ausdrückliche Quellzeit fehlt.",
    different_times: "Die Quellzeiten überschneiden sich nicht.",
    save: "Gruppe speichern",
    edit: "Gruppe bearbeiten / trennen",
    remove: "Aus dieser Gruppe entfernen",
    cancel: "Bearbeitung abbrechen",
    check: "Zusammenhang prüfen",
    refreshMembers: "Aktuelle Quellversionen laden",
    noTransfer:
      "Gruppieren und Trennen sendet keine Nachrichten, ändert keine Quellprüfungen und löscht keine Ereignisse. Entfernte Ereignisse bleiben im Quellbereich verfügbar.",
    limit:
      "Bis zu 12 Ereignisse auswählen. Eine neue Gruppe benötigt mindestens zwei Quellbereiche und geprüfte Orts- und Zeitnachweise für jedes Paar.",
    archive: "Gruppe archivieren",
    restore: "Gruppe wiederherstellen",
    archived: "Archiviert",
    active: "Aktiv",
    history: "Versionsverlauf",
    version: "Version",
    useRevision: "Diese Mitglieder in neuer Version verwenden",
    create: "Erstellt",
    revise: "Überarbeitet",
    split: "Getrennt",
    merge: "Mitglieder hinzugefügt",
    saved: "Gespeichert",
    readonly:
      "Ihre Rolle kann gespeicherte Gruppen lesen. Bearbeitung benötigt Verwaltungszugriff im Arbeitsbereich.",
    signIn: "Anmelden, um private Gruppen zu lesen.",
    bindingReview: "Geografische Zuordnung prüfen",
    reviewIntro:
      "Nur für Betreiber. Exaktes Quellobjekt und Gemeinde mit erlaubten Nachweisen prüfen. Name oder zeitliche Nähe reicht nicht. Diese Prüfung gewährt keine Quellrechte.",
    inspect: "Quellobjekt prüfen",
    areaCode: "BFS-Gemeindenummer",
    checkArea: "Amtliches Gebiet prüfen",
    evidenceHash: "SHA-256 des geprüften geografischen Nachweises",
    validUntil: "Prüfung gültig bis (UTC)",
    attest:
      "Ich habe anhand des angegebenen Nachweises geprüft, dass dieses genaue Quellobjekt zu dieser Gemeinde gehört.",
    publish: "Geografische Prüfung speichern",
    revoke: "Zuordnung widerrufen",
    sourceFeature: "Genaues Quellobjekt",
    existingBindings: "Vorhandene Zuordnungsprüfungen",
    noBindings: "Keine Zuordnungsprüfungen.",
  },
  "fr-CH": {
    title: "Évolutions liées",
    intro:
      "Comparez alertes, mesures des eaux et événements routiers dans un groupe privé par lieu. Un lien possible ne prouve pas une cause commune. Chaque source conserve son statut et sa vérification.",
    stories: "Mes groupes",
    newStory: "Créer un groupe",
    name: "Nom du groupe",
    candidates: "Choisir les événements sources",
    selected: "Événements sélectionnés",
    empty:
      "Aucun événement sur cette page. Créez une veille dans la rubrique source ou passez à la page suivante. Des données absentes ne signifient jamais que la zone est sûre.",
    noStories: "Aucun groupe enregistré dans cette vue.",
    more: "Page suivante",
    previous: "Première page",
    refresh: "Actualiser",
    loading: "Chargement…",
    failed:
      "La demande a échoué. Actualisez, vérifiez vos accès ou la version de l’événement, puis réessayez.",
    warnings: "Alertes",
    river: "Rivières et lacs",
    traffic: "Trafic routier",
    available: "Preuves actuelles",
    historical: "Preuves historiques",
    unavailable: "Preuves indisponibles",
    source: "Identité de la source",
    state: "Statut de la source",
    current: "Statut actuel de la source",
    open: "Ouvrir la version source exacte",
    reviewed: "Vérifié à la source",
    notReviewed: "Non vérifié à la source",
    unknown: "Inconnu",
    geography: "Zone vérifiée",
    missingPlace:
      "Aucun rattachement géographique actuel. Un opérateur doit vérifier l’objet source avec l’édition officielle des limites.",
    time: "Date de la source",
    instant: "Observation à un instant",
    interval: "Période de validité explicite",
    unknownTime: "Date source incomplète ; aucun chevauchement supposé.",
    possible: "Lien possible",
    unverified: "Lien à vérifier de nouveau",
    separate: "Événement séparé",
    reason: "Vérification du lien",
    same_verified_area_and_overlapping_time:
      "Même zone vérifiée et dates sources explicites qui se chevauchent.",
    source_unavailable: "Une source est indisponible.",
    same_event: "Ces références appartiennent au même événement officiel.",
    geography_unavailable: "Un rattachement est absent, expiré ou révoqué.",
    geography_changed: "La géographie source a changé.",
    different_places: "Zones vérifiées différentes.",
    time_unknown: "Date source explicite absente.",
    different_times: "Les dates sources ne se chevauchent pas.",
    save: "Enregistrer le groupe",
    edit: "Modifier / séparer le groupe",
    remove: "Retirer de ce groupe",
    cancel: "Annuler la modification",
    check: "Vérifier le lien",
    refreshMembers: "Charger les versions sources actuelles",
    noTransfer:
      "Regrouper ou séparer n’envoie aucune notification, ne change aucune vérification source et ne supprime aucun événement. Les événements retirés restent dans leur rubrique source.",
    limit:
      "Choisissez jusqu’à 12 événements. Un nouveau groupe exige au moins deux rubriques sources et des preuves de lieu et de date vérifiées pour chaque paire.",
    archive: "Archiver le groupe",
    restore: "Restaurer le groupe",
    archived: "Archivé",
    active: "Actif",
    history: "Historique des versions",
    version: "Version",
    useRevision: "Utiliser ces membres dans une nouvelle version",
    create: "Créé",
    revise: "Révisé",
    split: "Séparé",
    merge: "Membres ajoutés",
    saved: "Enregistré",
    readonly:
      "Votre rôle permet de lire les groupes enregistrés. Leur modification exige un accès de gestion de l’espace.",
    signIn: "Connectez-vous pour lire vos groupes privés.",
    bindingReview: "Vérifier le rattachement géographique",
    reviewIntro:
      "Réservé aux opérateurs. Vérifiez l’objet source exact et la commune avec des preuves autorisées. Un nom ou une proximité temporelle ne suffit pas. Cette vérification ne confère aucun droit sur la source.",
    inspect: "Examiner l’objet source",
    areaCode: "Numéro OFS de la commune",
    checkArea: "Vérifier la zone officielle",
    evidenceHash: "SHA-256 de la preuve géographique vérifiée",
    validUntil: "Vérification valable jusqu’au (UTC)",
    attest:
      "J’ai vérifié avec la preuve référencée que cet objet source exact appartient à cette commune.",
    publish: "Enregistrer la vérification géographique",
    revoke: "Révoquer le rattachement",
    sourceFeature: "Objet source exact",
    existingBindings: "Vérifications existantes",
    noBindings: "Aucune vérification de rattachement.",
  },
  "it-CH": {
    title: "Sviluppi correlati",
    intro:
      "Confronta allerte, osservazioni idriche ed eventi stradali in un gruppo privato per luogo. Una possibile relazione non prova una causa comune. Ogni fonte mantiene il proprio stato e la propria verifica.",
    stories: "I miei gruppi",
    newStory: "Crea un gruppo",
    name: "Nome del gruppo",
    candidates: "Scegli gli eventi delle fonti",
    selected: "Eventi selezionati",
    empty:
      "Nessun evento in questa pagina. Crea un monitoraggio nella sezione della fonte oppure passa alla pagina successiva. L’assenza di dati non significa che l’area sia sicura.",
    noStories: "Nessun gruppo salvato in questa vista.",
    more: "Pagina successiva",
    previous: "Prima pagina",
    refresh: "Aggiorna",
    loading: "Caricamento…",
    failed:
      "Richiesta non completata. Aggiorna, verifica l’accesso o la versione dell’evento e riprova.",
    warnings: "Allerte",
    river: "Fiumi e laghi",
    traffic: "Traffico stradale",
    available: "Prove attuali",
    historical: "Prove storiche",
    unavailable: "Prove non disponibili",
    source: "Identità della fonte",
    state: "Stato della fonte",
    current: "Stato attuale della fonte",
    open: "Apri la versione esatta della fonte",
    reviewed: "Verificato alla fonte",
    notReviewed: "Non verificato alla fonte",
    unknown: "Sconosciuto",
    geography: "Area verificata",
    missingPlace:
      "Nessun collegamento geografico attuale. Un operatore deve verificare l’oggetto della fonte con l’edizione ufficiale dei confini.",
    time: "Data della fonte",
    instant: "Osservazione in un istante",
    interval: "Intervallo di validità esplicito",
    unknownTime:
      "Data della fonte incompleta; nessuna sovrapposizione presunta.",
    possible: "Possibile relazione",
    unverified: "Relazione da verificare nuovamente",
    separate: "Evento separato",
    reason: "Verifica della relazione",
    same_verified_area_and_overlapping_time:
      "Stessa area verificata e tempi espliciti delle fonti sovrapposti.",
    source_unavailable: "Una fonte non è disponibile.",
    same_event: "Questi riferimenti appartengono allo stesso evento ufficiale.",
    geography_unavailable: "Un collegamento manca, è scaduto o è revocato.",
    geography_changed: "La geografia della fonte è cambiata.",
    different_places: "Aree verificate diverse.",
    time_unknown: "Manca il tempo esplicito della fonte.",
    different_times: "I tempi delle fonti non si sovrappongono.",
    save: "Salva gruppo",
    edit: "Modifica / separa gruppo",
    remove: "Rimuovi da questo gruppo",
    cancel: "Annulla modifica",
    check: "Verifica relazione",
    refreshMembers: "Carica versioni attuali delle fonti",
    noTransfer:
      "Raggruppare e separare non invia notifiche, non modifica le verifiche delle fonti e non elimina eventi. Gli eventi rimossi restano nella sezione della fonte.",
    limit:
      "Scegli fino a 12 eventi. Un nuovo gruppo richiede almeno due sezioni e prove verificate di luogo e tempo per ogni coppia.",
    archive: "Archivia gruppo",
    restore: "Ripristina gruppo",
    archived: "Archiviato",
    active: "Attivo",
    history: "Cronologia delle versioni",
    version: "Versione",
    useRevision: "Usa questi membri in una nuova versione",
    create: "Creato",
    revise: "Revisionato",
    split: "Separato",
    merge: "Membri aggiunti",
    saved: "Salvato",
    readonly:
      "Il tuo ruolo consente di leggere i gruppi salvati. Per modificarli serve l’accesso di gestione dello spazio.",
    signIn: "Accedi per leggere i tuoi gruppi privati.",
    bindingReview: "Verifica collegamento geografico",
    reviewIntro:
      "Solo per operatori. Verifica l’oggetto esatto della fonte e il comune con prove consentite. Un nome o un orario vicino non basta. Questa verifica non concede diritti sulla fonte.",
    inspect: "Esamina oggetto della fonte",
    areaCode: "Numero UST del comune",
    checkArea: "Verifica area ufficiale",
    evidenceHash: "SHA-256 della prova geografica verificata",
    validUntil: "Verifica valida fino al (UTC)",
    attest:
      "Ho verificato tramite la prova indicata che questo esatto oggetto della fonte appartiene al comune.",
    publish: "Salva verifica geografica",
    revoke: "Revoca collegamento",
    sourceFeature: "Oggetto esatto della fonte",
    existingBindings: "Verifiche esistenti",
    noBindings: "Nessuna verifica di collegamento.",
  },
  "rm-CH": {
    title: "Svilups colliads",
    intro:
      "Cumparegliar avertiments, observaziuns da las auas ed eveniments da traffic en ina gruppa privata tenor lieu. Ina relaziun pussaivla na cumprova nagina causa communabla. Mintga funtauna mantegna ses agen status e sia verificaziun.",
    stories: "Mias gruppas",
    newStory: "Crear ina gruppa",
    name: "Num da la gruppa",
    candidates: "Tscherner eveniments da funtaunas",
    selected: "Eveniments tschernids",
    empty:
      "Nagins eveniments sin questa pagina. Crear ina surveglianza en la rubrica da la funtauna u cuntinuar sin la proxima pagina. Datas mancantas na signifitgan mai che la regiun saja segira.",
    noStories: "Naginas gruppas memorisadas en questa vista.",
    more: "Proxima pagina",
    previous: "Emprima pagina",
    refresh: "Actualisar",
    loading: "Chargiar…",
    failed:
      "La dumonda n’ha betg funcziunà. Actualisar, controllar l’access u la versiun da l’eveniment e provar anc ina giada.",
    warnings: "Avertiments",
    river: "Flums e lais",
    traffic: "Traffic sin via",
    available: "Cumprovas actualas",
    historical: "Cumprovas istoricas",
    unavailable: "Cumprovas betg disponiblas",
    source: "Identitad da la funtauna",
    state: "Status da la funtauna",
    current: "Status actual da la funtauna",
    open: "Avrir la versiun exacta da la funtauna",
    reviewed: "Verifitgà a la funtauna",
    notReviewed: "Betg verifitgà a la funtauna",
    unknown: "Nunenconuschent",
    geography: "Territori verifitgà",
    missingPlace:
      "Nagina attribuziun geografica actuala. In gestiunari sto verifitgar l’object da la funtauna cun l’ediziun uffiziala dals cunfins.",
    time: "Temp da la funtauna",
    instant: "Observaziun en in mument",
    interval: "Interval explicit da validitad",
    unknownTime: "Temp da la funtauna incumplet; nagina coincidenza supponida.",
    possible: "Relaziun pussaivla",
    unverified: "Verifitgar danovamain la relaziun",
    separate: "Eveniment separà",
    reason: "Verificaziun da la relaziun",
    same_verified_area_and_overlapping_time:
      "Medem territori verifitgà e temps explicits da funtaunas che sa cruschan.",
    source_unavailable: "Ina funtauna n’è betg disponibla.",
    same_event: "Quests renviaments appartegnan al medem eveniment uffizial.",
    geography_unavailable: "In’attribuziun manca, è scadida u revocada.",
    geography_changed: "La geografia da la funtauna è sa midada.",
    different_places: "Territoris verifitgads differents.",
    time_unknown: "Il temp explicit da la funtauna manca.",
    different_times: "Ils temps da las funtaunas na sa cruschan betg.",
    save: "Memorisar gruppa",
    edit: "Modifitgar / separar gruppa",
    remove: "Allontanar da questa gruppa",
    cancel: "Interrumper modificaziun",
    check: "Verifitgar relaziun",
    refreshMembers: "Chargiar versiuns actualas da las funtaunas",
    noTransfer:
      "Gruppar e separar na trametta naginas notificaziuns, na mida naginas verificaziuns da funtaunas e na stizza nagins eveniments. Eveniments allontanads restan en la rubrica da la funtauna.",
    limit:
      "Tscherner fin a 12 eveniments. Ina nova gruppa dovra almain duas rubricas e cumprovas verifitgadas da lieu e temp per mintga pèra.",
    archive: "Archivar gruppa",
    restore: "Restaurar gruppa",
    archived: "Archivà",
    active: "Activ",
    history: "Cronologia da versiuns",
    version: "Versiun",
    useRevision: "Utilisar quests commembers en ina nova versiun",
    create: "Creà",
    revise: "Revedì",
    split: "Separà",
    merge: "Commembers agiuntads",
    saved: "Memorisà",
    readonly:
      "Vossa rolla permetta da leger gruppas memorisadas. Per modifitgar dovri access da gestiun dal spazi.",
    signIn: "S’annunziar per leger gruppas privatas.",
    bindingReview: "Verifitgar attribuziun geografica",
    reviewIntro:
      "Mo per gestiunaris. Verifitgar l’object exact da la funtauna e la vischnanca cun cumprovas permessas. In num u in temp vischin na basta betg. Questa verificaziun na dat nagins dretgs da funtauna.",
    inspect: "Examinar object da la funtauna",
    areaCode: "Numer UST da la vischnanca",
    checkArea: "Verifitgar territori uffizial",
    evidenceHash: "SHA-256 da la cumprova geografica verifitgada",
    validUntil: "Verificaziun valaivla fin (UTC)",
    attest:
      "Jau hai verifitgà cun la cumprova inditgada che quest object exact da la funtauna appartegna a questa vischnanca.",
    publish: "Memorisar verificaziun geografica",
    revoke: "Revocar attribuziun",
    sourceFeature: "Object exact da la funtauna",
    existingBindings: "Verificaziuns existentas",
    noBindings: "Naginas verificaziuns d’attribuziun.",
  },
};
