import type { Locale } from "./i18n";

export const riverAttribution: Record<Locale, string> = {
  "en-CH":
    "Federal Office for the Environment (FOEN) · Hydrological observations",
  "de-CH": "Bundesamt für Umwelt (BAFU) · Hydrologische Beobachtungen",
  "fr-CH":
    "Office fédéral de l’environnement (OFEV) · Observations hydrologiques",
  "it-CH": "Ufficio federale dell’ambiente (UFAM) · Osservazioni idrologiche",
  "rm-CH": "Uffizi federal d’ambient (UFAM) · Observaziuns idrologicas",
};

const en = {
  title: "River / Lake Watch",
  intro:
    "Private monitoring of official station readings and flood danger levels. Changes appear here; email is not enabled.",
  create: "Create monitor",
  name: "Monitor name",
  station: "Station or waterbody",
  search: "Search stations",
  choose: "Choose a station",
  metrics: "Measurements",
  W: "Water level",
  Q: "Discharge",
  WT: "Water temperature",
  danger: "Official station danger",
  rules: "Your thresholds",
  add: "Add threshold",
  remove: "Remove",
  absolute: "Above",
  rise: "Rise over a window",
  threshold: "Threshold",
  unit: "Unit",
  window: "Window (minutes)",
  datum:
    "Water level is elevation in metres above sea level at this station, not water depth. Use centimetres only for a rise.",
  preview: "Preview official data",
  save: "Save draft",
  saveEdit: "Save settings",
  cancel: "Cancel",
  start: "Start monitoring",
  pause: "Pause",
  resume: "Resume",
  archive: "Archive",
  edit: "Edit settings",
  delete: "Delete monitor",
  confirm: "Delete this private monitor, settings and change history?",
  refresh: "Refresh saved results",
  loading: "Loading…",
  empty: "No private monitors yet.",
  failed: "The request failed. Refresh and try again.",
  conflict: "The monitor changed. Refresh before continuing.",
  invalid: "Choose a station, name and measurements, and check each threshold.",
  unavailable:
    "Current official data is unavailable. Try the preview again later.",
  readonly:
    "Your role can read saved monitors. An administrator can create or change them.",
  current: "Current",
  stale: "Stale",
  unknown: "Unknown",
  draft: "Draft",
  active: "Active",
  paused: "Paused",
  archived: "Archived",
  ready: "Current data",
  partial_unknown: "Some data unavailable",
  waiting: "Waiting for a check",
  access_unavailable: "Access unavailable",
  access_or_source_unavailable: "Access or source unavailable",
  changes: "Change history",
  measurements: "Measurement history",
  settings: "Settings history",
  more: "Load more",
  noChanges: "No material changes yet.",
  source: "Official source",
  time: "Source time",
  quality: "Validation",
  validation_not_supplied: "Not supplied by source",
  provisional: "Provisional",
  validated: "Validated",
  definitive: "Definitive",
  revision: "Revision",
  priority: "Priority",
  development: "Development",
  threshold_crossed: "Threshold crossed",
  threshold_cleared: "Threshold cleared",
  danger_escalation: "Official danger increased",
  danger_downgrade: "Official danger decreased",
  reviewed: "Reviewed",
  not_relevant: "Not relevant",
  continue: "Continue monitoring",
  action_required: "Action required",
  recovered: "Recovered historical change",
  review: "Review",
  gap: "There is a gap in source history; missing states are unknown.",
  limits:
    "Readings are retained for 30 days. Recovery covers up to 12 hours of measurements. Official danger is the published station state; regional warnings and forecasts are separate products.",
};
type Copy = Record<keyof typeof en, string>;
export const riverCopy: Record<Locale, Copy> = {
  "en-CH": en,
  "de-CH": {
    title: "Fluss- / See-Monitoring",
    intro:
      "Privates Monitoring amtlicher Stationsmessungen und Hochwassergefahrenstufen. Änderungen erscheinen hier; E-Mail ist nicht aktiviert.",
    create: "Monitoring erstellen",
    name: "Name",
    station: "Station oder Gewässer",
    search: "Stationen suchen",
    choose: "Station auswählen",
    metrics: "Messgrössen",
    W: "Wasserstand",
    Q: "Abfluss",
    WT: "Wassertemperatur",
    danger: "Amtliche Stationsgefahr",
    rules: "Ihre Schwellenwerte",
    add: "Schwelle hinzufügen",
    remove: "Entfernen",
    absolute: "Über",
    rise: "Anstieg im Zeitfenster",
    threshold: "Schwellenwert",
    unit: "Einheit",
    window: "Zeitfenster (Minuten)",
    datum:
      "Der Wasserstand ist die Höhe in Metern über Meer an dieser Station, nicht die Wassertiefe. Zentimeter gelten nur für einen Anstieg.",
    preview: "Amtliche Daten prüfen",
    save: "Entwurf speichern",
    saveEdit: "Einstellungen speichern",
    cancel: "Abbrechen",
    start: "Monitoring starten",
    pause: "Pausieren",
    resume: "Fortsetzen",
    archive: "Archivieren",
    edit: "Einstellungen ändern",
    delete: "Monitoring löschen",
    confirm:
      "Dieses private Monitoring samt Einstellungen und Änderungshistorie löschen?",
    refresh: "Gespeicherte Ergebnisse aktualisieren",
    loading: "Wird geladen…",
    empty: "Noch kein privates Monitoring.",
    failed:
      "Die Anfrage ist fehlgeschlagen. Aktualisieren und erneut versuchen.",
    conflict: "Das Monitoring wurde geändert. Bitte zuerst aktualisieren.",
    invalid: "Station, Name, Messgrössen und Schwellenwerte prüfen.",
    unavailable:
      "Aktuelle amtliche Daten sind nicht verfügbar. Vorschau später erneut versuchen.",
    readonly:
      "Ihre Rolle kann gespeicherte Monitorings lesen. Änderungen erfordern eine Administratorrolle.",
    current: "Aktuell",
    stale: "Veraltet",
    unknown: "Unbekannt",
    draft: "Entwurf",
    active: "Aktiv",
    paused: "Pausiert",
    archived: "Archiviert",
    ready: "Aktuelle Daten",
    partial_unknown: "Daten teilweise nicht verfügbar",
    waiting: "Prüfung ausstehend",
    access_unavailable: "Zugriff nicht verfügbar",
    access_or_source_unavailable: "Zugriff oder Quelle nicht verfügbar",
    changes: "Änderungshistorie",
    measurements: "Messhistorie",
    settings: "Einstellungsverlauf",
    more: "Mehr laden",
    noChanges: "Noch keine wesentlichen Änderungen.",
    source: "Amtliche Quelle",
    time: "Quellzeit",
    quality: "Validierung",
    validation_not_supplied: "Von der Quelle nicht angegeben",
    provisional: "Provisorisch",
    validated: "Validiert",
    definitive: "Definitiv",
    revision: "Revision",
    priority: "Priorität",
    development: "Entwicklung",
    threshold_crossed: "Schwelle überschritten",
    threshold_cleared: "Schwelle unterschritten",
    danger_escalation: "Amtliche Gefahr gestiegen",
    danger_downgrade: "Amtliche Gefahr gesunken",
    reviewed: "Geprüft",
    not_relevant: "Nicht relevant",
    continue: "Weiter beobachten",
    action_required: "Handlung erforderlich",
    recovered: "Nachgelieferte historische Änderung",
    review: "Prüfen",
    gap: "Die Quellhistorie hat eine Lücke; fehlende Zustände sind unbekannt.",
    limits:
      "Messwerte bleiben 30 Tage gespeichert. Bis zu 12 Stunden Messhistorie können nachgeladen werden. Die amtliche Gefahr ist der veröffentlichte Stationszustand; regionale Warnungen und Vorhersagen sind eigene Produkte.",
  },
  "fr-CH": {
    title: "Suivi des rivières et lacs",
    intro:
      "Suivi privé des mesures officielles et des niveaux de danger de crue. Les changements apparaissent ici ; les e-mails ne sont pas activés.",
    create: "Créer un suivi",
    name: "Nom du suivi",
    station: "Station ou cours d’eau",
    search: "Rechercher une station",
    choose: "Choisir une station",
    metrics: "Mesures",
    W: "Niveau d’eau",
    Q: "Débit",
    WT: "Température de l’eau",
    danger: "Danger officiel à la station",
    rules: "Vos seuils",
    add: "Ajouter un seuil",
    remove: "Retirer",
    absolute: "Au-dessus de",
    rise: "Hausse sur une période",
    threshold: "Seuil",
    unit: "Unité",
    window: "Période (minutes)",
    datum:
      "Le niveau correspond à l’altitude en mètres au-dessus de la mer à cette station, pas à la profondeur. Les centimètres s’appliquent uniquement à une hausse.",
    preview: "Aperçu des données officielles",
    save: "Enregistrer le brouillon",
    saveEdit: "Enregistrer les paramètres",
    cancel: "Annuler",
    start: "Démarrer le suivi",
    pause: "Suspendre",
    resume: "Reprendre",
    archive: "Archiver",
    edit: "Modifier les paramètres",
    delete: "Supprimer le suivi",
    confirm:
      "Supprimer ce suivi privé, ses paramètres et son historique des changements ?",
    refresh: "Actualiser les résultats enregistrés",
    loading: "Chargement…",
    empty: "Aucun suivi privé pour le moment.",
    failed: "La demande a échoué. Actualisez puis réessayez.",
    conflict: "Le suivi a changé. Actualisez avant de continuer.",
    invalid: "Vérifiez la station, le nom, les mesures et chaque seuil.",
    unavailable:
      "Les données officielles actuelles sont indisponibles. Réessayez l’aperçu plus tard.",
    readonly:
      "Votre rôle permet de lire les suivis. Un administrateur peut les créer ou les modifier.",
    current: "Actuel",
    stale: "Ancien",
    unknown: "Inconnu",
    draft: "Brouillon",
    active: "Actif",
    paused: "Suspendu",
    archived: "Archivé",
    ready: "Données actuelles",
    partial_unknown: "Certaines données manquent",
    waiting: "En attente de vérification",
    access_unavailable: "Accès indisponible",
    access_or_source_unavailable: "Accès ou source indisponible",
    changes: "Historique des changements",
    measurements: "Historique des mesures",
    settings: "Historique des paramètres",
    more: "Charger davantage",
    noChanges: "Aucun changement important pour le moment.",
    source: "Source officielle",
    time: "Heure de la source",
    quality: "Validation",
    validation_not_supplied: "Non fournie par la source",
    provisional: "Provisoire",
    validated: "Validé",
    definitive: "Définitif",
    revision: "Révision",
    priority: "Priorité",
    development: "Évolution",
    threshold_crossed: "Seuil dépassé",
    threshold_cleared: "Retour sous le seuil",
    danger_escalation: "Hausse du danger officiel",
    danger_downgrade: "Baisse du danger officiel",
    reviewed: "Examiné",
    not_relevant: "Non pertinent",
    continue: "Poursuivre le suivi",
    action_required: "Action requise",
    recovered: "Changement historique récupéré",
    review: "Examiner",
    gap: "L’historique source présente une lacune ; les états manquants sont inconnus.",
    limits:
      "Les mesures sont conservées 30 jours. La récupération couvre au maximum 12 heures de mesures. Le danger officiel est l’état publié pour la station ; les alertes régionales et les prévisions sont des produits distincts.",
  },
  "it-CH": {
    title: "Monitoraggio di fiumi e laghi",
    intro:
      "Monitoraggio privato delle misure ufficiali e dei livelli di pericolo di piena. Le modifiche appaiono qui; le e-mail non sono attivate.",
    create: "Crea monitoraggio",
    name: "Nome",
    station: "Stazione o corso d’acqua",
    search: "Cerca stazioni",
    choose: "Scegli una stazione",
    metrics: "Misure",
    W: "Livello dell’acqua",
    Q: "Portata",
    WT: "Temperatura dell’acqua",
    danger: "Pericolo ufficiale della stazione",
    rules: "Le tue soglie",
    add: "Aggiungi soglia",
    remove: "Rimuovi",
    absolute: "Superiore a",
    rise: "Aumento in un intervallo",
    threshold: "Soglia",
    unit: "Unità",
    window: "Intervallo (minuti)",
    datum:
      "Il livello è la quota in metri sul mare presso la stazione, non la profondità. I centimetri si applicano solo a un aumento.",
    preview: "Anteprima dei dati ufficiali",
    save: "Salva bozza",
    saveEdit: "Salva impostazioni",
    cancel: "Annulla",
    start: "Avvia monitoraggio",
    pause: "Sospendi",
    resume: "Riprendi",
    archive: "Archivia",
    edit: "Modifica impostazioni",
    delete: "Elimina monitoraggio",
    confirm:
      "Eliminare questo monitoraggio privato, le impostazioni e la cronologia delle modifiche?",
    refresh: "Aggiorna risultati salvati",
    loading: "Caricamento…",
    empty: "Nessun monitoraggio privato.",
    failed: "Richiesta non riuscita. Aggiorna e riprova.",
    conflict: "Il monitoraggio è cambiato. Aggiorna prima di continuare.",
    invalid: "Controlla stazione, nome, misure e soglie.",
    unavailable:
      "I dati ufficiali attuali non sono disponibili. Riprova l’anteprima più tardi.",
    readonly:
      "Il tuo ruolo può leggere i monitoraggi. Un amministratore può crearli o modificarli.",
    current: "Attuale",
    stale: "Non aggiornato",
    unknown: "Sconosciuto",
    draft: "Bozza",
    active: "Attivo",
    paused: "Sospeso",
    archived: "Archiviato",
    ready: "Dati attuali",
    partial_unknown: "Alcuni dati non disponibili",
    waiting: "In attesa del controllo",
    access_unavailable: "Accesso non disponibile",
    access_or_source_unavailable: "Accesso o fonte non disponibile",
    changes: "Cronologia delle modifiche",
    measurements: "Cronologia delle misure",
    settings: "Cronologia delle impostazioni",
    more: "Carica altro",
    noChanges: "Nessuna modifica rilevante.",
    source: "Fonte ufficiale",
    time: "Ora della fonte",
    quality: "Validazione",
    validation_not_supplied: "Non fornita dalla fonte",
    provisional: "Provvisorio",
    validated: "Validato",
    definitive: "Definitivo",
    revision: "Revisione",
    priority: "Priorità",
    development: "Evoluzione",
    threshold_crossed: "Soglia superata",
    threshold_cleared: "Rientro sotto soglia",
    danger_escalation: "Pericolo ufficiale aumentato",
    danger_downgrade: "Pericolo ufficiale diminuito",
    reviewed: "Esaminato",
    not_relevant: "Non pertinente",
    continue: "Continua monitoraggio",
    action_required: "Azione necessaria",
    recovered: "Modifica storica recuperata",
    review: "Esamina",
    gap: "La cronologia della fonte presenta una lacuna; gli stati mancanti sono sconosciuti.",
    limits:
      "Le misure sono conservate per 30 giorni. Il recupero copre fino a 12 ore di misure. Il pericolo ufficiale è lo stato pubblicato per la stazione; allerte regionali e previsioni sono prodotti separati.",
  },
  "rm-CH": {
    title: "Surveglianza da flums e lais",
    intro:
      "Surveglianza privata da mesiraziuns uffizialas e stgalims da privel d’aua gronda. Las midadas cumparan qua; e-mails n’èn betg activads.",
    create: "Crear surveglianza",
    name: "Num",
    station: "Staziun u aua",
    search: "Tschertgar staziuns",
    choose: "Tscherner ina staziun",
    metrics: "Mesiraziuns",
    W: "Nivel da l’aua",
    Q: "Deflussiun",
    WT: "Temperatura da l’aua",
    danger: "Privel uffizial da la staziun",
    rules: "Vossas limitas",
    add: "Agiuntar limita",
    remove: "Allontanar",
    absolute: "Sur",
    rise: "Augment en in interval",
    threshold: "Limita",
    unit: "Unitad",
    window: "Interval (minutas)",
    datum:
      "Il nivel è l’autezza en meters sur mar a questa staziun, betg la profunditad. Centimeters valan mo per in augment.",
    preview: "Prevista da datas uffizialas",
    save: "Memorisar sboz",
    saveEdit: "Memorisar parameters",
    cancel: "Interrumper",
    start: "Cumenzar surveglianza",
    pause: "Far pausa",
    resume: "Cuntinuar",
    archive: "Archivar",
    edit: "Midar parameters",
    delete: "Stizzar surveglianza",
    confirm:
      "Stizzar questa surveglianza privata, ils parameters e l’istorgia da midadas?",
    refresh: "Actualisar resultats memorisads",
    loading: "Chargiar…",
    empty: "Anc nagina surveglianza privata.",
    failed:
      "La dumonda n’è betg reussida. Actualisai ed empruvai anc ina giada.",
    conflict: "La surveglianza è sa midada. Actualisai avant che cuntinuar.",
    invalid: "Controllai staziun, num, mesiraziuns e limitas.",
    unavailable:
      "Datas uffizialas actualas n’èn betg disponiblas. Empruvai la prevista pli tard.",
    readonly:
      "Vossa rolla po leger surveglianzas. In administratur po crear u midar ellas.",
    current: "Actual",
    stale: "Vegliandà",
    unknown: "Nunenconuschent",
    draft: "Sboz",
    active: "Activ",
    paused: "En pausa",
    archived: "Archivà",
    ready: "Datas actualas",
    partial_unknown: "Datas parzialmain indisponiblas",
    waiting: "Spetgar controlla",
    access_unavailable: "Access indisponibel",
    access_or_source_unavailable: "Access u funtauna indisponibla",
    changes: "Istorgia da midadas",
    measurements: "Istorgia da mesiraziuns",
    settings: "Istorgia dals parameters",
    more: "Chargiar dapli",
    noChanges: "Anc naginas midadas relevantas.",
    source: "Funtauna uffiziala",
    time: "Temp da la funtauna",
    quality: "Validaziun",
    validation_not_supplied: "Betg inditgà da la funtauna",
    provisional: "Provisoric",
    validated: "Validà",
    definitive: "Definitiv",
    revision: "Revisiun",
    priority: "Prioritad",
    development: "Svilup",
    threshold_crossed: "Limita surpassada",
    threshold_cleared: "Puspè sut la limita",
    danger_escalation: "Privel uffizial augmentà",
    danger_downgrade: "Privel uffizial sa reducì",
    reviewed: "Examinà",
    not_relevant: "Betg relevant",
    continue: "Cuntinuar surveglianza",
    action_required: "Acziun necessaria",
    recovered: "Midada istorica recuperada",
    review: "Examinar",
    gap: "L’istorgia da la funtauna ha ina largia; ils stadis mancants èn nunenconuschents.",
    limits:
      "Las mesiraziuns vegnan conservadas 30 dis. La recuperaziun cuvra fin a 12 uras. Il privel uffizial è il stadi publitgà da la staziun; avertiments regiunals e prognosas èn products separads.",
  },
};
