import type { Locale } from "./i18n";
const en = {
  title: "River / Lake changes",
  body: "Latest retained change for each development in your monitors. These are recorded observations, not a live water-safety assessment. Empty results do not mean safe conditions.",
  all: "All latest changes",
  unreviewed: "Unreviewed",
  empty: "No retained changes match this view.",
  previous: "Previous recorded reading",
  reading: "Recorded reading",
  detected: "Detected",
  recent: "Recent recorded sample",
  stale: "Older recorded sample",
  future: "Source time is in the future",
  evidence: "Open exact evidence",
  historical: "This change belongs to earlier monitor settings.",
  corrected: "Corrected source reading",
  back: "Previous page",
  next: "Next page",
  baseline: "No previous reading is recorded.",
  station: "Station",
  scope: "These River changes are private to you.",
};
type Copy = Record<keyof typeof en, string>;
export const riverTodayCopy: Record<Locale, Copy> = {
  "en-CH": en,
  "de-CH": {
    title: "Fluss- / See-Änderungen",
    body: "Letzte gespeicherte Änderung je Entwicklung Ihrer Monitorings. Dies sind aufgezeichnete Beobachtungen, keine aktuelle Beurteilung der Wassersicherheit. Leere Ergebnisse bedeuten keine sicheren Bedingungen.",
    all: "Alle letzten Änderungen",
    unreviewed: "Ungeprüft",
    empty: "Keine gespeicherten Änderungen entsprechen dieser Ansicht.",
    previous: "Vorheriger gespeicherter Messwert",
    reading: "Gespeicherter Messwert",
    detected: "Erkannt",
    recent: "Kürzlich gespeicherter Messwert",
    stale: "Älterer gespeicherter Messwert",
    future: "Quellzeit liegt in der Zukunft",
    evidence: "Exakten Beleg öffnen",
    historical: "Diese Änderung gehört zu früheren Monitoring-Einstellungen.",
    corrected: "Korrigierter Quellmesswert",
    back: "Vorherige Seite",
    next: "Nächste Seite",
    baseline: "Kein vorheriger Messwert gespeichert.",
    station: "Station",
    scope: "Diese Flussänderungen sind nur für Sie sichtbar.",
  },
  "fr-CH": {
    title: "Changements des rivières et lacs",
    body: "Dernier changement conservé par évolution de vos suivis. Il s’agit d’observations enregistrées, pas d’une évaluation en direct de la sécurité de l’eau. Des résultats vides ne signifient pas que les conditions sont sûres.",
    all: "Tous les derniers changements",
    unreviewed: "Non examinés",
    empty: "Aucun changement conservé ne correspond à cette vue.",
    previous: "Mesure précédente enregistrée",
    reading: "Mesure enregistrée",
    detected: "Détecté",
    recent: "Mesure récente enregistrée",
    stale: "Mesure ancienne enregistrée",
    future: "L’heure de la source est dans le futur",
    evidence: "Ouvrir la preuve exacte",
    historical: "Ce changement relève d’anciens paramètres du suivi.",
    corrected: "Mesure source corrigée",
    back: "Page précédente",
    next: "Page suivante",
    baseline: "Aucune mesure précédente enregistrée.",
    station: "Station",
    scope: "Ces changements sont privés et visibles uniquement par vous.",
  },
  "it-CH": {
    title: "Cambiamenti di fiumi e laghi",
    body: "Ultimo cambiamento conservato per ogni sviluppo dei tuoi monitoraggi. Sono osservazioni registrate, non una valutazione in diretta della sicurezza dell’acqua. Risultati vuoti non significano condizioni sicure.",
    all: "Tutti gli ultimi cambiamenti",
    unreviewed: "Da esaminare",
    empty: "Nessun cambiamento conservato corrisponde a questa vista.",
    previous: "Misurazione precedente registrata",
    reading: "Misurazione registrata",
    detected: "Rilevato",
    recent: "Misurazione recente registrata",
    stale: "Misurazione meno recente registrata",
    future: "L’ora della fonte è nel futuro",
    evidence: "Apri la prova esatta",
    historical:
      "Questo cambiamento appartiene a impostazioni precedenti del monitoraggio.",
    corrected: "Misurazione della fonte corretta",
    back: "Pagina precedente",
    next: "Pagina successiva",
    baseline: "Nessuna misurazione precedente registrata.",
    station: "Stazione",
    scope: "Questi cambiamenti sono privati e visibili solo a te.",
  },
  "rm-CH": {
    title: "Midadas da flums e lais",
    body: "Ultima midada conservada per mintga svilup da Voss monitorings. Quai èn observaziuns registradas, betg ina valitaziun actuala da la segirezza da l’aua. Resultats vids na signifitgan betg cundiziuns segiras.",
    all: "Tut las ultimas midadas",
    unreviewed: "Betg examinà",
    empty: "Naginas midadas conservadas correspundan a questa vista.",
    previous: "Mesiraziun precedenta registrada",
    reading: "Mesiraziun registrada",
    detected: "Constatà",
    recent: "Mesiraziun recenta registrada",
    stale: "Mesiraziun pli veglia registrada",
    future: "Il temp da la funtauna è en il futur",
    evidence: "Avrir la cumprova exacta",
    historical:
      "Questa midada tutga tar configuraziuns anteriuras dal monitoring.",
    corrected: "Mesiraziun da la funtauna curregida",
    back: "Pagina precedenta",
    next: "Proxima pagina",
    baseline: "Nagina mesiraziun precedenta registrada.",
    station: "Staziun",
    scope: "Questas midadas èn privatas e visiblas mo per Vus.",
  },
};
