import type { Locale } from "./i18n";

const languages: Locale[] = ["de-CH", "fr-CH", "it-CH", "rm-CH", "en-CH"];
// Columns: German, French, Italian, Romansh, English.
const words = {
  recurring: [
    "Wiederkehrender Zeitraum der Quelle. Angezeigt wird das aktuelle oder nächste gültige Zeitfenster in Schweizer Ortszeit. Sein Ende bestätigt keine freie Strasse.",
    "Période récurrente de la source. Le créneau actuel ou suivant est affiché à l’heure suisse. Sa fin ne confirme pas que la route est libre.",
    "Periodo ricorrente della fonte. È mostrato l’intervallo valido attuale o successivo nell’ora svizzera. La sua fine non conferma che la strada sia libera.",
    "Perioda recurrenta da la funtauna. La fanestra valaivla actuala u proxima vegn mussada en l’ura svizra. Sia fin na conferma betg ina via libra.",
    "Recurring source period. The current or next valid window is shown in Swiss local time. Its end does not confirm a clear road.",
  ],
  impactScope: [
    "Prüfen Sie Warnungen für Ihre Orte, aktuelle Routensperrungen und Belege für Änderungen, die Ihre beobachteten Erlasse betreffen.",
    "Examinez les alertes pour vos lieux, les fermetures actuelles de vos itinéraires et les preuves des changements concernant les actes suivis.",
    "Esamina gli avvisi per i tuoi luoghi, le chiusure attuali dei percorsi e le prove dei cambiamenti che riguardano gli atti monitorati.",
    "Controllai avertiments per Voss lieus, serradas actualas da Vossas rutas e cumprovas da midadas che pertutgan ils relaschs survegliads.",
    "Review warnings for your places, current route closures and evidence for changes affecting monitored laws.",
  ],
  inbox: [
    "Private Strassensperrungen",
    "Fermetures sur vos routes privées",
    "Chiusure sui tuoi percorsi privati",
    "Serradas sin Vossas rutas privatas",
    "Closures on your private routes",
  ],
  inboxScope: [
    "Aktuelle, bestätigte Sperrungen auf Ihren aktiven Routen. Lesen und Stummschalten gelten auch für Heute; die Rechtsfilter unten gelten für die übrigen Ereignisse.",
    "Fermetures actuelles confirmées sur vos itinéraires actifs. Lecture et masquage s’appliquent aussi à Aujourd’hui ; les filtres juridiques ci-dessous concernent les autres événements.",
    "Chiusure attuali confermate sui percorsi attivi. Lettura e silenziamento valgono anche per Oggi; i filtri giuridici sotto riguardano gli altri eventi.",
    "Serradas actualas confermadas sin Vossas rutas activas. Leger e metter sin mut vala er per Oz; ils filters giuridics sutvart pertutgan ils auters eveniments.",
    "Current confirmed closures on your active routes. Read and mute also apply to Today; the legal filters below apply to the other events.",
  ],
  inboxEmpty: [
    "Keine ungeprüften aktuellen Sperrungen auf dieser Seite. Dies bestätigt keine freie Strasse.",
    "Aucune fermeture actuelle non examinée sur cette page. Cela ne confirme pas que la route est libre.",
    "Nessuna chiusura attuale non esaminata in questa pagina. Ciò non conferma che la strada sia libera.",
    "Naginas serradas actualas betg controlladas sin questa pagina. Quai na conferma betg ina via libra.",
    "No unread current closures on this page. This does not confirm a clear road.",
  ],
  inboxUnverified: [
    "Ein Teil der Routen oder Änderungen ist noch nicht aktuell verifiziert. Öffnen Sie Road Watch, um Datenzugang und letzte Änderungen zu prüfen.",
    "Une partie des itinéraires ou changements n’est pas vérifiée à jour. Ouvrez Road Watch pour examiner l’accès aux données et les dernières modifications.",
    "Alcuni percorsi o cambiamenti non sono verificati e aggiornati. Apri Road Watch per controllare l’accesso ai dati e le ultime modifiche.",
    "Ina part da las rutas u midadas n’è betg verifitgada actualmain. Avri Road Watch per controllar l’access a las datas e las ultimas midadas.",
    "Some routes or changes could not be verified as current. Open Road Watch to check data access and the latest changes.",
  ],
  today: [
    "Neue Änderungen auf Ihren Routen",
    "Nouveaux changements sur vos trajets",
    "Nuove modifiche sui tuoi percorsi",
    "Novas midadas sin Voss trajects",
    "New changes on your routes",
  ],
  why: [
    "Warum Sie dies sehen",
    "Pourquoi cet événement apparaît",
    "Perché viene mostrato",
    "Pertge che Vus vesais quai",
    "Why you see this",
  ],
  unreadRoadChange: [
    "Eine ungelesene Änderung betrifft eine Strecke Ihrer aktiven Route.",
    "Un changement non lu concerne un tronçon de votre trajet actif.",
    "Una modifica non letta riguarda un tratto del percorso attivo.",
    "Ina midada betg legida pertutga in traject da Vossa ruta activa.",
    "An unread change affects a corridor on your active route.",
  ],
  urgent: [
    "Aktuelle Sperrung laut Quelle",
    "Fermeture actuelle signalée par la source",
    "Chiusura attuale segnalata dalla fonte",
    "Serrada actuala tenor la funtauna",
    "Current closure reported by source",
  ],
  todayEmpty: [
    "Keine weiteren ungelesenen Änderungen auf dieser Seite.",
    "Aucun autre changement non lu sur cette page.",
    "Nessun’altra modifica non letta in questa pagina.",
    "Naginas ulteriuras midadas betg legidas sin questa pagina.",
    "No further unread changes on this page.",
  ],
  selectedChange: [
    "Ausgewählte Änderung",
    "Changement sélectionné",
    "Modifica selezionata",
    "Midada tschernida",
    "Selected change",
  ],
  beforeChange: [
    "Vor dieser Änderung",
    "Avant ce changement",
    "Prima della modifica",
    "Avant questa midada",
    "Before this change",
  ],
  noPrevious: [
    "Keine frühere Version gespeichert.",
    "Aucune version précédente enregistrée.",
    "Nessuna versione precedente salvata.",
    "Nagina versiun precedenta memorisada.",
    "No earlier version was saved.",
  ],
  latestKnown: [
    "Letzter bekannter Stand",
    "Dernier état connu",
    "Ultimo stato noto",
    "Ultim stadi enconuschent",
    "Latest known state",
  ],
  newerAvailable: [
    "Seit der verlinkten Änderung liegt eine neuere Version vor.",
    "Une version plus récente existe depuis le changement lié.",
    "Esiste una versione più recente rispetto alla modifica collegata.",
    "Dapi la midada colliada datti ina versiun pli nova.",
    "A newer version exists since the linked change.",
  ],
  oldConfiguration: [
    "Diese Änderung stammt aus früheren Routeneinstellungen.",
    "Ce changement provient d’anciens paramètres du trajet.",
    "Questa modifica deriva da impostazioni precedenti del percorso.",
    "Questa midada deriva da parameters precedents dal traject.",
    "This change belongs to earlier route settings.",
  ],
  linkUnavailable: [
    "Diese verlinkte Änderung ist nicht verfügbar. Öffnen Sie Ihre Route erneut.",
    "Ce changement lié est indisponible. Ouvrez à nouveau votre trajet.",
    "La modifica collegata non è disponibile. Riapri il percorso.",
    "Questa midada colliada n’è betg disponibla. Avri danovamain Voss traject.",
    "This linked change is unavailable. Open your route again.",
  ],
  title: [
    "Strassenüberwachung",
    "Surveillance routière",
    "Monitoraggio stradale",
    "Surveglianza da vias",
    "Road Watch",
  ],
  intro: [
    "Speichern Sie Ihre Strecken und Fahrtrichtungen. Die Vorschau prüft den Datenzugang; Start beginnt die Überwachung.",
    "Enregistrez vos tronçons et sens de circulation. L’aperçu vérifie l’accès aux données ; Démarrer lance la surveillance.",
    "Salva tratti e direzioni. L’anteprima verifica l’accesso ai dati; Avvia inizia il monitoraggio.",
    "Memorisai ils trajects e las direcziuns. La prevista controllescha l’access a las datas; Avviar cumenza la surveglianza.",
    "Save your corridors and directions. Preview checks data access; Start begins monitoring.",
  ],
  create: [
    "Route hinzufügen",
    "Ajouter un trajet",
    "Aggiungi percorso",
    "Agiuntar in traject",
    "Add route",
  ],
  name: [
    "Name Ihrer Route",
    "Nom de votre trajet",
    "Nome del percorso",
    "Num dal traject",
    "Your route name",
  ],
  corridors: [
    "Strecken und Fahrtrichtungen",
    "Tronçons et sens de circulation",
    "Tratti e direzioni",
    "Trajects e direcziuns",
    "Corridors and directions",
  ],
  catalogHelp: [
    "Wählen Sie bis zu acht geprüfte Strecken. Das Verzeichnis zeigt nur verfügbare, freigegebene Einträge.",
    "Choisissez jusqu’à huit tronçons vérifiés. Le catalogue affiche uniquement les entrées disponibles et autorisées.",
    "Scegli fino a otto tratti verificati. Il catalogo mostra solo le voci disponibili e autorizzate.",
    "Tscherni fin otg trajects controllads. Il catalog mussa mo endataziuns disponiblas ed autorisadas.",
    "Choose up to eight reviewed corridors. The catalogue shows only available, permitted entries.",
  ],
  search: [
    "Strecke suchen",
    "Rechercher un tronçon",
    "Cerca un tratto",
    "Tschertgar in traject",
    "Search corridors",
  ],
  selected: [
    "Ausgewählte Strecken",
    "Tronçons sélectionnés",
    "Tratti selezionati",
    "Trajects tschernids",
    "Selected corridors",
  ],
  removeSelection: [
    "Auswahl entfernen",
    "Retirer la sélection",
    "Rimuovi selezione",
    "Allontanar la selecziun",
    "Remove selection",
  ],
  eventTypes: [
    "Wichtige Ereignisse",
    "Événements importants",
    "Eventi importanti",
    "Eveniments impurtants",
    "Important events",
  ],
  delay: [
    "Mindestverzögerung bei Stau (Minuten)",
    "Retard minimal en cas de bouchon (minutes)",
    "Ritardo minimo per code (minuti)",
    "Retard minimal en cas da colonnas (minutas)",
    "Minimum congestion delay (minutes)",
  ],
  delayHelp: [
    "Dieser Grenzwert gilt nur für gemessene Verzögerungen. Ausgewählte Sperrungen bleiben auch ohne Verzögerungswert relevant.",
    "Ce seuil concerne uniquement les retards connus. Les fermetures sélectionnées restent pertinentes sans retard chiffré.",
    "La soglia riguarda solo i ritardi noti. Le chiusure selezionate restano rilevanti senza un ritardo numerico.",
    "Questa limita vala mo per retards enconuschents. Serradas tschernidas restan relevantas era senza ina valur da retard.",
    "This threshold applies only to known delays. Selected closures remain relevant without a numeric delay.",
  ],
  planned: [
    "Geplante Ereignisse einschliessen",
    "Inclure les événements prévus",
    "Includi eventi pianificati",
    "Includer eveniments planisads",
    "Include planned events",
  ],
  preview: [
    "Vorschau prüfen",
    "Vérifier l’aperçu",
    "Verifica anteprima",
    "Controllar la prevista",
    "Check preview",
  ],
  ready: [
    "Diese Route kann gestartet werden.",
    "Ce trajet peut être démarré.",
    "Questo percorso può essere avviato.",
    "Quest traject po vegnir avià.",
    "This route can be started.",
  ],
  sourceOff: [
    "Für diese Auswahl sind noch keine aktuellen, freigegebenen Daten verfügbar.",
    "Les données actuelles autorisées ne sont pas encore disponibles pour cette sélection.",
    "I dati aggiornati e autorizzati non sono ancora disponibili per questa selezione.",
    "Datas actualas ed autorisadas n’èn anc betg disponiblas per questa selecziun.",
    "Current permitted data is not yet available for this selection.",
  ],
  unavailable: [
    "Nicht verfügbar",
    "Indisponible",
    "Non disponibile",
    "Betg disponibel",
    "Unavailable",
  ],
  save: [
    "Privat speichern",
    "Enregistrer en privé",
    "Salva privatamente",
    "Memorisar privat",
    "Save privately",
  ],
  cancel: ["Abbrechen", "Annuler", "Annulla", "Interrumper", "Cancel"],
  edit: ["Bearbeiten", "Modifier", "Modifica", "Modifitgar", "Edit"],
  start: ["Start", "Démarrer", "Avvia", "Avviar", "Start"],
  pause: ["Pausieren", "Suspendre", "Metti in pausa", "Far ina pausa", "Pause"],
  resume: ["Fortsetzen", "Reprendre", "Riprendi", "Cuntinuar", "Resume"],
  archive: ["Archivieren", "Archiver", "Archivia", "Archivar", "Archive"],
  remove: [
    "Route löschen",
    "Supprimer le trajet",
    "Elimina percorso",
    "Stizzar il traject",
    "Delete route",
  ],
  confirmDelete: [
    "Route und private Historie endgültig löschen?",
    "Supprimer définitivement ce trajet et son historique privé ?",
    "Eliminare definitivamente il percorso e la cronologia privata?",
    "Stizzar definitivamain il traject e sia cronologia privata?",
    "Permanently delete this route and its private history?",
  ],
  refresh: ["Aktualisieren", "Actualiser", "Aggiorna", "Actualisar", "Refresh"],
  loading: [
    "Wird geladen…",
    "Chargement…",
    "Caricamento…",
    "Chargiar…",
    "Loading…",
  ],
  failed: [
    "Die Anfrage konnte nicht abgeschlossen werden. Versuchen Sie es erneut.",
    "La demande n’a pas pu aboutir. Réessayez.",
    "Impossibile completare la richiesta. Riprova.",
    "La dumonda n’ha betg pudì vegnir terminada. Empruvai anc ina giada.",
    "The request could not be completed. Try again.",
  ],
  conflict: [
    "Die Route wurde geändert. Aktualisieren Sie sie vor der nächsten Änderung.",
    "Le trajet a changé. Actualisez-le avant de le modifier.",
    "Il percorso è cambiato. Aggiornalo prima di modificarlo.",
    "Il traject è vegnì midà. Actualisai el avant la proxima midada.",
    "The route changed. Refresh it before making another change.",
  ],
  featureOff: [
    "Die Strassenüberwachung ist derzeit nicht verfügbar.",
    "La surveillance routière est actuellement indisponible.",
    "Il monitoraggio stradale non è attualmente disponibile.",
    "La surveglianza da vias n’è actualmain betg disponibla.",
    "Road Watch is currently unavailable.",
  ],
  empty: [
    "Noch keine gespeicherten Routen.",
    "Aucun trajet enregistré.",
    "Nessun percorso salvato.",
    "Anc nagins trajects memorisads.",
    "No saved routes yet.",
  ],
  noCatalog: [
    "Keine verfügbaren Strecken auf dieser Seite.",
    "Aucun tronçon disponible sur cette page.",
    "Nessun tratto disponibile in questa pagina.",
    "Nagins trajects disponibels sin questa pagina.",
    "No available corridors on this page.",
  ],
  noEvents: [
    "Keine erfassten Änderungen auf dieser Seite. Dies bestätigt keine freie Fahrt.",
    "Aucun changement enregistré sur cette page. Cela ne confirme pas que la route est libre.",
    "Nessuna modifica registrata in questa pagina. Non è una conferma di strada libera.",
    "Naginas midadas registradas sin questa pagina. Quai na conferma betg ina via libra.",
    "No recorded changes on this page. This does not confirm a clear road.",
  ],
  more: [
    "Nächste Seite",
    "Page suivante",
    "Pagina successiva",
    "Proxima pagina",
    "Next page",
  ],
  previous: [
    "Vorherige Seite",
    "Page précédente",
    "Pagina precedente",
    "Pagina precedenta",
    "Previous page",
  ],
  history: [
    "Ereignisverlauf",
    "Historique de l’événement",
    "Cronologia dell’evento",
    "Cronologia da l’eveniment",
    "Event history",
  ],
  revisions: [
    "Gespeicherte Einstellungen",
    "Paramètres enregistrés",
    "Impostazioni salvate",
    "Parameters memorisads",
    "Saved settings history",
  ],
  events: [
    "Änderungen auf Ihrer Route",
    "Changements sur votre trajet",
    "Modifiche sul percorso",
    "Midadas sin Voss traject",
    "Changes on your route",
  ],
  review: [
    "Als gelesen markieren",
    "Marquer comme lu",
    "Segna come letto",
    "Marcar sco legì",
    "Mark as read",
  ],
  mute: [
    "Ereignis stummschalten",
    "Mettre l’événement en sourdine",
    "Silenzia evento",
    "Silenziar l’eveniment",
    "Mute event",
  ],
  unmute: [
    "Stummschaltung aufheben",
    "Réactiver l’événement",
    "Riattiva evento",
    "Reactivar l’eveniment",
    "Unmute event",
  ],
  unread: [
    "Neue Änderung",
    "Nouveau changement",
    "Nuova modifica",
    "Nova midada",
    "New change",
  ],
  reviewed: ["Gelesen", "Lu", "Letto", "Legì", "Read"],
  readonly: [
    "Ihre Rolle erlaubt das Lesen gespeicherter Routen.",
    "Votre rôle permet de consulter les trajets enregistrés.",
    "Il tuo ruolo consente di leggere i percorsi salvati.",
    "Vossa rolla permetta da leger trajects memorisads.",
    "Your role allows reading saved routes.",
  ],
  source: ["Quelle", "Source", "Fonte", "Funtauna", "Source"],
  time: [
    "Zeit (Europe/Zurich)",
    "Heure (Europe/Zurich)",
    "Ora (Europe/Zurich)",
    "Temp (Europe/Zurich)",
    "Time (Europe/Zurich)",
  ],
  version: ["Version", "Version", "Versione", "Versiun", "Version"],
  minutes: ["Minuten", "minutes", "minuti", "minutas", "minutes"],
  lanesRestricted: [
    "Betroffene Fahrstreifen",
    "Voies restreintes",
    "Corsie limitate",
    "Vials restrenschids",
    "Restricted lanes",
  ],
  lanesOperational: [
    "Offene Fahrstreifen laut Quelle",
    "Voies ouvertes selon la source",
    "Corsie aperte secondo la fonte",
    "Vials averts tenor la funtauna",
    "Operational lanes reported by source",
  ],
  accessChanged: [
    "Ihr Zugriff hat sich geändert. Aktualisieren Sie die Seite, um ihn erneut zu prüfen.",
    "Votre accès a changé. Actualisez la page pour le vérifier.",
    "Il tuo accesso è cambiato. Aggiorna la pagina per verificarlo.",
    "Voss access è sa midà. Actualisai la pagina per al controllar.",
    "Your access changed. Refresh the page to check it again.",
  ],
  validFrom: ["Ab", "Dès", "Dal", "A partir da", "From"],
  validUntil: ["Bis", "Jusqu’au", "Fino al", "Fin ils", "Until"],
  noEnd: [
    "Kein Endzeitpunkt angegeben",
    "Aucune fin précisée",
    "Nessuna fine indicata",
    "Nagina fin inditgada",
    "No end time supplied",
  ],
  unknown: [
    "Unbekannt",
    "Inconnu",
    "Sconosciuto",
    "Nunenconuschent",
    "Unknown",
  ],
} as const;
const statuses = {
  draft: ["Entwurf", "Brouillon", "Bozza", "Sboz", "Draft"],
  active: ["Aktiv", "Actif", "Attivo", "Activ", "Active"],
  paused: ["Pausiert", "En pause", "In pausa", "En pausa", "Paused"],
  archived: ["Archiviert", "Archivé", "Archiviato", "Archivà", "Archived"],
  planned: ["Geplant", "Prévu", "Pianificato", "Planisà", "Planned"],
  cleared: [
    "Quelle meldet Räumung",
    "Dégagement signalé par la source",
    "Sgombero segnalato dalla fonte",
    "La funtauna annunzia ina via libra",
    "Source reports clearance",
  ],
  possible_clearance: [
    "Mögliche Räumung gemeldet",
    "Dégagement possible signalé",
    "Possibile sgombero segnalato",
    "Via eventualmain libra annunziada",
    "Possible clearance reported",
  ],
  withdrawn: [
    "Meldung zurückgezogen",
    "Avis retiré",
    "Avviso ritirato",
    "Annunzia retratga",
    "Notice withdrawn",
  ],
  expired: [
    "Gültigkeit abgelaufen",
    "Validité expirée",
    "Validità scaduta",
    "Validitad scadida",
    "Validity expired",
  ],
  ended: [
    "Meldung beendet",
    "Avis terminé",
    "Avviso concluso",
    "Annunzia terminada",
    "Notice ended",
  ],
  suspended: [
    "Meldung ausgesetzt",
    "Avis suspendu",
    "Avviso sospeso",
    "Annunzia suspendida",
    "Notice suspended",
  ],
  not_relevant: [
    "Ausserhalb der gespeicherten Regeln",
    "Hors des règles enregistrées",
    "Fuori dalle regole salvate",
    "Ordaifer las reglas memorisadas",
    "Outside saved rules",
  ],
  unavailable: words.unavailable,
  stale: [
    "Daten veraltet",
    "Données périmées",
    "Dati obsoleti",
    "Datas antiquadas",
    "Stale data",
  ],
  ready: [
    "Daten verfügbar",
    "Données disponibles",
    "Dati disponibili",
    "Datas disponiblas",
    "Data available",
  ],
  waiting: [
    "Warten auf Prüfung",
    "En attente de vérification",
    "In attesa di verifica",
    "Spetgar sin controlla",
    "Waiting for check",
  ],
  not_started: [
    "Nicht gestartet",
    "Non démarré",
    "Non avviato",
    "Betg avià",
    "Not started",
  ],
  verified: [
    "Geprüfte Zuordnung",
    "Correspondance vérifiée",
    "Corrispondenza verificata",
    "Attribuziun controllada",
    "Verified match",
  ],
  partial: [
    "Teilweise Daten",
    "Données partielles",
    "Dati parziali",
    "Datas parzialas",
    "Partial data",
  ],
  unknown: words.unknown,
  certain: [
    "Bestätigt gemeldet",
    "Signalé comme certain",
    "Segnalato come certo",
    "Annunzià sco segir",
    "Reported as certain",
  ],
  probable: ["Wahrscheinlich", "Probable", "Probabile", "Probabel", "Probable"],
  riskOf: [
    "Mögliches Ereignis",
    "Événement possible",
    "Evento possibile",
    "Eveniment pussaivel",
    "Possible event",
  ],
  road_closure: [
    "Strassensperrung",
    "Route fermée",
    "Chiusura stradale",
    "Serrada da via",
    "Road closure",
  ],
  carriageway_closure: [
    "Fahrbahnsperrung",
    "Chaussée fermée",
    "Carreggiata chiusa",
    "Serrada da la charregiada",
    "Carriageway closure",
  ],
  lane_restriction: [
    "Fahrstreifenbeschränkung",
    "Restriction de voie",
    "Restrizione di corsia",
    "Restricziun da vial",
    "Lane restriction",
  ],
  congestion: ["Stau", "Bouchon", "Coda", "Colonna", "Congestion"],
  accident: ["Unfall", "Accident", "Incidente", "Accident", "Accident"],
  roadworks: [
    "Strassenarbeiten",
    "Travaux routiers",
    "Lavori stradali",
    "Lavurs da via",
    "Roadworks",
  ],
} as const;
export type RoadCopy = { [K in keyof typeof words]: string };
export const roadCopy = Object.fromEntries(
  languages.map((locale, i) => [
    locale,
    Object.fromEntries(
      Object.entries(words).map(([key, values]) => [key, values[i]]),
    ),
  ]),
) as Record<Locale, RoadCopy>;
export function roadLabel(locale: Locale, key: string): string {
  const value = Object.hasOwn(statuses, key)
    ? statuses[key as keyof typeof statuses][languages.indexOf(locale)]
    : undefined;
  return typeof value === "string" ? value : roadCopy[locale].unavailable;
}
