import type { Locale } from "./i18n";

const en = {
  title: "Source history",
  body: "Recorded every five minutes; retained for 30 days. Missing samples are gaps, not healthy operation. Source evidence and private decisions have separate retention rules.",
  period: "Period",
  source: "Source channel",
  day: "24 hours",
  week: "7 days",
  month: "30 days",
  metric: "Time since recorded event",
  latest: "Latest successful acquisition",
  oldest: "Oldest successful acquisition",
  publication: "Provider publication",
  boundary:
    "Bars show the largest recorded age in each hour, in seconds. Publication and acquisition timestamps may describe different records. These are not processing or delivery latency measurements.",
  chart: "Hourly recorded ages",
  gap: "Missing samples",
  samples: "Recorded / expected samples",
  hours: "Hourly detail",
  hour: "Hour",
  minimum: "Minimum seconds",
  maximum: "Maximum seconds",
  known: "Known values",
  state: "Recorded acquisition states",
  changed: "Source binding changed",
  previous: "Previous",
  next: "Next",
  page: "Page",
  empty:
    "No samples recorded for this period. History starts when the sampler runs; older activity is not reconstructed.",
  failed: "Source history could not be read. Reload to try again.",
  loading: "Loading source history…",
  permission: "Last permission state",
  collection: "Last collector state",
};
export const sourceHistoryCopy: Record<Locale, typeof en> = {
  "en-CH": en,
  "de-CH": {
    title: "Quellenverlauf",
    body: "Alle fünf Minuten erfasst und 30 Tage aufbewahrt. Fehlende Messpunkte sind Lücken, kein fehlerfreier Betrieb. Für Quellennachweise und persönliche Entscheidungen gelten eigene Aufbewahrungsregeln.",
    period: "Zeitraum",
    source: "Quellenkanal",
    day: "24 Stunden",
    week: "7 Tage",
    month: "30 Tage",
    metric: "Zeit seit dem erfassten Ereignis",
    latest: "Letzte erfolgreiche Erfassung",
    oldest: "Älteste erfolgreiche Erfassung",
    publication: "Veröffentlichung des Anbieters",
    boundary:
      "Balken zeigen das höchste erfasste Alter pro Stunde in Sekunden. Veröffentlichungs- und Erfassungszeiten können verschiedene Datensätze betreffen. Dies sind keine Verarbeitungs- oder Zustelllatenzen.",
    chart: "Stündlich erfasstes Alter",
    gap: "Fehlende Messpunkte",
    samples: "Erfasste / erwartete Messpunkte",
    hours: "Stündliche Details",
    hour: "Stunde",
    minimum: "Minimum in Sekunden",
    maximum: "Maximum in Sekunden",
    known: "Bekannte Werte",
    state: "Erfasste Zustände",
    changed: "Quellenbindung geändert",
    previous: "Zurück",
    next: "Weiter",
    page: "Seite",
    empty:
      "Keine Messpunkte für diesen Zeitraum. Der Verlauf beginnt mit der Erfassung; ältere Aktivität wird nicht rekonstruiert.",
    failed: "Der Quellenverlauf konnte nicht gelesen werden. Laden Sie erneut.",
    loading: "Quellenverlauf wird geladen…",
    permission: "Letzter Berechtigungsstatus",
    collection: "Letzter Erfassungsstatus",
  },
  "fr-CH": {
    title: "Historique des sources",
    body: "Relevés toutes les cinq minutes, conservés 30 jours. Les relevés manquants sont des lacunes, pas un fonctionnement normal. Les preuves des sources et décisions privées ont des règles de conservation distinctes.",
    period: "Période",
    source: "Canal source",
    day: "24 heures",
    week: "7 jours",
    month: "30 jours",
    metric: "Temps depuis l’événement enregistré",
    latest: "Dernière collecte réussie",
    oldest: "Plus ancienne collecte réussie",
    publication: "Publication du fournisseur",
    boundary:
      "Les barres indiquent l’âge maximal relevé par heure, en secondes. Publication et collecte peuvent concerner des enregistrements différents. Il ne s’agit pas de latences de traitement ou de livraison.",
    chart: "Âges relevés par heure",
    gap: "Relevés manquants",
    samples: "Relevés enregistrés / attendus",
    hours: "Détail horaire",
    hour: "Heure",
    minimum: "Minimum en secondes",
    maximum: "Maximum en secondes",
    known: "Valeurs connues",
    state: "États de collecte relevés",
    changed: "Source associée modifiée",
    previous: "Précédent",
    next: "Suivant",
    page: "Page",
    empty:
      "Aucun relevé pour cette période. L’historique commence avec les relevés ; l’activité antérieure n’est pas reconstruite.",
    failed: "Impossible de lire l’historique. Rechargez pour réessayer.",
    loading: "Chargement de l’historique…",
    permission: "Dernier état d’autorisation",
    collection: "Dernier état de collecte",
  },
  "it-CH": {
    title: "Cronologia delle fonti",
    body: "Rilevazioni ogni cinque minuti, conservate per 30 giorni. Le rilevazioni mancanti sono lacune, non un funzionamento regolare. Prove delle fonti e decisioni private hanno regole di conservazione separate.",
    period: "Periodo",
    source: "Canale della fonte",
    day: "24 ore",
    week: "7 giorni",
    month: "30 giorni",
    metric: "Tempo dall’evento registrato",
    latest: "Ultima raccolta riuscita",
    oldest: "Raccolta riuscita più vecchia",
    publication: "Pubblicazione del fornitore",
    boundary:
      "Le barre mostrano l’età massima registrata per ora, in secondi. Pubblicazione e raccolta possono riguardare record diversi. Non sono latenze di elaborazione o consegna.",
    chart: "Età registrate per ora",
    gap: "Rilevazioni mancanti",
    samples: "Rilevazioni registrate / previste",
    hours: "Dettaglio orario",
    hour: "Ora",
    minimum: "Minimo in secondi",
    maximum: "Massimo in secondi",
    known: "Valori noti",
    state: "Stati di raccolta registrati",
    changed: "Associazione della fonte cambiata",
    previous: "Precedente",
    next: "Successiva",
    page: "Pagina",
    empty:
      "Nessuna rilevazione per questo periodo. La cronologia inizia con le rilevazioni; l’attività precedente non viene ricostruita.",
    failed: "Impossibile leggere la cronologia. Ricarica per riprovare.",
    loading: "Caricamento della cronologia…",
    permission: "Ultimo stato del permesso",
    collection: "Ultimo stato della raccolta",
  },
  "rm-CH": {
    title: "Istorgia da las funtaunas",
    body: "Registraziuns mintga tschintg minutas, conservadas per 30 dis. Registraziuns mancantas èn largias, betg in manaschi senza problems. Cumprovas e decisiuns privatas han atgnas reglas da conservaziun.",
    period: "Perioda",
    source: "Chanal da funtauna",
    day: "24 uras",
    week: "7 dis",
    month: "30 dis",
    metric: "Temp dapi l’eveniment registrà",
    latest: "Ultima rimnada reussida",
    oldest: "La pli veglia rimnada reussida",
    publication: "Publicaziun dal purschider",
    boundary:
      "Las colonnas mussan la vegliadetgna maximala registrada per ura, en secundas. Publicaziun e rimnada pon pertutgar differentas datas. Quai n’èn betg retardaments da l’elavuraziun u da la consegna.",
    chart: "Vegliadetgna registrada per ura",
    gap: "Registraziuns mancantas",
    samples: "Registraziuns fatgas / spetgadas",
    hours: "Detagls per ura",
    hour: "Ura",
    minimum: "Minimum en secundas",
    maximum: "Maximum en secundas",
    known: "Valurs enconuschentas",
    state: "Stadis da rimnada registrads",
    changed: "Funtauna associada midada",
    previous: "Enavos",
    next: "Enavant",
    page: "Pagina",
    empty:
      "Naginas registraziuns per questa perioda. L’istorgia cumenza cun las registraziuns; activitad anteriura na vegn betg reconstruida.",
    failed: "L’istorgia na po betg vegnir legida. Chargiai danovamain.",
    loading: "Chargiar l’istorgia…",
    permission: "Ultim stadi da permissiun",
    collection: "Ultim stadi da rimnada",
  },
};
