import type { Locale } from "./i18n";

const en = {
  title: "Monitoring source operations",
  body: "Inspect the recorded source state for all nine directions. Reload reads local evidence; it does not collect data or change access.",
  boundary:
    "A current permission record or recent acquisition does not establish coverage, a valid monitor result or delivery consent. Source timestamps and successful acquisition are separate. Unknown means no comparable evidence was recorded.",
  open: "Open source and coverage workflow",
  refresh: "Reload evidence",
  loading: "Loading source evidence…",
  failed: "Source evidence could not be read. Reload to try again.",
  denied: "Platform administrator access is required.",
  checked: "Evidence checked",
  release: "Serving release",
  section: "Section switch",
  collector: "Collector configuration",
  access: "Permission record",
  expires: "Permission expires",
  acquisition: "Recorded acquisition",
  records: "Retained channel records",
  errors: "Records with failures",
  never: "Records without a successful acquisition",
  oldest: "Oldest successful acquisition",
  latest: "Latest successful acquisition",
  published: "Provider publication time",
  next: "Earliest scheduled request",
  unknown: "Unknown / not recorded",
  enabled: "Enabled",
  disabled: "Disabled",
  configured: "Configured",
  credentials_required: "Install the required source credentials",
  permission_required: "Record the reviewed source permission",
  channel_required:
    "A permitted current warning channel and native acquisition are still required",
  missing: "No configured permission record",
  expired: "Expired — review and renew access",
  revoked: "Revoked — source access unavailable",
  not_yet_valid: "Not yet valid",
  record_current: "Record is current; coverage is checked separately",
  public_contract: "Public dataset contract; inspect current dataset coverage",
  per_channel: "Inspect each channel below",
  partial: "Partial evidence",
  unobserved: "No acquisition recorded",
  recorded: "Successful acquisition recorded",
  invalid_clock: "Future source clock — check source timestamps",
  errors_state: "Acquisition failures recorded",
  trip_updates: "Trip updates",
  service_alerts: "Service alerts",
  safety_environment: "Swiss Safety & Environment",
  mobility: "Swiss Mobility",
  business_opportunities: "Swiss Business Opportunities",
  intellectual_property: "Swiss IP",
};
type Copy = typeof en;
export const sourceOperationsCopy: Record<Locale, Copy> = {
  "en-CH": en,
  "de-CH": {
    title: "Monitoring-Quellenbetrieb",
    body: "Prüfen Sie den erfassten Quellenstand aller neun Bereiche. Neuladen liest lokale Nachweise und ändert weder Datenabruf noch Zugang.",
    boundary:
      "Ein aktueller Berechtigungseintrag oder neuer Abruf belegt weder Abdeckung noch ein gültiges Monitorergebnis oder Versandzustimmung. Quellenzeit und erfolgreicher Abruf sind getrennt. Unbekannt bedeutet: kein vergleichbarer Nachweis erfasst.",
    open: "Quellen- und Abdeckungsprüfung öffnen",
    refresh: "Nachweise neu laden",
    loading: "Quellennachweise werden geladen…",
    failed: "Quellennachweise konnten nicht gelesen werden. Laden Sie erneut.",
    denied: "Plattformadministrator-Zugang erforderlich.",
    checked: "Nachweise geprüft",
    release: "Aktiver Release",
    section: "Bereichsschalter",
    collector: "Abrufkonfiguration",
    access: "Berechtigungseintrag",
    expires: "Berechtigung läuft ab",
    acquisition: "Erfasster Abruf",
    records: "Gespeicherte Kanaleinträge",
    errors: "Einträge mit Fehlern",
    never: "Einträge ohne erfolgreichen Abruf",
    oldest: "Ältester erfolgreicher Abruf",
    latest: "Neuester erfolgreicher Abruf",
    published: "Veröffentlichungszeit der Quelle",
    next: "Frühester geplanter Abruf",
    unknown: "Unbekannt / nicht erfasst",
    enabled: "Aktiviert",
    disabled: "Deaktiviert",
    configured: "Konfiguriert",
    credentials_required: "Erforderliche Quellenzugangsdaten einrichten",
    permission_required: "Geprüfte Quellenberechtigung erfassen",
    channel_required:
      "Ein erlaubter aktueller Warnkanal und dessen nativer Abruf fehlen noch",
    missing: "Kein konfigurierter Berechtigungseintrag",
    expired: "Abgelaufen — Zugang prüfen und erneuern",
    revoked: "Widerrufen — Quellenzugang nicht verfügbar",
    not_yet_valid: "Noch nicht gültig",
    record_current: "Eintrag aktuell; Abdeckung wird separat geprüft",
    public_contract: "Öffentlicher Datensatzvertrag; aktuelle Abdeckung prüfen",
    per_channel: "Jeden Kanal unten prüfen",
    partial: "Teilweise Nachweise",
    unobserved: "Kein Abruf erfasst",
    recorded: "Erfolgreicher Abruf erfasst",
    invalid_clock: "Quellenzeit liegt in der Zukunft — Zeitstempel prüfen",
    errors_state: "Abruffehler erfasst",
    trip_updates: "Fahrtaktualisierungen",
    service_alerts: "Verkehrsmeldungen",
    safety_environment: "Schweizer Sicherheit & Umwelt",
    mobility: "Schweizer Mobilität",
    business_opportunities: "Schweizer Geschäftsmöglichkeiten",
    intellectual_property: "Schweizer Schutzrechte",
  },
  "fr-CH": {
    title: "Exploitation des sources de suivi",
    body: "Consultez l’état enregistré des sources des neuf domaines. Recharger lit les preuves locales sans collecter de données ni modifier l’accès.",
    boundary:
      "Une autorisation actuelle ou une collecte récente ne prouve ni la couverture, ni un résultat valide, ni le consentement à l’envoi. Date de la source et collecte réussie sont distinctes. Inconnu signifie qu’aucune preuve comparable n’a été enregistrée.",
    open: "Ouvrir la vérification des sources et de la couverture",
    refresh: "Recharger les preuves",
    loading: "Chargement des preuves…",
    failed: "Impossible de lire les preuves. Rechargez pour réessayer.",
    denied: "Un accès administrateur de plateforme est requis.",
    checked: "Preuves vérifiées",
    release: "Version active",
    section: "Activation du domaine",
    collector: "Configuration de collecte",
    access: "Autorisation enregistrée",
    expires: "Expiration de l’autorisation",
    acquisition: "Collecte enregistrée",
    records: "Canaux conservés",
    errors: "Enregistrements en échec",
    never: "Enregistrements sans collecte réussie",
    oldest: "Plus ancienne collecte réussie",
    latest: "Dernière collecte réussie",
    published: "Date de publication du fournisseur",
    next: "Prochaine requête planifiée",
    unknown: "Inconnu / non enregistré",
    enabled: "Activé",
    disabled: "Désactivé",
    configured: "Configuré",
    credentials_required: "Configurer les identifiants requis pour la source",
    permission_required: "Enregistrer l’autorisation de source examinée",
    channel_required:
      "Un canal d’alerte actuel autorisé et sa collecte native restent nécessaires",
    missing: "Aucune autorisation configurée",
    expired: "Expirée — vérifier et renouveler l’accès",
    revoked: "Révoquée — accès indisponible",
    not_yet_valid: "Pas encore valide",
    record_current: "Autorisation actuelle ; couverture vérifiée séparément",
    public_contract:
      "Contrat du jeu de données public ; vérifier la couverture actuelle",
    per_channel: "Examiner chaque canal ci-dessous",
    partial: "Preuves partielles",
    unobserved: "Aucune collecte enregistrée",
    recorded: "Collecte réussie enregistrée",
    invalid_clock: "Date de source future — vérifier les horodatages",
    errors_state: "Échecs de collecte enregistrés",
    trip_updates: "Mises à jour des trajets",
    service_alerts: "Alertes de service",
    safety_environment: "Sécurité et environnement suisses",
    mobility: "Mobilité suisse",
    business_opportunities: "Opportunités commerciales suisses",
    intellectual_property: "Propriété intellectuelle suisse",
  },
  "it-CH": {
    title: "Operazioni delle fonti di monitoraggio",
    body: "Controlla lo stato registrato delle fonti per tutti i nove ambiti. Ricaricare legge prove locali senza raccogliere dati o modificare l’accesso.",
    boundary:
      "Un’autorizzazione attuale o un’acquisizione recente non dimostra copertura, risultati validi o consenso all’invio. Ora della fonte e acquisizione riuscita sono distinte. Sconosciuto significa che non è stata registrata una prova confrontabile.",
    open: "Apri la verifica delle fonti e della copertura",
    refresh: "Ricarica le prove",
    loading: "Caricamento delle prove…",
    failed: "Impossibile leggere le prove. Ricarica per riprovare.",
    denied: "È richiesto l’accesso di amministratore della piattaforma.",
    checked: "Prove verificate",
    release: "Versione attiva",
    section: "Attivazione dell’ambito",
    collector: "Configurazione della raccolta",
    access: "Autorizzazione registrata",
    expires: "Scadenza dell’autorizzazione",
    acquisition: "Acquisizione registrata",
    records: "Canali conservati",
    errors: "Registrazioni con errori",
    never: "Registrazioni senza acquisizione riuscita",
    oldest: "Acquisizione riuscita più vecchia",
    latest: "Ultima acquisizione riuscita",
    published: "Ora di pubblicazione del fornitore",
    next: "Prima richiesta pianificata",
    unknown: "Sconosciuto / non registrato",
    enabled: "Attivo",
    disabled: "Disattivo",
    configured: "Configurato",
    credentials_required: "Configura le credenziali richieste dalla fonte",
    permission_required: "Registra l’autorizzazione verificata della fonte",
    channel_required:
      "Servono ancora un canale di allerta attuale autorizzato e la sua acquisizione nativa",
    missing: "Nessuna autorizzazione configurata",
    expired: "Scaduta — verifica e rinnova l’accesso",
    revoked: "Revocata — accesso non disponibile",
    not_yet_valid: "Non ancora valida",
    record_current: "Registrazione attuale; copertura verificata separatamente",
    public_contract:
      "Contratto del dataset pubblico; verifica la copertura attuale",
    per_channel: "Controlla ogni canale qui sotto",
    partial: "Prove parziali",
    unobserved: "Nessuna acquisizione registrata",
    recorded: "Acquisizione riuscita registrata",
    invalid_clock: "Ora della fonte nel futuro — verifica i timestamp",
    errors_state: "Errori di acquisizione registrati",
    trip_updates: "Aggiornamenti dei viaggi",
    service_alerts: "Avvisi di servizio",
    safety_environment: "Sicurezza e ambiente svizzeri",
    mobility: "Mobilità svizzera",
    business_opportunities: "Opportunità commerciali svizzere",
    intellectual_property: "Proprietà intellettuale svizzera",
  },
  "rm-CH": {
    title: "Funcziunament da las funtaunas da monitoring",
    body: "Controllai il stadi registrà da las funtaunas per tut ils nov secturs. Chargiar danovamain legia cumprovas localas senza rimnar datas u midar l’access.",
    boundary:
      "Ina permissiun actuala u ina rimnada recenta na cumprova betg cuvrida, resultats valaivels u consentiment per spediziuns. Temp da la funtauna e rimnada reussida èn separads. Nunenconuschent munta ch’i manca ina cumprova cumparegliabla.",
    open: "Avrir la controlla da funtaunas e cuvrida",
    refresh: "Chargiar danovamain las cumprovas",
    loading: "Las cumprovas vegnan chargiadas…",
    failed: "Las cumprovas na pon betg vegnir legidas. Empruvai danovamain.",
    denied: "Access d’administratur da la plattafurma necessari.",
    checked: "Cumprovas controlladas",
    release: "Versiun activa",
    section: "Activaziun dal sectur",
    collector: "Configuraziun da rimnada",
    access: "Permissiun registrada",
    expires: "La permissiun scada",
    acquisition: "Rimnada registrada",
    records: "Chanals conservads",
    errors: "Endataziuns cun sbagls",
    never: "Endataziuns senza rimnada reussida",
    oldest: "La pli veglia rimnada reussida",
    latest: "Ultima rimnada reussida",
    published: "Temp da publicaziun dal furnitur",
    next: "Proxima dumonda planisada",
    unknown: "Nunenconuschent / betg registrà",
    enabled: "Activà",
    disabled: "Deactivà",
    configured: "Configurà",
    credentials_required: "Configurar las datas d’access necessarias",
    permission_required: "Registrar la permissiun da funtauna examinada",
    channel_required:
      "In chanal d’avertiment actual lubì e sia rimnada nativa mancan anc",
    missing: "Nagina permissiun configurada",
    expired: "Scadida — controllar e renovar l’access",
    revoked: "Revocada — access betg disponibel",
    not_yet_valid: "Anc betg valaivla",
    record_current: "Endataziun actuala; cuvrida controllada separadamain",
    public_contract:
      "Contract dal dataset public; controllar la cuvrida actuala",
    per_channel: "Controllar mintga chanal sutvart",
    partial: "Cumprovas parzialas",
    unobserved: "Nagina rimnada registrada",
    recorded: "Rimnada reussida registrada",
    invalid_clock: "Temp da funtauna en il futur — controllar ils temps",
    errors_state: "Sbagls da rimnada registrads",
    trip_updates: "Actualisaziuns da viadis",
    service_alerts: "Avis dal servetsch",
    safety_environment: "Segirezza ed ambient svizzers",
    mobility: "Mobilitad svizra",
    business_opportunities: "Occasiuns commerzialas svizras",
    intellectual_property: "Proprietad intellectuala svizra",
  },
};
