export const sourceReadingCopy = {
  "en-CH": {
    origin: "Source origin",
    unknownOrigin: "Origin not established",
    captured: "Saved on",
    stated: "Stated document date",
    userStated: "Stated document date · user supplied",
    unknownDate: "Not established",
    classification: "Source classification",
    unknownClassification: "Primary / secondary not established",
    provenance: "Saved source details",
    identifier: "Saved version",
    filename: "File name",
    format: "Format",
    language: "Language",
    digest: "Capture fingerprint",
    digestHelp: "Use this recorded fingerprint to identify the saved capture.",
    unknown: "Not available in this record",
    passages: "saved passages",
    characters: "saved characters",
    reading: "Read the saved evidence",
    readingHelp:
      "This reader shows the retained capture. The original source may have changed since it was saved.",
    sha: "SHA-256",
  },
  "de-CH": {
    origin: "Quellenherkunft",
    unknownOrigin: "Herkunft nicht festgestellt",
    captured: "Gespeichert am",
    stated: "Angegebenes Dokumentdatum",
    userStated: "Angegebenes Dokumentdatum · vom Benutzer",
    unknownDate: "Nicht festgestellt",
    classification: "Quellenklassifikation",
    unknownClassification: "Primär- oder Sekundärquelle nicht festgestellt",
    provenance: "Details zur gespeicherten Quelle",
    identifier: "Gespeicherte Version",
    filename: "Dateiname",
    format: "Format",
    language: "Sprache",
    digest: "Fingerabdruck der Erfassung",
    digestHelp:
      "Dieser gespeicherte Fingerabdruck identifiziert die erfasste Fassung.",
    unknown: "In diesem Eintrag nicht verfügbar",
    passages: "gespeicherte Passagen",
    characters: "gespeicherte Zeichen",
    reading: "Gespeicherte Belege lesen",
    readingHelp:
      "Diese Ansicht zeigt die gespeicherte Fassung. Die Originalquelle kann sich seit der Speicherung geändert haben.",
    sha: "SHA-256",
  },
  "fr-CH": {
    origin: "Origine de la source",
    unknownOrigin: "Origine non établie",
    captured: "Enregistré le",
    stated: "Date déclarée du document",
    userStated: "Date déclarée du document · fournie par l’utilisateur",
    unknownDate: "Non établie",
    classification: "Classification de la source",
    unknownClassification: "Source primaire ou secondaire non établie",
    provenance: "Détails de la source enregistrée",
    identifier: "Version enregistrée",
    filename: "Nom du fichier",
    format: "Format",
    language: "Langue",
    digest: "Empreinte de la capture",
    digestHelp: "Cette empreinte enregistrée identifie la version capturée.",
    unknown: "Indisponible dans cet enregistrement",
    passages: "passages enregistrés",
    characters: "caractères enregistrés",
    reading: "Lire les preuves enregistrées",
    readingHelp:
      "Cette vue montre la version conservée. La source originale peut avoir changé depuis son enregistrement.",
    sha: "SHA-256",
  },
  "it-CH": {
    origin: "Origine della fonte",
    unknownOrigin: "Origine non accertata",
    captured: "Salvato il",
    stated: "Data dichiarata del documento",
    userStated: "Data dichiarata del documento · fornita dall’utente",
    unknownDate: "Non accertata",
    classification: "Classificazione della fonte",
    unknownClassification: "Fonte primaria o secondaria non accertata",
    provenance: "Dettagli della fonte salvata",
    identifier: "Versione salvata",
    filename: "Nome del file",
    format: "Formato",
    language: "Lingua",
    digest: "Impronta della cattura",
    digestHelp: "Questa impronta registrata identifica la versione acquisita.",
    unknown: "Non disponibile in questo record",
    passages: "passaggi salvati",
    characters: "caratteri salvati",
    reading: "Leggi le prove salvate",
    readingHelp:
      "Questa vista mostra la versione conservata. La fonte originale potrebbe essere cambiata dopo il salvataggio.",
    sha: "SHA-256",
  },
  "rm-CH": {
    origin: "Origin da la funtauna",
    unknownOrigin: "Origin betg stabilì",
    captured: "Memorisà ils",
    stated: "Data inditgada dal document",
    userStated: "Data inditgada dal document · furnida da l’utilisader",
    unknownDate: "Betg stabilida",
    classification: "Classificaziun da la funtauna",
    unknownClassification: "Funtauna primara u secundara betg stabilida",
    provenance: "Detagls da la funtauna memorisada",
    identifier: "Versiun memorisada",
    filename: "Num da la datoteca",
    format: "Format",
    language: "Lingua",
    digest: "Impronta da la registraziun",
    digestHelp:
      "Questa impronta memorisada identifitgescha la versiun registrada.",
    unknown: "Betg disponibel en questa registraziun",
    passages: "passadis memorisads",
    characters: "caracters memorisads",
    reading: "Leger las cumprovas memorisadas",
    readingHelp:
      "Questa vista mussa la versiun conservada. La funtauna originala po esser sa midada dapi la memorisaziun.",
    sha: "SHA-256",
  },
} as const;
