import type { Locale } from "./i18n";

const en = {
  title: "Source attention",
  body: "Review access renewal and collection problems. Acknowledgement is personal and does not repair a source or grant access. Changed evidence requires a new review.",
  pending: "Needs review",
  all: "All current issues",
  acknowledged: "Acknowledged",
  acknowledge: "Acknowledge this evidence",
  connector: "Open connection settings",
  urgent: "Urgent",
  warning: "Attention",
  renewal7: "Access expires within 7 days",
  renewal30: "Access expires within 30 days",
  section: "The section is disabled",
  collector: "Collection is not configured or available",
  empty:
    "No recorded issues in this view. This does not confirm source coverage.",
  failed:
    "The source or your access changed, or the request failed. Reload before reviewing again.",
  loading: "Checking current source issues…",
  filter: "Issue visibility",
};
export const sourceAttentionCopy: Record<Locale, typeof en> = {
  "en-CH": en,
  "de-CH": {
    title: "Quellen prüfen",
    body: "Prüfen Sie Zugriffsverlängerungen und Erfassungsprobleme. Die Bestätigung ist persönlich; sie repariert keine Quelle und gewährt keinen Zugriff. Geänderte Nachweise erfordern eine neue Prüfung.",
    pending: "Zu prüfen",
    all: "Alle aktuellen Probleme",
    acknowledged: "Bestätigt",
    acknowledge: "Diese Nachweise bestätigen",
    connector: "Verbindungseinstellungen öffnen",
    urgent: "Dringend",
    warning: "Beachten",
    renewal7: "Zugriff endet innerhalb von 7 Tagen",
    renewal30: "Zugriff endet innerhalb von 30 Tagen",
    section: "Der Bereich ist deaktiviert",
    collector: "Erfassung ist nicht eingerichtet oder verfügbar",
    empty:
      "Keine erfassten Probleme in dieser Ansicht. Dies bestätigt keine Quellenabdeckung.",
    failed:
      "Quelle oder Zugriff haben sich geändert, oder die Anfrage ist fehlgeschlagen. Vor einer erneuten Prüfung neu laden.",
    loading: "Aktuelle Quellenprobleme werden geprüft…",
    filter: "Sichtbare Probleme",
  },
  "fr-CH": {
    title: "Sources à examiner",
    body: "Examinez les renouvellements d’accès et les problèmes de collecte. La confirmation est personnelle ; elle ne répare aucune source et n’accorde aucun accès. Les preuves modifiées nécessitent un nouvel examen.",
    pending: "À examiner",
    all: "Tous les problèmes actuels",
    acknowledged: "Confirmé",
    acknowledge: "Confirmer ces preuves",
    connector: "Ouvrir les paramètres de connexion",
    urgent: "Urgent",
    warning: "Attention",
    renewal7: "Accès expirant dans les 7 jours",
    renewal30: "Accès expirant dans les 30 jours",
    section: "La rubrique est désactivée",
    collector: "La collecte n’est pas configurée ou disponible",
    empty:
      "Aucun problème enregistré dans cette vue. Cela ne confirme pas la couverture des sources.",
    failed:
      "La source ou votre accès a changé, ou la requête a échoué. Rechargez avant de réexaminer.",
    loading: "Vérification des problèmes actuels des sources…",
    filter: "Problèmes affichés",
  },
  "it-CH": {
    title: "Fonti da controllare",
    body: "Controlla i rinnovi dell’accesso e i problemi di raccolta. La conferma è personale: non ripara la fonte né concede accesso. Le prove modificate richiedono un nuovo controllo.",
    pending: "Da controllare",
    all: "Tutti i problemi attuali",
    acknowledged: "Confermato",
    acknowledge: "Conferma queste prove",
    connector: "Apri le impostazioni di connessione",
    urgent: "Urgente",
    warning: "Attenzione",
    renewal7: "L’accesso scade entro 7 giorni",
    renewal30: "L’accesso scade entro 30 giorni",
    section: "La sezione è disattivata",
    collector: "La raccolta non è configurata o disponibile",
    empty:
      "Nessun problema registrato in questa vista. Ciò non conferma la copertura delle fonti.",
    failed:
      "La fonte o il tuo accesso è cambiato, oppure la richiesta non è riuscita. Ricarica prima di controllare di nuovo.",
    loading: "Controllo dei problemi attuali delle fonti…",
    filter: "Problemi visualizzati",
  },
  "rm-CH": {
    title: "Funtaunas da controllar",
    body: "Controllai ils access da prolungar ed ils problems da rimnada. La conferma è persunala; ella na reparescha nagina funtauna e na conceda nagin access. Cumprovas midadas dovran ina nova controlla.",
    pending: "Da controllar",
    all: "Tut ils problems actuals",
    acknowledged: "Confermà",
    acknowledge: "Confermar questas cumprovas",
    connector: "Avrir ils parameters da connexiun",
    urgent: "Urgent",
    warning: "Attenziun",
    renewal7: "L’access scada entaifer 7 dis",
    renewal30: "L’access scada entaifer 30 dis",
    section: "La rubrica è deactivada",
    collector: "La rimnada n’è betg configurada u disponibla",
    empty:
      "Nagins problems registrads en questa vista. Quai na conferma betg la cuvrida da las funtaunas.",
    failed:
      "La funtauna u Voss access è sa midà, u la dumonda n’è betg reussida. Chargiai danovamain avant la proxima controlla.",
    loading: "Ils problems actuals da las funtaunas vegnan controllads…",
    filter: "Problems mussads",
  },
};
