import type { Locale } from "./i18n";
import { riverCopy } from "./river-copy";

// Required source notice, SIMAP API GTC section 5. Romansh uses the original
// authoritative German wording because the source supplies no Romansh notice.
export const simapNotice: Record<Locale, string> = {
  "en-CH":
    "This is not an official publication. The data published on the www.simap.ch platform are authoritative.",
  "de-CH":
    "Dies ist keine amtliche Veröffentlichung. Massgebend sind die auf der Plattform www.simap.ch veröffentlichten Daten.",
  "fr-CH":
    "Ceci n'est pas une publication officielle. Les données publiées sur la plateforme www.simap.ch font foi.",
  "it-CH":
    "La presente pubblicazione non è ufficiale, fanno fede i dati pubblicati sulla piattaforma www.simap.ch.",
  "rm-CH":
    "Dies ist keine amtliche Veröffentlichung. Massgebend sind die auf der Plattform www.simap.ch veröffentlichten Daten.",
};

const en = {
  featureOff: "Tender Watch is not enabled on this site.",
  excerpt:
    "This is a shortened source extract. Download the original publication for the complete fields.",
  title: "Tender Watch",
  intro: "Discover public SIMAP tenders and keep a private review history.",
  scope:
    "Public publications only. Tender documents and Q&A have not been verified. Decisions stay inside Helvetic Lens; no bid or message is submitted.",
  sourceOff:
    "The public source is unavailable. You can save a profile and manage existing records.",
  company: "Company name",
  capabilities: "Capabilities",
  addCapability: "Add capability",
  capabilityName: "Capability name",
  phrases: "Search phrases — one per line",
  cpv: "CPV codes — eight digits, separated by commas",
  descendants: "Include officially verified CPV descendants",
  cantons: "Contract locations — leave empty for all cantons",
  languages: "Offer languages — leave empty for any",
  authority: "Authority level",
  federal: "Federal",
  cantonal: "Cantonal",
  municipal: "Municipal",
  other: "Other",
  advanced: "Exclusions and qualifications",
  excludedPhrases: "Excluded phrases — one per line",
  excludedCpv: "Excluded CPV codes",
  excludedTypes: "Excluded contract types",
  service: "Services",
  supply: "Supplies",
  construction: "Construction",
  minValue: "Minimum contract value (CHF)",
  maxValue: "Maximum contract value (CHF)",
  references: "Available references — blank means unknown",
  certificates: "Certificates — one per line; blank means unknown",
  semantic:
    "Semantic scoring is disabled. Results explain explicit phrases and verified CPV classifications; eligibility still needs your review.",
  check: "Check discovery settings",
  plan: "Discovery plan — no live search performed",
  queryNeeded:
    "Add a CPV code or a phrase of at least three characters to start discovery.",
  invalid: "Check the company name, capabilities, codes and filters.",
  tenders: "Tenders",
  none: "No saved tenders in this selection. This does not establish that no opportunities exist.",
  all: "All",
  following: "Following",
  follow: "Follow tender",
  unfollow: "Stop following",
  new: "New",
  needs_review: "Needs review",
  deadline: "Offer deadline",
  noDeadline: "The source does not provide a verified deadline.",
  phase: "Publication stage",
  open: "Open",
  advance_notice: "Advance notice",
  awarded: "Awarded",
  cancelled: "Cancelled",
  revoked: "Revoked",
  bid: "Bid",
  no_bid: "No-bid",
  monitor: "Monitor",
  internalDecision: "Your internal decision",
  retained:
    "The previous decision is retained. Review the current version before deciding again.",
  original: "Download original publication",
  publicFields: "Public source fields",
  evidence: "Evidence",
  matches: "Matched criteria",
  exclusions: "Exclusions",
  unknowns: "Unverified criteria",
  gaps: "Declared qualification gaps",
  projectContext: "Project CPV context — relevance to this lot is unverified",
  evidenceHelp:
    "Source text is shown in an available publication language. Missing documents or answers are not evidence that no requirements exist.",
  details: "Open tender",
  back: "Back to tenders",
  noReasons: "No confirmed entries.",
  profileOld:
    "These results use an earlier profile revision. The next source check will reassess them.",
  lastCheck: "Last source check",
  nextCheck: "Next source check",
  new_opportunity: "New opportunity",
  material_update: "Material source change",
  source_update: "Source update",
  late_evidence: "Earlier source evidence",
  profile_reassessment: "Profile reassessment",
  match: "Criteria matched",
  excluded: "Excluded",
  no_match: "No criteria matched",
  collecting_public: "Collecting public publications",
  public_cycle_complete: "Public collection cycle complete",
  partial_public_coverage: "Partial public coverage",
  publication_withheld: "Waiting for permitted publication time",
  storage_capacity:
    "Collection paused at the storage limit. Saved evidence and decisions are preserved; contact the site operator to restore capacity.",
  source_rights_unavailable:
    "Collection is waiting because source permissions are unavailable. Earlier evidence is retained but restricted publications cannot be opened.",
  invalid_source_contract: "Source format could not be verified",
  source_error: "Source request failed",
  rate_limited: "Waiting before the next source request",
  publicOnly: "Public source only",
  noEmail: "Email delivery requires your explicit consent in each monitor.",
  confirmed: "Settings checked",
  retainedRevision: "Profile revision",
  sourceLimit:
    "Discovery checks the last 90 days in overlapping six-hour cycles. Source limits or failures can leave gaps.",
  material: "Changed fields",
  titleField: "Title",
  procurement: "Procurement",
  lot_criteria: "Lot criteria",
  project_criteria: "Project criteria",
  terms: "Terms",
  qa_schedule: "Q&A schedule",
  offer_languages: "Offer languages",
};
type Extra = Record<keyof typeof en, string>;
const extra: Record<Locale, Extra> = {
  "en-CH": en,
  "de-CH": {
    featureOff:
      "Ausschreibungsmonitoring ist auf dieser Website nicht aktiviert.",
    excerpt:
      "Dies ist ein gekürzter Quellenauszug. Die vollständigen Angaben stehen in der Originalpublikation zum Herunterladen.",
    title: "Ausschreibungsmonitoring",
    intro:
      "Öffentliche SIMAP-Ausschreibungen finden und Prüfungen privat dokumentieren.",
    scope:
      "Nur öffentliche Publikationen. Ausschreibungsunterlagen und Fragen/Antworten sind nicht verifiziert. Entscheidungen bleiben in Helvetic Lens; es wird kein Angebot und keine Nachricht übermittelt.",
    sourceOff:
      "Die öffentliche Quelle ist nicht verfügbar. Profile und bestehende Einträge können verwaltet werden.",
    company: "Firmenname",
    capabilities: "Kompetenzen",
    addCapability: "Kompetenz hinzufügen",
    capabilityName: "Kompetenzbezeichnung",
    phrases: "Suchbegriffe — einer pro Zeile",
    cpv: "CPV-Codes — acht Ziffern, durch Kommas getrennt",
    descendants: "Amtlich verifizierte CPV-Untercodes einschliessen",
    cantons: "Ausführungsorte — leer für alle Kantone",
    languages: "Angebotssprachen — leer für alle",
    authority: "Ebene der Vergabestelle",
    federal: "Bund",
    cantonal: "Kanton",
    municipal: "Gemeinde",
    other: "Andere",
    advanced: "Ausschlüsse und Qualifikationen",
    excludedPhrases: "Ausgeschlossene Begriffe — einer pro Zeile",
    excludedCpv: "Ausgeschlossene CPV-Codes",
    excludedTypes: "Ausgeschlossene Auftragsarten",
    service: "Dienstleistungen",
    supply: "Lieferungen",
    construction: "Bauarbeiten",
    minValue: "Mindestauftragswert (CHF)",
    maxValue: "Höchstauftragswert (CHF)",
    references: "Verfügbare Referenzen — leer bedeutet unbekannt",
    certificates: "Zertifikate — eines pro Zeile; leer bedeutet unbekannt",
    semantic:
      "Semantische Bewertung ist deaktiviert. Ergebnisse erläutern Begriffe und verifizierte CPV-Klassifikationen; die Eignung muss geprüft werden.",
    check: "Sucheinstellungen prüfen",
    plan: "Suchplan — keine Live-Suche durchgeführt",
    queryNeeded:
      "Für die Suche einen CPV-Code oder einen Begriff mit mindestens drei Zeichen ergänzen.",
    invalid: "Firmenname, Kompetenzen, Codes und Filter prüfen.",
    tenders: "Ausschreibungen",
    none: "Keine gespeicherten Ausschreibungen in dieser Auswahl. Daraus folgt nicht, dass keine Chancen bestehen.",
    all: "Alle",
    following: "Verfolgt",
    follow: "Ausschreibung verfolgen",
    unfollow: "Verfolgung beenden",
    new: "Neu",
    needs_review: "Prüfung erforderlich",
    deadline: "Angebotsfrist",
    noDeadline: "Die Quelle liefert keine verifizierte Frist.",
    phase: "Publikationsphase",
    open: "Offen",
    advance_notice: "Vorankündigung",
    awarded: "Zugeschlagen",
    cancelled: "Abgebrochen",
    revoked: "Widerrufen",
    bid: "Angebot planen",
    no_bid: "Kein Angebot",
    monitor: "Beobachten",
    internalDecision: "Ihre interne Entscheidung",
    retained:
      "Die bisherige Entscheidung bleibt erhalten. Vor einer erneuten Entscheidung die aktuelle Version prüfen.",
    original: "Originalpublikation herunterladen",
    publicFields: "Öffentliche Quellenangaben",
    evidence: "Belege",
    matches: "Passende Kriterien",
    exclusions: "Ausschlüsse",
    unknowns: "Unverifizierte Kriterien",
    gaps: "Deklarierte Qualifikationslücken",
    projectContext:
      "CPV-Kontext des Projekts — Relevanz für dieses Los nicht verifiziert",
    evidenceHelp:
      "Quellentext erscheint in einer verfügbaren Publikationssprache. Fehlende Unterlagen oder Antworten belegen keine fehlenden Anforderungen.",
    details: "Ausschreibung öffnen",
    back: "Zurück zu Ausschreibungen",
    noReasons: "Keine bestätigten Einträge.",
    profileOld:
      "Diese Ergebnisse verwenden eine frühere Profilrevision. Die nächste Quellenprüfung bewertet sie neu.",
    lastCheck: "Letzte Quellenprüfung",
    nextCheck: "Nächste Quellenprüfung",
    new_opportunity: "Neue Gelegenheit",
    material_update: "Wesentliche Quellenänderung",
    source_update: "Quellenaktualisierung",
    late_evidence: "Frühere Quellenbelege",
    profile_reassessment: "Profilneubewertung",
    match: "Kriterien erfüllt",
    excluded: "Ausgeschlossen",
    no_match: "Keine passenden Kriterien",
    collecting_public: "Öffentliche Publikationen werden erfasst",
    public_cycle_complete: "Öffentlicher Erfassungszyklus abgeschlossen",
    partial_public_coverage: "Teilweise öffentliche Abdeckung",
    publication_withheld: "Warten auf erlaubten Publikationszeitpunkt",
    storage_capacity:
      "Die Erfassung wartet wegen des Speicherlimits. Belege und Entscheidungen bleiben erhalten. Wenden Sie sich für zusätzliche Kapazität an den Betreiber.",
    source_rights_unavailable:
      "Die Erfassung wartet auf geklärte Quellenrechte. Frühere Belege bleiben gespeichert; gesperrte Publikationen können nicht geöffnet werden.",
    invalid_source_contract: "Quellenformat nicht verifizierbar",
    source_error: "Quellenanfrage fehlgeschlagen",
    rate_limited: "Warten vor der nächsten Quellenanfrage",
    publicOnly: "Nur öffentliche Quelle",
    noEmail:
      "Der E-Mail-Versand erfordert Ihre ausdrückliche Zustimmung in jedem Monitor.",
    confirmed: "Einstellungen geprüft",
    retainedRevision: "Profilrevision",
    sourceLimit:
      "Die Suche prüft die letzten 90 Tage in überlappenden Sechsstundenzyklen. Quellenlimits und Fehler können Lücken verursachen.",
    material: "Geänderte Felder",
    titleField: "Titel",
    procurement: "Beschaffung",
    lot_criteria: "Loskriterien",
    project_criteria: "Projektkriterien",
    terms: "Bedingungen",
    qa_schedule: "Fragenfristen",
    offer_languages: "Angebotssprachen",
  },
  "fr-CH": {
    featureOff: "La veille des appels d’offres n’est pas activée sur ce site.",
    excerpt:
      "Cet extrait de la source est abrégé. Téléchargez la publication originale pour consulter les champs complets.",
    title: "Veille des appels d’offres",
    intro:
      "Trouvez les appels d’offres publics SIMAP et conservez un historique privé de vos examens.",
    scope:
      "Publications publiques uniquement. Les documents et questions/réponses ne sont pas vérifiés. Les décisions restent dans Helvetic Lens ; aucune offre ni aucun message n’est envoyé.",
    sourceOff:
      "La source publique est indisponible. Vous pouvez enregistrer un profil et gérer les éléments existants.",
    company: "Nom de l’entreprise",
    capabilities: "Compétences",
    addCapability: "Ajouter une compétence",
    capabilityName: "Nom de la compétence",
    phrases: "Expressions de recherche — une par ligne",
    cpv: "Codes CPV — huit chiffres, séparés par des virgules",
    descendants: "Inclure les sous-codes CPV officiellement vérifiés",
    cantons: "Lieux d’exécution — vide pour tous les cantons",
    languages: "Langues des offres — vide pour toutes",
    authority: "Niveau de l’adjudicateur",
    federal: "Fédéral",
    cantonal: "Cantonal",
    municipal: "Communal",
    other: "Autre",
    advanced: "Exclusions et qualifications",
    excludedPhrases: "Expressions exclues — une par ligne",
    excludedCpv: "Codes CPV exclus",
    excludedTypes: "Types de marchés exclus",
    service: "Services",
    supply: "Fournitures",
    construction: "Construction",
    minValue: "Valeur minimale du marché (CHF)",
    maxValue: "Valeur maximale du marché (CHF)",
    references: "Références disponibles — vide signifie inconnu",
    certificates: "Certificats — un par ligne ; vide signifie inconnu",
    semantic:
      "La notation sémantique est désactivée. Les résultats expliquent les expressions et classifications CPV vérifiées ; l’aptitude reste à examiner.",
    check: "Vérifier les paramètres de recherche",
    plan: "Plan de recherche — aucune recherche en direct effectuée",
    queryNeeded:
      "Ajoutez un code CPV ou une expression d’au moins trois caractères pour lancer la recherche.",
    invalid:
      "Vérifiez le nom de l’entreprise, les compétences, codes et filtres.",
    tenders: "Appels d’offres",
    none: "Aucun appel d’offres enregistré dans cette sélection. Cela ne prouve pas l’absence d’opportunités.",
    all: "Tous",
    following: "Suivis",
    follow: "Suivre l’appel d’offres",
    unfollow: "Arrêter le suivi",
    new: "Nouveau",
    needs_review: "À examiner",
    deadline: "Délai de remise des offres",
    noDeadline: "La source ne fournit pas de délai vérifié.",
    phase: "Phase de publication",
    open: "Ouvert",
    advance_notice: "Préavis",
    awarded: "Adjugé",
    cancelled: "Interrompu",
    revoked: "Révoqué",
    bid: "Prévoir une offre",
    no_bid: "Pas d’offre",
    monitor: "Surveiller",
    internalDecision: "Votre décision interne",
    retained:
      "La décision précédente est conservée. Examinez la version actuelle avant de décider à nouveau.",
    original: "Télécharger la publication originale",
    publicFields: "Données publiques de la source",
    evidence: "Éléments probants",
    matches: "Critères correspondants",
    exclusions: "Exclusions",
    unknowns: "Critères non vérifiés",
    gaps: "Lacunes de qualification déclarées",
    projectContext:
      "Contexte CPV du projet — pertinence pour ce lot non vérifiée",
    evidenceHelp:
      "Le texte source apparaît dans une langue disponible. L’absence de documents ou de réponses ne prouve pas l’absence d’exigences.",
    details: "Ouvrir l’appel d’offres",
    back: "Retour aux appels d’offres",
    noReasons: "Aucune entrée confirmée.",
    profileOld:
      "Ces résultats utilisent une ancienne révision du profil. La prochaine vérification les réévaluera.",
    lastCheck: "Dernière vérification",
    nextCheck: "Prochaine vérification",
    new_opportunity: "Nouvelle opportunité",
    material_update: "Modification substantielle",
    source_update: "Mise à jour de la source",
    late_evidence: "Éléments antérieurs",
    profile_reassessment: "Réévaluation du profil",
    match: "Critères correspondants",
    excluded: "Exclu",
    no_match: "Aucun critère correspondant",
    collecting_public: "Collecte des publications publiques",
    public_cycle_complete: "Cycle public terminé",
    partial_public_coverage: "Couverture publique partielle",
    publication_withheld: "En attente de l’heure de publication autorisée",
    storage_capacity:
      "La collecte attend : la limite de stockage est atteinte. Les preuves et décisions sont conservées. Contactez l’exploitant pour rétablir la capacité.",
    source_rights_unavailable:
      "La collecte attend la clarification des droits de la source. Les preuves antérieures sont conservées ; les publications restreintes ne peuvent pas être ouvertes.",
    invalid_source_contract: "Format de la source non vérifié",
    source_error: "Échec de la requête source",
    rate_limited: "Attente avant la prochaine requête",
    publicOnly: "Source publique uniquement",
    noEmail:
      "L’envoi d’e-mails nécessite votre consentement explicite dans chaque suivi.",
    confirmed: "Paramètres vérifiés",
    retainedRevision: "Révision du profil",
    sourceLimit:
      "La recherche couvre les 90 derniers jours par cycles de six heures qui se chevauchent. Les limites ou erreurs de source peuvent laisser des lacunes.",
    material: "Champs modifiés",
    titleField: "Titre",
    procurement: "Marché",
    lot_criteria: "Critères du lot",
    project_criteria: "Critères du projet",
    terms: "Conditions",
    qa_schedule: "Calendrier des questions",
    offer_languages: "Langues des offres",
  },
  "it-CH": {
    featureOff: "Il monitoraggio degli appalti non è attivato su questo sito.",
    excerpt:
      "Questo estratto della fonte è abbreviato. Scarica la pubblicazione originale per tutti i campi.",
    title: "Monitoraggio degli appalti",
    intro:
      "Trova gli appalti pubblici SIMAP e conserva una cronologia privata delle verifiche.",
    scope:
      "Solo pubblicazioni pubbliche. Documenti di gara e domande/risposte non sono verificati. Le decisioni restano in Helvetic Lens; nessuna offerta o messaggio viene inviato.",
    sourceOff:
      "La fonte pubblica non è disponibile. Puoi salvare un profilo e gestire i dati esistenti.",
    company: "Nome dell’azienda",
    capabilities: "Competenze",
    addCapability: "Aggiungi competenza",
    capabilityName: "Nome della competenza",
    phrases: "Espressioni di ricerca — una per riga",
    cpv: "Codici CPV — otto cifre, separati da virgole",
    descendants: "Includi i sottocodici CPV verificati ufficialmente",
    cantons: "Luoghi d’esecuzione — vuoto per tutti i cantoni",
    languages: "Lingue delle offerte — vuoto per tutte",
    authority: "Livello dell’ente aggiudicatore",
    federal: "Federale",
    cantonal: "Cantonale",
    municipal: "Comunale",
    other: "Altro",
    advanced: "Esclusioni e qualifiche",
    excludedPhrases: "Espressioni escluse — una per riga",
    excludedCpv: "Codici CPV esclusi",
    excludedTypes: "Tipi di appalto esclusi",
    service: "Servizi",
    supply: "Forniture",
    construction: "Costruzione",
    minValue: "Valore minimo dell’appalto (CHF)",
    maxValue: "Valore massimo dell’appalto (CHF)",
    references: "Referenze disponibili — vuoto significa sconosciuto",
    certificates: "Certificati — uno per riga; vuoto significa sconosciuto",
    semantic:
      "La valutazione semantica è disattivata. I risultati spiegano espressioni e classificazioni CPV verificate; l’idoneità richiede una verifica.",
    check: "Verifica le impostazioni di ricerca",
    plan: "Piano di ricerca — nessuna ricerca dal vivo eseguita",
    queryNeeded:
      "Aggiungi un codice CPV o un’espressione di almeno tre caratteri per avviare la ricerca.",
    invalid: "Controlla nome dell’azienda, competenze, codici e filtri.",
    tenders: "Appalti",
    none: "Nessun appalto salvato in questa selezione. Questo non dimostra l’assenza di opportunità.",
    all: "Tutti",
    following: "Seguiti",
    follow: "Segui appalto",
    unfollow: "Interrompi il seguito",
    new: "Nuovo",
    needs_review: "Da verificare",
    deadline: "Termine di presentazione",
    noDeadline: "La fonte non fornisce un termine verificato.",
    phase: "Fase della pubblicazione",
    open: "Aperto",
    advance_notice: "Preavviso",
    awarded: "Aggiudicato",
    cancelled: "Interrotto",
    revoked: "Revocato",
    bid: "Pianifica offerta",
    no_bid: "Nessuna offerta",
    monitor: "Osserva",
    internalDecision: "La tua decisione interna",
    retained:
      "La decisione precedente è conservata. Verifica la versione attuale prima di decidere di nuovo.",
    original: "Scarica la pubblicazione originale",
    publicFields: "Dati pubblici della fonte",
    evidence: "Prove",
    matches: "Criteri corrispondenti",
    exclusions: "Esclusioni",
    unknowns: "Criteri non verificati",
    gaps: "Lacune di qualifica dichiarate",
    projectContext:
      "Contesto CPV del progetto — pertinenza per questo lotto non verificata",
    evidenceHelp:
      "Il testo della fonte appare in una lingua disponibile. Documenti o risposte mancanti non dimostrano l’assenza di requisiti.",
    details: "Apri appalto",
    back: "Torna agli appalti",
    noReasons: "Nessuna voce confermata.",
    profileOld:
      "Questi risultati usano una revisione precedente del profilo. Il prossimo controllo li rivaluterà.",
    lastCheck: "Ultimo controllo",
    nextCheck: "Prossimo controllo",
    new_opportunity: "Nuova opportunità",
    material_update: "Modifica sostanziale",
    source_update: "Aggiornamento della fonte",
    late_evidence: "Prove precedenti",
    profile_reassessment: "Rivalutazione del profilo",
    match: "Criteri corrispondenti",
    excluded: "Escluso",
    no_match: "Nessun criterio corrispondente",
    collecting_public: "Raccolta delle pubblicazioni pubbliche",
    public_cycle_complete: "Ciclo pubblico completato",
    partial_public_coverage: "Copertura pubblica parziale",
    publication_withheld: "In attesa dell’ora di pubblicazione autorizzata",
    storage_capacity:
      "La raccolta è in attesa perché è stato raggiunto il limite di archiviazione. Prove e decisioni sono conservate. Contatta il gestore per ripristinare la capacità.",
    source_rights_unavailable:
      "La raccolta attende la verifica dei diritti della fonte. Le prove precedenti sono conservate; le pubblicazioni con accesso limitato non possono essere aperte.",
    invalid_source_contract: "Formato della fonte non verificato",
    source_error: "Richiesta alla fonte fallita",
    rate_limited: "Attesa prima della prossima richiesta",
    publicOnly: "Solo fonte pubblica",
    noEmail:
      "L’invio di e-mail richiede il tuo consenso esplicito in ogni monitoraggio.",
    confirmed: "Impostazioni verificate",
    retainedRevision: "Revisione del profilo",
    sourceLimit:
      "La ricerca copre gli ultimi 90 giorni in cicli sovrapposti di sei ore. Limiti o errori della fonte possono lasciare lacune.",
    material: "Campi modificati",
    titleField: "Titolo",
    procurement: "Appalto",
    lot_criteria: "Criteri del lotto",
    project_criteria: "Criteri del progetto",
    terms: "Condizioni",
    qa_schedule: "Calendario delle domande",
    offer_languages: "Lingue delle offerte",
  },
  "rm-CH": {
    featureOff:
      "La surveglianza da las submissiuns n’è betg activada sin questa pagina.",
    excerpt:
      "Quest extract da la funtauna è scursanì. Telechargiai la publicaziun originala per las indicaziuns cumplettas.",
    title: "Surveglianza da las submissiuns",
    intro:
      "Chattai submissiuns publicas SIMAP e tegnai ina cronologia privata da las controllas.",
    scope:
      "Mo publicaziuns publicas. Documents da submissiun e dumondas/respostas n’èn betg verifitgads. Decisiuns restan en Helvetic Lens; nagina offerta u messadi na vegn tramess.",
    sourceOff:
      "La funtauna publica n’è betg disponibla. Vus pudais memorisar in profil e administrar las endataziuns existentas.",
    company: "Num da l’interpresa",
    capabilities: "Cumpetenzas",
    addCapability: "Agiuntar cumpetenza",
    capabilityName: "Num da la cumpetenza",
    phrases: "Expressiuns da tschertga — ina per lingia",
    cpv: "Codes CPV — otg cifras, separadas cun commas",
    descendants: "Includer sutcodes CPV verifitgads uffizialmain",
    cantons: "Lieus d’execuziun — vid per tut ils chantuns",
    languages: "Linguas da las offertas — vid per tuttas",
    authority: "Nivel da l’autoritad",
    federal: "Federal",
    cantonal: "Chantunal",
    municipal: "Communal",
    other: "Auter",
    advanced: "Exclusiuns e qualificaziuns",
    excludedPhrases: "Expressiuns exclusas — ina per lingia",
    excludedCpv: "Codes CPV exclus",
    excludedTypes: "Tips d’incumbensa exclus",
    service: "Servetschs",
    supply: "Furniziuns",
    construction: "Construcziun",
    minValue: "Valur minimala da l’incumbensa (CHF)",
    maxValue: "Valur maximala da l’incumbensa (CHF)",
    references: "Referenzas disponiblas — vid signifitga nunenconuschent",
    certificates: "Certificats — in per lingia; vid signifitga nunenconuschent",
    semantic:
      "La valitaziun semantica è deactivada. Ils resultats decleran expressiuns e classificaziuns CPV verifitgadas; l’adattaziun sto anc vegnir controllada.",
    check: "Controllar ils parameters da tschertga",
    plan: "Plan da tschertga — nagina tschertga directa fatga",
    queryNeeded:
      "Agiuntai in code CPV u in’expressiun cun almain trais caracters per cumenzar la tschertga.",
    invalid:
      "Controllai il num da l’interpresa, las cumpetenzas, ils codes ed ils filters.",
    tenders: "Submissiuns",
    none: "Naginas submissiuns memorisadas en questa selecziun. Quai na cumprova betg ch’i na dat naginas pussaivladads.",
    all: "Tuttas",
    following: "Suandadas",
    follow: "Suandar la submissiun",
    unfollow: "Terminar il suandar",
    new: "Nov",
    needs_review: "Controlla necessaria",
    deadline: "Termin per las offertas",
    noDeadline: "La funtauna na furnescha nagin termin verifitgà.",
    phase: "Fasa da publicaziun",
    open: "Avert",
    advance_notice: "Preannunzia",
    awarded: "Surdà",
    cancelled: "Interrut",
    revoked: "Revocà",
    bid: "Planisar offerta",
    no_bid: "Nagina offerta",
    monitor: "Observar",
    internalDecision: "Vossa decisiun interna",
    retained:
      "La decisiun precedenta vegn mantegnida. Controllai la versiun actuala avant da decider danovamain.",
    original: "Telechargiar la publicaziun originala",
    publicFields: "Indicaziuns publicas da la funtauna",
    evidence: "Cumprovas",
    matches: "Criteris correspundents",
    exclusions: "Exclusiuns",
    unknowns: "Criteris betg verifitgads",
    gaps: "Mancanzas da qualificaziun decleradas",
    projectContext:
      "Context CPV dal project — relevanza per quest lot betg verifitgada",
    evidenceHelp:
      "Il text da la funtauna cumpara en ina lingua disponibla. Documents u respostas mancantas na cumprovan betg l’absenza da pretensiuns.",
    details: "Avrir la submissiun",
    back: "Enavos tar las submissiuns",
    noReasons: "Naginas endataziuns confermadas.",
    profileOld:
      "Quests resultats dovran ina revisiun precedenta dal profil. La proxima controlla als valitescha danovamain.",
    lastCheck: "Ultima controlla",
    nextCheck: "Proxima controlla",
    new_opportunity: "Nova pussaivladad",
    material_update: "Midada essenziala",
    source_update: "Actualisaziun da la funtauna",
    late_evidence: "Cumprovas anteriuras",
    profile_reassessment: "Nova valitaziun dal profil",
    match: "Criteris correspundents",
    excluded: "Exclus",
    no_match: "Nagins criteris correspundents",
    collecting_public: "Rimnar publicaziuns publicas",
    public_cycle_complete: "Ciclus public terminà",
    partial_public_coverage: "Cuverta publica parziala",
    publication_withheld: "Spetgar l’ura da publicaziun permessa",
    storage_capacity:
      "La rimnada spetga pervi dal limit da memoria. Cumprovas e decisiuns restan conservadas. Contactai il gestiunari per augmentar la capacitad.",
    source_rights_unavailable:
      "La rimnada spetga sin dretgs da la funtauna sclerids. Cumprovas anteriuras restan conservadas; publicaziuns bloccadas na pon betg vegnir avertas.",
    invalid_source_contract: "Format da la funtauna betg verifitgà",
    source_error: "Dumonda a la funtauna betg reussida",
    rate_limited: "Spetgar avant la proxima dumonda",
    publicOnly: "Mo funtauna publica",
    noEmail:
      "La spediziun dad e-mails dovra vos consentiment explicit en mintga monitoring.",
    confirmed: "Parameters controllads",
    retainedRevision: "Revisiun dal profil",
    sourceLimit:
      "La tschertga controlla ils ultims 90 dis en ciclus da sis uras che sa cuvran. Limits u sbagls da la funtauna pon laschar largias.",
    material: "Champs midads",
    titleField: "Titel",
    procurement: "Acquisiziun",
    lot_criteria: "Criteris dal lot",
    project_criteria: "Criteris dal project",
    terms: "Cundiziuns",
    qa_schedule: "Chalender da las dumondas",
    offer_languages: "Linguas da las offertas",
  },
};
export const tenderCopy = Object.fromEntries(
  Object.entries(extra).map(([locale, values]) => [
    locale,
    { ...riverCopy[locale as Locale], ...values },
  ]),
) as Record<Locale, (typeof riverCopy)[Locale] & Extra>;
