import type { Locale } from "./i18n";
const en = {
  title: "Trademark & IP Watch",
  intro:
    "Save the brands and goods or services you want to monitor in Switzerland.",
  private: "Your portfolios are private to your account in this organization.",
  source:
    "Official IPI access and source rights are not configured. Saving a portfolio creates a draft; it does not start a search or send email.",
  assessment:
    "Name similarity produces candidates for IP review. It does not establish infringement or confirm a legal conflict. A class match alone does not prove similar goods or services.",
  calibration:
    "Similarity methods need reviewed calibration for the selected name language. Unsupported pronunciation remains unavailable.",
  saved: "Saved portfolios",
  create: "Create portfolio",
  portfolio: "Portfolio name",
  brands: "Monitored brands",
  brand: "Brand name",
  addBrand: "Add brand",
  removeBrand: "Remove brand",
  language: "Name language",
  exact: "Watch exact names",
  similar: "Watch similar names",
  variants: "Word variants (one per line, up to 8)",
  owners: "Owners of interest (one per line, up to 8)",
  classes: "Nice class numbers (1–45, separated by commas)",
  goods: "Relevant goods and services",
  addGoods: "Add goods/service interest",
  removeGoods: "Remove interest",
  interest: "Interest name",
  phrase: "Matching phrase",
  phraseLanguage: "Phrase language",
  addPhrase: "Add phrase variant",
  removePhrase: "Remove phrase",
  goodsHelp:
    "Enter the words you use for your products or services. Add explicit phrase variants for each source language; matching does not invent translations.",
  save: "Save draft",
  edit: "Edit portfolio",
  history: "Configuration history",
  version: "Version",
  archive: "Archive portfolio",
  remove: "Delete portfolio",
  confirm:
    "Permanently delete this archived portfolio and its private history?",
  cancel: "Cancel",
  refresh: "Refresh",
  back: "Back",
  next: "Next page",
  loading: "Loading portfolios…",
  empty: "No saved portfolios.",
  failed: "The portfolio is unavailable. Refresh and try again.",
  conflict: "The portfolio changed. Refresh before saving again.",
  invalid: "Check the brand names, phrase variants and class numbers (1–45).",
  unavailable:
    "Trademark Watch is unavailable for this account or environment.",
  readonly:
    "You can read your saved portfolios. Changes require an organization administrator role.",
  draft: "Draft",
  active: "Active",
  paused: "Paused",
  archived: "Archived",
};
export const trademarkCopy: Record<Locale, Record<keyof typeof en, string>> = {
  "en-CH": en,
  "de-CH": {
    title: "Marken- und IP-Monitoring",
    intro:
      "Speichern Sie die Marken sowie Waren oder Dienstleistungen, die Sie in der Schweiz beobachten möchten.",
    private:
      "Ihre Portfolios sind innerhalb dieser Organisation nur für Ihr Konto sichtbar.",
    source:
      "Der offizielle IGE-Zugang und die Quellenrechte sind nicht eingerichtet. Speichern erstellt einen Entwurf; es startet keine Suche und versendet keine E-Mails.",
    assessment:
      "Namensähnlichkeit liefert Kandidaten zur IP-Prüfung. Sie bestätigt weder eine Verletzung noch einen Rechtskonflikt. Dieselbe Klasse allein beweist keine ähnlichen Waren oder Dienstleistungen.",
    calibration:
      "Ähnlichkeitsmethoden benötigen eine geprüfte Kalibrierung für die gewählte Namenssprache. Nicht unterstützte Aussprache bleibt nicht verfügbar.",
    saved: "Gespeicherte Portfolios",
    create: "Portfolio erstellen",
    portfolio: "Portfolioname",
    brands: "Beobachtete Marken",
    brand: "Markenname",
    addBrand: "Marke hinzufügen",
    removeBrand: "Marke entfernen",
    language: "Namenssprache",
    exact: "Exakte Namen beobachten",
    similar: "Ähnliche Namen beobachten",
    variants: "Wortvarianten (eine pro Zeile, höchstens 8)",
    owners: "Interessierende Inhaber (einer pro Zeile, höchstens 8)",
    classes: "Nizza-Klassennummern (1–45, durch Kommas getrennt)",
    goods: "Relevante Waren und Dienstleistungen",
    addGoods: "Waren-/Dienstleistungsinteresse hinzufügen",
    removeGoods: "Interesse entfernen",
    interest: "Interessenname",
    phrase: "Suchphrase",
    phraseLanguage: "Phrasensprache",
    addPhrase: "Phrasenvariante hinzufügen",
    removePhrase: "Phrase entfernen",
    goodsHelp:
      "Geben Sie Begriffe für Ihre Produkte oder Dienstleistungen ein. Ergänzen Sie ausdrückliche Varianten je Quellensprache; der Abgleich erfindet keine Übersetzungen.",
    save: "Entwurf speichern",
    edit: "Portfolio bearbeiten",
    history: "Konfigurationshistorie",
    version: "Version",
    archive: "Portfolio archivieren",
    remove: "Portfolio löschen",
    confirm:
      "Dieses archivierte Portfolio und seine private Historie endgültig löschen?",
    cancel: "Abbrechen",
    refresh: "Aktualisieren",
    back: "Zurück",
    next: "Nächste Seite",
    loading: "Portfolios werden geladen…",
    empty: "Keine gespeicherten Portfolios.",
    failed:
      "Das Portfolio ist nicht verfügbar. Aktualisieren Sie und versuchen Sie es erneut.",
    conflict:
      "Das Portfolio wurde geändert. Aktualisieren Sie vor dem erneuten Speichern.",
    invalid:
      "Prüfen Sie Markennamen, Phrasenvarianten und Klassennummern (1–45).",
    unavailable:
      "Marken-Monitoring ist für dieses Konto oder diese Umgebung nicht verfügbar.",
    readonly:
      "Sie können Ihre gespeicherten Portfolios lesen. Änderungen benötigen die Rolle Organisationsadministrator.",
    draft: "Entwurf",
    active: "Aktiv",
    paused: "Pausiert",
    archived: "Archiviert",
  },
  "fr-CH": {
    title: "Veille des marques et de la PI",
    intro:
      "Enregistrez les marques et les produits ou services à surveiller en Suisse.",
    private:
      "Vos portefeuilles sont privés à votre compte dans cette organisation.",
    source:
      "L’accès officiel à l’IPI et les droits de la source ne sont pas configurés. L’enregistrement crée un brouillon ; il ne lance aucune recherche et n’envoie aucun e-mail.",
    assessment:
      "La similitude des noms produit des candidats à examiner en PI. Elle ne confirme ni contrefaçon ni conflit juridique. Une classe commune ne prouve pas à elle seule la similitude des produits ou services.",
    calibration:
      "Les méthodes de similitude nécessitent un calibrage vérifié pour la langue du nom. Une prononciation non prise en charge reste indisponible.",
    saved: "Portefeuilles enregistrés",
    create: "Créer un portefeuille",
    portfolio: "Nom du portefeuille",
    brands: "Marques surveillées",
    brand: "Nom de marque",
    addBrand: "Ajouter une marque",
    removeBrand: "Retirer la marque",
    language: "Langue du nom",
    exact: "Surveiller les noms exacts",
    similar: "Surveiller les noms similaires",
    variants: "Variantes de mots (une par ligne, 8 au maximum)",
    owners: "Titulaires d’intérêt (un par ligne, 8 au maximum)",
    classes: "Numéros de classes de Nice (1–45, séparés par des virgules)",
    goods: "Produits et services pertinents",
    addGoods: "Ajouter un intérêt produit/service",
    removeGoods: "Retirer l’intérêt",
    interest: "Nom de l’intérêt",
    phrase: "Expression de recherche",
    phraseLanguage: "Langue de l’expression",
    addPhrase: "Ajouter une variante",
    removePhrase: "Retirer l’expression",
    goodsHelp:
      "Saisissez les termes de vos produits ou services. Ajoutez des variantes explicites pour chaque langue source ; la correspondance n’invente pas de traductions.",
    save: "Enregistrer le brouillon",
    edit: "Modifier le portefeuille",
    history: "Historique de configuration",
    version: "Version",
    archive: "Archiver le portefeuille",
    remove: "Supprimer le portefeuille",
    confirm:
      "Supprimer définitivement ce portefeuille archivé et son historique privé ?",
    cancel: "Annuler",
    refresh: "Actualiser",
    back: "Retour",
    next: "Page suivante",
    loading: "Chargement des portefeuilles…",
    empty: "Aucun portefeuille enregistré.",
    failed: "Le portefeuille est indisponible. Actualisez et réessayez.",
    conflict: "Le portefeuille a changé. Actualisez avant de réenregistrer.",
    invalid:
      "Vérifiez les noms de marques, les expressions et les classes (1–45).",
    unavailable:
      "La veille des marques est indisponible pour ce compte ou cet environnement.",
    readonly:
      "Vous pouvez lire vos portefeuilles. Les modifications nécessitent le rôle d’administrateur d’organisation.",
    draft: "Brouillon",
    active: "Actif",
    paused: "En pause",
    archived: "Archivé",
  },
  "it-CH": {
    title: "Monitoraggio marchi e PI",
    intro: "Salva i marchi e i prodotti o servizi da monitorare in Svizzera.",
    private:
      "I portafogli sono privati per il tuo account in questa organizzazione.",
    source:
      "L’accesso ufficiale IPI e i diritti della fonte non sono configurati. Il salvataggio crea una bozza; non avvia ricerche né invia e-mail.",
    assessment:
      "La somiglianza dei nomi genera candidati da esaminare per la PI. Non conferma contraffazioni o conflitti legali. Una classe comune da sola non dimostra prodotti o servizi simili.",
    calibration:
      "I metodi di somiglianza richiedono una calibrazione verificata per la lingua del nome. Le pronunce non supportate restano non disponibili.",
    saved: "Portafogli salvati",
    create: "Crea portafoglio",
    portfolio: "Nome del portafoglio",
    brands: "Marchi monitorati",
    brand: "Nome del marchio",
    addBrand: "Aggiungi marchio",
    removeBrand: "Rimuovi marchio",
    language: "Lingua del nome",
    exact: "Monitora nomi esatti",
    similar: "Monitora nomi simili",
    variants: "Varianti di parole (una per riga, massimo 8)",
    owners: "Titolari di interesse (uno per riga, massimo 8)",
    classes: "Numeri delle classi di Nizza (1–45, separati da virgole)",
    goods: "Prodotti e servizi pertinenti",
    addGoods: "Aggiungi interesse prodotto/servizio",
    removeGoods: "Rimuovi interesse",
    interest: "Nome dell’interesse",
    phrase: "Espressione di ricerca",
    phraseLanguage: "Lingua dell’espressione",
    addPhrase: "Aggiungi variante",
    removePhrase: "Rimuovi espressione",
    goodsHelp:
      "Inserisci i termini dei tuoi prodotti o servizi. Aggiungi varianti esplicite per ogni lingua della fonte; la corrispondenza non inventa traduzioni.",
    save: "Salva bozza",
    edit: "Modifica portafoglio",
    history: "Cronologia della configurazione",
    version: "Versione",
    archive: "Archivia portafoglio",
    remove: "Elimina portafoglio",
    confirm:
      "Eliminare definitivamente questo portafoglio archiviato e la sua cronologia privata?",
    cancel: "Annulla",
    refresh: "Aggiorna",
    back: "Indietro",
    next: "Pagina successiva",
    loading: "Caricamento portafogli…",
    empty: "Nessun portafoglio salvato.",
    failed: "Il portafoglio non è disponibile. Aggiorna e riprova.",
    conflict:
      "Il portafoglio è cambiato. Aggiorna prima di salvare nuovamente.",
    invalid: "Controlla nomi dei marchi, varianti e classi (1–45).",
    unavailable:
      "Il monitoraggio marchi non è disponibile per questo account o ambiente.",
    readonly:
      "Puoi leggere i tuoi portafogli. Le modifiche richiedono il ruolo di amministratore dell’organizzazione.",
    draft: "Bozza",
    active: "Attivo",
    paused: "In pausa",
    archived: "Archiviato",
  },
  "rm-CH": {
    title: "Monitoring da marcas e PI",
    intro:
      "Memorisai las marcas ed ils products u servetschs che Vus vulais observar en Svizra.",
    private:
      "Voss portfolios èn privats per Voss conto en questa organisaziun.",
    source:
      "L’access uffizial IPI ed ils dretgs da la funtauna n’èn betg configurads. Memorisar creescha in sboz; quai na lantscha nagina tschertga e na trametta nagins e-mails.",
    assessment:
      "La sumeglientscha da nums producescha candidats per ina controlla da PI. Ella na conferma nagina violaziun u conflict giuridic. La medema classa suletta na cumprova betg products u servetschs sumegliants.",
    calibration:
      "Metodas da sumeglientscha dovran ina calibraziun verifitgada per la lingua dal num. Pronunzias betg sustegnidas restan betg disponiblas.",
    saved: "Portfolios memorisads",
    create: "Crear portfolio",
    portfolio: "Num dal portfolio",
    brands: "Marcas observadas",
    brand: "Num da la marca",
    addBrand: "Agiuntar marca",
    removeBrand: "Allontanar marca",
    language: "Lingua dal num",
    exact: "Observar nums exacts",
    similar: "Observar nums sumegliants",
    variants: "Variantas da pleds (ina per lingia, maximalmain 8)",
    owners: "Titulars d’interess (in per lingia, maximalmain 8)",
    classes: "Numers da classas da Nizza (1–45, separads cun commas)",
    goods: "Products e servetschs relevants",
    addGoods: "Agiuntar interess per product/servetsch",
    removeGoods: "Allontanar interess",
    interest: "Num da l’interess",
    phrase: "Expressiun da tschertga",
    phraseLanguage: "Lingua da l’expressiun",
    addPhrase: "Agiuntar varianta",
    removePhrase: "Allontanar expressiun",
    goodsHelp:
      "Endatai ils terms per Voss products u servetschs. Agiuntai variantas explicitas per mintga lingua da la funtauna; il cumparegliar n’inventa naginas translaziuns.",
    save: "Memorisar sboz",
    edit: "Modifitgar portfolio",
    history: "Istorgia da la configuraziun",
    version: "Versiun",
    archive: "Archivar portfolio",
    remove: "Stizzar portfolio",
    confirm:
      "Stizzar definitivamain quest portfolio archivà e sia istorgia privata?",
    cancel: "Interrumper",
    refresh: "Actualisar",
    back: "Enavos",
    next: "Proxima pagina",
    loading: "Chargiar portfolios…",
    empty: "Nagins portfolios memorisads.",
    failed:
      "Il portfolio n’è betg disponibel. Actualisai ed empruvai danovamain.",
    conflict:
      "Il portfolio è sa midà. Actualisai avant da memorisar danovamain.",
    invalid:
      "Controllai ils nums da marcas, las variantas e las classas (1–45).",
    unavailable:
      "Il monitoring da marcas n’è betg disponibel per quest conto u ambient.",
    readonly:
      "Vus pudais leger Voss portfolios. Midadas dovran la rolla d’administratur da l’organisaziun.",
    draft: "Sboz",
    active: "Activ",
    paused: "En pausa",
    archived: "Archivà",
  },
};
