import type { Locale } from "./i18n";
const en = {
  tracking: "Register monitoring",
  check: "Check source readiness",
  start: "Start monitoring",
  pause: "Pause monitoring",
  scan: "Check register updates",
  ready: "Permitted register records are available for this portfolio.",
  blocked:
    "Monitoring needs current register records with permission for matching and display.",
  calibration: "Similarity assessment is unavailable for these languages",
  scope:
    "Results cover available permitted records only. They are candidates for IP review, not confirmed legal conflicts or a complete clearance search.",
  candidates: "Candidates for private review",
  empty:
    "No available candidates on this page. This does not establish that a mark is clear.",
  unavailable:
    "Current evidence is unavailable or needs refreshing. Previous private decisions remain retained.",
  open: "Open evidence and review",
  current: "Current evidence",
  before: "Before the change",
  at: "Evidence at detection",
  newer: "A newer review is available below.",
  history: "Register change history",
  reviews: "Private decision history",
  needsReview: "Needs review",
  reviewed: "Reviewed",
  relevant: "Relevant",
  not_relevant: "Not relevant",
  monitor: "Keep monitoring",
  counsel: "Mark for counsel",
  internal:
    "Decisions stay private. Marking for counsel does not contact anyone, file an objection or set a legal deadline.",
  unknown: "Unknown",
  mark: "Mark",
  official_id: "Register identifier",
  owners: "Owners",
  representatives: "Representatives",
  classes: "Nice classes",
  goods_services: "Goods and services",
  status: "Register status",
  origin: "Register scope",
  national_ch: "Swiss national registration",
  international_designating_ch:
    "International registration designating Switzerland",
  application_date: "Application date",
  publication_date: "Publication date",
  registration_date: "Registration date",
  renewal_date: "Renewal date",
  expiry_date: "Expiry date",
  cancellation_date: "Cancellation date",
  source: "Original register record",
  why: "Why this candidate was selected",
  exact: "Exact name",
  lexical: "Lexical similarity",
  phonetic: "Phonetic similarity",
  owner_interest: "Owner of interest",
  goods: "Matching explicit goods/service phrases",
  classHelp:
    "Class overlap alone does not establish similarity of goods or a legal conflict.",
  incomplete: "Some comparisons are unavailable; the assessment is incomplete.",
  high: "Priority: goods/service phrase overlap",
  review: "Priority: IP review",
  notSelected: "The current configuration no longer selects this record.",
  changed: "Register facts changed",
  new_candidate: "New candidate",
  portfolio_changed: "Portfolio changed",
  evaluation_changed: "Assessment changed",
  deadline_changed: "Deadline inputs changed",
  source_changed: "Source changed",
  evidence_gap: "An intermediate evidence version is unavailable",
  detected: "Detected",
  last: "Last check",
  next: "Next check",
  waiting: "Waiting for a check",
  catching_up: "Processing register updates",
  partial: "Partial assessment",
  source_unavailable: "Source unavailable",
  healthy: "Available records checked",
  today: "Trademark Watch · Today",
  inbox: "Trademark Watch · pending reviews",
};
type Copy = { [K in keyof typeof en]: string };
export const trademarkReviewCopy: Record<Locale, Copy> = {
  "en-CH": en,
  "de-CH": {
    tracking: "Registerüberwachung",
    check: "Quellenbereitschaft prüfen",
    start: "Überwachung starten",
    pause: "Überwachung pausieren",
    scan: "Registeränderungen prüfen",
    ready: "Zulässige Registerdaten sind für dieses Portfolio verfügbar.",
    blocked:
      "Die Überwachung benötigt aktuelle Registerdaten mit Erlaubnis für Abgleich und Anzeige.",
    calibration: "Ähnlichkeitsprüfung für diese Sprachen nicht verfügbar",
    scope:
      "Ergebnisse beziehen sich nur auf verfügbare, zulässige Datensätze. Sie sind Kandidaten zur IP-Prüfung, keine bestätigten Rechtskonflikte oder vollständige Markenrecherche.",
    candidates: "Kandidaten zur privaten Prüfung",
    empty:
      "Keine verfügbaren Kandidaten auf dieser Seite. Dies bestätigt keine freie Marke.",
    unavailable:
      "Aktuelle Belege fehlen oder müssen aktualisiert werden. Bisherige private Entscheidungen bleiben erhalten.",
    open: "Belege und Prüfung öffnen",
    current: "Aktuelle Belege",
    before: "Vor der Änderung",
    at: "Belege bei Erkennung",
    newer: "Eine neuere Prüfung ist unten verfügbar.",
    history: "Registeränderungen",
    reviews: "Private Entscheidungen",
    needsReview: "Prüfung erforderlich",
    reviewed: "Geprüft",
    relevant: "Relevant",
    not_relevant: "Nicht relevant",
    monitor: "Weiter beobachten",
    counsel: "Für Rechtsberatung markieren",
    internal:
      "Entscheidungen bleiben privat. Die Markierung kontaktiert niemanden, erhebt keinen Widerspruch und setzt keine Rechtsfrist.",
    unknown: "Unbekannt",
    mark: "Marke",
    official_id: "Registerkennung",
    owners: "Inhaber",
    representatives: "Vertreter",
    classes: "Nizza-Klassen",
    goods_services: "Waren und Dienstleistungen",
    status: "Registerstatus",
    origin: "Registerumfang",
    national_ch: "Nationale Schweizer Eintragung",
    international_designating_ch:
      "Internationale Eintragung mit Schutz für die Schweiz",
    application_date: "Anmeldedatum",
    publication_date: "Veröffentlichungsdatum",
    registration_date: "Eintragungsdatum",
    renewal_date: "Verlängerungsdatum",
    expiry_date: "Ablaufdatum",
    cancellation_date: "Löschdatum",
    source: "Originaler Registereintrag",
    why: "Grund der Auswahl",
    exact: "Exakter Name",
    lexical: "Lexikalische Ähnlichkeit",
    phonetic: "Phonetische Ähnlichkeit",
    owner_interest: "Beobachteter Inhaber",
    goods: "Übereinstimmende ausdrückliche Waren-/Dienstleistungsbegriffe",
    classHelp:
      "Klassenüberschneidung allein belegt keine Warenähnlichkeit oder Rechtskollision.",
    incomplete: "Einige Vergleiche fehlen; die Bewertung ist unvollständig.",
    high: "Priorität: Waren-/Dienstleistungsbegriffe überschneiden sich",
    review: "Priorität: IP-Prüfung",
    notSelected:
      "Die aktuelle Konfiguration wählt diesen Eintrag nicht mehr aus.",
    changed: "Registerdaten geändert",
    new_candidate: "Neuer Kandidat",
    portfolio_changed: "Portfolio geändert",
    evaluation_changed: "Bewertung geändert",
    deadline_changed: "Fristgrundlagen geändert",
    source_changed: "Quelle geändert",
    evidence_gap: "Eine zwischenzeitliche Belegversion fehlt",
    detected: "Erkannt",
    last: "Letzte Prüfung",
    next: "Nächste Prüfung",
    waiting: "Wartet auf Prüfung",
    catching_up: "Registeränderungen werden verarbeitet",
    partial: "Teilweise Bewertung",
    source_unavailable: "Quelle nicht verfügbar",
    healthy: "Verfügbare Einträge geprüft",
    today: "Trademark Watch · Heute",
    inbox: "Trademark Watch · offene Prüfungen",
  },
  "fr-CH": {
    tracking: "Veille du registre",
    check: "Vérifier les sources",
    start: "Démarrer la veille",
    pause: "Mettre en pause",
    scan: "Vérifier les changements",
    ready: "Des données autorisées sont disponibles pour ce portefeuille.",
    blocked:
      "La veille nécessite des données récentes autorisées pour la comparaison et l’affichage.",
    calibration: "Comparaison de similarité indisponible pour ces langues",
    scope:
      "Les résultats couvrent seulement les données disponibles et autorisées. Ce sont des candidats à examiner en PI, pas des conflits juridiques confirmés ni une recherche exhaustive.",
    candidates: "Candidats à examiner en privé",
    empty:
      "Aucun candidat disponible sur cette page. Cela ne confirme pas la disponibilité d’une marque.",
    unavailable:
      "Les preuves actuelles sont indisponibles ou à actualiser. Les décisions privées précédentes sont conservées.",
    open: "Ouvrir les preuves et l’examen",
    current: "Preuves actuelles",
    before: "Avant le changement",
    at: "Preuves lors de la détection",
    newer: "Un examen plus récent est disponible ci-dessous.",
    history: "Historique des changements",
    reviews: "Historique des décisions privées",
    needsReview: "À examiner",
    reviewed: "Examiné",
    relevant: "Pertinent",
    not_relevant: "Non pertinent",
    monitor: "Continuer la veille",
    counsel: "Marquer pour conseil juridique",
    internal:
      "Les décisions restent privées. Ce marquage ne contacte personne, ne dépose aucune opposition et ne fixe aucun délai juridique.",
    unknown: "Inconnu",
    mark: "Marque",
    official_id: "Identifiant du registre",
    owners: "Titulaires",
    representatives: "Mandataires",
    classes: "Classes de Nice",
    goods_services: "Produits et services",
    status: "Statut au registre",
    origin: "Portée du registre",
    national_ch: "Enregistrement national suisse",
    international_designating_ch:
      "Enregistrement international désignant la Suisse",
    application_date: "Date de dépôt",
    publication_date: "Date de publication",
    registration_date: "Date d’enregistrement",
    renewal_date: "Date de renouvellement",
    expiry_date: "Date d’expiration",
    cancellation_date: "Date de radiation",
    source: "Entrée originale du registre",
    why: "Motif de sélection",
    exact: "Nom exact",
    lexical: "Similarité lexicale",
    phonetic: "Similarité phonétique",
    owner_interest: "Titulaire suivi",
    goods: "Expressions explicites de produits/services correspondantes",
    classHelp:
      "Des classes communes ne prouvent pas seules la similarité des produits ni un conflit juridique.",
    incomplete:
      "Certaines comparaisons sont indisponibles ; l’évaluation est incomplète.",
    high: "Priorité : expressions de produits/services communes",
    review: "Priorité : examen PI",
    notSelected: "La configuration actuelle ne sélectionne plus cette entrée.",
    changed: "Données du registre modifiées",
    new_candidate: "Nouveau candidat",
    portfolio_changed: "Portefeuille modifié",
    evaluation_changed: "Évaluation modifiée",
    deadline_changed: "Bases du délai modifiées",
    source_changed: "Source modifiée",
    evidence_gap: "Une version intermédiaire des preuves manque",
    detected: "Détecté",
    last: "Dernière vérification",
    next: "Prochaine vérification",
    waiting: "En attente de vérification",
    catching_up: "Traitement des changements",
    partial: "Évaluation partielle",
    source_unavailable: "Source indisponible",
    healthy: "Données disponibles vérifiées",
    today: "Trademark Watch · Aujourd’hui",
    inbox: "Trademark Watch · examens en attente",
  },
  "it-CH": {
    tracking: "Monitoraggio del registro",
    check: "Verifica le fonti",
    start: "Avvia monitoraggio",
    pause: "Metti in pausa",
    scan: "Verifica gli aggiornamenti",
    ready: "Sono disponibili dati autorizzati per questo portafoglio.",
    blocked:
      "Il monitoraggio richiede dati recenti autorizzati per confronto e visualizzazione.",
    calibration: "Valutazione di somiglianza non disponibile per queste lingue",
    scope:
      "I risultati coprono solo dati disponibili e autorizzati. Sono candidati alla revisione PI, non conflitti legali confermati o una ricerca completa.",
    candidates: "Candidati alla revisione privata",
    empty:
      "Nessun candidato disponibile su questa pagina. Ciò non conferma la disponibilità di un marchio.",
    unavailable:
      "Le prove attuali non sono disponibili o vanno aggiornate. Le decisioni private precedenti restano conservate.",
    open: "Apri prove e revisione",
    current: "Prove attuali",
    before: "Prima della modifica",
    at: "Prove al rilevamento",
    newer: "Una revisione più recente è disponibile sotto.",
    history: "Cronologia delle modifiche",
    reviews: "Cronologia delle decisioni private",
    needsReview: "Da esaminare",
    reviewed: "Esaminato",
    relevant: "Rilevante",
    not_relevant: "Non rilevante",
    monitor: "Continua monitoraggio",
    counsel: "Segna per consulenza legale",
    internal:
      "Le decisioni restano private. Il contrassegno non contatta nessuno, non deposita opposizioni e non fissa scadenze legali.",
    unknown: "Sconosciuto",
    mark: "Marchio",
    official_id: "Identificativo del registro",
    owners: "Titolari",
    representatives: "Rappresentanti",
    classes: "Classi di Nizza",
    goods_services: "Prodotti e servizi",
    status: "Stato nel registro",
    origin: "Ambito del registro",
    national_ch: "Registrazione nazionale svizzera",
    international_designating_ch:
      "Registrazione internazionale designante la Svizzera",
    application_date: "Data di domanda",
    publication_date: "Data di pubblicazione",
    registration_date: "Data di registrazione",
    renewal_date: "Data di rinnovo",
    expiry_date: "Data di scadenza",
    cancellation_date: "Data di cancellazione",
    source: "Voce originale del registro",
    why: "Motivo della selezione",
    exact: "Nome esatto",
    lexical: "Somiglianza lessicale",
    phonetic: "Somiglianza fonetica",
    owner_interest: "Titolare seguito",
    goods: "Espressioni esplicite di prodotti/servizi corrispondenti",
    classHelp:
      "Le classi comuni da sole non provano somiglianza di prodotti o conflitti legali.",
    incomplete:
      "Alcuni confronti non sono disponibili; la valutazione è incompleta.",
    high: "Priorità: espressioni di prodotti/servizi comuni",
    review: "Priorità: revisione PI",
    notSelected: "La configurazione attuale non seleziona più questa voce.",
    changed: "Dati del registro modificati",
    new_candidate: "Nuovo candidato",
    portfolio_changed: "Portafoglio modificato",
    evaluation_changed: "Valutazione modificata",
    deadline_changed: "Basi del termine modificate",
    source_changed: "Fonte modificata",
    evidence_gap: "Una versione intermedia delle prove non è disponibile",
    detected: "Rilevato",
    last: "Ultima verifica",
    next: "Prossima verifica",
    waiting: "In attesa di verifica",
    catching_up: "Elaborazione degli aggiornamenti",
    partial: "Valutazione parziale",
    source_unavailable: "Fonte non disponibile",
    healthy: "Dati disponibili verificati",
    today: "Trademark Watch · Oggi",
    inbox: "Trademark Watch · revisioni in attesa",
  },
  "rm-CH": {
    tracking: "Surveglianza dal register",
    check: "Verifitgar las funtaunas",
    start: "Cumenzar la surveglianza",
    pause: "Metter en pausa",
    scan: "Verifitgar midadas",
    ready: "Datas autorisadas èn disponiblas per quest portfolio.",
    blocked:
      "La surveglianza dovra datas actualas cun permissiun per cumparegliar e mussar.",
    calibration:
      "Valitaziun da sumeglientscha betg disponibla per questas linguas",
    scope:
      "Ils resultats cuvran mo datas disponiblas ed autorisadas. Els èn candidats per ina controlla da PI, betg conflicts giuridics confermads u ina tschertga cumpletta.",
    candidates: "Candidats per controlla privata",
    empty:
      "Nagins candidats disponibels sin questa pagina. Quai na conferma betg ina marca libra.",
    unavailable:
      "Las cumprovas actualas mancan u ston vegnir actualisadas. Las decisiuns privatas precedentas restan conservadas.",
    open: "Avrir cumprovas e controlla",
    current: "Cumprovas actualas",
    before: "Avant la midada",
    at: "Cumprovas a la detecziun",
    newer: "Ina controlla pli nova è disponibla sutvart.",
    history: "Istorgia da las midadas",
    reviews: "Istorgia da las decisiuns privatas",
    needsReview: "Da controllar",
    reviewed: "Controllà",
    relevant: "Relevant",
    not_relevant: "Betg relevant",
    monitor: "Cuntinuar la surveglianza",
    counsel: "Marcar per cussegl giuridic",
    internal:
      "Las decisiuns restan privatas. La marca na contactescha nagin, na inoltra nagina opposiziun e na fixescha nagin termin giuridic.",
    unknown: "Nunenconuschent",
    mark: "Marca",
    official_id: "Identificatur dal register",
    owners: "Titulars",
    representatives: "Represchentants",
    classes: "Classas da Nizza",
    goods_services: "Rauba e servetschs",
    status: "Status dal register",
    origin: "Sectur dal register",
    national_ch: "Registraziun naziunala svizra",
    international_designating_ch:
      "Registraziun internaziunala cun designaziun da la Svizra",
    application_date: "Data da dumonda",
    publication_date: "Data da publicaziun",
    registration_date: "Data da registraziun",
    renewal_date: "Data da renovaziun",
    expiry_date: "Data da scadenza",
    cancellation_date: "Data da radiaziun",
    source: "Endataziun originala dal register",
    why: "Motiv da la selecziun",
    exact: "Num exact",
    lexical: "Sumeglientscha lexicala",
    phonetic: "Sumeglientscha fonetica",
    owner_interest: "Titular observà",
    goods: "Expressiuns explicitas correspundentas da rauba/servetschs",
    classHelp:
      "Classas communablas na cumprovan betg sulettas sumeglientscha da rauba u in conflict giuridic.",
    incomplete:
      "Intginas cumparegliaziuns mancan; la valitaziun è incumpletta.",
    high: "Prioritad: expressiuns da rauba/servetschs communablas",
    review: "Prioritad: controlla PI",
    notSelected:
      "La configuraziun actuala na selecziunescha betg pli questa endataziun.",
    changed: "Datas dal register midadas",
    new_candidate: "Nov candidat",
    portfolio_changed: "Portfolio midà",
    evaluation_changed: "Valitaziun midada",
    deadline_changed: "Basas dal termin midadas",
    source_changed: "Funtauna midada",
    evidence_gap: "Ina versiun intermediara da las cumprovas manca",
    detected: "Chattà",
    last: "Ultima controlla",
    next: "Proxima controlla",
    waiting: "Spetga ina controlla",
    catching_up: "Elavuraziun da las midadas",
    partial: "Valitaziun parziala",
    source_unavailable: "Funtauna betg disponibla",
    healthy: "Datas disponiblas controlladas",
    today: "Trademark Watch · Oz",
    inbox: "Trademark Watch · controllas pendentas",
  },
};
export function trademarkChangeLabel(
  locale: keyof typeof trademarkReviewCopy,
  code: string,
) {
  const c = trademarkReviewCopy[locale];
  const field = code.replace(/^changed_/, "");
  return code.startsWith("changed_") && field in c
    ? `${c.changed}: ${c[field as keyof Copy]}`
    : c[code as keyof Copy] || c.changed;
}
