"""Server-authored review prose; source wording is never translated here."""

COPY = {
    "en-CH": {
        "unassigned": "Not assigned",
        "passage": "Passage",
        "review": "Impact review",
        "added": "Added {label}",
        "removed": "Removed {label}",
        "modified": "Modified {label}",
        "added_text": "New wording: “{new}”",
        "removed_text": "Earlier wording removed: “{old}”",
        "modified_text": "Earlier: “{old}” Current: “{new}”",
        "unknown_scope": "Applicability to the organization has not been established. Review the cited scope against its actual activities.",
        "unknown_status": "The official legal status has not been assessed from the supplied evidence.",
        "unknown_actions": "No decision about next actions has been established. An empty list does not mean that no action is needed.",
        "interpretation": "AI interpretations and review suggestions require checking against the cited wording and organization facts.",
        "limited": "Review coverage is partial; other material changes remain in the saved comparison.",
        "no_change": "The complete saved comparison contains no substantive wording changes after formatting and structural differences are excluded.",
        "no_change_reason": "This comparison does not require an AI change assessment. It does not establish whether unchanged rules apply to the organization.",
    },
    "de-CH": {
        "unassigned": "Nicht zugewiesen",
        "passage": "Passage",
        "review": "Wirkungsprüfung",
        "added": "Hinzugefügt: {label}",
        "removed": "Entfernt: {label}",
        "modified": "Geändert: {label}",
        "added_text": "Neuer Wortlaut: «{new}»",
        "removed_text": "Entfernter früherer Wortlaut: «{old}»",
        "modified_text": "Früher: «{old}» Aktuell: «{new}»",
        "unknown_scope": "Die Anwendbarkeit auf die Organisation ist nicht festgestellt. Prüfen Sie den belegten Geltungsbereich anhand ihrer tatsächlichen Tätigkeiten.",
        "unknown_status": "Der offizielle Rechtsstatus wurde anhand der vorliegenden Belege nicht beurteilt.",
        "unknown_actions": "Es wurde kein Entscheid über nächste Schritte festgestellt. Eine leere Liste bedeutet nicht, dass kein Handlungsbedarf besteht.",
        "interpretation": "KI-Auslegungen und Prüfvorschläge müssen anhand des zitierten Wortlauts und der Organisationsangaben geprüft werden.",
        "limited": "Die Prüfung ist unvollständig; weitere wesentliche Änderungen bleiben im gespeicherten Vergleich.",
        "no_change": "Der vollständige gespeicherte Vergleich enthält nach Ausschluss von Formatierungs- und Strukturunterschieden keine wesentlichen Wortlautänderungen.",
        "no_change_reason": "Dieser Vergleich benötigt keine KI-Änderungsbewertung. Er stellt nicht fest, ob unveränderte Regeln auf die Organisation anwendbar sind.",
    },
    "fr-CH": {
        "unassigned": "Non attribué",
        "passage": "Passage",
        "review": "Examen de l’impact",
        "added": "Ajout : {label}",
        "removed": "Suppression : {label}",
        "modified": "Modification : {label}",
        "added_text": "Nouvelle formulation : « {new} »",
        "removed_text": "Ancienne formulation supprimée : « {old} »",
        "modified_text": "Avant : « {old} » Maintenant : « {new} »",
        "unknown_scope": "L’applicabilité à l’organisation n’est pas établie. Vérifiez le champ d’application cité au regard de ses activités réelles.",
        "unknown_status": "Le statut juridique officiel n’a pas été évalué à partir des preuves fournies.",
        "unknown_actions": "Aucune décision sur les prochaines actions n’est établie. Une liste vide ne signifie pas qu’aucune action n’est nécessaire.",
        "interpretation": "Les interprétations et suggestions de l’IA doivent être vérifiées à partir du texte cité et des faits de l’organisation.",
        "limited": "L’examen est partiel ; d’autres modifications importantes restent dans la comparaison enregistrée.",
        "no_change": "La comparaison complète ne contient aucune modification substantielle du texte après exclusion des différences de mise en forme et de structure.",
        "no_change_reason": "Cette comparaison ne nécessite pas d’évaluation des changements par l’IA. Elle n’établit pas si les règles inchangées s’appliquent à l’organisation.",
    },
    "it-CH": {
        "unassigned": "Non assegnato",
        "passage": "Passaggio",
        "review": "Esame dell’impatto",
        "added": "Aggiunta: {label}",
        "removed": "Rimozione: {label}",
        "modified": "Modifica: {label}",
        "added_text": "Nuova formulazione: «{new}»",
        "removed_text": "Formulazione precedente rimossa: «{old}»",
        "modified_text": "Prima: «{old}» Ora: «{new}»",
        "unknown_scope": "L’applicabilità all’organizzazione non è stata stabilita. Verificare l’ambito citato rispetto alle sue attività effettive.",
        "unknown_status": "Lo stato giuridico ufficiale non è stato valutato sulla base delle prove fornite.",
        "unknown_actions": "Non è stata stabilita una decisione sulle prossime azioni. Un elenco vuoto non significa che non sia necessario agire.",
        "interpretation": "Le interpretazioni e i suggerimenti dell’IA richiedono una verifica del testo citato e dei fatti dell’organizzazione.",
        "limited": "L’esame è parziale; altre modifiche sostanziali restano nel confronto salvato.",
        "no_change": "Il confronto completo salvato non contiene modifiche sostanziali del testo dopo l’esclusione delle differenze di formato e struttura.",
        "no_change_reason": "Questo confronto non richiede una valutazione delle modifiche da parte dell’IA. Non stabilisce se le regole invariate si applicano all’organizzazione.",
    },
    "rm-CH": {
        "unassigned": "Betg attribuì",
        "passage": "Passadi",
        "review": "Examinaziun da l’impact",
        "added": "Agiuntà: {label}",
        "removed": "Allontanà: {label}",
        "modified": "Midà: {label}",
        "added_text": "Nova formulaziun: «{new}»",
        "removed_text": "Formulaziun anteriura allontanada: «{old}»",
        "modified_text": "Pli baud: «{old}» Ussa: «{new}»",
        "unknown_scope": "L’applicabladad a l’organisaziun n’è betg stabilida. Examinai il champ d’applicaziun cità tenor sias activitads effectivas.",
        "unknown_status": "Il status giuridic uffizial n’è betg vegnì valità a basa da las cumprovas furnidas.",
        "unknown_actions": "Nagina decisiun davart ils proxims pass n’è stabilida. Ina glista vida na signifitga betg ch’i na dovria nagina acziun.",
        "interpretation": "Las interpretaziuns e propostas da l’IA ston vegnir examinadas a basa dal text cità e dals fatgs da l’organisaziun.",
        "limited": "L’examinaziun è parziala; ulteriuras midadas essenzialas restan en la cumparegliaziun memorisada.",
        "no_change": "La cumparegliaziun cumpletta memorisada na cuntegna naginas midadas essenzialas dal text suenter l’exclusiun da differenzas da format e structura.",
        "no_change_reason": "Questa cumparegliaziun na dovra nagina valitaziun da midadas da l’IA. Ella na stabilescha betg sche las reglas nunmidadas s’applitgeschan a l’organisaziun.",
    },
}


def decision_copy(locale: str) -> dict:
    return COPY.get(locale, COPY["en-CH"])
