"""Permission-bound trademark register evidence.

Revision ID: 5efb1c69dc50
Revises: 4dfa0b58cb4f
"""
import sqlalchemy as sa

from alembic import op

revision = "5efb1c69dc50"
down_revision = "4dfa0b58cb4f"
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trademark_source_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('policy_hash', sa.String(length=64), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trademark_register_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('record_key', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('material_sequence', sa.Integer(), nullable=False),
    sa.Column('material_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.LargeBinary(), nullable=True),
    sa.Column('raw_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('normalized_hash', sa.String(length=64), nullable=False),
    sa.Column('normalized_payload', sa.LargeBinary(), nullable=True),
    sa.Column('normalized_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sequence >= 1 AND material_sequence >= 1', name='ck_trademark_register_sequence'),
    sa.ForeignKeyConstraint(['permission_id'], ['trademark_source_permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'permission_id', 'record_key', name='uq_trademark_register_scope'),
    sa.UniqueConstraint('permission_id', 'record_key', 'sequence', name='uq_trademark_register_sequence')
    )
    op.create_index(op.f('ix_trademark_register_revisions_normalized_expires_at'), 'trademark_register_revisions', ['normalized_expires_at'], unique=False)
    op.create_index(op.f('ix_trademark_register_revisions_permission_id'), 'trademark_register_revisions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_trademark_register_revisions_raw_expires_at'), 'trademark_register_revisions', ['raw_expires_at'], unique=False)
    op.create_table('trademark_source_selections',
    sa.Column('source_key', sa.String(length=80), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('cursor_version', sa.Integer(), nullable=False),
    sa.Column('last_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('generation >= 1 AND cursor_version >= 0', name='ck_trademark_source_selection'),
    sa.ForeignKeyConstraint(['permission_id'], ['trademark_source_permissions.id'], ),
    sa.PrimaryKeyConstraint('source_key')
    )
    op.create_table('trademark_register_heads',
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('record_key', sa.String(length=64), nullable=False),
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('generation >= 1', name='ck_trademark_head_generation'),
    sa.ForeignKeyConstraint(['permission_id'], ['trademark_source_permissions.id'], ),
    sa.ForeignKeyConstraint(['revision_id', 'permission_id', 'record_key'], ['trademark_register_revisions.id', 'trademark_register_revisions.permission_id', 'trademark_register_revisions.record_key'], name='fk_trademark_head_revision'),
    sa.PrimaryKeyConstraint('permission_id', 'record_key')
    )
    op.create_table('trademark_source_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('record_key', sa.String(length=64), nullable=False),
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('cursor_version', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('change', sa.JSON(), nullable=False),
    sa.CheckConstraint('generation >= 1 AND cursor_version >= 1', name='ck_trademark_source_receipt'),
    sa.ForeignKeyConstraint(['permission_id'], ['trademark_source_permissions.id'], ),
    sa.ForeignKeyConstraint(['revision_id', 'permission_id', 'record_key'], ['trademark_register_revisions.id', 'trademark_register_revisions.permission_id', 'trademark_register_revisions.record_key'], name='fk_trademark_receipt_revision'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_id', 'generation', 'request_key', name='uq_trademark_source_request')
    )
    op.create_index(op.f('ix_trademark_source_receipts_permission_id'), 'trademark_source_receipts', ['permission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trademark_source_receipts_permission_id'), table_name='trademark_source_receipts')
    op.drop_table('trademark_source_receipts')
    op.drop_table('trademark_register_heads')
    op.drop_table('trademark_source_selections')
    op.drop_index(op.f('ix_trademark_register_revisions_raw_expires_at'), table_name='trademark_register_revisions')
    op.drop_index(op.f('ix_trademark_register_revisions_permission_id'), table_name='trademark_register_revisions')
    op.drop_index(op.f('ix_trademark_register_revisions_normalized_expires_at'), table_name='trademark_register_revisions')
    op.drop_table('trademark_register_revisions')
    op.drop_table('trademark_source_permissions')
    # ### end Alembic commands ###
