"""initial_schema

Revision ID: 7520cab4fdac
Revises:
Create Date: 2026-08-31 18:02:59.417950

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7520cab4fdac"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("business_areas", sa.JSON(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("section", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_checked", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("discovery", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "laws",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("current_version_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_checked", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_result", sa.String(length=40), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("law_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("extractor", sa.String(length=40), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("passages", sa.JSON(), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("artifact_key", sa.String(length=80), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("origin", sa.String(length=30), nullable=False),
        sa.Column("declared_date", sa.String(length=10), nullable=True),
        sa.Column("date_provenance", sa.String(length=30), nullable=True),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["law_id"],
            ["laws.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("law_id", "content_hash", "extractor", name="uq_law_content"),
    )
    op.create_index(op.f("ix_versions_law_id"), "versions", ["law_id"], unique=False)
    op.create_table(
        "comparisons",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("law_id", sa.String(length=36), nullable=False),
        sa.Column("old_version_id", sa.String(length=36), nullable=False),
        sa.Column("new_version_id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=30), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["law_id"],
            ["laws.id"],
        ),
        sa.ForeignKeyConstraint(
            ["new_version_id"],
            ["versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["old_version_id"],
            ["versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("old_version_id", "new_version_id", "mode", name="uq_comparison_pair"),
    )
    op.create_index(op.f("ix_comparisons_law_id"), "comparisons", ["law_id"], unique=False)
    op.create_table(
        "observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("law_id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("origin", sa.String(length=30), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("artifact_key", sa.String(length=80), nullable=False),
        sa.Column("declared_date", sa.String(length=10), nullable=True),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["law_id"],
            ["laws.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_observations_law_id"), "observations", ["law_id"], unique=False)
    op.create_index(op.f("ix_observations_version_id"), "observations", ["version_id"], unique=False)
    op.create_table(
        "analyses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("comparison_id", sa.String(length=36), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("coverage", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["comparison_id"],
            ["comparisons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_analyses_cache_key"), "analyses", ["cache_key"], unique=False)
    op.create_index(op.f("ix_analyses_comparison_id"), "analyses", ["comparison_id"], unique=False)
    op.create_table(
        "scan_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scan_id", sa.String(length=36), nullable=False),
        sa.Column("law_id", sa.String(length=36), nullable=False),
        sa.Column("baseline_version_id", sa.String(length=36), nullable=True),
        sa.Column("new_version_id", sa.String(length=36), nullable=True),
        sa.Column("comparison_id", sa.String(length=36), nullable=True),
        sa.Column("monitoring_comparison_id", sa.String(length=36), nullable=True),
        sa.Column("mode", sa.String(length=30), nullable=False),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("result", sa.String(length=40), nullable=True),
        sa.Column("live_result", sa.String(length=40), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("analysis_status", sa.String(length=30), nullable=False),
        sa.Column("events", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_version_id"],
            ["versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["comparison_id"],
            ["comparisons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["law_id"],
            ["laws.id"],
        ),
        sa.ForeignKeyConstraint(
            ["monitoring_comparison_id"],
            ["comparisons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["new_version_id"],
            ["versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scan_items_law_id"), "scan_items", ["law_id"], unique=False)
    op.create_index(op.f("ix_scan_items_scan_id"), "scan_items", ["scan_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scan_items_scan_id"), table_name="scan_items")
    op.drop_index(op.f("ix_scan_items_law_id"), table_name="scan_items")
    op.drop_table("scan_items")
    op.drop_index(op.f("ix_analyses_comparison_id"), table_name="analyses")
    op.drop_index(op.f("ix_analyses_cache_key"), table_name="analyses")
    op.drop_table("analyses")
    op.drop_index(op.f("ix_observations_version_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_law_id"), table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_comparisons_law_id"), table_name="comparisons")
    op.drop_table("comparisons")
    op.drop_index(op.f("ix_versions_law_id"), table_name="versions")
    op.drop_table("versions")
    op.drop_table("laws")
    op.drop_table("sources")
    op.drop_table("scans")
    op.drop_table("profiles")
    # ### end Alembic commands ###
