"""Owner-private auction tracking, review and source cursors."""
import sqlalchemy as sa

from alembic import op

revision = "81ce4f920a83"
down_revision = "70bd3e81fe72"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('monitor_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('record_key', sa.String(length=64), nullable=False),
    sa.Column('source_key', sa.String(length=80), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('source_revision_id', sa.String(length=36), nullable=False),
    sa.Column('source_generation', sa.Integer(), nullable=False),
    sa.Column('profile_revision', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('material_sequence', sa.Integer(), nullable=False),
    sa.Column('reviewed_sequence', sa.Integer(), nullable=False),
    sa.Column('following', sa.Boolean(), nullable=False),
    sa.Column('decision', sa.String(length=12), nullable=True),
    sa.Column('deadline_generation', sa.Integer(), nullable=False),
    sa.Column('deadline_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IS NULL OR decision IN ('inspect','bid','no_bid','monitor')", name='ck_auction_item_decision'),
    sa.CheckConstraint('version >= 1 AND material_sequence >= 1 AND reviewed_sequence >= 0 AND deadline_generation >= 1', name='ck_auction_item_versions'),
    sa.ForeignKeyConstraint(['monitor_id', 'organization_id'], ['auction_monitors.id', 'auction_monitors.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['auction_source_permissions.id'], ),
    sa.ForeignKeyConstraint(['source_revision_id', 'permission_id', 'record_key'], ['auction_source_record_revisions.id', 'auction_source_record_revisions.permission_id', 'auction_source_record_revisions.record_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_auction_item_scope'),
    sa.UniqueConstraint('monitor_id', 'record_key', name='uq_auction_item_identity')
    )
    op.create_index(op.f('ix_auction_items_monitor_id'), 'auction_items', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_auction_items_organization_id'), 'auction_items', ['organization_id'], unique=False)
    op.create_table('auction_private_source_cursors',
    sa.Column('monitor_id', sa.String(length=36), nullable=False),
    sa.Column('source_key', sa.String(length=80), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('after_key', sa.String(length=64), nullable=True),
    sa.CheckConstraint('generation >= 1', name='ck_auction_private_cursor_generation'),
    sa.ForeignKeyConstraint(['monitor_id', 'organization_id'], ['auction_monitors.id', 'auction_monitors.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['auction_source_permissions.id'], ),
    sa.PrimaryKeyConstraint('monitor_id', 'source_key')
    )
    op.create_index(op.f('ix_auction_private_source_cursors_organization_id'), 'auction_private_source_cursors', ['organization_id'], unique=False)
    op.create_table('auction_runtimes',
    sa.Column('monitor_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('health', sa.String(length=40), nullable=False),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id', 'organization_id'], ['auction_monitors.id', 'auction_monitors.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monitor_id')
    )
    op.create_index(op.f('ix_auction_runtimes_next_check_at'), 'auction_runtimes', ['next_check_at'], unique=False)
    op.create_index(op.f('ix_auction_runtimes_organization_id'), 'auction_runtimes', ['organization_id'], unique=False)
    op.create_table('auction_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('item_version', sa.Integer(), nullable=False),
    sa.Column('material_sequence', sa.Integer(), nullable=False),
    sa.Column('source_revision_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=12), nullable=True),
    sa.Column('following', sa.Boolean(), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IS NULL OR decision IN ('inspect','bid','no_bid','monitor')", name='ck_auction_decision_value'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id', 'organization_id'], ['auction_items.id', 'auction_items.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_revision_id'], ['auction_source_record_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'item_version', name='uq_auction_decision_version')
    )
    op.create_index(op.f('ix_auction_decisions_item_id'), 'auction_decisions', ['item_id'], unique=False)
    op.create_index(op.f('ix_auction_decisions_organization_id'), 'auction_decisions', ['organization_id'], unique=False)
    op.create_table('auction_item_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('source_revision_id', sa.String(length=36), nullable=False),
    sa.Column('previous_revision_id', sa.String(length=36), nullable=True),
    sa.Column('profile_revision', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('change_codes', sa.JSON(), nullable=False),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sequence >= 1 AND profile_revision >= 1', name='ck_auction_item_event_sequence'),
    sa.ForeignKeyConstraint(['item_id', 'organization_id'], ['auction_items.id', 'auction_items.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_revision_id'], ['auction_source_record_revisions.id'], ),
    sa.ForeignKeyConstraint(['source_revision_id'], ['auction_source_record_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'sequence', name='uq_auction_item_event_sequence')
    )
    op.create_index(op.f('ix_auction_item_events_created_at'), 'auction_item_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_auction_item_events_item_id'), 'auction_item_events', ['item_id'], unique=False)
    op.create_index(op.f('ix_auction_item_events_organization_id'), 'auction_item_events', ['organization_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auction_item_events_organization_id'), table_name='auction_item_events')
    op.drop_index(op.f('ix_auction_item_events_item_id'), table_name='auction_item_events')
    op.drop_index(op.f('ix_auction_item_events_created_at'), table_name='auction_item_events')
    op.drop_table('auction_item_events')
    op.drop_index(op.f('ix_auction_decisions_organization_id'), table_name='auction_decisions')
    op.drop_index(op.f('ix_auction_decisions_item_id'), table_name='auction_decisions')
    op.drop_table('auction_decisions')
    op.drop_index(op.f('ix_auction_runtimes_organization_id'), table_name='auction_runtimes')
    op.drop_index(op.f('ix_auction_runtimes_next_check_at'), table_name='auction_runtimes')
    op.drop_table('auction_runtimes')
    op.drop_index(op.f('ix_auction_private_source_cursors_organization_id'), table_name='auction_private_source_cursors')
    op.drop_table('auction_private_source_cursors')
    op.drop_index(op.f('ix_auction_items_organization_id'), table_name='auction_items')
    op.drop_index(op.f('ix_auction_items_monitor_id'), table_name='auction_items')
    op.drop_table('auction_items')
    # ### end Alembic commands ###
