"""Add complete-feature live runtime and public source ledger.

Revision ID: b2849cd3f65a
Revises: a1738bc2e54f
"""

import sqlalchemy as sa

from alembic import op

revision = "b2849cd3f65a"
down_revision = "a1738bc2e54f"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_source_artifacts',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('identity', sa.String(length=512), nullable=False),
    sa.Column('byte_count', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attribution', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('sha256')
    )
    op.create_index(op.f('ix_monitoring_source_artifacts_retention_until'), 'monitoring_source_artifacts', ['retention_until'], unique=False)
    op.create_index(op.f('ix_monitoring_source_artifacts_source_id'), 'monitoring_source_artifacts', ['source_id'], unique=False)
    op.create_table('monitoring_source_channels',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('next_fetch_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_token', sa.String(length=36), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_source_channels_next_fetch_at'), 'monitoring_source_channels', ['next_fetch_at'], unique=False)
    op.create_table('monitoring_source_samples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_hash', sa.String(length=64), nullable=False),
    sa.Column('series_hash', sa.String(length=64), nullable=False),
    sa.Column('valid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('sample_json', sa.JSON(), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('revision >= 1', name='ck_source_sample_revision'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_hash', 'valid_at', 'revision', name='uq_source_sample_revision')
    )
    op.create_index(op.f('ix_monitoring_source_samples_channel_hash'), 'monitoring_source_samples', ['channel_hash'], unique=False)
    op.create_index(op.f('ix_monitoring_source_samples_retention_until'), 'monitoring_source_samples', ['retention_until'], unique=False)
    op.create_index(op.f('ix_monitoring_source_samples_series_hash'), 'monitoring_source_samples', ['series_hash'], unique=False)
    op.create_index(op.f('ix_monitoring_source_samples_valid_at'), 'monitoring_source_samples', ['valid_at'], unique=False)
    op.create_table('monitoring_commands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('request_key', sa.String(length=120), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id', 'organization_id'], ['monitoring_subjects.id', 'monitoring_subjects.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'request_key', name='uq_monitoring_command_key')
    )
    op.create_index(op.f('ix_monitoring_commands_organization_id'), 'monitoring_commands', ['organization_id'], unique=False)
    op.create_index(op.f('ix_monitoring_commands_subject_id'), 'monitoring_commands', ['subject_id'], unique=False)
    op.create_table('monitoring_live_streams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('binding_hash', sa.String(length=64), nullable=False),
    sa.Column('binding_json', sa.JSON(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.CheckConstraint('sequence >= 0', name='ck_live_stream_sequence'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id', 'organization_id'], ['monitoring_subjects.id', 'monitoring_subjects.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_live_stream_scope'),
    sa.UniqueConstraint('subject_id', 'run_id', 'binding_hash', name='uq_live_stream_binding')
    )
    op.create_index(op.f('ix_monitoring_live_streams_organization_id'), 'monitoring_live_streams', ['organization_id'], unique=False)
    op.create_index(op.f('ix_monitoring_live_streams_run_id'), 'monitoring_live_streams', ['run_id'], unique=False)
    op.create_index(op.f('ix_monitoring_live_streams_subject_id'), 'monitoring_live_streams', ['subject_id'], unique=False)
    op.create_table('monitoring_runtimes',
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('configuration_revision', sa.Integer(), nullable=False),
    sa.Column('email_consent', sa.Boolean(), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_poll_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health', sa.String(length=40), nullable=False),
    sa.Column('current_stream_ids', sa.JSON(), nullable=False),
    sa.CheckConstraint('version >= 1 AND configuration_revision >= 1', name='ck_runtime_versions'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id', 'organization_id'], ['monitoring_subjects.id', 'monitoring_subjects.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_index(op.f('ix_monitoring_runtimes_next_poll_at'), 'monitoring_runtimes', ['next_poll_at'], unique=False)
    op.create_index(op.f('ix_monitoring_runtimes_organization_id'), 'monitoring_runtimes', ['organization_id'], unique=False)
    op.create_table('monitoring_live_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('stream_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('material_id', sa.String(length=64), nullable=True),
    sa.Column('signal_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sequence >= 1', name='ck_live_entry_sequence'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stream_id', 'organization_id'], ['monitoring_live_streams.id', 'monitoring_live_streams.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_live_entry_scope'),
    sa.UniqueConstraint('stream_id', 'input_hash', name='uq_live_entry_input'),
    sa.UniqueConstraint('stream_id', 'material_id', name='uq_live_entry_material'),
    sa.UniqueConstraint('stream_id', 'sequence', name='uq_live_entry_sequence')
    )
    op.create_index(op.f('ix_monitoring_live_entries_created_at'), 'monitoring_live_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_monitoring_live_entries_organization_id'), 'monitoring_live_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_monitoring_live_entries_signal_hash'), 'monitoring_live_entries', ['signal_hash'], unique=False)
    op.create_index(op.f('ix_monitoring_live_entries_stream_id'), 'monitoring_live_entries', ['stream_id'], unique=False)
    op.create_table('monitoring_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('signal_hash', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('configuration_revision', sa.Integer(), nullable=False),
    sa.Column('consent_version', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('pending', 'sending', 'sent', 'suppressed', 'uncertain')", name='ck_monitoring_delivery_state'),
    sa.ForeignKeyConstraint(['entry_id', 'organization_id'], ['monitoring_live_entries.id', 'monitoring_live_entries.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'channel', name='uq_monitoring_delivery_entry')
    )
    op.create_index(op.f('ix_monitoring_deliveries_due_at'), 'monitoring_deliveries', ['due_at'], unique=False)
    op.create_index(op.f('ix_monitoring_deliveries_entry_id'), 'monitoring_deliveries', ['entry_id'], unique=False)
    op.create_index(op.f('ix_monitoring_deliveries_organization_id'), 'monitoring_deliveries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_monitoring_deliveries_owner_user_id'), 'monitoring_deliveries', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_monitoring_deliveries_signal_hash'), 'monitoring_deliveries', ['signal_hash'], unique=False)
    op.create_index(op.f('ix_monitoring_deliveries_state'), 'monitoring_deliveries', ['state'], unique=False)
    op.create_table('monitoring_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('reviewed', 'not_relevant', 'continue', 'action_required')", name='ck_monitoring_review_decision'),
    sa.CheckConstraint('version >= 1', name='ck_monitoring_review_version'),
    sa.ForeignKeyConstraint(['entry_id', 'organization_id'], ['monitoring_live_entries.id', 'monitoring_live_entries.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'version', name='uq_monitoring_review_version')
    )
    op.create_index(op.f('ix_monitoring_reviews_entry_id'), 'monitoring_reviews', ['entry_id'], unique=False)
    op.create_index(op.f('ix_monitoring_reviews_organization_id'), 'monitoring_reviews', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_reviews_organization_id'), table_name='monitoring_reviews')
    op.drop_index(op.f('ix_monitoring_reviews_entry_id'), table_name='monitoring_reviews')
    op.drop_table('monitoring_reviews')
    op.drop_index(op.f('ix_monitoring_deliveries_state'), table_name='monitoring_deliveries')
    op.drop_index(op.f('ix_monitoring_deliveries_signal_hash'), table_name='monitoring_deliveries')
    op.drop_index(op.f('ix_monitoring_deliveries_owner_user_id'), table_name='monitoring_deliveries')
    op.drop_index(op.f('ix_monitoring_deliveries_organization_id'), table_name='monitoring_deliveries')
    op.drop_index(op.f('ix_monitoring_deliveries_entry_id'), table_name='monitoring_deliveries')
    op.drop_index(op.f('ix_monitoring_deliveries_due_at'), table_name='monitoring_deliveries')
    op.drop_table('monitoring_deliveries')
    op.drop_index(op.f('ix_monitoring_live_entries_stream_id'), table_name='monitoring_live_entries')
    op.drop_index(op.f('ix_monitoring_live_entries_signal_hash'), table_name='monitoring_live_entries')
    op.drop_index(op.f('ix_monitoring_live_entries_organization_id'), table_name='monitoring_live_entries')
    op.drop_index(op.f('ix_monitoring_live_entries_created_at'), table_name='monitoring_live_entries')
    op.drop_table('monitoring_live_entries')
    op.drop_index(op.f('ix_monitoring_runtimes_organization_id'), table_name='monitoring_runtimes')
    op.drop_index(op.f('ix_monitoring_runtimes_next_poll_at'), table_name='monitoring_runtimes')
    op.drop_table('monitoring_runtimes')
    op.drop_index(op.f('ix_monitoring_live_streams_subject_id'), table_name='monitoring_live_streams')
    op.drop_index(op.f('ix_monitoring_live_streams_run_id'), table_name='monitoring_live_streams')
    op.drop_index(op.f('ix_monitoring_live_streams_organization_id'), table_name='monitoring_live_streams')
    op.drop_table('monitoring_live_streams')
    op.drop_index(op.f('ix_monitoring_commands_subject_id'), table_name='monitoring_commands')
    op.drop_index(op.f('ix_monitoring_commands_organization_id'), table_name='monitoring_commands')
    op.drop_table('monitoring_commands')
    op.drop_index(op.f('ix_monitoring_source_samples_valid_at'), table_name='monitoring_source_samples')
    op.drop_index(op.f('ix_monitoring_source_samples_series_hash'), table_name='monitoring_source_samples')
    op.drop_index(op.f('ix_monitoring_source_samples_retention_until'), table_name='monitoring_source_samples')
    op.drop_index(op.f('ix_monitoring_source_samples_channel_hash'), table_name='monitoring_source_samples')
    op.drop_table('monitoring_source_samples')
    op.drop_index(op.f('ix_monitoring_source_channels_next_fetch_at'), table_name='monitoring_source_channels')
    op.drop_table('monitoring_source_channels')
    op.drop_index(op.f('ix_monitoring_source_artifacts_source_id'), table_name='monitoring_source_artifacts')
    op.drop_index(op.f('ix_monitoring_source_artifacts_retention_until'), table_name='monitoring_source_artifacts')
    op.drop_table('monitoring_source_artifacts')
    # ### end Alembic commands ###
