"""river lake monitoring

Revision ID: c395ad04e76b
Revises: b2849cd3f65a
Create Date: 2026-09-12 13:25:25.150056

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c395ad04e76b'
down_revision: str | Sequence[str] | None = 'b2849cd3f65a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('river_measurements',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('station_id', sa.String(length=4), nullable=False),
    sa.Column('metric', sa.String(length=12), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_river_measurements_measured_at'), 'river_measurements', ['measured_at'], unique=False)
    op.create_index(op.f('ix_river_measurements_station_id'), 'river_measurements', ['station_id'], unique=False)
    op.create_table('river_source_cache',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('next_fetch_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_token', sa.String(length=36), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=40), nullable=True),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('river_monitors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('health', sa.String(length=40), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('next_poll_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','active','paused','archived')", name='ck_river_status'),
    sa.CheckConstraint('version >= 1 AND revision >= 1', name='ck_river_versions'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_river_monitor_scope'),
    sa.UniqueConstraint('organization_id', 'owner_user_id', 'request_key', name='uq_river_monitor_request')
    )
    op.create_index(op.f('ix_river_monitors_next_poll_at'), 'river_monitors', ['next_poll_at'], unique=False)
    op.create_index(op.f('ix_river_monitors_organization_id'), 'river_monitors', ['organization_id'], unique=False)
    op.create_index(op.f('ix_river_monitors_owner_user_id'), 'river_monitors', ['owner_user_id'], unique=False)
    op.create_table('river_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('monitor_id', sa.String(length=36), nullable=False),
    sa.Column('development_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=True),
    sa.Column('review_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id', 'organization_id'], ['river_monitors.id', 'river_monitors.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monitor_id', 'sequence', name='uq_river_change_sequence')
    )
    op.create_index(op.f('ix_river_changes_development_id'), 'river_changes', ['development_id'], unique=False)
    op.create_index(op.f('ix_river_changes_monitor_id'), 'river_changes', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_river_changes_organization_id'), 'river_changes', ['organization_id'], unique=False)
    op.create_table('river_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('monitor_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id', 'organization_id'], ['river_monitors.id', 'river_monitors.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monitor_id', 'revision', name='uq_river_revision')
    )
    op.create_index(op.f('ix_river_revisions_monitor_id'), 'river_revisions', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_river_revisions_organization_id'), 'river_revisions', ['organization_id'], unique=False)


def downgrade() -> None:
    """Remove only the additive C6 tables."""
    op.drop_index(op.f('ix_river_revisions_organization_id'), table_name='river_revisions')
    op.drop_index(op.f('ix_river_revisions_monitor_id'), table_name='river_revisions')
    op.drop_table('river_revisions')
    op.drop_index(op.f('ix_river_changes_organization_id'), table_name='river_changes')
    op.drop_index(op.f('ix_river_changes_monitor_id'), table_name='river_changes')
    op.drop_index(op.f('ix_river_changes_development_id'), table_name='river_changes')
    op.drop_table('river_changes')
    op.drop_index(op.f('ix_river_monitors_owner_user_id'), table_name='river_monitors')
    op.drop_index(op.f('ix_river_monitors_organization_id'), table_name='river_monitors')
    op.drop_index(op.f('ix_river_monitors_next_poll_at'), table_name='river_monitors')
    op.drop_table('river_monitors')
    op.drop_table('river_source_cache')
    op.drop_index(op.f('ix_river_measurements_station_id'), table_name='river_measurements')
    op.drop_index(op.f('ix_river_measurements_measured_at'), table_name='river_measurements')
    op.drop_table('river_measurements')
    # ### end Alembic commands ###
