"""Private tender profiles, dossier versions and internal decisions."""

import sqlalchemy as sa

from alembic import op

revision = "e5b7cf26098d"
down_revision = "d4a6be15f87c"
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_cpv_cache',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('ancestry', sa.JSON(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('tender_material_sections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('payload_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('payload_bytes > 0', name='ck_tender_material_size'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_material_sections_created_at'), 'tender_material_sections', ['created_at'], unique=False)
    op.create_table('tender_publication_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('publication_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('payload_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('payload_bytes > 0', name='ck_tender_snapshot_size'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_publication_snapshots_created_at'), 'tender_publication_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_tender_publication_snapshots_project_id'), 'tender_publication_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_tender_publication_snapshots_publication_id'), 'tender_publication_snapshots', ['publication_id'], unique=False)
    op.create_table('tender_source_leases',
    sa.Column('key', sa.String(length=24), nullable=False),
    sa.Column('next_request_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_token', sa.String(length=36), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tender_source_restrictions',
    sa.Column('scope', sa.String(length=12), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('policy_reference', sa.String(length=500), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("scope IN ('project','publication')", name='ck_tender_restriction_scope'),
    sa.PrimaryKeyConstraint('scope', 'target_id')
    )
    op.create_table('tender_storage_state',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('used_bytes', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('used_bytes >= 0', name='ck_tender_storage_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_monitors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('email_revision', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('health', sa.String(length=40), nullable=False),
    sa.Column('next_poll_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','active','paused','archived')", name='ck_tender_monitor_status'),
    sa.CheckConstraint('version >= 1 AND revision >= 1', name='ck_tender_monitor_version'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_tender_monitor_scope'),
    sa.UniqueConstraint('organization_id', 'owner_user_id', 'request_key', name='uq_tender_monitor_request')
    )
    op.create_index(op.f('ix_tender_monitors_next_poll_at'), 'tender_monitors', ['next_poll_at'], unique=False)
    op.create_index(op.f('ix_tender_monitors_organization_id'), 'tender_monitors', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tender_monitors_owner_user_id'), 'tender_monitors', ['owner_user_id'], unique=False)
    op.create_table('tender_collections',
    sa.Column('monitor_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('lease_token', sa.String(length=36), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id', 'organization_id'], ['tender_monitors.id', 'tender_monitors.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monitor_id')
    )
    op.create_index(op.f('ix_tender_collections_organization_id'), 'tender_collections', ['organization_id'], unique=False)
    op.create_table('tender_dossiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('monitor_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('lot_key', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('following', sa.Boolean(), nullable=False),
    sa.Column('latest_sequence', sa.Integer(), nullable=False),
    sa.Column('latest_ordinal', sa.Integer(), nullable=False),
    sa.Column('review_state', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=12), nullable=True),
    sa.Column('reviewed_sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IS NULL OR decision IN ('bid','no_bid','monitor')", name='ck_tender_dossier_decision'),
    sa.CheckConstraint("review_state IN ('new','needs_review','reviewed')", name='ck_tender_dossier_review'),
    sa.CheckConstraint('version >= 1 AND latest_sequence >= 0 AND latest_ordinal >= 0', name='ck_tender_dossier_version'),
    sa.ForeignKeyConstraint(['monitor_id', 'organization_id'], ['tender_monitors.id', 'tender_monitors.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_tender_dossier_scope'),
    sa.UniqueConstraint('monitor_id', 'project_id', 'lot_key', name='uq_tender_dossier_identity')
    )
    op.create_index(op.f('ix_tender_dossiers_monitor_id'), 'tender_dossiers', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_tender_dossiers_organization_id'), 'tender_dossiers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tender_dossiers_project_id'), 'tender_dossiers', ['project_id'], unique=False)
    op.create_index(op.f('ix_tender_dossiers_updated_at'), 'tender_dossiers', ['updated_at'], unique=False)
    op.create_table('tender_email_policies',
    sa.Column('monitor_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('recipient_email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('revision >= 1', name='ck_tender_email_revision'),
    sa.ForeignKeyConstraint(['monitor_id', 'organization_id'], ['tender_monitors.id', 'tender_monitors.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monitor_id', 'revision')
    )
    op.create_index(op.f('ix_tender_email_policies_organization_id'), 'tender_email_policies', ['organization_id'], unique=False)
    op.create_table('tender_profile_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('monitor_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('configuration_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id', 'organization_id'], ['tender_monitors.id', 'tender_monitors.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monitor_id', 'revision', name='uq_tender_profile_revision')
    )
    op.create_index(op.f('ix_tender_profile_revisions_monitor_id'), 'tender_profile_revisions', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_tender_profile_revisions_organization_id'), 'tender_profile_revisions', ['organization_id'], unique=False)
    op.create_table('tender_document_access',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('publication_id', sa.String(length=36), nullable=False),
    sa.Column('account_reference', sa.String(length=200), nullable=False),
    sa.Column('policy_reference', sa.String(length=500), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retain_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_observation_id', sa.String(length=36), nullable=True),
    sa.Column('last_observation_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('retain_until >= valid_until', name='ck_tender_document_retention'),
    sa.ForeignKeyConstraint(['dossier_id', 'organization_id'], ['tender_dossiers.id', 'tender_dossiers.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', 'dossier_id', name='uq_tender_document_access_scope')
    )
    op.create_index(op.f('ix_tender_document_access_dossier_id'), 'tender_document_access', ['dossier_id'], unique=False)
    op.create_index(op.f('ix_tender_document_access_organization_id'), 'tender_document_access', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tender_document_access_retain_until'), 'tender_document_access', ['retain_until'], unique=False)
    op.create_index(op.f('ix_tender_document_access_valid_until'), 'tender_document_access', ['valid_until'], unique=False)
    op.create_table('tender_document_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('access_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('state', sa.JSON(), nullable=True),
    sa.Column('deltas', sa.JSON(), nullable=True),
    sa.Column('previous_id', sa.String(length=36), nullable=True),
    sa.Column('stored_bytes', sa.BigInteger(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('stored_bytes >= 0 AND sequence >= 1', name='ck_tender_doc_observation_bounds'),
    sa.ForeignKeyConstraint(['access_id', 'organization_id', 'dossier_id'], ['tender_document_access.id', 'tender_document_access.organization_id', 'tender_document_access.dossier_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_id', 'sequence', name='uq_tender_doc_observation_sequence'),
    sa.UniqueConstraint('id', 'organization_id', 'dossier_id', name='uq_tender_doc_observation_scope')
    )
    op.create_index(op.f('ix_tender_document_observations_access_id'), 'tender_document_observations', ['access_id'], unique=False)
    op.create_index(op.f('ix_tender_document_observations_dossier_id'), 'tender_document_observations', ['dossier_id'], unique=False)
    op.create_index(op.f('ix_tender_document_observations_organization_id'), 'tender_document_observations', ['organization_id'], unique=False)
    op.create_table('tender_document_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('access_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=256), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('text_sha256', sa.String(length=64), nullable=False),
    sa.Column('extractor_version', sa.String(length=100), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('body', sa.LargeBinary(), nullable=True),
    sa.Column('parsed', sa.JSON(), nullable=True),
    sa.Column('stored_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('stored_bytes >= 0', name='ck_tender_document_stored_bytes'),
    sa.ForeignKeyConstraint(['access_id', 'organization_id', 'dossier_id'], ['tender_document_access.id', 'tender_document_access.organization_id', 'tender_document_access.dossier_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_id', 'item_id', 'content_sha256', 'text_sha256', 'extractor_version', name='uq_tender_document_projection')
    )
    op.create_index(op.f('ix_tender_document_snapshots_access_id'), 'tender_document_snapshots', ['access_id'], unique=False)
    op.create_index(op.f('ix_tender_document_snapshots_dossier_id'), 'tender_document_snapshots', ['dossier_id'], unique=False)
    op.create_index(op.f('ix_tender_document_snapshots_organization_id'), 'tender_document_snapshots', ['organization_id'], unique=False)
    op.create_table('tender_dossier_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.String(length=36), nullable=False),
    sa.Column('publication_ordinal', sa.Integer(), nullable=False),
    sa.Column('profile_revision', sa.Integer(), nullable=False),
    sa.Column('observation_key', sa.String(length=36), nullable=False),
    sa.Column('document_observation_id', sa.String(length=36), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('publish_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('material_keys', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('match', sa.JSON(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_observation_id', 'organization_id', 'dossier_id'], ['tender_document_observations.id', 'tender_document_observations.organization_id', 'tender_document_observations.dossier_id'], ),
    sa.ForeignKeyConstraint(['dossier_id', 'organization_id'], ['tender_dossiers.id', 'tender_dossiers.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_hash'], ['tender_publication_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id', 'publication_id', 'source_hash', 'profile_revision', 'observation_key', name='uq_tender_dossier_evidence'),
    sa.UniqueConstraint('dossier_id', 'sequence', name='uq_tender_dossier_sequence'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_tender_version_scope')
    )
    op.create_index(op.f('ix_tender_dossier_versions_document_observation_id'), 'tender_dossier_versions', ['document_observation_id'], unique=False)
    op.create_index(op.f('ix_tender_dossier_versions_dossier_id'), 'tender_dossier_versions', ['dossier_id'], unique=False)
    op.create_index(op.f('ix_tender_dossier_versions_organization_id'), 'tender_dossier_versions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tender_dossier_versions_source_hash'), 'tender_dossier_versions', ['source_hash'], unique=False)
    op.create_table('tender_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=12), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('bid','no_bid','monitor')", name='ck_tender_decision_value'),
    sa.ForeignKeyConstraint(['dossier_id', 'organization_id'], ['tender_dossiers.id', 'tender_dossiers.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dossier_id', 'sequence'], ['tender_dossier_versions.dossier_id', 'tender_dossier_versions.sequence'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id', 'request_key', name='uq_tender_decision_request')
    )
    op.create_index(op.f('ix_tender_decisions_dossier_id'), 'tender_decisions', ['dossier_id'], unique=False)
    op.create_index(op.f('ix_tender_decisions_organization_id'), 'tender_decisions', ['organization_id'], unique=False)
    op.create_table('tender_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('monitor_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_version_id', sa.String(length=36), nullable=False),
    sa.Column('consent_revision', sa.Integer(), nullable=False),
    sa.Column('signal_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('pending','sending','sent','uncertain','suppressed')", name='ck_tender_delivery_state'),
    sa.ForeignKeyConstraint(['evidence_version_id', 'organization_id'], ['tender_dossier_versions.id', 'tender_dossier_versions.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitor_id', 'consent_revision'], ['tender_email_policies.monitor_id', 'tender_email_policies.revision'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitor_id', 'organization_id'], ['tender_monitors.id', 'tender_monitors.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_version_id', 'consent_revision', name='uq_tender_delivery_intent')
    )
    op.create_index(op.f('ix_tender_deliveries_due_at'), 'tender_deliveries', ['due_at'], unique=False)
    op.create_index(op.f('ix_tender_deliveries_evidence_version_id'), 'tender_deliveries', ['evidence_version_id'], unique=False)
    op.create_index(op.f('ix_tender_deliveries_monitor_id'), 'tender_deliveries', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_tender_deliveries_organization_id'), 'tender_deliveries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tender_deliveries_owner_user_id'), 'tender_deliveries', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_tender_deliveries_signal_hash'), 'tender_deliveries', ['signal_hash'], unique=False)
    op.create_index(op.f('ix_tender_deliveries_state'), 'tender_deliveries', ['state'], unique=False)
    op.create_table('tender_version_sections',
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=64), nullable=False),
    sa.Column('locator', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['tender_material_sections.id'], ),
    sa.ForeignKeyConstraint(['version_id', 'organization_id'], ['tender_dossier_versions.id', 'tender_dossier_versions.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', 'name')
    )
    op.create_index(op.f('ix_tender_version_sections_organization_id'), 'tender_version_sections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tender_version_sections_section_id'), 'tender_version_sections', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_version_sections_section_id'), table_name='tender_version_sections')
    op.drop_index(op.f('ix_tender_version_sections_organization_id'), table_name='tender_version_sections')
    op.drop_table('tender_version_sections')
    op.drop_index(op.f('ix_tender_deliveries_state'), table_name='tender_deliveries')
    op.drop_index(op.f('ix_tender_deliveries_signal_hash'), table_name='tender_deliveries')
    op.drop_index(op.f('ix_tender_deliveries_owner_user_id'), table_name='tender_deliveries')
    op.drop_index(op.f('ix_tender_deliveries_organization_id'), table_name='tender_deliveries')
    op.drop_index(op.f('ix_tender_deliveries_monitor_id'), table_name='tender_deliveries')
    op.drop_index(op.f('ix_tender_deliveries_evidence_version_id'), table_name='tender_deliveries')
    op.drop_index(op.f('ix_tender_deliveries_due_at'), table_name='tender_deliveries')
    op.drop_table('tender_deliveries')
    op.drop_index(op.f('ix_tender_decisions_organization_id'), table_name='tender_decisions')
    op.drop_index(op.f('ix_tender_decisions_dossier_id'), table_name='tender_decisions')
    op.drop_table('tender_decisions')
    op.drop_index(op.f('ix_tender_dossier_versions_source_hash'), table_name='tender_dossier_versions')
    op.drop_index(op.f('ix_tender_dossier_versions_organization_id'), table_name='tender_dossier_versions')
    op.drop_index(op.f('ix_tender_dossier_versions_dossier_id'), table_name='tender_dossier_versions')
    op.drop_index(op.f('ix_tender_dossier_versions_document_observation_id'), table_name='tender_dossier_versions')
    op.drop_table('tender_dossier_versions')
    op.drop_index(op.f('ix_tender_document_snapshots_organization_id'), table_name='tender_document_snapshots')
    op.drop_index(op.f('ix_tender_document_snapshots_dossier_id'), table_name='tender_document_snapshots')
    op.drop_index(op.f('ix_tender_document_snapshots_access_id'), table_name='tender_document_snapshots')
    op.drop_table('tender_document_snapshots')
    op.drop_index(op.f('ix_tender_document_observations_organization_id'), table_name='tender_document_observations')
    op.drop_index(op.f('ix_tender_document_observations_dossier_id'), table_name='tender_document_observations')
    op.drop_index(op.f('ix_tender_document_observations_access_id'), table_name='tender_document_observations')
    op.drop_table('tender_document_observations')
    op.drop_index(op.f('ix_tender_document_access_valid_until'), table_name='tender_document_access')
    op.drop_index(op.f('ix_tender_document_access_retain_until'), table_name='tender_document_access')
    op.drop_index(op.f('ix_tender_document_access_organization_id'), table_name='tender_document_access')
    op.drop_index(op.f('ix_tender_document_access_dossier_id'), table_name='tender_document_access')
    op.drop_table('tender_document_access')
    op.drop_index(op.f('ix_tender_profile_revisions_organization_id'), table_name='tender_profile_revisions')
    op.drop_index(op.f('ix_tender_profile_revisions_monitor_id'), table_name='tender_profile_revisions')
    op.drop_table('tender_profile_revisions')
    op.drop_index(op.f('ix_tender_email_policies_organization_id'), table_name='tender_email_policies')
    op.drop_table('tender_email_policies')
    op.drop_index(op.f('ix_tender_dossiers_updated_at'), table_name='tender_dossiers')
    op.drop_index(op.f('ix_tender_dossiers_project_id'), table_name='tender_dossiers')
    op.drop_index(op.f('ix_tender_dossiers_organization_id'), table_name='tender_dossiers')
    op.drop_index(op.f('ix_tender_dossiers_monitor_id'), table_name='tender_dossiers')
    op.drop_table('tender_dossiers')
    op.drop_index(op.f('ix_tender_collections_organization_id'), table_name='tender_collections')
    op.drop_table('tender_collections')
    op.drop_index(op.f('ix_tender_monitors_owner_user_id'), table_name='tender_monitors')
    op.drop_index(op.f('ix_tender_monitors_organization_id'), table_name='tender_monitors')
    op.drop_index(op.f('ix_tender_monitors_next_poll_at'), table_name='tender_monitors')
    op.drop_table('tender_monitors')
    op.drop_table('tender_storage_state')
    op.drop_table('tender_source_restrictions')
    op.drop_table('tender_source_leases')
    op.drop_index(op.f('ix_tender_publication_snapshots_publication_id'), table_name='tender_publication_snapshots')
    op.drop_index(op.f('ix_tender_publication_snapshots_project_id'), table_name='tender_publication_snapshots')
    op.drop_index(op.f('ix_tender_publication_snapshots_created_at'), table_name='tender_publication_snapshots')
    op.drop_table('tender_publication_snapshots')
    op.drop_index(op.f('ix_tender_material_sections_created_at'), table_name='tender_material_sections')
    op.drop_table('tender_material_sections')
    op.drop_table('tender_cpv_cache')
    # ### end Alembic commands ###
